### ISSUE TITLE
iOS8以下能否支持？ 

### ISSUE THREAD

**Issue by february29** [longitachi/ZLPhotoBrowser#10]
iOS8以下弹出的ZLPhotoActionSheet 不能够显示照片。点击相册也显示不出照片。

**Comment by longitachi** [comment]
你好，是支持iOS8的，你是不是没有给权限？

**Comment by valentman** [comment]
最低就是iOS8了。这个工程基于Photos.framework，而Photos.framework是iOS8之后才有的库。回答楼主~
