### ISSUE TITLE
预览已选择图片的方法无法传是否是原图参数

### ISSUE THREAD

**Issue by ToForgive** [longitachi/ZLPhotoBrowser#101]
## 在相册里选择两张图片并勾选原图确定后，已选择的图片进入查看，底部有原图按钮但是未被选中，而且查看已选择图片的方法无法传是否是原图的参数。
详情见下图：
![](http://ww3.sinaimg.cn/large/0060lm7Tly1fjz1i1p0e9g30aq0l9x6p.gif)

选择照片回调里void (^selectImageBlock)(NSArray<UIImage *> *images, NSArray<PHAsset *> *assets, BOOL isOriginal)有isOriginal参数返回是否选择了原图。
但是预览用户已选择的照片的方法- (void)previewSelectedPhotos:(NSArray<UIImage *> *)photos assets:(NSArray<PHAsset *> *)assets index:(NSInteger)index 却没有办法传递是否为原图的参数，这样导致了如果已经选择了原图，无法取消选择。
因为有时候就像demo和微信一样，选择完图片以后不是立即上传所以会出现选择完原图再取消的情况。
希望能给previewSelectedPhotos方法加上isOriginal属性。

**Comment by longitachi** [comment]
好的，可以的话你可以暂时先修改下，给方法添加一个参数，下次更新我会加上

**Comment by longitachi** [comment]
pod 2.4.5 已添加该参数
