### ISSUE TITLE
进入相册界面查看相片时单击会回到第一张

### ISSUE THREAD

**Issue by JianmingFu** [longitachi/ZLPhotoBrowser#103]
进入相册界面查看相片时单击会回到第一张，比如说我点击查看的是第10张，然后我滑动查看到了第15张，我单点后又回到了第10张，感觉不是很适合习惯

**Comment by longitachi** [comment]
你好，我没太看懂你描述的意思，单点后又回到第十张是什么意思，可不可以整一个gif或者详细描述下操作步骤？

**Comment by JianmingFu** [comment]
[QQ20170930-164218-HD.mp4.zip](https://github.com/longitachi/ZLPhotoBrowser/files/1346277/QQ20170930-164218-HD.mp4.zip)

**Comment by JianmingFu** [comment]
好像是适配问题 我这个是用5s 九点几的版本测的，但是我用6 ios11测的话又没问题

**Comment by JianmingFu** [comment]
看到我发的视频了吗

**Comment by longitachi** [comment]
看到了。但是我用iPhone 8的模拟器去点，没有点出来这个问题

**Comment by JianmingFu** [comment]
所以我说是适配问题呀。

**Comment by JianmingFu** [comment]
库功能挺全的，这个倒是小问题 star

**Comment by longitachi** [comment]
我这边没有5s 9.多的机器。 只有10的机器，苹果关闭验证了，也刷不下去了

**Comment by JianmingFu** [comment]
模拟器上应该可以选择的吧

**Comment by longitachi** [comment]
我在iOS 8.1模拟器上点出来了，我看下找找原因

**Comment by JianmingFu** [comment]
我用其他机型测了一下，好像ios8/9下就会出现这个问题 ios11不会

**Comment by longitachi** [comment]
在iOS 8/9 下面，单点之后会比11机型上多走一个scrollviewdidscroll的方法，这里面取_collectionView的contentoffset值，不是正确的contentoffset值。感觉这是苹果的bug吧，更新11之前都没问题

**Comment by JianmingFu** [comment]
反正每次更新都会出点幺蛾子。。。好像又更新版本了

**Comment by longitachi** [comment]
找到原因了，不知道为啥设置一下这个view的坐标会导致出现这个问题，
![aede8338-ab8c-4326-9658-87adcb7e486c](https://user-images.githubusercontent.com/11711768/31044671-495a2146-a606-11e7-887f-48b112b2265e.png)

把方法改为这个就好了，不应该算坐标的
```objc
- (void)handlerSingleTap
{
    _hideNavBar = !_hideNavBar;
    
    _navView.hidden = _hideNavBar;
    _bottomView.hidden = _hideNavBar;
}
```

**Comment by JianmingFu** [comment]
嗯，解决问题了！
