### ISSUE TITLE
请问可以不使用Cocoapods吗？

### ISSUE THREAD

**Issue by liuyi** [longitachi/ZLPhotoBrowser#105]
因为我的项目很纯粹，基本不会用到很多其他第三方的库，不希望搞太多复杂的流程。
请问如果我手动加入你的这个模块，可以不使用Cocoapods吗？
如果可以的话，请问要怎么弄呢？

**Comment by longitachi** [comment]
你看下readme文档，使用方法有介绍不使用cocoapods的集成方式

**Comment by liuyi** [comment]
反应好快啊  谢谢！
请问是指的这个吗？
Manually
1.直接把PhotoBrowser文件夹拖入到您的工程中
2.导入 Photos.framework及PhotosUI.framework
3.项目依赖 SDWebImage，所以需要导入该框架
4.导入 "ZLPhotoActionSheet.h"


我还以为是先手动这样完了后  还要执行后面的 Cocoapods 部分呢。
对IOS不是很熟悉 不好意思了

**Comment by longitachi** [comment]
是的

**Comment by liuyi** [comment]
好的 谢谢你

**Comment by liuyi** [comment]
手动加入了 
1.直接把PhotoBrowser文件夹拖入到您的工程中
ZLCollectionCell.h  显示错误：请问如何处理呀？
![image](https://user-images.githubusercontent.com/848803/31447218-1558dd06-ae67-11e7-8cd9-7c9c0a3c19bf.png)

**Comment by liuyi** [comment]
/Volumes/data/work/git/ddschool/dev/frameworks/runtime-src/proj.appstore/base/PhotoBrowser/ZLCollectionCell.m:170:5: Expected ';' at end of declaration
/Volumes/data/work/git/ddschool/dev/frameworks/runtime-src/proj.appstore/base/PhotoBrowser/ZLDefine.h:54:43: Expanded from macro 'weakify'
/Volumes/data/work/git/ddschool/dev/frameworks/runtime-src/proj.appstore/base/PhotoBrowser/ZLCollectionCell.m:177:9: Expected ';' at end of declaration
/Volumes/data/work/git/ddschool/dev/frameworks/runtime-src/proj.appstore/base/PhotoBrowser/ZLDefine.h:55:45: Expanded from macro 'strongify'
/Volumes/data/work/git/ddschool/dev/frameworks/runtime-src/proj.appstore/base/PhotoBrowser/ZLCollectionCell.m:202:1: Use of '@import' when modules are disabled


/Volumes/data/work/git/ddschool/dev/frameworks/runtime-src/proj.appstore/base/PhotoBrowser/ZLCollectionCell.m:170:13: A parameter list without types is only allowed in a function definition
