### ISSUE TITLE
手动加入PhotoBrowser到工程，代码在XCODE报错。

### ISSUE THREAD

**Issue by liuyi** [longitachi/ZLPhotoBrowser#107]
/Volumes/data/work/git/ddschool/dev/frameworks/runtime-src/proj.appstore/base/PhotoBrowser/ZLCollectionCell.m
![image](https://user-images.githubusercontent.com/848803/31452218-e74e366a-ae73-11e7-81a4-7c29eea0d102.png)

请问需要如何处理呀

**Comment by longitachi** [comment]
你看下ZLDefine里面有没有这两个宏
```objc
#define weakify(var)   __weak typeof(var) weakSelf = var
#define strongify(var) __strong typeof(var) strongSelf = var
```

**Comment by liuyi** [comment]
#define weakify(var)   __weak typeof(var) weakSelf = var
#define strongify(var) __strong typeof(var) strongSelf = var
有这两个宏定义，然后我的代码是从github下拉的master分支的代码。
请问这个代码是稳定的吗？是不是另外有稳定的版本？
谢谢~~

**Comment by liuyi** [comment]
发现在ZLDefine.h里没有 weakSelf  和 strongSelf的定义是正确的吗？

**Comment by longitachi** [comment]
应该是有这两个宏的，每个版本都有的

**Comment by longitachi** [comment]
目前这个版本是稳定的，暂时没有发现bug

**Comment by liuyi** [comment]
大神  我直接拖到工程里的动作应该没错吧？
你能看到刚刚的那个截图吗  
   weakify(self);   有四个错误  说有类型不对啥的？

**Comment by liuyi** [comment]
大神 可以加你QQ向你请教吗？

**Comment by liuyi** [comment]
很神奇的是  wakify(self) 在其他的类里没一点问题  都显示正常的。

**Comment by liuyi** [comment]
不好意思 刚把.h文件也加入到了Compile Sources ，
现在去掉了这些.h文件后 出现了88个错误，
然后我用的XCODE版本是：Version 9.0 (9A235)   发布的IOS版本为11

请问是不是 跟这个有关系呢？

**Comment by liuyi** [comment]
请问是不是所有文件都要标记使用  -fobjc-arc  ?

**Comment by liuyi** [comment]
找到问题了，不知道是不是xcode问题还是怎么的。

将
 所有的 __weak typeof(var) weakSelf = var
所有的 strongify(var) __strong typeof(var) strongSelf = var

修改为:
  __weak __typeof(var) weakSelf = var
 __strong __typeof(var) strongSelf = var

解决了这些问题。

原因是:
Use __typeof instead of typeof.

This is because both __typeof and typeof are extensions to C, but typeof is only enabled in Clang when the language is a GNUXX variant of C, but not for CXX.

解决方案来自于:
https://stackoverflow.com/questions/32145326/weak-typeofself-weakself-self-expected-at-end-of-declaration 
第二个答案

我不知道是不是我的姿势不对 还是怎么的 总之 我遇到了这个问题。
xcode 昨天升级到了9 所以8上面没有什么测试过 不知道是不是版本原因
