### ISSUE TITLE
多次点击相册，取消--》相册--》取消  崩溃，多次点击相册，选取照片 崩溃

### ISSUE THREAD

**Issue by liuyi** [longitachi/ZLPhotoBrowser#108]
XCODE 9编译，
运行于IPAD2
 IOS 9.3.5

多次点击按钮执行这个代码 ，然后选择里面的相册，然后取消
-(void) showAlbum{
    NSLog(@"PhotoCamera takePhoto");
    
    //调用相册
    [self.actionSheet showPreviewAnimated:YES];
}

1、多次点击相册，取消--》相册--》取消  崩溃

2、多次点击相册，选取照片 崩溃

====错误输出======
 Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'attempt to scroll to invalid index path: <NSIndexPath: 0x1c455f40> {length = 2, path = 0 - 16}'
*** First throw call stack:
(0x24ab391b 0x2424ee17 0x24ab3861 0x2929e673 0x16b3c7 0x16ab9d 0x2902aab9 0x270c2bcd 0x270be375 0x270be209 0x270bd6d1 0x270bd3a5 0x29021b79 0x24a756c9 0x24a739cd 0x24a73dff 0x249c3229 0x249c3015 0x25fb3ac9 0x29097189 0x1c2711 0x2466b873)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by liuyi** [comment]
@longitachi  请问可以加你QQ向你咨询一下怎么使用吗？因为我在把这个功能加入到cocos2dx 做的APP里，发现有内存泄漏。每次show/hide 都会残留内存 一直不断的涨1-2M

**Comment by longitachi** [comment]
495181165
