### ISSUE TITLE
选中照片的问题

### ISSUE THREAD

**Issue by yuditxj** [longitachi/ZLPhotoBrowser#11]
请问，我选择好照片，然后忘记选某张照片了，再重新返回的时候之前选择的照片又要重新选择了，这个时候能优化一下

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/issues/5
看这个issue里面的回答，有解决方法。
有好些朋友开issue说过这个标记已选择图片的问题，但是我之所以不加进去是有一定原因的。
1：如果有这个功能，你必须把ZLPhotoActionSheet的实例声明为类变量/属性，这样该对象的数据才不会在消失时候给释放掉，这个根据使用者习惯，随意性太大
2：如果采用每次调ZLPhotoActionSheet时候把已选择图片数组传回去的话，这个更加麻烦，相册里面的操作是根据PHAsset来控制的，而最后回调的图片是一个 UIImage 的数组
我在Readme里面加上这个说明好了。
