### ISSUE TITLE
是不是应该开放设置整体的主题色

### ISSUE THREAD

**Issue by Yueeeeee** [longitachi/ZLPhotoBrowser#112]
demo里的所有蓝色都应该整理成一个色值属性,开放设置,作为主题色

**Comment by Yueeeeee** [comment]
sheet的标题最好可以自定义,拍摄cell的点击事件可以自定义成拍摄视频或者照片,这些都可以开放出来

**Comment by longitachi** [comment]
你好，最近正在添加自定义导航背景色，标题色，底部工具栏各种颜色，及使用开发者自定义图片的功能，稍后会发布新版本

**Comment by Yueeeeee** [comment]
ZLPhotoActionSheet弹出的触发事件是navigationItem.rightBarButtonItem,没有方法判断这个ZLPhotoActionSheet的dissmiss来更改navigationItem.rightBarButtonItem的enable状态,点两次会弹出两个ZLPhotoActionSheet
