### ISSUE TITLE
This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes

### ISSUE THREAD

**Issue by LiberalChen** [longitachi/ZLPhotoBrowser#113]
![image](https://user-images.githubusercontent.com/19303164/31653411-16dac628-b2e8-11e7-88aa-6493aed6722f.png)

报这个错误了，在子线程更新 UI？

另外，我的 APP 的状态栏一直是隐藏的，调用 ZLPhotoBrowser 之后 状态栏就出来了，怎么设置一直隐藏啊

**Comment by longitachi** [comment]
这个警告2.4.8已经解决了，更新下即可，暂时不能设置一直隐藏，你可以在 ZLPhotoAcitonSheet的hide方法里，设置下当退出照片选择器的时候隐藏状态栏

**Comment by LiberalChen** [comment]
好的

**Comment by LiberalChen** [comment]
开放个 api 吧。要不每次更新还得改你的代码~

**Comment by longitachi** [comment]
好的，后续会做处理

**Comment by LiberalChen** [comment]
更新了2.4.9，我设置了直选一张，然后直接进入编辑，点“完成”退出的时候，还是有状态栏~ 还有个问题：我设置相册内部显示拍照按钮，能不能拍完照之后页可以编辑一下

**Comment by longitachi** [comment]
不好意思，你暂时先把`ZLEditViewController` 和 `ZLEditVideoViewController` 里面 `viewWillDisappear`这个方法里的这行代码删除`[UIApplication sharedApplication].statusBarHidden = NO;`

然后把`ZLShowBigImgViewController` 的下面这个方法内的代码修改成这个
```
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    
    [UIApplication sharedApplication].statusBarHidden = NO;
    [self.navigationController setNavigationBarHidden:YES animated:NO];
    
    if (!_isFirstAppear) {
        return;
    }
    
    [_collectionView setContentOffset:CGPointMake((kViewWidth+kItemMargin)*_indexBeforeRotation, 0)];
}
```
