### ISSUE TITLE
图片选择器全都上移了64个像素

### ISSUE THREAD

**Issue by liudaolu** [longitachi/ZLPhotoBrowser#114]
rt

**Comment by longitachi** [comment]
有图吗？

**Comment by liudaolu** [comment]
<img width="447" alt="qq20171017-174556 2x" src="https://user-images.githubusercontent.com/11287047/31658340-518fd38c-b363-11e7-93c3-afb7c2a80939.png">
<img width="447" alt="qq20171017-174707 2x" src="https://user-images.githubusercontent.com/11287047/31658346-54e89db6-b363-11e7-802a-f7acbc0244df.png">


真机也是这样，不知道是不是因为用了ZFNavigationController的关系

**Comment by longitachi** [comment]
应该是的，我这边机型上没有这个问题，ZFNavigationController 是不是全局修改了一些东西？

**Comment by liudaolu** [comment]
不清楚。。

**Comment by liudaolu** [comment]
但是你那个demo在ios11又是好的，很奇怪

**Comment by liudaolu** [comment]
[[UIScrollView appearance] setContentInsetAdjustmentBehavior:UIScrollViewContentInsetAdjustmentNever];

是因为全局设置了这个。。
