### ISSUE TITLE
内存不足选择图片从iCloud请求回退会崩溃

### ISSUE THREAD

**Issue by yanfengc** [longitachi/ZLPhotoBrowser#115]

**Comment by longitachi** [comment]
是在demo里出现的吗，是怎么出现这种情况，大约选择了多少张图片，然后是在什么情况下崩溃的？

**Comment by yanfengc** [comment]
嗯,刚在demo里出现的  断点在ZLBigImageCell  437行  strongSelf->_loadOK = YES;

**Comment by yanfengc** [comment]
测试机内存是16G的,下载各种应用占满了,然后图片需要从iCloud里加载,点击预览图来回滑动,加载了不少图片貌似,然后点击的回退按钮,出现的崩溃.

**Comment by linnan777** [comment]
同样出现，崩溃位置一样。

**Comment by longitachi** [comment]
这个内存不足，是手机存储空间不足吗

**Comment by GitHubMrfan** [comment]
同样出现，崩溃位置一样。求指导

**Comment by longitachi** [comment]
@GitHubMrfan 这个内存不足是手机存储空间不足还是运行内存不足？
