### ISSUE TITLE
xib 文件报资源暂时不可用

### ISSUE THREAD

**Issue by ThinkWMV** [longitachi/ZLPhotoBrowser#117]
ibtool --reference-external-strings-file --errors --warnings --notices --minimum-deployment-target 9.3 --output-format human-readable-text --compile /Users/duan/Library/Developer/Xcode/DerivedData/SHUILIANDONG-brajnpjsddaijgcneillrldnxyck/Build/Products/Debug-iphonesimulator/SHUILIANDONG.app/ZLPhotoBrowserCell.nib /Users/duan/Desktop/SHUILIANDONG/Pods/ZLPhotoBrowser/PhotoBrowser/resource/ZLPhotoBrowserCell.xib --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/Users/duan/Desktop/SHUILIANDONG/Pods/Target Support Files/Pods-SHUILIANDONG/Pods-SHUILIANDONG-resources.sh: line 48: echo: write error: Resource temporarily unavailable
Command /bin/sh failed with exit code 1

**Comment by ThinkWMV** [comment]
不好意思 是target 9.3 的问题 😓

**Comment by ThinkWMV** [comment]
这个报错怎么解决啊？

**Comment by longitachi** [comment]
这是啥情况下出现的问题？

**Comment by ThinkWMV** [comment]
之前一直用着好好的，突然就报这个错，前两天我从新pod 导入后没有了，今天跑起来的时候又报错了，把库删掉就没有了。

**Comment by longitachi** [comment]
这个暂时没遇到过，你clean下项目，重启xcode可以吗？

**Comment by ThinkWMV** [comment]
现在又报这个错，按clean后 重启xcode 还是不可以，要不我加一下您QQ或者微信

**Comment by longitachi** [comment]
不好意思，公司这两天网络太烂，github一直打不开，495181165

**Comment by ThinkWMV** [comment]
不好意思，这边已经解决了，发现和这个没有多大的关系，是pods加载的问题，勾选上这个就OK了。
<img width="632" alt="2017-11-11 10 20 17" src="https://user-images.githubusercontent.com/16930062/32685352-45b2665e-c6ca-11e7-94e2-8846158c7b7d.png">
