### ISSUE TITLE
系统相册中的大像素图（4961x3508），setSelectImageBlock获取到的images大小为1000x708，图片像素缩小不清晰了

### ISSUE THREAD

**Issue by ysysbaobei** [longitachi/ZLPhotoBrowser#119]
系统相册中的大像素图（4961x3508），setSelectImageBlock获取到的images大小为1000x708，图片像素缩小不清晰了。

请大神解决下，大像素图和长图选择出来模糊不清的问题，谢谢！

**Comment by longitachi** [comment]
暂时没有找到解决获取原图之后而不压缩导致内存升高的办法

看下这个#118，之前是获取的原图，获取之后做了一个相应的缩放，相对不缩放内存会省下很大一部分。 就比如这个issue，一下选择100张原图，直接内存暴涨导致崩溃。所以又做了一个优化，在请求原图时候就进行一个缩放，但这样确实会又出现了你提的这个问题。

**Comment by longitachi** [comment]
最新版本会修改图片压缩方式，保证原图图片尺寸不变

**Comment by ysysbaobei** [comment]
支持大神

**Comment by longitachi** [comment]
新版本修改了压缩方式，可以试下

**Comment by ysysbaobei** [comment]
增加了shouldAnialysisAsset接口，能否在shouldAnialysisAsset=NO的情况，给出[actionSheet setSelectImageBlock:^(NSArray<UIImage *> * _Nonnull images, NSArray<PHAsset *> * _Nonnull assets, BOOL isOriginal) {}];中如何通过PHAsset获取到原图image？

**Comment by longitachi** [comment]
ZLPhotoManager中
```
/**
 获取原图data，转换gif图
 */
+ (void)requestOriginalImageDataForAsset:(PHAsset *)asset completion:(void (^)(NSData *, NSDictionary *))completion;

/**
 * @brief 获取原图
 */
+ (void)requestOriginalImageForAsset:(PHAsset *)asset completion:(void (^)(UIImage *, NSDictionary *))completion;
```

**Comment by ysysbaobei** [comment]
能否在项目中把shouldAnialysisAsset为YES和NO的例子补充完整？我这边试了下，处理有问题

**Comment by longitachi** [comment]
我去看下，如果不是一下选择几十张图片的原图，没必要设置为NO

**Comment by ysysbaobei** [comment]
我这边需要一次选择几百张照片原图，还需要根据原图得到缩略图。能否把官方项目里的例子写详细一点，感觉我这边的代码还是存在内存问题

**Comment by longitachi** [comment]
pod2.5.0.1 提供了逐个解析方法

**Comment by ysysbaobei** [comment]
谢谢大神。
能否提供shouldAnialysisAsset=NO时对于gif，livephoto和视频的批量处理

**Comment by ysysbaobei** [comment]
还有个问题，如何将系统相册中的多个视频批量保存到app的documents下？

**Comment by longitachi** [comment]
1、现在对于gif、livephoto、video，都处理得有一个第一帧封面图，关于播放的话，可单个点击哪个播放那个，当然可以使用框架内提供的预览api。
2、你说的这个视频批量导出，暂时没有这个功能，不过框架提供的视频编辑功能中，有保存到本地沙盒的方法，你可以在拿到asset数组后自行扩展
