### ISSUE TITLE
照片选择返回结果

### ISSUE THREAD

**Issue by yuditxj** [longitachi/ZLPhotoBrowser#12]
返回的结果是image数组，会不会很占内存？是不是返回一个路径更合适？

**Comment by longitachi** [comment]
这是从相册里面选择的，如果我不解析成UIImage对象给你，也是没办法给你路径的。
或不然要给你PHAsset的对象自己去解析了(不存在路径这一说的)，还有就是你只要不自己在回调block中产生循环引用，返回的图片数组是会被释放掉的。 你可以用instruments进行一个内存的检测。

**Comment by ApeHC** [comment]
你好, 返回的selectPhotoModels数组, 遍历的时候娶不到asset属性, 请问为什么, 因为我这里会上传图片有普通图片和Gif图片, 需要拿到图片的其他信息

**Comment by longitachi** [comment]
![temp](https://cloud.githubusercontent.com/assets/11711768/22912338/d9273964-f29f-11e6-8d75-87814c3e7da3.png)
怎么会没有asset属性呢，我这边测试都能拿到

**Comment by ApeHC** [comment]
这样是能拿到, 但是用点语法取不到,报属性不存在,例如: model.asset  ,不知道是不是我的方式不对

**Comment by longitachi** [comment]
你导入 ZLSelectPhotoModel 头文件就行了

**Comment by longitachi** [comment]
下次更新时候我把这个头文件放到.h里面。

**Comment by ApeHC** [comment]
才看见, 可以了,谢谢
