### ISSUE TITLE
pod2.5.0.1提供逐个解析方法，解决添加大量图片崩溃

### ISSUE THREAD

**Issue by sprother** [longitachi/ZLPhotoBrowser#120]
添加250张图片崩溃:CGSImageDataLock: Cannot allocate memory
建议保留只获取phasset对象回调 不加载图片啊 现在的接口是把图片和assets都回调,添加图片多了吃不消

**Comment by longitachi** [comment]
#118

**Comment by longitachi** [comment]
如果不回调image的话，使用者在单独进行解析岂不是很麻烦，在#118这个issue里做了优化

**Comment by sprother** [comment]
我觉得看情况吧 图片太多一般都是添加到队列 上传的时候再取出图片上传 麻烦是麻烦点 不会出现内存问题,但对于几十张的来说直接取出来应该没啥问题 我这种三百张的需求会爆炸-.-所以我觉得两种接口应该同时存在,一般人不会传那么多图片,真遇到了,感觉呗掐住了颈部似的 哈哈

**Comment by longitachi** [comment]
你先按照 #118  中说的方法试一下

**Comment by longitachi** [comment]
最新版本会添加一个参数 `shouldAnialysisAsset` 控制是否进行解析图片

**Comment by sprother** [comment]
嘿嘿 好的 谢谢

**Comment by ysysbaobei** [comment]
我觉得看情况吧 图片太多一般都是添加到队列 上传的时候再取出图片上传 麻烦是麻烦点 不会出现内存问题,但对于几十张的来说直接取出来应该没啥问题 我这种三百张的需求会爆炸-.-所以我觉得两种接口应该同时存在,一般人不会传那么多图片,真遇到了,感觉呗掐住了颈部似的 哈哈
----------新增的只保留phasset对象回调的接口，能否在回调的block例子里写完整，如何获取到原图？
获取不到原图实在是个大问题
