### ISSUE TITLE
添加字典扩展导致的错误

### ISSUE THREAD

**Issue by LiberalChen** [longitachi/ZLPhotoBrowser#122]
![image](https://user-images.githubusercontent.com/19303164/31933665-596a4e50-b86f-11e7-9407-9c350d0f8c43.png)
![image](https://user-images.githubusercontent.com/19303164/31933745-9e8b6212-b86f-11e7-8c66-d332ee6a9a4b.png)

wo'zai我在项目中给NSDictionary加了上面的分类，在选择图片的时候崩溃了

**Comment by longitachi** [comment]
这根框架没关系吧，你自己调试下啥原因
