### ISSUE TITLE
如果我不需要原图呢？

### ISSUE THREAD

**Issue by paopaoping** [longitachi/ZLPhotoBrowser#123]
因为我是要上传图片的，要保证上传速度，用户体验，如果我不想让用户能够点击原图，有什么方法属性可以屏蔽原图按钮

**Comment by longitachi** [comment]
暂时没有接口可以屏蔽原图按钮，后续会加上，框架内虽然显示的原图，但是只是保证了尺寸不变的情况下进行了大小的压缩，所以10M左右的照片大约只有500kb左右，如果还大的话，你可以在拿到图片后做一个大小压缩

**Comment by longitachi** [comment]
pod 2.5.0.1 提供了该参数，控制是否可以选择原图
