### ISSUE TITLE
当系统使用tabbar的时候有明显bug

### ISSUE THREAD

**Issue by meliuxudong** [longitachi/ZLPhotoBrowser#124]
有tabbar的页面调用zlactionsheet后，打开一个预览图，然后左上角返回，点击屏幕收回弹窗的时候，屏幕里控件计算高度时候并没有计算tabbar高度，导致整个view超出屏幕一个tabbar高度。hide的函数没有起到作用，连系统的tableviewcontroller高度都是不对的。你可以放一个控件在底部，下面约束底边，看这个情况，或者直接看tabbleviewcontroller 下部的情况。

**Comment by meliuxudong** [comment]
最后我的解决方案是 在调用你这个程序的界面加上这个。
- (void)viewWillAppear:(BOOL)animated{
    [super viewWillAppear:animated];
    self.tabBarController.tabBar.hidden = NO;
}

你hide函数中的self.tabBarController.tabBar.hidden = NO；没有起作用

**Comment by longitachi** [comment]
好的，有空了我会先测试一下

**Comment by longitachi** [comment]
找到问题所在了，问题出现在iOS11上，在非iPhone X设备上多计算了一个safeareainserts.bottom
