### ISSUE TITLE
请教一下，一个流程问题

### ISSUE THREAD

**Issue by Samuel-liuse** [longitachi/ZLPhotoBrowser#128]
ZLPhotoActionSheet *actionSheet = [[ZLPhotoActionSheet alloc] init];
    actionSheet.maxSelectCount = 1;
    actionSheet.sender = self.rootViewController;
    actionSheet.sortAscending = NO;
    actionSheet.allowEditImage = YES;
    actionSheet.clipRatios = @[GetClipRatio(1,1)];
    actionSheet.editAfterSelectThumbnailImage = YES;

    [actionSheet showPhotoLibrary];
如此，单选图片，强制默认1:1比例，默认相册入口。
当我从相册选择照片能进入照片编辑页面，
但我点击拍照，拍照完成后确定选择照片，直接回调了，不会进入编辑照片。
不知道这是不是流程的问题。

其他小建议 
1、单选，默认相册点击-进入编辑 流程-在底部tab的文字可以隐藏掉
2、编辑页面 切换横竖按钮在只有1:1比例的时候 可以隐藏掉

感恩作者无私奉献

**Comment by longitachi** [comment]
这样设置拍照后没有进入编辑界面应该算个bug，后面会修复下，后续更新会采纳提出的建议

**Comment by Samuel-liuse** [comment]
更新 2.5.0.2 了，actionSheet.clipRatios = @[GetClipRatio(1,1)];  这句话失效了，如果只设置一个就是默认是custom了。

`ZLPhotoActionSheet *actionSheet = [[ZLPhotoActionSheet alloc] init];
    //设置照片最大预览数
//    actionSheet.maxPreviewCount = 20;
    //设置照片最大选择数
    actionSheet.maxSelectCount = 1;
    actionSheet.sender = self.rootViewController;
    actionSheet.sortAscending = NO;
    actionSheet.allowEditImage = YES;
    actionSheet.clipRatios = @[GetClipRatio(1,1)];
    actionSheet.editAfterSelectThumbnailImage = YES;
    actionSheet.navTitleColor = [UIColor whiteColor];
    actionSheet.navBarColor = self.rootViewController.navigationController.navigationBar.backgroundColor;
    actionSheet.bottomViewBgColor = [UIColor blackColor];
    
    actionSheet.bottomBtnsNormalTitleColor = [UIColor clearColor];
    actionSheet.bottomBtnsDisableBgColor = [UIColor clearColor];
    [actionSheet setSelectImageBlock:^(NSArray<UIImage *> * _Nonnull images, NSArray<PHAsset *> * _Nonnull assets, BOOL isOriginal) {
        //your codes
    }];`

**Comment by Samuel-liuse** [comment]
`if (![self shouldHideClipRatioView]) {
        //这只是初始坐标，实际坐标在viewdidlayoutsubviews里面布局
        _menuScroll = [[UIScrollView alloc] initWithFrame:CGRectMake(0, 0, kViewWidth-70, 80)];
        _menuScroll.backgroundColor = [UIColor clearColor];
        _menuScroll.showsHorizontalScrollIndicator = NO;
        _menuScroll.clipsToBounds = NO;
        [self.view addSubview:_menuScroll];
        //旋转按钮
        UIView *view = [[UIView alloc] init];
        view.backgroundColor = [[UIColor whiteColor] colorWithAlphaComponent:.8];
        [self.view addSubview:view];
        _rotateBtn = [UIButton buttonWithType:UIButtonTypeCustom];
        _rotateBtn.frame = CGRectMake(15, 20, 40, 40);
        _rotateBtn.imageView.contentMode = UIViewContentModeScaleAspectFit;
        [_rotateBtn setBackgroundImage:GetImageWithName(@"btn_rotate") forState:UIControlStateNormal];
        [_rotateBtn addTarget:self action:@selector(pushedRotateBtn:) forControlEvents:UIControlEventTouchUpInside];
        [view addSubview:_rotateBtn];
    }`

**Comment by Samuel-liuse** [comment]
ZLEditViewController.h
line 448

if (![self shouldHideClipRatioView]) {
        //这只是初始坐标，实际坐标在viewdidlayoutsubviews里面布局
        _menuScroll = [[UIScrollView alloc] initWithFrame:CGRectMake(0, 0, kViewWidth-70, 80)];
        _menuScroll.backgroundColor = [UIColor clearColor];
        _menuScroll.showsHorizontalScrollIndicator = NO;
        _menuScroll.clipsToBounds = NO;
        [self.view addSubview:_menuScroll];
        //旋转按钮
        UIView *view = [[UIView alloc] init];
        view.backgroundColor = [[UIColor whiteColor] colorWithAlphaComponent:.8];
        [self.view addSubview:view];
        _rotateBtn = [UIButton buttonWithType:UIButtonTypeCustom];
        _rotateBtn.frame = CGRectMake(15, 20, 40, 40);
        _rotateBtn.imageView.contentMode = UIViewContentModeScaleAspectFit;
        [_rotateBtn setBackgroundImage:GetImageWithName(@"btn_rotate") forState:UIControlStateNormal];
        [_rotateBtn addTarget:self action:@selector(pushedRotateBtn:) forControlEvents:UIControlEventTouchUpInside];
        [view addSubview:_rotateBtn];
    }

**Comment by longitachi** [comment]
😓 我看下

**Comment by longitachi** [comment]
更新了下，你可以先在 `- (void)setCropMenu` 这个方法里把下面代码删除
```
if (![self shouldHideClipRatioView]) {
    return
}
```
在 `- (void)viewDidLayoutSubviews` 方法作如下更改
```
if (hideClipRatioView) {
        _rotateBtn.hidden = YES;
        _menuScroll.hidden = YES;
    } else {
        _rotateBtn.superview.frame = CGRectMake(kViewWidth-70-inset.right, kViewHeight-128-inset.bottom, 70, 80);
        _menuScroll.frame = CGRectMake(inset.left, kViewHeight-128-inset.bottom, kViewWidth-70-inset.left-inset.right, 80);
    }
```
