### ISSUE TITLE
好几次调用相册都crash在这个地方，请赶紧看看 —— 2.4.6版本已解决

### ISSUE THREAD

**Issue by JianmingFu** [longitachi/ZLPhotoBrowser#129]
![a6d51f88-a4ee-46d5-919e-32dbdbda1cc9](https://user-images.githubusercontent.com/26958858/32266549-c69a37ec-bf22-11e7-84b8-8e0e43cc0a3a.png)

**Comment by longitachi** [comment]
这是哪个版本？

**Comment by JianmingFu** [comment]
pod  ZLPhotoBrowser (2.4.5)

**Comment by JianmingFu** [comment]
不是每次都能浮现，但是遇到过几次

**Comment by longitachi** [comment]
你更新下最新版本，2.4.5貌似是会有这个问题

**Comment by JianmingFu** [comment]
不得不说，相册调起的速度还是挺快的。
