### ISSUE TITLE
请教一个崩溃问题，急

### ISSUE THREAD

**Issue by yaoyongkang** [longitachi/ZLPhotoBrowser#130]
当进入相册点返回按钮时，返回到照片界面时如图
![img_0481](https://user-images.githubusercontent.com/16550349/32309572-8137e5f0-bfc7-11e7-9921-4487b9252305.PNG)
点击任意cell都会崩溃，崩溃点指向
![f99d8ed0-61ce-4d78-85e7-337f92826424](https://user-images.githubusercontent.com/16550349/32309613-da15b74c-bfc7-11e7-9946-4ccd0a698eb3.png)
日志输出为
![4d2e7228-6962-4d9b-bb6c-def6a9844fb7](https://user-images.githubusercontent.com/16550349/32309651-14b1163a-bfc8-11e7-882b-7413a8ebf30f.png)
这个crash问题该怎么解决？

**Comment by longitachi** [comment]
什么版本？

**Comment by yaoyongkang** [comment]
框架是我从demo中直接copy到项目中的，没有使用pod，手机系统是11.0.3的，因为使用pod下来的版本的ZLPhotoActionSheet类与demo中的ZLPhotoActionSheet类中的属性相差很远，pod下来的很多属性被取消了，所以用的是demo的框架，不过demo框架中在手机上运行是没问题的，所以很好奇是不是某个属性没设置导致crash还是其他的原因导致crash

**Comment by yaoyongkang** [comment]
不对，大神，我的意思是我使用pod后下来最新版本的ZLPhotoActionSheet类中，allowSelectImage，allowSelectGif，allowEditImage等等的属性都没有了

**Comment by longitachi** [comment]
不会吧，我试试

**Comment by yaoyongkang** [comment]
会不会与我使用pod的命令有关？我使用的pod命令是pod install --verbose --no-repo-update

**Comment by yaoyongkang** [comment]
刚刚我查看了一下，我使用pod下来的版本是2.0.4的。。。为什么pod下来的版本不是最新的？

**Comment by longitachi** [comment]
执行下 `pod setup`

**Comment by yaoyongkang** [comment]
👌，我执行一下pod setup看看

**Comment by yaoyongkang** [comment]
大神，我把pod setup执行完更新到最新的2.5.0.1版本后，还是会出现以上的问题，而且我发现，无论我把使用这个库的触发方法写在项目的任何一个地方都会出来这个崩溃，所以很想知道原因是什么，我用自己写的demo使用相同的方法都没有问题，就是项目中不可以，好郁闷

**Comment by longitachi** [comment]
你把项目中关于这个框架的东西先全部删掉，然后pod试一下

**Comment by yaoyongkang** [comment]
好的，我先试试一下

**Comment by yaoyongkang** [comment]
刚刚试过了，还是不行，出现同样的问题

**Comment by longitachi** [comment]
不好意思，这个确实没遇到过，看你的报错截图，像是UIKit里面的，清理下项目重启xcode呢？

**Comment by yaoyongkang** [comment]
清理的方式都试过了，还是不行，我得好好研究一下bug出现的原因，到时候再反馈一下
