### ISSUE TITLE
ZLPhotoActionSheet.m的- (void)showPreview:(BOOL)preview animate:(BOOL)animate函数里：[self showNoAuthorityVC];会执行2次

### ISSUE THREAD

**Issue by ysysbaobei** [longitachi/ZLPhotoBrowser#132]
隐私中没开启相册权限时，
ZLPhotoActionSheet.m的- (void)showPreview:(BOOL)preview animate:(BOOL)animate函数里：[self showNoAuthorityVC];会执行2次

**Comment by longitachi** [comment]
刚试了下，确实会走两遍，我看下
