### ISSUE TITLE
新增自行切换框架语言api

### ISSUE THREAD

**Issue by ysysbaobei** [longitachi/ZLPhotoBrowser#133]
问下新增自行切换框架语言api是什么意思？以前的版本在多语言上有什么问题？

**Comment by longitachi** [comment]
没有问题，就是新增了一个功能，有些app可以手动切换语言，新增的api可以设置跟随系统(即之前的)，也可以手动设置语言

**Comment by ysysbaobei** [comment]
明白了，谢谢
