### ISSUE TITLE
2.5不支持pod集成

### ISSUE THREAD

**Issue by Eelson126** [longitachi/ZLPhotoBrowser#134]
2.5不支持pod集成

**Comment by longitachi** [comment]
我刚才试了下，可能是因为pod版本号的问题，如果是2.5.0.* 的格式  那么就对于2.5.0的版本只能装最新的2.5.0.*版本，也就是2.5.0和2.5.0.1都不在支持。   我以后会避免这种版本号格式

**Comment by longitachi** [comment]
我试了下MJRefresh，中间也会有几个版本 `3.0.9~3.1.14.1` 不能安装
