### ISSUE TITLE
希望大神做一下向下兼容

### ISSUE THREAD

**Issue by LGLee** [longitachi/ZLPhotoBrowser#135]
1. 支持一下Xcode8,iOS的低版本,现在还有好多人用5s版本的
2. 使用pods下来 @available(iOS 11, *)这个错能兼容一下吗,为了升级,我们一般都不会去改pod里面的东西吧

**Comment by longitachi** [comment]
你好，现在iPhone X出来了，你们的项目应该也会适配的吧？ 
`@available(iOS 11, *)` 倒是好说，改一下判断版本方法就好了， 但是项目里使用了iOS11的api `safeAreaInsets` 去适配iPhone X，所以xcode8 也会报没有这个api的错
