### ISSUE TITLE
预览图片可以加入点击图片消失预览的功能吗 —— pod 2.7.4已添加下拉返回

### ISSUE THREAD

**Issue by TonyYuChufang** [longitachi/ZLPhotoBrowser#136]
希望老哥能够加入这个功能

**Comment by longitachi** [comment]
根据后面扩展情况，考虑在内

**Comment by eric1202** [comment]
或者增加一个一个点击事件的回掉

**Comment by longitachi** [comment]
emmmm，近期会添加下拉返回的功能。

**Comment by eric1202** [comment]
ZLPhotoActionSheet showPhotoLibraryWithSender 选择的时候可以下拉
ZLPhotoActionSheet previewPhotos preview预览的时候不能下拉 

在ZLShowBigImgViewController 87行 `if (self.canInteractivePop) {` 强行改也会有问题

**Comment by longitachi** [comment]
预览时候是present出来的导航，现在不支持这个逻辑。只支持从小图界面到大图界面的返回
