### ISSUE TITLE
iphone6s plus ios10.3.3真机崩溃, ios11不会崩溃 —— 详见readme中问答第二条

### ISSUE THREAD

**Issue by chenjiangui** [longitachi/ZLPhotoBrowser#137]
如上
![29da437a-2fc6-4701-9e32-f407be797f28](https://user-images.githubusercontent.com/18565140/32530087-b2a46fe4-c401-11e7-9b58-e1508ed42b6f.png)

**Comment by longitachi** [comment]
这个问题readme里面已经写明了
![4f7c6515-78ae-42a8-a46b-a0da4592e86a](https://user-images.githubusercontent.com/11711768/32530406-ff9b2532-c478-11e7-87d7-6ce9f28527d6.png)

**Comment by 15394537523** [comment]
我就是xcode9,也会报错?

**Comment by longitachi** [comment]
看红框里的，不是xcode版本的问题，是pod版本，从2.4.3以下更新上来会有问题

**Comment by chenjiangui** [comment]
好吧 我没用pod  ios10.3.3崩溃 ios8.4正常 ios11正常

**Comment by chenjiangui** [comment]
我用pod试试

**Comment by longitachi** [comment]
你按照上面的方法清理一下试试
