### ISSUE TITLE
一直被PLeakSniffer检测到内存泄漏

### ISSUE THREAD

**Issue by czl0325** [longitachi/ZLPhotoBrowser#139]
兄弟，你的ZLPhotoBrowser一直被PLeakSniffer检测到内存泄漏啊。不知道为什么泄漏。。。

在你有选择照片的时候，退出当前页面就提示内存泄漏了。

**Comment by longitachi** [comment]
明天我看下，没见过这个PLeakSniffer框架，明天试试

**Comment by longitachi** [comment]
你好，我用了下MLeaksFinder检测了下，没有提示内存泄漏，而且你可以在 dealloc 方法里面打印日志，都是有走该方法的
