### ISSUE TITLE
支持国际化

### ISSUE THREAD

**Issue by mouse-lin** [longitachi/ZLPhotoBrowser#14]

**Comment by mouse-lin** [comment]
我在 Fork 的分支已经实现国际化了(简体中文、英文、日文、繁体中文)，等我整理好再提了 PL 过来

**Comment by longitachi** [comment]
好的

**Comment by zzgo** [comment]
刚好也想求国际化。不过我的建议，是暴露设置文字的接口，然后由使用者自己传值过去。

**Comment by longitachi** [comment]
你说的暴露设置文字的接口是什么意思，是里面显示的字体之类的暴露给使用者？ 要是这个的话就不用了太麻烦。  最近两天我会更新下国际化，根据机身语言显示不同语言

**Comment by zzgo** [comment]
嗯，辛苦作者了。我这里需求是英语，德语，法语，葡萄牙语。希望支持。

**Comment by longitachi** [comment]
最近较忙，我目前只准备支持  中（简繁）英日，到时候你需要的话，添加在bundle文件下添加对应的Localizable.strings 并加上对应语言的翻译即可

**Comment by longitachi** [comment]
还有就是我也不懂这些语言，翻译起来难免会不准确- -

**Comment by zzgo** [comment]
木事。有地方改就行。看到你很多好用的作品，向你学习

**Comment by longitachi** [comment]
已经更新了，你可以拉一下，切换模拟器或手机语言测下
