### ISSUE TITLE
选择图片后再次打开图库后能标记已选择的图片继续添加

### ISSUE THREAD

**Issue by ios-zl** [longitachi/ZLPhotoBrowser#140]
我这里想继续添加图片,但是每次都是从0开始选择图片,非常麻烦,你这里有继续上次图片选择的功能吗？
有没有单纯的预览模式,预览图片不允许再次选择直接查看已选择图片呢？ 
望解答,谢谢。

**Comment by longitachi** [comment]
有的，你看下 `arrSelectedAssets` 这个属性，看下demo， 记录上次已选择的图片，把回调给你的asset数组传入即可

**Comment by ios-zl** [comment]
选中问题解决了,tks。
你写的库很棒,解决了我很多图片相关操作需求。不过我这边用swift调用这个库功能还是有些繁琐，有想过移一个单纯图片选择展示的Swift版本么？

**Comment by longitachi** [comment]
swift版本写了一部分，中间遇到点问题，解决不了，就不想再写了

**Comment by ios-zl** [comment]
你好，我这里又出了点状况。
选择图片后点击图片预览,当我使用previewSelectedPhotos方法以后,再使用showPreview不会出现图片选择器了,我希望预览后还能继续添加照片,应该怎么做呢？

**Comment by longitachi** [comment]
你用demo试一下会不会出现这种情况， 我刚才用demo试了下 选择照片之后，点击图片预览，然后调用 `showPreviewAnimated:` 这个方法是可以出现预览快速选择视图的，调用直接进入相册的也是可以的

**Comment by ios-zl** [comment]
唔...
我看了你最新的Demo,点击预览图片和显示相册调用的是不同的photoActionSheet。

因为用户有可能会多次选择添加图片,如果选择你这种方式多次初始化,内存有可能会增加很多。
所以我这里用的全局photoActionSheet来选择、显示图片,它只有一个对象,当previewSelectedPhotos以后，showPreview的方法没有生效,咱们的情况不同呢。

你这里是不是应该增加一个单例对象,保持内存平衡呢？

**Comment by longitachi** [comment]
我这边测试多次初始化并不会导致内存增加，只有在第一次初始化时候会增加一些内存，后续初始化保持不变，浮动很小。
![d652420e-fb9b-41c2-89f3-14a884831754](https://user-images.githubusercontent.com/11711768/32881564-9e9f63b8-caec-11e7-8a78-b14b84120c3f.png)

**Comment by longitachi** [comment]
你先在 ZLPhotoActionSheet 中的 `- (ZLShowBigImgViewController *)pushBigImageToPreview:(NSArray *)photos index:(NSInteger)index` 这个方法内，把 `self.preview = NO;` 这一行代码注释掉即可

**Comment by ios-zl** [comment]
唔...
使用了你上述方案,然后点击预览也会出现图片选择器,看来还是不行呢。
还是使用你Demo中的创建方案好了。

在我没有选择原图的情况下,我这边选择8张图片内存暴涨了60M，这个应该选择图片时图片解析的锅吧？

**Comment by longitachi** [comment]
这跟你选择的图片大小也有一定的关系，如果内存涨的多，你可以采用框架里提供的逐个解析方法，即设置`shouldAnialysisAsset`为NO，然后按照demo中提供方法，对比下内存增长情况

**Comment by ios-zl** [comment]
好的,我会尝试降低图片内存这一块的操作。
给你个建议,把你项目按照市场常见需求做几个模式进行拓展,例如单图片的头像选择、裁剪与上传,照片预览。多图片选择、预览。单独照片裁剪、音频选择、视频选择。(多开几个项目骗几个Star还不是美滋滋,ac娘正经脸.jpg)
非常感谢你的开源,项目非常棒。

**Comment by longitachi** [comment]
头像选择之类的感觉过于简单，没必要单独拎出来，  裁剪的话，太多好用的框架了，框架中的裁剪也是借鉴了CLImageEditor的代码， 视频编辑倒是可以考虑拎出来
