### ISSUE TITLE
状态栏样式

### ISSUE THREAD

**Issue by xiuluodaren** [longitachi/ZLPhotoBrowser#142]
首先感谢您的无私奉献，给大家提供了如此方便优秀的图片多选框架。
本人在使用过程中有一个小小的bug:
在进入相册界面的时候系统状态栏样式变成了   UIStatusBarStyleLightContent  查看源代码发现是由于在
ZLPhotoBrowser.m 的viewWillAppear方法中指定了状态栏样式为 UIStatusBarStyleLightContent，并未使用属性 previousStatusBarStyle，而且属性previousStatusBarStyle也是私有属性。如果设计允许的话是否可以将该属性改成普通属性？然后在ZLPhotoBrowser.m 的viewWillAppear中使用previousStatusBarStyle指定状态栏样式呢？

**Comment by longitachi** [comment]
你好，谢谢提出意见，后续版本会更新将状态栏样式api公布出来
