### ISSUE TITLE
降序获取视频顺序有问题

### ISSUE THREAD

**Issue by ysysbaobei** [longitachi/ZLPhotoBrowser#145]
正常部分：
升序即ZLPhotoActionSheet的sortAscending = YES;获取照片和视频，最新的照片和和视频都在底部；
降序获取照片，最新照片在顶部；

异常部分：
降序即ZLPhotoActionSheet的sortAscending = NO;获取视频，最新视频部分在底部、部分在中间，部分在底部；而iPhone自带的照片app里，顺序正常；------我的app里拍摄了视频，存在app里，然后保存到iPhone自带的照片app里，用zlPhotoBroswer获取顺序正常；  不正常的部分是：我的app里以前用itunes文件共享导入了一些视频，这些视频保存到iPhone自带的照片app里，用zlPhotoBroswer获取顺序不正常，最新视频部分在底部、部分在中间，部分在底部

**Comment by longitachi** [comment]
你好，麻烦你用微博和简书看一下，顺序是否有问题？

**Comment by ysysbaobei** [comment]
微博的视频顺序和iPhone自带的“照片”app的顺序一样；
zlPhotoBroswer降序获取视频的顺序有问题，用itunes导入的视频位置在最后，新拍摄的视频在最前端；微博的itunes导入的视频和新拍摄的视频都在一起

**Comment by longitachi** [comment]
好的，我检查下

**Comment by longitachi** [comment]
你好，你把`+ (ZLAlbumListModel *)getCameraRollAlbumList:(BOOL)allowSelectVideo allowSelectImage:(BOOL)allowSelectImage`这个方法里 排序方式 @"creationData" 这个 字符串换成 @"modificationData" 试一下有问题没

**Comment by longitachi** [comment]
这样貌似更乱了。。。

**Comment by harry-zhao1234** [comment]
后续有解决这个问题么

**Comment by longitachi** [comment]
没有解决，没找到解决办法

**Comment by longitachi** [comment]
已解决顺序错误的问题，不过暂未发版，这周会随着`4.0.3`版本发布
