### ISSUE TITLE
关于相册导航栏标题“Camera Roll”的问题

### ISSUE THREAD

**Issue by ElliotXY** [longitachi/ZLPhotoBrowser#146]
您好，我发现，无论是demo还是实际的代码，多语言的时候，这个相册的导航栏标题一直是“Camera Roll”，无法随着多语言而改变，请查阅！

**Comment by longitachi** [comment]
你看下readme里面，是不是忘记添加 `Localized resources can be mixed` 这个key了

**Comment by longitachi** [comment]
懂你的意思了，你应该是使用的手动切换语言，看下这个注释，手动切换语言，只能切换框架内定义的多语言，值域相册的名字，暂时只能根据手机系统语言
```
/**
 框架语言，默认 ZLLanguageSystem (跟随系统语言)
 仅切换框架内定义的语言，由于相册名字根据系统语言进行获取，所以相册列表界面为当前系统语言
 */
@property (nonatomic, assign) ZLLanguageType languageType;
```

**Comment by ElliotXY** [comment]
对，谢谢，希望下一版改进一下，修改成可以自定义或者跟随资源文件改变。

**Comment by ElliotXY** [comment]
希望相册名称可以也能手动更改啊，中文状态下出现 Camera Roll 很别扭的

**Comment by longitachi** [comment]
2.5.3版本 已优化这个问题

**Comment by ElliotXY** [comment]
谢谢
