### ISSUE TITLE
视频上传怎么上传

### ISSUE THREAD

**Issue by lzc12313** [longitachi/ZLPhotoBrowser#147]

**Comment by longitachi** [comment]
你拿到asset对象后，可以使用 `ZLPhotoManager` 中的 `requestVideoForAsset:completion:` 方法，在回调的 info 字典中，有视频的路径，上传即可

**Comment by lzc12313** [comment]
打印出来这个    PHImageFileSandboxExtensionTokenKey = "89a0e78700cef83db801a8ce9261304532444bbd;00000000;00000000;000000000000001b;com.apple.avasset.read-only;01;01000003;0000000101018a92;/private/var/mobile/Media/DCIM/100APPLE/IMG_0383.MOV";这个key里面好多值的

还有,视频可以转换为mp4吗,里面的好像是mov

**Comment by longitachi** [comment]
视频转换我倒是没做过，应该可以吧，你搜搜资料
