### ISSUE TITLE
代码带有入侵性 会在相册自动生成一个ZLPhotoBrowser的相册，还有就是编辑视频和图片存在bug  当我如此设置后，还是无法编辑照片和视频

### ISSUE THREAD

**Issue by EdwinXiang** [longitachi/ZLPhotoBrowser#148]
![image](https://user-images.githubusercontent.com/15166467/33240609-9e7a29a4-d2f3-11e7-948d-d66c8b6ec5b0.png)
ZLPhotoActionSheet *ac = [[ZLPhotoActionSheet alloc] init];
    
    //相册参数配置
    ZLPhotoConfiguration *configuration = [ZLPhotoConfiguration defaultPhotoConfiguration];
    configuration.allowEditVideo = YES;
    configuration.allowEditImage = YES;
    ac.configuration = configuration;
    
    //如调用的方法无sender参数，则该参数必传
    ac.sender = self;
    //选择回调
    [ac setSelectImageBlock:^(NSArray<UIImage *> * _Nonnull images, NSArray<PHAsset *> * _Nonnull assets, BOOL isOriginal) {
        
    }];
    
    //调用相册
    [ac showPhotoLibrary];

**Comment by longitachi** [comment]
你好，不是带有侵入性，而是在拍照、录视频、保存编辑的照片、编辑视频后 需要保存到相册，相册名字为软件名字，不是固定位ZLPhotoBrowser，编辑图片及视频我这边暂时没有点出来bug，不过编辑视频后回调没在主线程，稍后会优化更新一下版本
