### ISSUE TITLE
裁剪视频后视频裁剪界面一直存在，而不是回到相册选择界面或者直接退出相机拿到裁剪后的地址，并且作为三方库，建议视频拍摄和裁剪后的格式都适用mp4，这样ios和安卓都通用，不需要进行格式转码

### ISSUE THREAD

**Issue by EdwinXiang** [longitachi/ZLPhotoBrowser#149]

**Comment by longitachi** [comment]
稍后会更新下，支持设置导出视频格式，由于视频存在单选及  与照片混合选择的情况，所以暂时不会回调路径，可通过 `ZLPhotoManager` 中的解析视频的方法，拿到info后去获取对应视频的路径

**Comment by longitachi** [comment]
2.5.3版本 已新增对视频格式设置的api，支持 mov, mp4, 3gp等格式

**Comment by EdwinXiang** [comment]
好的  感谢感谢  这个格式可设置是一个很好的变革
