### ISSUE TITLE
iPad 不支持

### ISSUE THREAD

**Issue by yaoyue** [longitachi/ZLPhotoBrowser#15]
在 iPad 下模拟器测试，点击选择照片，无法弹出视图，我查了已经获取到了图片，无法弹出选择图片的视图.

**Comment by yaoyue** [comment]
我查看了对应的 xib 文件，确实是以前的适配只做了针对 iPhone 的约束，谢谢作者及时更新

**Comment by yaoyue** [comment]
我查看了对应的 xib 文件，确实是以前的适配只做了针对 iPhone 的约束，谢谢作者及时更新

**Comment by mouse-lin** [comment]
刚想提个 PR，发现 @longitachi 已经修改了 👍

**Comment by longitachi** [comment]
刚修改后忘了回复了，最近有点忙- -
