### ISSUE TITLE
自定义裁减比例问题

### ISSUE THREAD

**Issue by xiuluodaren** [longitachi/ZLPhotoBrowser#150]
您好，请问裁剪图片如何自定义比例啊？您在注释中是这么说明的： 
/**
 根据需要设置自身需要的裁剪比例
 @discussion e.g.:1:1，请使用ZLDefine中所提供方法 GetClipRatio(NSInteger value1, NSInteger value2)，该数组可不设置，有默认比例，为（Custom, 1:1, 4:3, 3:2, 16:9）
 */
@property (nonatomic, strong) NSArray<NSDictionary *> *clipRatios;

可是我使用GetClipRatio方法好像无效啊？所以我修改了clipRatios属性，这个会有什么影响嘛？
 NSDictionary *dict = GetClipRatio(1, 7);
    NSLog(@"%@",dict);
    
    /**
     根据需要设置自身需要的裁剪比例
     */
    configuration.clipRatios = @[dict];

**Comment by longitachi** [comment]
我这边试了下是有效的啊？你所说的无效是不能按照1:7的比例进行裁剪？

**Comment by zzBelieve** [comment]
对的..  设置 16:9 跟9:16 是一样的裁剪框大小

**Comment by xiuluodaren** [comment]
我以为clipRatios不可设置。。。原来是得用GetClipRatio生成的字典填充。。。搞明白了
还有就是怎么锁定只能横屏裁剪啊大神？

**Comment by xiuluodaren** [comment]
我看到在  ZLRatio 的 initWithValue1方法里长短边分别取了最大和最小，所以这个大概是不能控制的？

**Comment by longitachi** [comment]
这个当时是固定宽为短边，下次更新我把这个去掉吧。
关于强制横屏这个，由于是用push的方式弹出的裁剪界面，所以不支持强制横屏

**Comment by xiuluodaren** [comment]
额。。。我的意思是能不能不让旋转比例，就是宽大于高那样的。

**Comment by zzBelieve** [comment]
<img width="488" alt="qq20171127-1 2x" src="https://user-images.githubusercontent.com/10309351/33255080-ce110a6e-d386-11e7-8d55-fec1c267f443.png">

这个不做比较大小的话就可以了.


<img width="479" alt="qq20171127-2 2x" src="https://user-images.githubusercontent.com/10309351/33255133-197a140a-d387-11e7-90e9-3b4ed4355440.png">

**Comment by xiuluodaren** [comment]
嗯，这个我暂时改了一下，现在就是旋转那我直接隐藏了旋转按钮。。。

**Comment by xiuluodaren** [comment]
绝对值最好还是加上吧，万一手癌写个负数呢。。。。

**Comment by zzBelieve** [comment]
哈哈 我也是隐藏了旋转按钮...

**Comment by scholar-ink** [comment]
有属性隐藏旋转按钮吗？@zzBelieve

**Comment by zzBelieve** [comment]
@scholar-ink  没有.
