### ISSUE TITLE
怎么获取到选取的图片路径呀

### ISSUE THREAD

**Issue by tuoyinzhou91Jon** [longitachi/ZLPhotoBrowser#151]
怎么获取到选取的图片路径呀

**Comment by longitachi** [comment]
你好，暂时回调的block中是无法获取的，如果要获取，暂时使用`ZLPhotoManager` 中 `requestImageForAsset:size:completion:`方法，根据回调中的字典中`PHImageFileURLKey`来获取。  

下个版本将会把对应路径通过回调返回过去

**Comment by longitachi** [comment]
我刚才试着改动了下，如果在回调中返回路径的话，会造成很多不必要的麻烦， 所以我准备 仅提供一个获取 路径的方法

**Comment by tuoyinzhou91Jon** [comment]
嗯嗯，静等你的更新，谢谢！
我是从requestOriginalImageForAsset 里面调取了图片的路径。
