### ISSUE TITLE
自定义拍照

### ISSUE THREAD

**Issue by Eesnh** [longitachi/ZLPhotoBrowser#152]
选择自定义拍照，拍摄的视频，点击确定后，控制的打印这个错误

[avas] AVAudioSession.mm:1177:-[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

**Comment by Eesnh** [comment]
你好，自定义拍摄视频，获取的缩略图为nil

**Comment by longitachi** [comment]
保存到相册成功了吗？
