### ISSUE TITLE
导出的视频有压缩吗 ——  pod 2.5.5版本已支持

### ISSUE THREAD

**Issue by CHENDONGY** [longitachi/ZLPhotoBrowser#155]
要上传视频，现在拿到的视频是经过压缩的吗。或者有提供压缩方法自行压缩

**Comment by longitachi** [comment]
视频没有压缩，还没有提供压缩的方法，你可以先自己进行压缩，后续版本会在api中加入压缩的方法

**Comment by CHENDONGY** [comment]
@longitachi 好的，正准备更换使用你的项目。希望能提供视频压缩这个api

**Comment by longitachi** [comment]
你可以先修改为 `AVAssetExportPresetMediumQuality`，这个我测试了下，15.7M的视频，导出后大约2.5M左右

**Comment by CHENDONGY** [comment]
好的，谢谢
