### ISSUE TITLE
视频如何判断是否在本地？

### ISSUE THREAD

**Issue by x1340939306** [longitachi/ZLPhotoBrowser#156]

**Comment by longitachi** [comment]
框架里面有方法，`ZLPhotoManeger` 中有两个方法，第一个是解析缩略图时候拿到的data，第二个就是直接拿asset去解析视频，拿到的AVPlayerItem，如果为nil则不再本地

**Comment by x1340939306** [comment]
没有同步方法吗？

**Comment by longitachi** [comment]
第一个就是同步的 `judgeAssetisInLocalAblum`

**Comment by x1340939306** [comment]
judgeAssetisInLocalAblum这个是判断图片的，视频的也能用这个吗？

**Comment by x1340939306** [comment]
[[asset valueForKey:@"filename"] hasSuffix:@"GIF"]  这样判断gif是非法的，私有方法，审核会不会被拒？

**Comment by longitachi** [comment]
视频可以使用，用参数名怎么会是非法的。  不会被拒的

**Comment by x1340939306** [comment]
filename没有公开，是私有方法，网上说会被拒

**Comment by longitachi** [comment]
有朋友用过，上架了，没问题

**Comment by x1340939306** [comment]
ok，3Q
