### ISSUE TITLE
你的 图片 浏览器 转屏的时候的navagation是错误的  并且一些照片的显示大小也是错误的

### ISSUE THREAD

**Issue by JamWangJam** [longitachi/ZLPhotoBrowser#157]
就是 你在竖屏浏览一个图片 然后 横屏 把 navagation 隐藏 在竖屏回来 点不出来navagation 希望尽快解决 另外  图片浏览的时候的大小 于 这个图片在相册展示的大小不同

**Comment by longitachi** [comment]
好的，第一个问题刚试了下，已重现，下个版本会解决。
第二个问题图片展示大小的，如果是宽度小于屏幕宽度的话，系统相册是放大到了屏幕宽度，我是采用了不同的显示方法按照图片宽高进行显示的，QQ也是按照图片宽高进行显示的。微信是和系统相册显示方式一样。
