### ISSUE TITLE
【建议】能否提供一个直接进入相机选择界面

### ISSUE THREAD

**Issue by scholar-ink** [longitachi/ZLPhotoBrowser#159]
【建议】能否提供一个直接进入相机选择界面

**Comment by scholar-ink** [comment]
好吧，虽然可以直接改一下你的代码，但是还是希望在pod 里面有这个方法，因为习惯都是用pod管理第三方的。

**Comment by longitachi** [comment]
不太明白直接进入相机选择界面什么意思？现在提供的有预览快速选择和直接进入相册选择啊。

**Comment by scholar-ink** [comment]
额额，就是直接拍照😁

**Comment by JamWangJam** [comment]
哎 同感 就是逼着 改你代码  这还能不明白?  就是弹出个 alert  直接 选择调用相机  不 弹出你那个预览的view?  而且我发现 有内存泄漏的 地方

**Comment by longitachi** [comment]
不要预览相册的view的话，把`maxPreviewCount`设置为`0`就好了

**Comment by howedeng** [comment]
同样的问题，能多增加一个选项吗，进来时选择相册还是相机，现在要先打开相册才能使用相机，多了一步

**Comment by longitachi** [comment]
![a50a6b780a7f7e5809046d8b52469d04](https://user-images.githubusercontent.com/11711768/39361860-d2380880-4a56-11e8-8d71-1a008049ddf5.png)
这样的效果吗，这里不是可以直接拍照吗

**Comment by dong136279559** [comment]
我们需要自定义这个界面,而不是呈现这样的效果,所以希望把拍照的接口暴露出来.

**Comment by scyios** [comment]
我们也是 需要自定义界面 所以希望把 调用把直接 调用 相机 和 相册接口都露出来  虽然我们可以改你的代码 但是我觉得这是一种不尊重作者的行为
