### ISSUE TITLE
图片浏览器卡顿

### ISSUE THREAD

**Issue by liuduanwen** [longitachi/ZLPhotoBrowser#16]
我发现当push到ZLShowBigImgViewController的时候，如果加载的图片过大就会出现卡顿，加载截图之类的小图片就不会出现卡顿，往楼主解决，另外楼主pop时候设置的clearcolor 我感觉可以用 self.view.clipsToBounds = YES;这个来代替就没有问题了，希望楼主可以解决这个问题

**Comment by liuduanwen** [comment]
暂时找到的原因是option.synchronous，感觉这个应该是同步，异步问题，当push时候，默认为NO，这时候是异步加载图片，会push一半的时候完成加载，造成卡顿的假象，暂时解决方法是第一次加载控制器设synchronous为YES，后面继续设为NO(不然后面滑动cell会出现卡的问题) ;望楼主能够解决这个问题，本人photoKit没怎么看,无法做深入研究

**Comment by longitachi** [comment]
我用真机试了，这个在push或者present时候加载图片没有明显的卡顿现象啊。包括拍照的或者下载的大图

**Comment by liuduanwen** [comment]
有可能是我那台测试机性能不好吧

**Comment by longitachi** [comment]
发现问题可能是由于加载图片尺寸过大导致的稍微卡顿，最新版本已优化
