### ISSUE TITLE
按照前三个步骤设置之后出现了崩溃

### ISSUE THREAD

**Issue by yanqiuLove** [longitachi/ZLPhotoBrowser#160]
进入到我的控制器vc，点击vc中button实现如下代码：
ZLPhotoActionSheet *ac = [[ZLPhotoActionSheet alloc] init];
    //相册参数配置，configuration有默认值，可直接使用并对其属性进行修改
    ac.configuration.maxSelectCount = 3;
    //如调用的方法无sender参数，则该参数必传
    ac.sender = self;
    //选择回调
    [ac setSelectImageBlock:^(NSArray<UIImage *> * _Nonnull images, NSArray<PHAsset *> * _Nonnull assets, BOOL isOriginal) {
        //your codes
    }];

最终程序崩溃在下面这行代码
self = [[kZLPhotoBrowserBundle loadNibNamed:@"ZLPhotoActionSheet" owner:self options:nil] lastObject];

**Comment by longitachi** [comment]
有错误信息吗？

**Comment by yanqiuLove** [comment]
![image](https://user-images.githubusercontent.com/19206208/33862677-e83200d0-df1e-11e7-9f01-5c11f7175af8.png)
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available

**Comment by longitachi** [comment]
是在oc项目还是swift项目中， pod集成的吗？什么系统的手机？

**Comment by yanqiuLove** [comment]
是在OC项目中，pod继承的，iPhone6  11.1.2

**Comment by yanqiuLove** [comment]
我的Xcode版本是9.1

**Comment by longitachi** [comment]
在其他测试机和模拟器上也会崩溃吗？  清理下项目试试， 不行的话你试试把 `kZLPhotoBrowserBundle` 这个宏 改成 `[NSBundle bundleForClass:[ZLPhotoBrowser class]]` 看下还崩溃不。

**Comment by yanqiuLove** [comment]
好的，我先试试，非常感谢~

**Comment by yanqiuLove** [comment]
模拟器和其他测试机（6sp 11.0.1）也是同样的错误,更换宏也是同样的问题

**Comment by longitachi** [comment]
这就有点奇怪了，我这边也是pod集成的，没遇到过这个问题。之前有个朋友issue，也是crash到这一行代码，但是原因貌似不同，https://github.com/longitachi/ZLPhotoBrowser/pull/153。 我搜搜资料 看有没有类似的情况

**Comment by yanqiuLove** [comment]
好的，我也再研究研究

**Comment by longitachi** [comment]
你把初始化方法换成这两行代码试试
`UINib *nib = [UINib nibWithNibName:@"ZLPhotoActionSheet" bundle:kZLPhotoBrowserBundle];
    self = [nib instantiateWithOwner:self options:nil].firstObject;`

**Comment by yanqiuLove** [comment]
还是不行，我把kZLPhotoBrowserBundle这个宏按照你说的那种方式改完也不可以，同一个位置
![image](https://user-images.githubusercontent.com/19206208/33870675-e86bbbf6-df49-11e7-85ee-396e90e8248b.png)

**Comment by longitachi** [comment]
好吧，实在不行你试试手动集成。或者pod删除了，重新装一下。  记得先pod setup一下

**Comment by yanqiuLove** [comment]
发现问题了，这次在使用pod安装之后报出了The process has been returned to the state before expression evaluation这个错误信息，我尝试着在ZLPhotoActionSheet的初始化中调用了一下self = [super init];并更换初始化方式，最后发现在Build Phases中找不到ZLPhotoActionSheet.xib这个文件，当然这种情况只出现在pod管理的情况下，我手动集成能够正常使用，至于为什么pod集成的时候为什么找不到ZLPhotoActionSheet.xib文件我就不知道了，平时很少用xib（老是出各种各样的问题），我再想是否可以把这个xib换掉
