### ISSUE TITLE
pod 2.5.4版本似乎没有更新

### ISSUE THREAD

**Issue by CHENDONGY** [longitachi/ZLPhotoBrowser#161]
使用 pod集成的2.5.4版本 没有 ```视频导出方法中添加压缩设置参数;```相应的api

**Comment by longitachi** [comment]
这个还没有推，等这几天看下有没有issue新bug，有的话一起改了，没的话就这两天就推上去2.5.5版本

**Comment by CHENDONGY** [comment]
提个建议呀，项目啊中的图标很多比较模糊，希望能清晰一点

**Comment by longitachi** [comment]
是图片资源吗？

**Comment by CHENDONGY** [comment]
是的，比如标识视频的那个播放资源，还有选中图片的标识都有点模糊

**Comment by longitachi** [comment]
我看下，重新切个图，等会更新下2.5.5版本

**Comment by longitachi** [comment]
pod 2.5.5已更新
