### ISSUE TITLE
判断图片是否在本地引起内存暴涨，判断了10张大概涨了90M？请问怎么处理？

### ISSUE THREAD

**Issue by x1340939306** [longitachi/ZLPhotoBrowser#162]
+ (BOOL)judgeAssetisInLocalAblum:(PHAsset *)asset
{
    PHImageRequestOptions *option = [[PHImageRequestOptions alloc] init];
    option.networkAccessAllowed = NO;
    option.synchronous = YES;
    
    __block BOOL isInLocalAblum = YES;
    
    [[PHCachingImageManager defaultManager] requestImageDataForAsset:asset options:option resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
        isInLocalAblum = imageData ? YES : NO;
    }];
    return isInLocalAblum;
}

**Comment by longitachi** [comment]
问下你是怎么去触发这个判断的？就逐个点击选择十张吗？

**Comment by x1340939306** [comment]
ZLBigImageCell 中判断是否在本地，加入一个标识，然后，暴涨了

**Comment by longitachi** [comment]
我这边试了下，无论是在本地的照片或者是在iCloud上的照片，在大图或者小图界面，去选择照片(每次选择均会触发这个判断)，内存是不会上涨的。 你现在在使用的是哪个版本？更新下最新的2.5.5试试

**Comment by x1340939306** [comment]
![cc255793-ca36-4818-8388-a22d4d43248a](https://user-images.githubusercontent.com/7719403/33971304-bfa9af88-e0b2-11e7-9755-47e6f6b3eb5a.png)
![fe252c33-3e30-4393-b98e-e052d19c6f26](https://user-images.githubusercontent.com/7719403/33971305-bfe3a35a-e0b2-11e7-88f5-687f1f311050.png)
<img width="293" alt="qq20171214-093901 2x" src="https://user-images.githubusercontent.com/7719403/33971306-c0197bc4-e0b2-11e7-94d4-d4f97a9a81bb.png">


我说错了，ZLCollectionCell在这个cell里

**Comment by longitachi** [comment]
这个方法里面是没有这句代码的吧？

**Comment by longitachi** [comment]
这个判断是否在本地，涉及到同步去解析asset，是会消耗一定的内存和占用主线程，所以不会去放到ZLCollectionCell里面频繁的调用，频繁调用会导致界面卡顿

**Comment by x1340939306** [comment]
没有，我自己加的，这边要求要有个是否在本地的标识。

**Comment by longitachi** [comment]
你好，你可以根据回调中info字典去判断
```
{
    PHImageResultDeliveredImageFormatKey = 4035;
    PHImageResultIsDegradedKey = 0;
    PHImageResultIsInCloudKey = 1;
    PHImageResultIsPlaceholderKey = 0;
    PHImageResultRequestIDKey = 255;
    PHImageResultWantedImageFormatKey = 4035;
}
```

**Comment by x1340939306** [comment]
好的，谢谢

**Comment by yingkong1987** [comment]
其实你只要用autorelease包好就行了.

上面的info也是你这个请求的返回值之一.
