### ISSUE TITLE
一个小小的问题原图按钮有点小字显不全了

### ISSUE THREAD

**Issue by wyt666** [longitachi/ZLPhotoBrowser#164]
![1de62b64607fc69bc8060d8784dfe697](https://user-images.githubusercontent.com/15173846/33982578-ef6816b8-e0eb-11e7-9eb1-52b04c18b766.png)

**Comment by longitachi** [comment]
这个是最新版本2.5.5吗？

**Comment by wyt666** [comment]
@longitachi 是最新版本2.5.5

**Comment by longitachi** [comment]
我这边用 真机 iPhone SE，iPhone 6，iPhone 7p，模拟器iPhone X测试，四种语言显示都是正常的啊。

**Comment by wyt666** [comment]
@longitachi  是xcode或系统版本的问题吗？我用的都是最新版本，iOS 11.2.5beta。  我把那个按钮宽度调大一点就显示全了
<img width="2002" alt="qq20171215-141906 2x" src="https://user-images.githubusercontent.com/15173846/34029377-3df146b2-e1a3-11e7-99c2-8d23366f33d7.png">

**Comment by longitachi** [comment]
应该是吧，说不好。我手机系统11.1.2  xcode9.1的

**Comment by zhugexiaobo** [comment]
11.2 真机/模拟器都显示不全

**Comment by longitachi** [comment]
下次更新优化一下这个
