### ISSUE TITLE
只能选择相片或视频的情况下，怎么令视频为1而不能多选。

### ISSUE THREAD

**Issue by tuoyinzhou91Jon** [longitachi/ZLPhotoBrowser#165]
只能选择相片或视频的情况下，怎么令视频为1而不能多选，并且将视频取消选择的时候再次选择相片时候，相片的最大选择数不受影响。
总结来说，相片和视频的最大选择数是独立的嘛？

**Comment by longitachi** [comment]
我有点没明白你的意思。 你可以在调相册时候选择不传入`arrSelectedAssets`就好了，就可以每次选择都是重新开始选择 设置下 `maxSelectCount = 1;`

**Comment by tuoyinzhou91Jon** [comment]
就是想实现微信朋友圈选择图片和视频的那种效果

**Comment by longitachi** [comment]
就是每次都重新选择呗？那就按我刚才说的就行，demo里面不是有记录上次选择这个uiswitch吗？你可以看下

**Comment by Henry519** [comment]
就是不能混合选择的时候，视频没有选择状态按钮，且点击视频就直接退出选择页面返回选择值了，建议作者参考下微信朋友圈照片与视频的选择方式

**Comment by longitachi** [comment]
@Henry519 你好，没太明白你的意思，你说的没有选择状态按钮是什么意思？是单选情况下没有选择按钮吗
