### ISSUE TITLE
图片本身大小20M，选择了使用原图方法，直接返回的图片大小成了68M —— UIImageJPEGRepresentation获取会显示偏大

### ISSUE THREAD

**Issue by MrCWW** [longitachi/ZLPhotoBrowser#168]
[ZLPhotoManager requestOriginalImageForAsset:asset completion:^(UIImage *image, NSDictionary *info) {
        NSData * imageData = UIImageJPEGRepresentation(image,1);
        
        NSUInteger   lengthaaa = [imageData length]/1024;
        NSLog(@"%lu",(unsigned long)lengthaaa);

    }];

**Comment by longitachi** [comment]
用UIImageJPEGRepresentation(image, 1.0)转换data，出来的结果就是比原图大小大好多，我刚才测试了下其他的照片选择框架一样的。你也可以直接拉项目里一张图片，用这个方法转换下，一样变大好多。 我测试直接拉项目里一张10M左右照片，用这个方法转换 data.length 为21594587

**Comment by longitachi** [comment]
如果想要获取asset原图大小，可以用 `+ (void)requestOriginalImageDataForAsset:(PHAsset *)asset completion:(void (^)(NSData *, NSDictionary *))completion;`这个方法
