### ISSUE TITLE
每次裁剪完图片，相册里就会多出一张图片来，有办法不生成新图片在相册里吗

### ISSUE THREAD

**Issue by LiberalChen** [longitachi/ZLPhotoBrowser#169]
每次裁剪完图片，相册里就会多出一张图片来，有办法不生成新图片在相册里吗

**Comment by longitachi** [comment]
不保存即可，修改`ZLEditViewController`这个方法
```
- (void)btnDone_click
{
    ZLImageNavigationController *nav = (ZLImageNavigationController *)self.navigationController;
    
    UIImage *image = [self clipImage];
    
    if (nav.callSelectClipImageBlock) {
        nav.callSelectClipImageBlock(image, nil);
     }
}
```

**Comment by LiberalChen** [comment]
![wechatimg241](https://user-images.githubusercontent.com/19303164/34194927-10bbcb44-e596-11e7-977e-b3e80a170506.jpeg)


改完甭在这了~

**Comment by LiberalChen** [comment]
改为甭在这了
![wechatimg241](https://user-images.githubusercontent.com/19303164/34195017-7035ca02-e596-11e7-9d4f-d7d2dff77bc3.jpeg)

**Comment by longitachi** [comment]
这个地方把 @[asset] 改成nil
