### ISSUE TITLE
双手指放大或着缩小图片上下左右滑动会出现问题

### ISSUE THREAD

**Issue by liuduanwen** [longitachi/ZLPhotoBrowser#17]
![img_0632](https://cloud.githubusercontent.com/assets/11530485/15771543/196485fc-299e-11e6-84aa-9df9741d9ec2.jpg)
![img_0633](https://cloud.githubusercontent.com/assets/11530485/15771544/19d0131c-299e-11e6-8817-72b6829c6966.jpg)

**Comment by longitachi** [comment]
已解决，请下载最新版本即可

**Comment by liuduanwen** [comment]
谢谢楼主更新
