### ISSUE TITLE
一个纯透明的图片，裁剪之后变成了白色的了

### ISSUE THREAD

**Issue by LiberalChen** [longitachi/ZLPhotoBrowser#170]
一个纯透明的图片，裁剪之后变成了白色的了

**Comment by longitachi** [comment]
刚测试了下确实会这样，我看看

**Comment by LiberalChen** [comment]
@longitachi ，你好~有啥解决方案了吗

**Comment by longitachi** [comment]
@LiberalChen 前两天看了下，暂时没有什么方案。 刚才又试着试了下系统相册的编辑，一张透明的照片，裁剪后也是变成了白色的图片
