### ISSUE TITLE
是否考虑添加一个配置选项，是否保存生成新图片

### ISSUE THREAD

**Issue by adntian** [longitachi/ZLPhotoBrowser#173]
在某些应用场景下，图片编辑后或者拍照编辑后并不需要保存图片到相册中
是否可以添加一或两个配置项，

- 用于设置在编辑图片后，是/否自动保存生成的图片到相册

- 拍照的图片是/否保存在相册

> 场景就是采集某些图片上传，但并不想同时也保存在本地的情况

实现上面的配置，可能会影响到下面回调的第二个参数（36行）

`
/**
 选择照片回调，回调解析好的图片、对应的asset对象、是否原图
 pod 2.2.6版本之后 统一通过selectImageBlock回调
 */
`
`
@property (nonatomic, copy) void (^selectImageBlock)(NSArray<UIImage *> *__nullable images, NSArray<PHAsset *> *assets, BOOL isOriginal);
`

当然，这里我也有个曲线的实现方式，**使用完图片后，自行删除**，这样想想也是没有那么的必要了，希望作者可以做为一个参考吧，看看有没有必要去添加了，谢谢

**Comment by longitachi** [comment]
编辑后是否保存生成的图片，这个可以加上，前几天也有个朋友issue说了这个地方。 但是拍照后是否保存这个，由于涉及到的地方有点多，所以第二点拍照图片是否保存相册这个还会保持现在的逻辑。

**Comment by adntian** [comment]
好的，辛苦了！

**Comment by LiberalChen** [comment]
现在 pod 下来的 还是2.6.1，还没有是否保存这个功能~

**Comment by longitachi** [comment]
@LiberalChen 我还没有更新到cocoapods。只是先推到了github

**Comment by LiberalChen** [comment]
@longitachi 哦哦，啥时更新 cocoapods 啊

**Comment by longitachi** [comment]
@LiberalChen  今天吧
