### ISSUE TITLE
在有tabbar的页面弹出，会有一个黑条底部

### ISSUE THREAD

**Issue by LXXuanCai** [longitachi/ZLPhotoBrowser#175]
这个怎么解决

**Comment by LXXuanCai** [comment]
![image](https://user-images.githubusercontent.com/25808187/34556093-9d9ec790-f0fa-11e7-8f8d-6fed57bba8fe.png)

**Comment by longitachi** [comment]
看下是哪一个版本

**Comment by LXXuanCai** [comment]
之前是2.61，刚更新完2.62，仍然会有这种现象，系统10.3.3

**Comment by LXXuanCai** [comment]
经测试模拟器11.2，同样bug

**Comment by longitachi** [comment]
我这边测试了下，并不会出现这种bug啊，xcode9.1，模拟器是11.1的。显示正常。 你是用的是系统的tabbarController还是其他的，或者有没有什么其他设置影响了这个？

**Comment by LXXuanCai** [comment]
tabbar是自定义的tabbar，更多的我一会看看试试吧

**Comment by LXXuanCai** [comment]
原因有了，在调用了 [self.actionSheet showPreviewAnimated:YES];这一句后，tabBar.hidden = YES;了

**Comment by LXXuanCai** [comment]
![bfdc6dc05279b6f51b25c776151c9061](https://user-images.githubusercontent.com/25808187/34637445-c1c84c6c-f27c-11e7-81e3-0b2e1140a238.jpg)
![e14a5389e71c57fe022d284f28779ce5](https://user-images.githubusercontent.com/25808187/34637448-cfc7162c-f27c-11e7-9c4b-0e3ecd61e446.jpg)

**Comment by LXXuanCai** [comment]
![74c0fc9a3f4f652c9067508672e51e3a](https://user-images.githubusercontent.com/25808187/34637470-29625962-f27d-11e7-948e-2bf1d6e5d459.jpg)
![f0fb36ee-1ebb-466c-854a-806e8fdc2cab](https://user-images.githubusercontent.com/25808187/34637471-2c8f7e9e-f27d-11e7-9a71-2df973767234.png)

**Comment by LXXuanCai** [comment]
自己加个一句taibar.hidden = no，tabbar回来了

**Comment by longitachi** [comment]
你这样有问题，被遮盖
```
if (self.sender.tabBarController.tabBar && self.sender.tabBarController.tabBar.hidden == NO) {
        self.senderTabBarIsShow = YES;
        self.sender.tabBarController.tabBar.hidden = YES;
    }
    
    UIEdgeInsets inset = UIEdgeInsetsZero;
    if (@available(iOS 11, *)) {
        double flag = .0;
        if (self.senderTabBarIsShow) {
            flag = 49;
        }
        inset = self.sender.view.safeAreaInsets;
        inset.bottom -= flag;
        [self.verBottomSpace setConstant:inset.bottom];
    }
    if (self.animate) {
        __block CGRect frame = self.baseView.frame;
        frame.origin.y = kViewHeight;
        self.baseView.frame = frame;
        [UIView animateWithDuration:0.2 animations:^{
            frame.origin.y -= kBaseViewHeight;
            self.baseView.frame = frame;
        } completion:nil];
    }
```
你看下这个 `- (void)show`方法里这个inset，还有最终的frame值都是多少

**Comment by LXXuanCai** [comment]
好的

**Comment by LXXuanCai** [comment]
系统10.3.3 手机6S
- (void)show方法 断点
走完第一句（305行）
(lldb) po self.frame
(origin = (x = 0, y = 0), size = (width = 375, height = 618))

走完(327/328行)
    if (self.animate) {
        __block CGRect frame = self.baseView.frame;

(lldb) po frame
(origin = (x = 0, y = 367), size = (width = 375, height = 300))

对y设置后
(lldb) po frame
(origin = (x = 0, y = 667), size = (width = 375, height = 300))

**Comment by LXXuanCai** [comment]
设置完hidden = no 后，果然有一点点被挡住了

**Comment by longitachi** [comment]
下边那一块黑色的，是你控制器的`self.view`吗？ 你先自己调调，我在更新xcode，等会创建个自定义tabbarcontroller的项目试试

**Comment by LXXuanCai** [comment]
下面一块是啥也没有....本来是tabbar

**Comment by LXXuanCai** [comment]
我好想知道了点什么。隐藏tabbar后，self.view并不会自动全屏，冲突点应该就在这里了，估么不会全屏，还有我的self.view的高是618正是667-49的高度

**Comment by longitachi** [comment]
![d9757918-156e-4c5d-8298-5610b8464686](https://user-images.githubusercontent.com/11711768/34638184-78565288-f301-11e7-95f5-8dfa51db9366.png)
使用的`CYLTabBarController`的demo，不会导致下方黑屏

**Comment by LXXuanCai** [comment]
现在有点崩溃了，想集成CYLTabBarController，结果发现过程也一堆bug，先暂时不管这个，调用直接进入相册算了.......但是直接进入相册好像没有摄像机啊

**Comment by LXXuanCai** [comment]
actionSheet.configuration.allowForceTouch = YES;//相册内拍照
//设置相册内部显示拍照按钮
 actionSheet.configuration.allowTakePhotoInLibrary = YES;
//设置在内部拍照按钮上实时显示相机俘获画面
 actionSheet.configuration.showCaptureImageOnTakePhotoBtn = YES;

**Comment by longitachi** [comment]
可以的啊，你试试demo

**Comment by LXXuanCai** [comment]
demo也一样，照片选择为NO后，不会再相册里显示拍摄视频的

**Comment by longitachi** [comment]
额，你没说前提是不允许选择照片。。。 这个是bug，我稍后修改下，拍摄视频后来加的，没考虑到这点

**Comment by LXXuanCai** [comment]
解决不允许选择照片但允许选择及拍摄视频时，相册内不显示拍照按钮的bug
谢谢，这样就解决了留黑边的问题.....这个思路叫做，暂时解决不了问题，所以解决出问题的人，哈哈

**Comment by LXXuanCai** [comment]
是因为版本没变么，pod update你这个还是2.6.2

**Comment by LXXuanCai** [comment]
Using ZLPhotoBrowser (2.6.2)

**Comment by longitachi** [comment]
我还没更新上去，在做一个新功能，完成后一起推上去

**Comment by longitachi** [comment]
更新2.6.3版本即可
