### ISSUE TITLE
请问 你那个类 可以导出视频的路径的 是哪一个

### ISSUE THREAD

**Issue by JamWangJam** [longitachi/ZLPhotoBrowser#176]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个问题，而不是问一个问题

#### 关于 Issue
1. 当前cocoapods版本
2. 遇到问题（如有可能，请详细描述，建议附上截图。不负责的 issue 可能会被 close）

**Comment by longitachi** [comment]
请查看 `ZLPhotoManager` 类，注释很详细
