### ISSUE TITLE
请问 支持 网络视频 吗?   您 做了 选择视频 图片混排 但是播放网络的只是支持 图片浏览器吗?

### ISSUE THREAD

**Issue by JamWangJam** [longitachi/ZLPhotoBrowser#177]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个问题，而不是问一个问题

#### 关于 Issue
1. 当前cocoapods版本
2. 遇到问题（如有可能，请详细描述，建议附上截图。不负责的 issue 可能会被 close）

**Comment by longitachi** [comment]
我没太明白你的问题。  现在是不支持预览网络视频的。 仅支持预览网络图片及本地图片。
