### ISSUE TITLE
Max Select Count :2 这个最大选择提示文案支持修改吗 —— pod 2.6.3已支持

### ISSUE THREAD

**Issue by yimao009** [longitachi/ZLPhotoBrowser#178]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

- [x] 我已经查阅了已有的issue，没有找到相同的
- [x] 我想提出一个问题，而不是问一个问题

#### 关于 Issue
1. 当前cocoapods版本
2. 遇到问题（如有可能，请详细描述，建议附上截图。不负责的 issue 可能会被 close）

**Comment by longitachi** [comment]
暂时是不支持api修改多语言这个提示的，如果有需要，可以先在 `PhotoBrowser/resource/ZLPhotoBrowser.bundler/*.lproj`下的文件修改对应的提示

**Comment by longitachi** [comment]
下个版本添加一个 支持修改部分自定义多语言 的功能

**Comment by yimao009** [comment]
是的， 我现在都是在那个bundle里修改，总感觉这不是很好都解决方案； 哈哈；

**Comment by longitachi** [comment]
已经更新了该功能，暂时还没推到cocoapods上

**Comment by longitachi** [comment]
更新2.6.3版本即可
