### ISSUE TITLE
有没有只吊起相机的方法

### ISSUE THREAD

**Issue by JianMingFu** [longitachi/ZLPhotoBrowser#179]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
暂时没有，如果需要，可以参照 `ZLCustomCamera` 里面的方法，自己写一个，拎出来修改下就好了

**Comment by no-trouble** [comment]
> 暂时没有，如果需要，可以参照 `ZLCustomCamera` 里面的方法，自己写一个，拎出来修改下就好了。不过貌似你可以直接初始化这个类的对象直接使用，可以试试

是的。不过自定义相机类应该加一个取消拍照的回调。

**Comment by longitachi** [comment]
@no-trouble 新版本已经提供只调起相机的方法
