### ISSUE TITLE
你好，想问下怎么将选出来的图片转成Base64编码或者可以直接上传的格式？

### ISSUE THREAD

**Issue by Stevezhong0506** [longitachi/ZLPhotoBrowser#18]
想问下怎么将选出来的图片转成Base64编码或者可以直接上传的格式？

**Comment by longitachi** [comment]
你上传需要什么格式？

**Comment by Stevezhong0506** [comment]
因为之前没做过上传图片的功能，还想请您指点一下~~我目前想到最简单的方式是传base64编码给后台，这样会不会有问题呢？还有一种是上传文件流，但是目前没有头绪，请问您有做过类似的么？

**Comment by Stevezhong0506** [comment]
这个是不支持iOS7么？

**Comment by longitachi** [comment]
对，最低支持到iOS8.0， 那就不知道，我们的图片上传就是单纯的把image转化成data，进行post请求就好了。
