### ISSUE TITLE
大佬，可否让框架支持播放网络视频？ —— pod 2.6.3已支持

### ISSUE THREAD

**Issue by edocx** [longitachi/ZLPhotoBrowser#180]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
#171 #177

**Comment by longitachi** [comment]
#171

**Comment by longitachi** [comment]
你这个支持网络视频的需求是什么？仅仅预览网络视频？还是和本地相册里的图片视频、网络图片、本地图片混合在一起？

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/commit/8193a1562d7271da3774b23016cb6e1f8ba58e3f
pod 2.6.3已支持
