### ISSUE TITLE
当第一张图片放大时继续往后面滑动翻页，到第四张的时候，图片只有一点点大？

### ISSUE THREAD

**Issue by 284885166** [longitachi/ZLPhotoBrowser#181]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [x] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
已重现，我看下原因

**Comment by 284885166** [comment]
好的
