### ISSUE TITLE
大佬，框架支持本地gif,不支持网络gif,可否把这个功能加上？

### ISSUE THREAD

**Issue by edocx** [longitachi/ZLPhotoBrowser#182]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
sd现在这版本貌似不支持直接显示网络gif了。
