### ISSUE TITLE
iOS8系统下保存编辑后的视频失败 —— 2.6.4版本已解决

### ISSUE THREAD

**Issue by ChandHsu** [longitachi/ZLPhotoBrowser#185]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
视频裁剪出来的结果:
PHAsset *asset = [self getAssetFromlocalIdentifier:placeholderAsset.localIdentifier];
asset是空的,iOS8系统,找到原因是url不对,添加以下代码可以解决:
NSString *urlStr = [url absoluteString];
        if (![urlStr containsString:@"file://"]) {
            url = [NSURL fileURLWithPath:urlStr];
        }

**Comment by longitachi** [comment]
是哪个版本？ 另外79行没找到对应代码。。说下方法名吧，你说的这块代码是添加到哪个方法里？

**Comment by ChandHsu** [comment]
是最新的版本,昨天我刚下的;
+ (void)saveVideoToAblum:(NSURL *)url completion:(void (^)(BOOL, PHAsset *))completion{}
这个里面;
是我添加了代码后变成了79行,不好意思!

**Comment by longitachi** [comment]
![e5230d33-4c3f-4d1f-bbc1-fb6d4456649e](https://user-images.githubusercontent.com/11711768/35022130-3b9fb868-fb6f-11e7-8682-b3afebac8fb2.png)
你先别加上面的判断，把这个地方修改下，看在iOS8 系统下还报错不

**Comment by ChandHsu** [comment]
ok,不报错了
