### ISSUE TITLE
希望能加上只指定支持比例选择 现在支持多种比例  但是不能指定一种

### ISSUE THREAD

**Issue by 984344996** [longitachi/ZLPhotoBrowser#186]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

- [x] 我已经查阅了已有的issue，没有找到相同的
- [x] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
什么比例？编辑图片的比例？

**Comment by 984344996** [comment]
对啊，比如我要用户上传头像，只允许1:1  这个需求量很大的，80%用你这个编辑功能基本上都是上传头像，我只想让它支持1:1的截取，而且必须截取后才能算选取成功。你这个截取是可选的

**Comment by longitachi** [comment]
你看下 `ZLPhotoConfiguration` 这个类的参数，有一个 `clipRatios`
```
/**
 根据需要设置自身需要的裁剪比例
 
 @discussion e.g.:1:1，请使用ZLDefine中所提供方法 GetClipRatio(NSInteger value1, NSInteger value2)，该数组可不设置，有默认比例，为（Custom, 1:1, 4:3, 3:2, 16:9），如果所设置比例只有一个且 为 Custom 或 1:1，则编辑图片界面隐藏下方比例工具条
 */
@property (nonatomic, strong) NSArray<NSDictionary *> *clipRatios;
```

**Comment by longitachi** [comment]
不过必须截取你可以设置 选择最大数为1，然后有一个 `editAfterSelectThumbnailImage ` 设置为yes即可
```
/**
 在小图界面选择 图片/视频 后直接进入编辑界面，默认NO
 
 @discussion 编辑图片 仅在allowEditImage为YES 且 maxSelectCount为1 的情况下，置为YES有效，编辑视频则在 allowEditVideo为YES 且 maxSelectCount为1情况下，置为YES有效
 */
@property (nonatomic, assign) BOOL editAfterSelectThumbnailImage;
```

**Comment by scyios** [comment]
选完图片之后如何直接进入 裁剪界面啊  现在有一步是可以选择裁剪 滤镜 旋转

**Comment by wmadao11** [comment]
@longitachi 请问一下，当前版本(4.0.4)，`ZLPhotoConfiguration`已经没有`clipRatios `参数了。 这个功能改版后没有了吗

**Comment by longitachi** [comment]
@wmadao11 swift版本暂时没有，这个功能后续添加
