### ISSUE TITLE
运行demo是打开相册，查看图片详情的时候，如果图片未加载完全，点返回，会出现崩溃。

### ISSUE THREAD

**Issue by GitHubMrfan** [longitachi/ZLPhotoBrowser#187]
断点在，   strongSelf->_loadOK = YES;
<img width="1016" alt="2018-01-18 9 13 43" src="https://user-images.githubusercontent.com/21231400/35075887-898c421e-fc30-11e7-95cd-cab9850dd837.png">

**Comment by longitachi** [comment]
具体怎么操作的，我这边没重现出来。 你可以先把` _loadOK` 改为 `@property (nonatomic, assign) BOOL loadOK;`属性的声明，把`strongSelf->_loadOK`改为`strongSelf.loadOK`解决这个问题
