### ISSUE TITLE
你好，请问 原图 按钮 能隐藏吗？

### ISSUE THREAD

**Issue by wyhu** [longitachi/ZLPhotoBrowser#188]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by wyhu** [comment]
你好，请问原图按钮能隐藏吗

**Comment by longitachi** [comment]
/**
 是否允许选择原图，默认YES
 */
@property (nonatomic, assign) BOOL allowSelectOriginal;

**Comment by Jinkeycode** [comment]
allowSelectOriginal 为 false 的时候是默认使用原图吗？

**Comment by wyhu** [comment]
不是




------------------ 原始邮件 ------------------
发件人: "Jinkeycode"<notifications@github.com>; 
发送时间: 2019年6月17日(星期一) 下午4:18
收件人: "longitachi/ZLPhotoBrowser"<ZLPhotoBrowser@noreply.github.com>; 
抄送: "胡伟亚"<596031524@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [longitachi/ZLPhotoBrowser] 你好，请问 原图 按钮 能隐藏吗？ (#188)




allowSelectOriginal 为 false 的时候是默认使用原图吗？

**Comment by Jinkeycode** [comment]
@wyhu 那么怎么能隐藏原图按钮，默认选择原图呢
