### ISSUE TITLE
能否添加设置只能单选视频

### ISSUE THREAD

**Issue by jackiehu** [longitachi/ZLPhotoBrowser#189]
能否添加设置只能单选视频

**Comment by longitachi** [comment]
`allowSelectImage=NO` `maxSelectCount=1`即可

**Comment by jackiehu** [comment]
我想同时可以选择照片和视频,照片可以选多个但是视频只能选一个,不过通过修改你的代码已经实现了,希望以后能加入这个功能

**Comment by tuoyinzhou91Jon** [comment]
新手同求此效果，但是改代码不是很会改

**Comment by YuStephen** [comment]
楼上的分享下更改位置啊@jackiehu
