### ISSUE TITLE
图片链接判断出现问题了,按后缀这样判断不行啊 —— pod 2.6.5 已解决

### ISSUE THREAD

**Issue by WangGuibin** [longitachi/ZLPhotoBrowser#190]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

我们图片是传到阿里云那边的,然后每个图片的后缀并没有`png`,`jpg`这个后缀, 我看到您的实现里写的是根据这些后缀去匹配

ZLPhotoActionSheet.m 文件 261行这个方法 
```
    NSArray *imageExtensions = @[@"jpg", @"jpeg", @"png", @"gif"];

  if ([obj isKindOfClass:NSURL.class]) {
            model.url = obj;
            if ([imageExtensions containsObject:((NSURL *)obj).absoluteString.pathExtension]) {
                model.type = ZLAssetMediaTypeNetImage;
            } else {
                model.type = ZLAssetMediaTypeNetVideo;
            }
```
然后我的图片全都浏览不了, 一个类似于▶️按钮的玩意  全屏黑....  [复现率100%]
链接示例: 
`http://upload.ddys168.com//jiajiamuying_upload/20171202/15122102005a227f1830119`
`http://upload.ddys168.com//jiajiamuying_upload/20171202/15122102005a227f185b1dc`
我建议再添加http等网络协议去过滤,应该合理一点. 
希望尽快完善,加油💪

**Comment by longitachi** [comment]
我打开你给的这个链接示例，直接让我下载了个压缩文件，这个不是图片吧？

**Comment by WangGuibin** [comment]
是图片呀 没有后缀的,是阿里云的, http://upload.ddys168.com//f85fa4371413d43ac4c3b89b96a3d552  再试试看

**Comment by WangGuibin** [comment]
不知道为啥丢到浏览器自动下载.dms格式的文件,你把.dms后缀去掉是可以打开的,这个情况很坑爹,我和后端沟通下应该可以解决~  添麻烦啦😆

**Comment by zhugexiaobo** [comment]
建议直接用 `NSURL` 的 `pathExtension`，因为 `NSString` 无法处理像 `http://demo.edusoho.com/files/course/2014/12-03/1355313f0491562440.jpg?4.5.3` 这样的 url。
@longitachi

**Comment by zhugexiaobo** [comment]
不过这里的判断太简单粗暴了点，非 `@"jpg", @"jpeg", @"png", @"gif"` 的即为视频，这样判断不太严谨。
建议视频和图片分开来处理，比如使用 `- (void)previewVideos:(NSArray *)photos index:(NSInteger)index hideToolBar:(BOOL)hideToolBar complete:(void (^)(NSArray *photos))complete` 这样的接口。

**Comment by longitachi** [comment]
@zhugexiaobo 但是有些需要视频和图片一起预览的，我也没有找到什么比较好的方法，所以才写死了四种常见的图片格式， 你上面说的`NSURL`的`pathExtension`能解决这个问题吗？

**Comment by zhugexiaobo** [comment]
`pathExtension` 只能针对有后缀的图片地址，判断比 `NSString` 的 `pathExtension` 更准确些，但是并不能解决这个 issue 所提出的问题。
我所知道的根据图片链接准确判断格式的方法来自 [SDWebImage](https://github.com/rs/SDWebImage/blob/master/SDWebImage/NSData%2BImageContentType.m)，但前提是要先下载，所以我才建议视频和图片分开处理
