### ISSUE TITLE
设置不允许选择图片后，进入相机，快门拍照按钮不能使用

### ISSUE THREAD

**Issue by qzlwoios** [longitachi/ZLPhotoBrowser#196]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
因为不允许选择照片，所以点击拍照是不能使用的，这时候只能长按拍照。

**Comment by qzlwoios** [comment]
好的，还有一个问题，在plus上选取招聘，一直提示加载中请稍后，图片没法选择，有时候还会闪退，是什么问题呢

**Comment by longitachi** [comment]
我没遇到过这情况，怎么重现。 断点是在哪个地方崩溃了，你截个图看下
