### ISSUE TITLE
国际语言里面的中文写错了。

### ISSUE THREAD

**Issue by ZhangMingHeng** [longitachi/ZLPhotoBrowser#200]
"ZLPhotoBrowserNoCameraAuthorityText" = "请在iPhone的\"设置-隐私-相机\"选项中，允许%@访问你的相机";
"ZLPhotoBrowserNoAblumAuthorityText" = "请在iPhone的\"设置-隐私-相机\"选项中，允许%@访问你的相册";
第二个应该是照片呀。

**Comment by ZhangMingHeng** [comment]
还有一个问题，获取App名称时你用‘CFBundleDisplayName’的key，如果没有在info.plist中设置取出来的是nil，为什么不用‘CFBundleName’ 这个呢？？？

**Comment by longitachi** [comment]
好的，下次更新会修改为照片。 因为 `#define kAPPName [kInfoDict valueForKey:@"CFBundleDisplayName"] ?: [kInfoDict valueForKey:@"CFBundleName"]` 这种获取方法支持多语言的App名称
