### ISSUE TITLE
您好！请问拍照和拍视频都显示“图片保存失败”、“视频保存失败”是什么原因啊？

### ISSUE THREAD

**Issue by ghost** [longitachi/ZLPhotoBrowser#201]
您好！楼主，请问拍照和拍视频都显示“图片保存失败”、“视频保存失败”是什么原因啊？麻烦您解答一下，万分感谢！

**Comment by longitachi** [comment]
控制台有错误日志输出吗？或者你打下断点定位一下失败的代码行截图我看下

**Comment by Mark-jiepan** [comment]
就是控制台无任何输出，选择相册是可以的，就是拍照和拍视频都是显示“图片保存失败”。还有，选择相册的照片后，点击编辑之后也是显示“图片保存失败”。

**Comment by longitachi** [comment]
😓，你现在使用的是什么版本。我这边试了几次没试出来，我这边不好确定出错位置，暂时想不到什么原因。你尝试下调试走走，看看具体在哪个地方保存失败了。

**Comment by Mark-jiepan** [comment]
我使用的是您现在的版本，我先调试一下，然后定位到具体失败地方我给您截图。

**Comment by tangpeng0703** [comment]
大佬大佬，我这也显示保存失败，是最新版的，我这是直接把你的东西给拷贝出来的

2018-03-02 16:46:57.257056 WorkPortal[13895:4041991] Cannot snapshot view (<UIKeyboardImpl: 0x102219820; frame = (0 0; 375 216); layer = <CALayer: 0x170427d00>>) with afterScreenUpdates:NO, because the view is not in a window. Use afterScreenUpdates:YES.

**Comment by tangpeng0703** [comment]
@longitachi  - (void)saveImage:(UIImage *)image videoUrl:(NSURL *)videoUrl
这个方法里，suc回调的是NO 
提示保存失败，但是返回界面再进来的时候，实际是已经在相册里
2018-03-02 17:36:58.008698 WorkPortal[14041:4066950] 创建相册：(null)失败
2018-03-02 17:37:06.898880 WorkPortal[14041:4067278] 创建相册：(null)失败
希望大佬回复，谢谢

**Comment by tangpeng0703** [comment]
哈哈，解决了，就是相册名称的问题，我有点犯2了

**Comment by tangpeng0703** [comment]
我用邮箱直接回复的，不知道你能不能看得到，创建相册的时候，有一个名字，你把那个名字改一下，不要用从plist文件里获取的，就好了




| |
汤鹏
邮箱：18510970653@163.com
|

签名由 网易邮箱大师 定制

在2018年03月02日 20:36，long 写道：

@tangpeng0703 创建相册为什么失败了，怎么解决的？

**Comment by longitachi** [comment]
@tangpeng0703 如果不从plist里面获取的话，用户软件名称不同，总不能写死一个相册名字啊。。

**Comment by tangpeng0703** [comment]
@longitachi 我目前就只有一个项目里用到这个，我先写死的，这个问题，大佬再研究一下，辛苦
