### ISSUE TITLE
选择图片的时候 崩溃了

### ISSUE THREAD

**Issue by LiberalChen** [longitachi/ZLPhotoBrowser#204]
![default](https://user-images.githubusercontent.com/19303164/36963648-0aea5972-208f-11e8-93f7-e8407c640444.jpeg)

**Comment by LiberalChen** [comment]
选完图片，进入裁剪界面时候会出现，但有的图片就没事

**Comment by longitachi** [comment]
这个是裁剪完之后点击确定时候吧？你能在点击确定时，调试下生成图片的这个方法（`clipImage`）吗，看下哪里成nil了。

**Comment by LiberalChen** [comment]
这是在 选择完照片，刚进入裁剪界面的时候，图片一直显示不出来，菊花在转，然后一会就崩溃了

**Comment by longitachi** [comment]
能往上看下崩溃点吗，这个崩溃是最后一个断点了，你再往前面几个步骤看看

**Comment by LiberalChen** [comment]
在转菊花，我点了下 确定  崩了
![3123123123](https://user-images.githubusercontent.com/19303164/37020406-9688a0de-2156-11e8-9336-c46339bd2dbf.jpeg)

**Comment by longitachi** [comment]
好吧，你先在这个点击确定的地方加个判断吧，判断image不为空。 不过图片会一直加载不出来吗？你既然能编辑说明肯定是本地的图片，不是iCloud上的，应该很快就出来了，我还没遇到这情况
