### ISSUE TITLE
首次进入，用系统相机录制完视频后，相册内没有实时显示更新。但是有显示选择。录制多个视频后，显示有选择有一个，但不知选的是哪一个。

### ISSUE THREAD

**Issue by CherishSmile** [longitachi/ZLPhotoBrowser#206]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by CherishSmile** [comment]
单选模式下

**Comment by CherishSmile** [comment]
![wechatimg155](https://user-images.githubusercontent.com/17586122/37010186-56f819c6-2125-11e8-9bcd-0252cb170647.jpeg)
![wechatimg156](https://user-images.githubusercontent.com/17586122/37010190-5d2091ac-2125-11e8-8c54-bd6451ae1812.jpeg)

**Comment by longitachi** [comment]
单选模式下，录制完视频之后应该直接走回调了吧。 我刚才试了下，都是直接回调了，没有在停留在你发的这个图的界面

**Comment by CherishSmile** [comment]
单选模式，并且每次重新进入拍摄，我今天试了四五十次，每次打断点就没问题，正常dismiss，只要不打断点95%的几率会出现这种问题。后来用log输出，大概找到了问题所在。但是我并不清楚是怎样引起的。（ios10.3.3）
<img width="890" alt="qq20180306-151420 2x" src="https://user-images.githubusercontent.com/17586122/37018924-2b0a8534-2151-11e8-9a80-de5669e8ed6f.png">
<img width="818" alt="qq20180306-151631 2x" src="https://user-images.githubusercontent.com/17586122/37018977-6a7acfda-2151-11e8-83bf-d273e27bb561.png">

**Comment by longitachi** [comment]
系统解析asset时候，是会先解析一个缩略图返回给你的，然后这个 `PHImageResultIsDegradedKey`值便为`YES`，当系统解析完成，拿到大图后，这个值才会为NO。
你直接录制的视频，又没有在iCloud上，按理说存储后很快就解析到了。所以我暂时也不太清楚出现这个的原因
