### ISSUE TITLE
选择视频上传的时候可否设置只能选择一个视频上传

### ISSUE THREAD

**Issue by a544844** [longitachi/ZLPhotoBrowser#207]
[感谢提交问题，提交]([url](`url`)) issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by a544844** [comment]
怎么做图片和视频的区分

**Comment by longitachi** [comment]
选择视频时候可以禁止选择图片，然后把最大选择数量设置为1即可。 

你说的图片和视频的区分是什么意思？不太明白

**Comment by a544844** [comment]
选择图片和视频的区分,如果选择图片就不能选择视频,图片可以多张上传,视频只能上传一个,我说的视频和图片区分是,返回的数据可以区分是视频的data还是图片的data嘛

**Comment by longitachi** [comment]
暂时没有这个功能，可以设置两者不能同时选择，但不能同时设置两者不同的选择数量。返回的数据中有`PHAsset`对象，通过这个对象的`mediaType`即可区分视频还是图片

**Comment by MrNAVY** [comment]
怎么设置只能选一个视频

**Comment by MrNAVY** [comment]
直接设置成图片跟视频选择各自设置自己的最大值不是更好么




| |
邓海军
邮箱：navydun@163.com
|

签名由 网易邮箱大师 定制

在2018年06月07日 11:24，long 写道：

@MrNAVY 设置只能选择视频模式，然后最大值为1

**Comment by Henry519** [comment]
@longitachi 希望作者能添加一个在同时允许选择照片与视频的情况下，照片与视频可以单独设置选择的数量的功能，跟@MrNAVY 一样的需求。正常应用中这种需求很多，图片多选视频只能单选
