### ISSUE TITLE
如果想上传视频的话,如何拿到视频的URL或者data

### ISSUE THREAD

**Issue by a544844** [longitachi/ZLPhotoBrowser#210]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
上传视频的话，必须先导出对应的`PHAsset`对象，导出方法有回调导出后的路径，这样便可拿到data

**Comment by yangfangkuo** [comment]
这个方法给返回的路径是 /private/var/mobile/Media/DCIM/104APPLE/ 目录下的 ,不是越狱设备应该是没有权限读取里面的数据的

**Comment by longitachi** [comment]
所以提供了导出视频到沙盒的方法，导出后block中有导出后的路径，可以通过该路径拿到data

**Comment by yangfangkuo** [comment]
好像系统相机的话 拍完视频的话 默认就是在沙盒temp路径下 ,照片不是,你说的导出视频到沙盒?我不知道你说的是什么意思?难道是把相册的视频导入到app目录下?这个方法不好,           
     PHImageManager *manager = [PHImageManager defaultManager];
                [manager requestAVAssetForVideo:assert options:options resultHandler:^(AVAsset * _Nullable asset, AVAudioMix * _Nullable audioMix, NSDictionary * _Nullable info) {
                    AVURLAsset *urlAsset = (AVURLAsset *)asset;
                    NSURL *url = urlAsset.URL;
                    NSData *data = [NSData dataWithContentsOfURL:url];
}]; 使用这个系统方法获取data 好像是更稳一点的 我不知道你说的是不是就是这个方法
