### ISSUE TITLE
pod升级到2.6.4 ZLdefine.h报错

### ISSUE THREAD

**Issue by puhahalx** [longitachi/ZLPhotoBrowser#211]
static inline void ShowAlert(NSString *message, UIViewController *sender)  方法报错Expected identifier or '('     Use of undeclared identifier 'controller'      Expected ')'  
但是看代码好像没有错的样子 并且无法unlock这个文件    我xcode版本是9.0

**Comment by puhahalx** [comment]
![79c4b445-3025-46f7-8b21-750e89eb5dd8](https://user-images.githubusercontent.com/28496967/37190543-57401b96-2395-11e8-996e-1b083f02149f.png)

**Comment by puhahalx** [comment]
![9b28cbf9-b424-402f-a72a-7f3cf0311e94](https://user-images.githubusercontent.com/28496967/37190559-7292f878-2395-11e8-82c8-b097c601fc2f.png)

**Comment by puhahalx** [comment]
我知道了 是我自己的问题 我在pch文件里之前就定义了一个一摸一样的方法

**Comment by longitachi** [comment]
好吧，解决就好
