### ISSUE TITLE
xcode 9.2 很多警告

### ISSUE THREAD

**Issue by youyoukong** [longitachi/ZLPhotoBrowser#212]
反馈问题.pods带入工程后. 有20+的警告. 有如下两种,is only available on iOS 9.1 or newer, introduced in iOS 9.1.
菜鸡表示,不会修复, 模拟器和真机目前没有发生问题.

**Comment by longitachi** [comment]
能截几个图看下吗，警告的地方的代码

**Comment by longitachi** [comment]
我看到了。 我平常不想看到那么Pod库里的警告，所以我在Podfile里面会添加一句 `inhibit_all_warnings!`来忽略所有 通过Pod集成的三方库的警告。😓

**Comment by youyoukong** [comment]
才看到邮件.感谢指导.
