### ISSUE TITLE
想问下关于Swift4中桥接ZL使用的问题

### ISSUE THREAD

**Issue by jiajun1991** [longitachi/ZLPhotoBrowser#213]
在Swift4中用ZL，setSelectImageBlock没法调用，该怎么解决呢

**Comment by longitachi** [comment]
我并不多熟悉swift，尝试了下没整出来。。不好意思，你可以询问下经常使用swift的朋友

**Comment by lcbest** [comment]
我也遇到了同样的问题。提示Value of type 'ZLPhotoActionSheet' has no member 'selectImageBlock'
Use of undeclared type 'PHAsset'

**Comment by jiajun1991** [comment]
好的

**Comment by longitachi** [comment]
@lcbest 你在使用的地方添加 `import Photos`可以解决这一个

**Comment by lcbest** [comment]
@longitachi 666，import Photos解决了该问题，非常感谢！
@jiajun1991 你可以试一下import Photos 应该就可以点出属性了。
ac.selectImageBlock = {(_ images: [UIImage]?, assets:[PHAsset] , isOriginal:Bool) -> Void in
            
            }

**Comment by jiajun1991** [comment]
@longitachi @lcbest 非常感谢！

**Comment by fengweiru** [comment]
@longitachi @lcbest 感谢
