### ISSUE TITLE
bug：网络预览图片和视频时闪退

### ISSUE THREAD

**Issue by zhangzhanzg** [longitachi/ZLPhotoBrowser#216]
![2018-03-20 3 30 35](https://user-images.githubusercontent.com/8486303/37641203-c2ebfe84-2c53-11e8-92f3-3a86dc1febbd.png)

**Comment by longitachi** [comment]
具体是怎么操作，然后崩溃了？

**Comment by zhangzhanzg** [comment]
就是进入网络预览页面，左右来回滑动切换图片和视频的崩溃了。猜测是因为KVO没有及时移除引起的

**Comment by ParadiseGitHub** [comment]
我遇到了同样的问题，在iPhone6 Plus iOS10系统，每次预览网络视频和图片时，都会崩溃，崩溃日志跟@zhangzhang 的一样，但是在iOS11就没有这个问题！！！

**Comment by longitachi** [comment]
@ParadiseGitHub 你试试在`ZLPreviewNetVideo`这个类的`seekToZero`添加如下代码
```
- (void)seekToZero
{
    [self.playLayer.player.currentItem removeObserver:self forKeyPath:@"playbackBufferEmpty"];
    [self.playLayer.player.currentItem removeObserver:self forKeyPath:@"playbackLikelyToKeepUp"];
    
    AVPlayer *player = self.playLayer.player;
    [player.currentItem seekToTime:kCMTimeZero];
}
```

**Comment by zhangzhanzg** [comment]
好的，谢谢




张站
手机：17600056168
2018年04月19日
在2018年04月19日 10:06，long 写道：

@ParadiseGitHub 你试试在ZLPreviewNetVideo这个类的seekToZero添加如下代码

- (void)seekToZero
{
    [self.playLayer.player.currentItem removeObserver:self forKeyPath:@"playbackBufferEmpty"];
    [self.playLayer.player.currentItem removeObserver:self forKeyPath:@"playbackLikelyToKeepUp"];
    
    AVPlayer *player = self.playLayer.player;
    [player.currentItem seekToTime:kCMTimeZero];
}

**Comment by longitachi** [comment]
2.6.6版本已经解决了，添加这两行代码，需要把之前dealloc中的observer删掉
