### ISSUE TITLE
崩溃BUG_ pods版本：ZLPhotoBrowser (2.6.2)

### ISSUE THREAD

**Issue by JianMingFu** [longitachi/ZLPhotoBrowser#217]
我设置的是不允许选择视频，只能选择图片，但是在相册界面使用相机拍摄视频后，回到相册默认会选中当前拍摄的视频，点击确定回调会崩溃。 不知道我描述清楚没有。。。

--- 祝大佬事业顺利！

**Comment by longitachi** [comment]
描述清除了- -确实是个bug，下个版本会更新
