### ISSUE TITLE
提交个BUG

### ISSUE THREAD

**Issue by xqd93** [longitachi/ZLPhotoBrowser#22]
图片浏览器来回看图片，有时能放大的图片滑动回来后不能放大了
- (void)resetSubviewSize
  {
  CGRect frame;
  frame.origin = CGPointZero;
  
  UIImage *image = self.imageView.image;
  CGFloat imageScale = image.size.height/image.size.width;
  CGFloat screenScale = kViewHeight/kViewWidth;
  if (image.size.width <= CGRectGetWidth(self.frame) && image.size.height <= CGRectGetHeight(self.frame)) {
      frame.size.width = image.size.width;
      frame.size.height = image.size.height;
  } else {
      if (imageScale > screenScale) {
          frame.size.height = CGRectGetHeight(self.frame);
          frame.size.width = CGRectGetHeight(self.frame)/imageScale;
      } else {
          frame.size.width = CGRectGetWidth(self.frame);
          frame.size.height = CGRectGetWidth(self.frame) \* imageScale;
      }
  }
  self.scrollView.zoomScale = 1;//差了这句
  self.scrollView.contentSize = frame.size;
  [self.scrollView scrollRectToVisible:self.bounds animated:NO];
  self.containerView.frame = frame;
  self.containerView.center = self.scrollView.center;
  self.imageView.frame = self.containerView.bounds;
  }

**Comment by longitachi** [comment]
最近生病了，一周后统一整，谢谢

**Comment by longitachi** [comment]
谢谢，已更改
