### ISSUE TITLE
有时候toast被present出来的大图预览挡住

### ISSUE THREAD

**Issue by darkhandz** [longitachi/ZLPhotoBrowser#220]
ToastUtils，`+ (void)show:(NSString *)message atTop:(BOOL)atTop showTime:(float)showTime`

有时候toast被present出来的大图预览挡住了，建议挪一下到顶：

`[[UIApplication sharedApplication].keyWindow bringSubviewToFront:toastView];`

**Comment by longitachi** [comment]
好的，我看下
