### ISSUE TITLE
关于直接调用相机的问题

### ISSUE THREAD

**Issue by ChandHsu** [longitachi/ZLPhotoBrowser#227]
大神你好,我调用了ZLCustomCamera去拍视频,拍摄完成之后执行saveVideo,save的回调block内包含的PHAsset,我解析出来的视频首图是逆时针90度的.
然后我又执行一次,这次是执行选择操作,直接选择刚刚保存的视频,获得的视频首图是正常的了,请问是哪里出了问题呢,急,望指教!

**Comment by jianqingyu** [comment]
请问怎么解决
