### ISSUE TITLE
为什么一直显示“加载中，请稍后”

### ISSUE THREAD

**Issue by xiaoqiang051512** [longitachi/ZLPhotoBrowser#231]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by xiaoqiang051512** [comment]
进入相册，点击确定按钮后，一直显示“加载中，请稍后”。
+ (BOOL)judgeAssetisInLocalAblum:(PHAsset *)asset
{
    PHImageRequestOptions *option = [[PHImageRequestOptions alloc] init];
    option.networkAccessAllowed = NO;
    option.synchronous = YES;
    
    __block BOOL isInLocalAblum = YES;
    
    [[PHCachingImageManager defaultManager] requestImageDataForAsset:asset options:option resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
        isInLocalAblum = imageData ? YES : NO;
    }];
    return isInLocalAblum;
}
这里一直返回为NO，明明图片我已经从iCloud上下载下来了

**Comment by longitachi** [comment]
你在QQ或微信上试一下能不能选择

**Comment by xiaoqiang051512** [comment]
我发现我把我的照片iCloud 关闭照片功能，只用本地的话没问题。但是从iCloud下载下来就会有问题

**Comment by longitachi** [comment]
你这个从iCloud上下载，是在手机相册界面下载了？还是在什么地方下载了

**Comment by xiaoqiang051512** [comment]
我的图片托管在iCloud 上，进入选择相片界面会从iCloud上下载原图，原图已经下载好了之后还是，点击确定按钮就弹出toast：“加载中，请稍后”

**Comment by longitachi** [comment]
问下，在我的demo里查看大图界面，能显示你从iCloud上下载的图片吗？

**Comment by longitachi** [comment]
你把这个方法修改为这样试下
```
+ (BOOL)judgeAssetisInLocalAblum:(PHAsset *)asset
{
    NSArray *resourceArray = [PHAssetResource assetResourcesForAsset:asset];
    BOOL bIsLocallayAvailable = [[resourceArray.firstObject valueForKey:@"locallyAvailable"] boolValue];
    return bIsLocallayAvailable;
}
```

**Comment by xiaoqiang051512** [comment]
嗯  换成你的方法可以了 ！谢谢哈

**Comment by xiaoqiang051512** [comment]
不过这是iOS 9 以后新出的方法

**Comment by longitachi** [comment]
你好，问下你当时出现这种无法选择一直加载中是在什么版本的系统中 
#251
这个方法好像在iOS9的系统上判断结果全部是NO
