### ISSUE TITLE
优化视频裁剪界面 —— pod 2.6.7

### ISSUE THREAD

**Issue by xiangkesi** [longitachi/ZLPhotoBrowser#234]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by xiangkesi** [comment]
用同一个视频大概三分钟左右，进入裁剪编辑界面微信的几乎秒进，这个需要转圈很长时间进入，然后点击进行裁剪的时候需要转圈很长时间，还裁剪不成功，最后转圈消失就不动了也不消失当前界面，希望作者大牛尽快优化长一点视频裁剪界面加载和裁剪过程

**Comment by xiangkesi** [comment]
测试了一下,是获取图片每一帧的函数处理的太慢了

**Comment by longitachi** [comment]
pod 2.6.7版本已优化
