### ISSUE TITLE
选择照片的时候NA title 出现英文，而两边都是中文

### ISSUE THREAD

**Issue by yangzheng006** [longitachi/ZLPhotoBrowser#236]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

![Uploading WX20180502-132228@2x.png…]()

**Comment by yangzheng006** [comment]
<img width="381" alt="wx20180502-132228 2x" src="https://user-images.githubusercontent.com/10958391/39506608-576289e6-4e0c-11e8-81b1-64f0e89a4958.png">

**Comment by yangzheng006** [comment]
建议增加  -(UIStatusBarStyle) preferredStatusBarStyle 来设置statusbar的颜色

**Comment by longitachi** [comment]
`ZLPhotoConfiguration`这个类中提供的有`statusBarStyle` 这个属性

**Comment by longitachi** [comment]
你好，你说的这个navtitle是英文，两侧按钮是中文的情况我没重现出来，你是设置的系统语言还是制定了中文简？

**Comment by yangzheng006** [comment]
语言系统我是默认中文的，没有显示的设置

**Comment by yangzheng006** [comment]
![Uploading WX20180619-180620@2x.png…]()

**Comment by longitachi** [comment]
原因：info.plist 文件中需要添加键 `Localized resources can be mixed` 值为 `YES`
