### ISSUE TITLE
相册页面底部工具栏消失

### ISSUE THREAD

**Issue by midorigb** [longitachi/ZLPhotoBrowser#238]
#### 关于 Issue
1. 当前所使用的cocoapods版本: 2.6.6
2. 开发环境: Xcode 9.3(9E145), SDK iOS 11.3
3. 问题描述: 从2.5.2更新到2.6.6版本后，调用[ac showPhotoLibrary] 底部工具栏没有了，单张的预览点进去是有的。

代码如下:

    __weak typeof(self) weakSelf = self;

    ZLPhotoActionSheet *actionSheet = [[ZLPhotoActionSheet alloc] init];

    actionSheet.sender = self;
    [actionSheet setSelectImageBlock:^(NSArray<UIImage *> * _Nonnull images, NSArray<PHAsset *> * _Nonnull assets, BOOL isOriginal) {
        NSMutableArray*array = [NSMutableArray arrayWithArray:images];
        if (weakSelf.dataSource == nil) {
            weakSelf.dataSource = array;
        } else{
            weakSelf.dataSource = [weakSelf.dataSource arrayByAddingObjectsFromArray:array].copy;
        }
        [weakSelf.colletionView reloadData];
    }];
    [actionSheet showPhotoLibrary];

截图如下：
![simulator screen shot - iphone x - 2018-05-04 at 09 50 21](https://user-images.githubusercontent.com/1879894/39610425-bc43b07a-4f82-11e8-9287-15d5815444a6.jpg)

![simulator screen shot - iphone x - 2018-05-04 at 10 06 27](https://user-images.githubusercontent.com/1879894/39610452-006a1c4e-4f83-11e8-8c33-d14fbf8370df.jpg)

**Comment by longitachi** [comment]
是什么手机？还是iPhone X的模拟器？

**Comment by midorigb** [comment]
iPhone X的模拟器

**Comment by longitachi** [comment]
#244
