### ISSUE TITLE
取消选择所有图片后，点击确定还是有一张图片。

### ISSUE THREAD

**Issue by PengChJ** [longitachi/ZLPhotoBrowser#24]
为什么取消选择所有图片，点击确定后还是会有一张图片？我试过QQ空间的图片上传功能，跟你的框架处理流程类似，也是取消所有选择，或者没有选择的时候，点击确定后，也会附带一张图片。
这段代码里面为什么一定要强行增加一张图片呢？不可以传一个空数组回去吗？
- (void)btnDone_Click:(UIButton *)btn
  {
  if (self.arraySelectPhotos.count == 0) {
      PHAsset *asset = _arrayDataSources[_currentPage-1];
      if (![[ZLPhotoTool sharePhotoTool] judgeAssetisInLocalAblum:asset]) {
          ShowToastLong(@"图片加载中，请稍后");
          return;
      }
      ZLSelectPhotoModel *model = [[ZLSelectPhotoModel alloc] init];
      model.asset = asset;
      model.localIdentifier = asset.localIdentifier;
      [_arraySelectPhotos addObject:model];
  }
  if (self.btnDoneBlock) {
      self.btnDoneBlock(self.arraySelectPhotos, self.isSelectOriginalPhoto);
  }
  }

**Comment by longitachi** [comment]
你好，QQ空间里或者QQ聊天在查看大图的时候，点击确定时候，如果没有选择任何照片，则会默认选择当前显示的照片返回。 如果你需要传回空数组的话，第一个if判断 注释掉就好了

**Comment by PengChJ** [comment]
我试过注释掉第一个if，但是屏幕会一直卡在“正在处理”。

**Comment by longitachi** [comment]
注视到第一个if代码块之后，你去ZLPhotoActionSheet.m中找到"- (void)requestSelPhotos:(UIViewController *)vc"这个方法，在方法的开始加如下代码
"
if (self.arraySelectPhotos.count == 0) {
        [self done:nil];
        [self hide];
        [vc.navigationController dismissViewControllerAnimated:YES completion:nil];
        return;
    }
"

**Comment by PengChJ** [comment]
Thank you!完美解决了。
