### ISSUE TITLE
预览网络图片视频崩溃

### ISSUE THREAD

**Issue by NorthDogLi** [longitachi/ZLPhotoBrowser#240]
5.7号：
刚下载的demo，点击 预览网络图片视频 左右滑动后崩溃：
*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <ZLPreviewNetVideo 0x7fb4c9da21f0> for the key path "playbackBufferEmpty" from <AVPlayerItem 0x6000000177f0> because it is not registered as an observer.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011039012b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010f5dff41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000110405245 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010f008f15 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 497
	4   Foundation                          0x000000010f008ccb -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 84
	5   ZLPhotoBrowser                      0x000000010da3d000 -[ZLPreviewNetVideo seekToZero] + 160
	6   ZLPhotoBrowser                      0x000000010da34082 -[ZLPreviewView handlerEndDisplaying] + 914
	7   ZLPhotoBrowser                      0x000000010da888e9 -[ZLShowBigImgViewController collectionView:didEndDisplayingCell:forItemAtIndexPath:] + 169
	8   UIKit                               0x00000001122e171f -[UICollectionView _notifyDidEndDisplayingCellIfNeeded:forIndexPath:] + 195
	9   UIKit                               0x00000001122e9dda __43-[UICollectionView _updateVisibleCellsNow:]_block_invoke_3 + 679
	10  UIKit                               0x00000001122e99a5 __43-[UICollectionView _updateVisibleCellsNow:]_block_invoke_2.982 + 337
	11  CoreFoundation                      0x0000000110314d72 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	12  UIKit                               0x00000001122e981c __43-[UICollectionView _updateVisibleCellsNow:]_block_invoke.981 + 195
	13  UIKit                               0x00000001122e6848 -[UICollectionView _updateVisibleCellsNow:] + 3652
	14  UIKit                               0x00000001122ecc21 -[UICollectionView layoutSubviews] + 364
	15  UIKit                               0x00000001118e0a6d -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1439
	16  QuartzCore                          0x000000011164961c -[CALayer layoutSublayers] + 159
	17  QuartzCore                          0x000000011164d7ad _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 401
	18  QuartzCore                          0x00000001115d486c _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 364
	19  QuartzCore                          0x0000000111601946 _ZN2CA11Transaction6commitEv + 500
	20  QuartzCore                          0x000000011154e3cc _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 960
	21  QuartzCore                          0x000000011168e894 _ZL22display_timer_callbackP12__CFMachPortPvlS1_ + 248
	22  CoreFoundation                      0x000000011031f899 __CFMachPortPerform + 169
	23  CoreFoundation                      0x000000011031f7d9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	24  CoreFoundation                      0x000000011031f741 __CFRunLoopDoSource1 + 465
	25  CoreFoundation                      0x0000000110317524 __CFRunLoopRun + 2596
	26  CoreFoundation                      0x0000000110316889 CFRunLoopRunSpecific + 409
	27  GraphicsServices                    0x000000011c89b9c6 GSEventRunModal + 62
	28  UIKit                               0x000000011180f5d6 UIApplicationMain + 159
	29  ZLPhotoBrowser                      0x000000010da6f1df main + 111
	30  libdyld.dylib                       0x000000011488ad81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by longitachi** [comment]
已查到原因，下个版本会更新解决
