### ISSUE TITLE
ZLThumbnailViewController bottomView 看不见

### ISSUE THREAD

**Issue by iFallen** [longitachi/ZLPhotoBrowser#244]
ZLThumbnailViewController bottomView 在我的工程里面看不见。
pods和导入源码都不好使，Demo没问题。

后来翻了哈源码，发现我的工程对通过runtime 对 UIViewConttroller统一设置了
self.automaticallyAdjustsScrollViewInsets = false;
self.edgesForExtendedLayout = UIRectEdgeNone;

导致bottomView fame超出屏幕了，有点尴尬😄。
之后在ZLThumbnailViewController添加了    

self.automaticallyAdjustsScrollViewInsets = true;
self.edgesForExtendedLayout = UIRectEdgeAll;

**Comment by longitachi** [comment]
多谢帮解决这个问题 #238
