### ISSUE TITLE
错误（视频编辑）

### ISSUE THREAD

**Issue by luowenqi** [longitachi/ZLPhotoBrowser#249]
感谢你的开源框架，这是我发现的问题
在选择遮罩层模式下，对视频长度进行编辑，拖动改变视频长度，有一部分加上了这招，有一部分没有遮罩，应该是所有未被选中的部分全部有遮罩
![4a6d1c6845a224e41d123ef6f518ccba](https://user-images.githubusercontent.com/26103491/39913952-2a731cf8-5536-11e8-878c-a34cd91a8599.png)

**Comment by longitachi** [comment]
好的
