### ISSUE TITLE
相册位置错乱

### ISSUE THREAD

**Issue by Chana719** [longitachi/ZLPhotoBrowser#25]
每次进入选择相册界面，相册的位置都是不一样的，总是错乱，请问博主，知道这个问题吗？？ 如果看到了，麻烦回复下哈，谢谢！

**Comment by longitachi** [comment]
这个问题还真没遇见过，能发一些图吗？gif的最好

**Comment by Chana719** [comment]
先给你说下重现方式吧，拿你的demo为例，打开app－选择照片－相册  进去，里面的照片不是按照的时间的顺序排的，有那么2张3张，会是之前的照片，你可以在真机上试试，因为在模拟器上就几张照片是看不出来的，博主可以试试哈！谢谢

**Comment by Chana719** [comment]
或者我们可以加微信或者QQ在线聊

**Comment by longitachi** [comment]
495181165，加一下
