### ISSUE TITLE
iOS 9 本地图片无法选择，还请查证

### ISSUE THREAD

**Issue by ElliotXY** [longitachi/ZLPhotoBrowser#251]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by ElliotXY** [comment]
提示“请在系统相册中下载到本地后重新尝试”，iOS 10及11 正常

**Comment by ElliotXY** [comment]
最新版 2.6.9版本

**Comment by longitachi** [comment]
不好意思，才看到，手里没有iOS9的机器，问下iOS8下面正常吗

**Comment by ElliotXY** [comment]
您好，试了一下，iOS 8 及 10  11 都正常，iOS 是从2.6.7这个版本开始不行了，2.6.6版本可以，问题如下图提示。
![111](https://user-images.githubusercontent.com/20962182/40344909-8befa866-5dc9-11e8-8acd-578646f0d7c4.png)

**Comment by ElliotXY** [comment]
模拟器iOS9 也是不行

**Comment by longitachi** [comment]
最近比较忙，明天我下载一个iOS9的模拟器试一下。

**Comment by longitachi** [comment]
你看下`ZLPhotoManager`的这个方法，调试一下，看是不是iOS9一直返回的NO
```
+ (BOOL)judgeAssetisInLocalAblum:(PHAsset *)asset
{
    __block BOOL result = NO;
    if (@available(iOS 9.0, *)) {
        // https://stackoverflow.com/questions/31966571/check-given-phasset-is-icloud-asset
        NSArray *resourceArray = [PHAssetResource assetResourcesForAsset:asset];
        if (resourceArray.count) {
            result = [[resourceArray.firstObject valueForKey:@"locallyAvailable"] boolValue];
        }
    } else {
        PHImageRequestOptions *option = [[PHImageRequestOptions alloc] init];
        option.networkAccessAllowed = NO;
        option.synchronous = YES;
        
        [[PHCachingImageManager defaultManager] requestImageDataForAsset:asset options:option resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
            result = imageData ? YES : NO;
        }];
    }
    return result;
}
```

**Comment by ElliotXY** [comment]
是的，这块的逻辑有点问题
![11111](https://user-images.githubusercontent.com/20962182/40468032-b50eac06-5f5e-11e8-9fb3-7f6c7a441fdf.png)
这个判断条件不对

**Comment by fengweiru** [comment]
我也发现这个问题9.3.2上，刚截屏的图片所有图片选择返回都为NO

**Comment by ElliotXY** [comment]
暂时先用 2.6.6吧

**Comment by longitachi** [comment]
我搜了搜资料，这个方法是iOS9出的，但是iOS9上确实会出现问题，等这两天会改下这个

**Comment by zhangtibin** [comment]
这个问题在 iOS 10.2.1 系统中也会返回 NO，请问有什么解决办法没？
