### ISSUE TITLE
1.如果我设置最大选择100张,这时候选择99张没问题,但是100张就卡死了

### ISSUE THREAD

**Issue by hanyvchen** [longitachi/ZLPhotoBrowser#252]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
问下是怎么个卡死情况，是点击第100张按钮时候直接卡死，还是选择100张后，点击了确定按钮解析图片过程中内存爆掉卡死了？

**Comment by hanyvchen** [comment]
是在解析的时候卡死的,之后没有遇到这个问题,应该是图片太多的原因
