### ISSUE TITLE
即使选择了原图，发现图片尺寸还是缩小了

### ISSUE THREAD

**Issue by ipad4** [longitachi/ZLPhotoBrowser#254]
从ZLPhotoBrowser里选择出的原图保存下来，对比一下相册中的原图，尺寸变小了

**Comment by longitachi** [comment]
size没有改变，改变了data的大小

**Comment by ipad4** [comment]
经测试，size确实改变了，应当将requestOriginalImageForAsset方法中调用requestImageForAsset方法时的size参数传PHImageManagerMaximumSize

**Comment by ipad4** [comment]
我是测试的这张图：https://raw.githubusercontent.com/ipad4/resourcetest/master/IMG_3748-2.JPG
原图尺寸为：3024 × 4032
选出来保存后尺寸为：2304 × 3072

**Comment by longitachi** [comment]
我等会选择几张照片测试一下

**Comment by ipad4** [comment]
可能跟图片有关，可以用尽可能的大的图片试试。
我测试如果把ZLPhotoManager.m中第435行代码CGSizeMake(asset.pixelWidth, asset.pixelHeight)修改为PHImageManagerMaximumSize 就不会出现上述问题。
