### ISSUE TITLE
判断照片在本地相册的bug

### ISSUE THREAD

**Issue by huanghe810229530** [longitachi/ZLPhotoBrowser#261]
系统是iOS11.2  iPhone6 plus

照片存在本地，选择照片时提示“请在系统相册下载”。QQ是正常可选，而且照片确实是在本地相册。

屏蔽下面代码后可以正常使用：
`
// https://stackoverflow.com/questions/31966571/check-given-phasset-is-icloud-asset
        NSArray *resourceArray = [PHAssetResource assetResourcesForAsset:asset];
        if (resourceArray.count) {
            result = [[resourceArray.firstObject valueForKey:@"locallyAvailable"] boolValue];
        }
`
上面的判断是有问题的。

**Comment by longitachi** [comment]
1. QQ可以正常查看大图发送吗？
2. 相册中也可以正常查看大图吗？
3. 该框架可以正常查看大图但不能选择吗？

**Comment by huanghe810229530** [comment]
前两点试过了都可以，第三点没试过，但是在相册勾选时候提示要下载到本地。现在不影响使用，先放着吧。
