### ISSUE TITLE
预览网络视频,点击返回就闪退了

### ISSUE THREAD

**Issue by hanyvchen** [longitachi/ZLPhotoBrowser#262]
![1183650796ba9839cfac35b89828fd1f](https://user-images.githubusercontent.com/16074762/41334856-87d2e5de-6f19-11e8-8891-10e4cb578717.jpg)
播放视频后,点击返回闪退

**Comment by hongdong** [comment]
一样的问题
[ZLPreviewNetVideo retain]: message sent to deallocated instance 0x7fe42f50ff40
调用了释放的对象
希望作者能尽快看到。

**Comment by hongdong** [comment]
![image](https://user-images.githubusercontent.com/5499518/41787973-9c30af88-767c-11e8-864d-d948c67545a1.png)
加这个就好了

**Comment by hanyvchen** [comment]
好了

**Comment by longitachi** [comment]
@hongdong 是最新版本吗，怎么操作会crash
