### ISSUE TITLE
Iphone X 開啟速度 頓1秒左右

### ISSUE THREAD

**Issue by c941010623** [longitachi/ZLPhotoBrowser#266]
使用環境 真機 Iphone X 256G and iOS 11.4
我使用 actionSheet.showPhotoLibrary() 直接呼叫相冊清單

相冊清單出現之後(視窗往上的動畫)
動畫出現到最頂端並沒有覆蓋到全部[top] (在最上面的畫面上會看到我的背景[白色])
之後頓住1秒，才會整個覆蓋上去 (預設 水藍色)
請問我該如何調適他呢 ?

**Comment by longitachi** [comment]
`actionSheet.configuration.showCaptureImageOnTakePhotoBtn = NO`
