### ISSUE TITLE
怎么隐藏或替换 选择图片视图中的 导航栏返回键？ —— 2.7.1 fixed

### ISSUE THREAD

**Issue by linjiaxing1992** [longitachi/ZLPhotoBrowser#267]
![screenshot 2018-06-20_09-54-03](https://user-images.githubusercontent.com/16900223/41633239-75d4739a-7403-11e8-948f-8e87ae6541ff.png)

我发现我根本隐藏不了它  找了好几个地方

**Comment by longitachi** [comment]
为什么要隐藏呢？。。

**Comment by linjiaxing1992** [comment]
Emmmm 相统一一下整个app的导航栏以及按钮呀，应该说是替换

**Comment by longitachi** [comment]
你是想要替换返回按钮的图片？

**Comment by linjiaxing1992** [comment]
对呀  但是发现直接设置会变成原本的黑色箭头在，自己自定义的箭头也一起在😂

**Comment by longitachi** [comment]
好的，这两天会更新下，添加自定义导航返回按钮图片功能
