### ISSUE TITLE
多選照片時的編輯 BUG

### ISSUE THREAD

**Issue by c941010623** [longitachi/ZLPhotoBrowser#269]
我目前多選照片之後
再利用 previewSelectedPhotos 點選照片時，每張照片都有 編輯 按鈕
所以我編輯了
但是照片卻從多張變成只有一張。

請問我該如何多張編輯
又或者
多張照片時，可否讓 previewSelectedPhotos 中的編輯按鈕消失呢

另外我發現
比如我選5張照片
previewSelectedPhotos 每一張照片都有編輯
按確定之後 image 從5張變成編輯後的那一張 .....

DEMO 裡面的 DNOE 會有 Done(5)
可是我的只有 Done ....

**Comment by longitachi** [comment]
你好。选择五张时候应该是没有显示编辑按钮的吧。 只有单选或者没有选择时候才会显示编辑按钮，暂时不支持多张编辑

**Comment by c941010623** [comment]
Sorry ，我指的是 使用 previewSelectedPhotos
之後如果有多張的情況下，依然會有編輯 可以使用

**Comment by longitachi** [comment]
好的，我看到了
