### ISSUE TITLE
必须要先show 那个actionsheet吗?可不可以直接跳到多选相册里

### ISSUE THREAD

**Issue by JCleqiang** [longitachi/ZLPhotoBrowser#27]

**Comment by longitachi** [comment]
可以的。稍微改下代码就好了，我现在电脑在公司。周日了回复你

**Comment by JCleqiang** [comment]
大神 不是说周日回复我吗 @longitachi

**Comment by longitachi** [comment]
等下，更新了xcode8项目配置出现点问题

**Comment by longitachi** [comment]
注释下面两行，添加一行，你随便看一下代码应该就能看出来
- (void)showWithSender:(UIViewController *)sender animate:(BOOL)animate lastSelectPhotoModels:(NSArray<ZLSelectPhotoModel *> *)lastSelectPhotoModels completion:(void (^)(NSArray<UIImage *> * _Nonnull, NSArray<ZLSelectPhotoModel *> * _Nonnull))completion
{
    self.handler = completion;
    self.animate = animate;
    self.sender  = sender;
    self.previousStatusBarStyle = [UIApplication sharedApplication].statusBarStyle;
    [self.arraySelectPhotos removeAllObjects];
    [self.arraySelectPhotos addObjectsFromArray:lastSelectPhotoModels];
    
    //[self loadPhotoFromAlbum];
    //[self show];
    [self btnPhotoLibrary_Click:nil];
}

**Comment by longitachi** [comment]
我这边更新xcode8，配置出了点问题，运行不了，有啥问题再回复好了

**Comment by JCleqiang** [comment]
OK @longitachi

**Comment by JCleqiang** [comment]
如果是直接跳到多选相册,选择完成点"确定"不会调completion:(void (^)(NSArray<UIImage *> *selectPhotos, NSArray<ZLSelectPhotoModel *> *selectPhotoModels))completion 这个 block

**Comment by longitachi** [comment]
不好意思，前两天太忙，等会更新下代码， 你把ZLPhotoActionSheet属性声明为类变量就好了。 不然的话就等我待会更新代码

**Comment by devalcry** [comment]
如果是在表里用的话，这也太尴尬了。

**Comment by longitachi** [comment]
在表里用什么意思？

**Comment by longitachi** [comment]
想直接弹出相册界面，有新的接口，请仔细看下介绍。里面都有

**Comment by devalcry** [comment]
在TableViewController里用，这是加在控制器里的，滑动的时候会跟着走啊！

**Comment by lilovexin** [comment]
ZLPhotoActionSheet 里面的 有什么方法可以将其隐藏吗？？

**Comment by lilovexin** [comment]
ZLPhotoActionSheet就是不显示里面的控件

**Comment by longitachi** [comment]
@lilovexin 不显示里面的控件什么意思？
