### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by darkThanBlack** [longitachi/ZLPhotoBrowser#270]
Will this project support ``Carthage``? Thank you very much!

**Comment by darkThanBlack** [comment]
May these link provide some help:
https://blog.yourtion.com/public-frameworks-with-carthage.html
http://shinancao.github.io/2017/07/16/Project-Design-4/

**Comment by longitachi** [comment]
👌

**Comment by longitachi** [comment]
问下，你用carthage 能 安装 `GUImage` 这个框架吗？

**Comment by longitachi** [comment]
![4430e314-6c9e-4900-8f96-dc8b0b99b747](https://user-images.githubusercontent.com/11711768/42505830-8adccca4-8472-11e8-9d2f-57a989afe4e5.png)

先整一个demo试下，`carthage update`时候`GPUImage`，一直报错搜了好多，搜了一些资料，暂时没有解决

**Comment by longitachi** [comment]
好的，我考虑下

**Comment by longitachi** [comment]
3.0.0 已支持carthage
