### ISSUE TITLE
单选裁剪图片问题

### ISSUE THREAD

**Issue by LoSenTrad** [longitachi/ZLPhotoBrowser#273]
你好,我看了好多反馈,我说一下需求很大的一个需求,就是单选图片,直接进入预定好的裁剪比例编辑界面,然后选取图片.现在只能手动点击裁剪才能做指定的裁剪比例裁剪.

**Comment by chenfengfeng** [comment]
@LoSenTrad 我也是有这个需求，我工具只选择了裁剪一种，比例也默认一种，其实建议这种情况下打开就默认裁剪不能取消裁剪，这样是比较合理的

**Comment by longitachi** [comment]
之前有这个功能，后来添加了滤镜就添加了工具条，最新版本3.0.0版本已换回原来的功能，即该issue提的
