### ISSUE TITLE
为什么导航栏标题的颜色是白色的

### ISSUE THREAD

**Issue by halocq** [longitachi/ZLPhotoBrowser#279]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [x ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）
最新版本，是白色而且没有找到设置的地方

**Comment by longitachi** [comment]
这个可以自定义的，默认是白色的

**Comment by halocq** [comment]
@longitachi 设置了navTitleColor没有效果

**Comment by halocq** [comment]
demo也不行的

**Comment by halocq** [comment]
actionSheet.navTitleColor = [UIColor blackColor];
    actionSheet.navBarColor = [UIColor whiteColor];

![image](https://user-images.githubusercontent.com/11287047/42363938-004627f0-812c-11e8-8452-6be9cb89b1e6.png)

**Comment by longitachi** [comment]
你用的是什么版本？更新下版本吧
`actionSheet.configuration.navBarColor` `actionSheet.configuration.navTitleColor`

**Comment by halocq** [comment]
更新之后好了，谢谢！如何在混合选择的时候可以控制视频的数量啊？

**Comment by longitachi** [comment]
这个暂时不支持的

**Comment by halocq** [comment]
那有什么比较好的思路吗？

**Comment by longitachi** [comment]
修改源码的话可以再 `ZLPhotoConfiguration` 类里面添加视频最大数量
