### ISSUE TITLE
请问，Swift里为什么不能调用showWithSender方法，急

### ISSUE THREAD

**Issue by EricDengR** [longitachi/ZLPhotoBrowser#28]

**Comment by longitachi** [comment]
这个我没有试过，你创建桥接文件之后不能吗？

**Comment by EricDengR** [comment]
@longitachi 是的，Bridging-Header.h文件里已经import头文件了，可是在其他swift类里不能调用showWithSender方法

**Comment by longitachi** [comment]
我帮你问问吧，我没用过swift桥接文件搞过这个。

**Comment by EricDengR** [comment]
太感谢了

**Comment by longitachi** [comment]
我朋友试的都行，你是不是配置文件里没有设置桥接文件路径，还有就是导入后编译一下

**Comment by EricDengR** [comment]
<img width="1056" alt="qq20160921-0 2x" src="https://cloud.githubusercontent.com/assets/13251150/18714158/72400ec6-8047-11e6-8c25-8778b8a878a7.png">

桥接文件应该是没问题，能调用这个类，但是showWithSender方法还是不能调用。不过我在OC的类里面倒是可以正常调用该方法。哦，对了，我用的是Swift 3会不会有什么影响

**Comment by longitachi** [comment]
我刚才试了下，和你一样，不能调用showWithSender。 这个我就不知道了，2.0是可以的

**Comment by EricDengR** [comment]
(；′⌒`)，咋办，大神帮我看看怎么可以改进一下吧，拜托了

**Comment by longitachi** [comment]
。。。我不太懂swfit，你看下是不是所有的oc框架swift3.0都不能调用了，如果都不能用了，那肯定是有哪个地方可以设置的

**Comment by EricDengR** [comment]
我目前还是先用回上一个版本了，然后在plist里添加了个key，解决在XCode8/iOS10中访问本地相册导致crash的问题
