### ISSUE TITLE
ZLPhotoBrowseriCloudPhotoText(提示请在系统相册中下载到本地后重新尝试)

### ISSUE THREAD

**Issue by Lzs402835236** [longitachi/ZLPhotoBrowser#286]
xcode9.4.1,系统11.4.真机6p.进入相册选取页面多选本地以前照片时,总是提示:请在系统相册中下载到本地后重新尝试.直接拍照后可选!希望作者能提供一个解决思路.在5s上.11.3系统可正常选取

**Comment by longitachi** [comment]
好的，我看下。
```
+ (BOOL)judgeAssetisInLocalAblum:(PHAsset *)asset
{
    __block BOOL result = NO;
    if (@available(iOS 10.0, *)) {
        // https://stackoverflow.com/questions/31966571/check-given-phasset-is-icloud-asset
        // 这个api虽然是9.0出的，但是9.0会全部返回NO，未知原因，暂时先改为10.0
        NSArray *resourceArray = [PHAssetResource assetResourcesForAsset:asset];
        if (resourceArray.count) {
            result = [[resourceArray.firstObject valueForKey:@"locallyAvailable"] boolValue];
        }
    } else {
        PHImageRequestOptions *option = [[PHImageRequestOptions alloc] init];
        option.networkAccessAllowed = NO;
        option.synchronous = YES;
        
        [[PHCachingImageManager defaultManager] requestImageDataForAsset:asset options:option resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
            result = imageData ? YES : NO;
        }];
    }
    return result;
}
```
如果11.4判断是否在本地也会出错，那么我感觉苹果真的有毒。

**Comment by Lzs402835236** [comment]
亲测,11.4返回NO,作者有什么好的解决办法没!还有在选取照片页面,导航栏返回按钮重复没找到问题,我这边没有自定义,将你的resource里的navBackBtn@2x改名也还是重复显示按钮!

**Comment by Lzs402835236** [comment]
我将该方法判断去掉后,发现11.4部分照片可选择!可还是没解决问题!头疼
+ (BOOL)judgeAssetisInLocalAblum:(PHAsset *)asset
{
    __block BOOL result = NO;
        PHImageRequestOptions *option = [[PHImageRequestOptions alloc] init];
        option.networkAccessAllowed = NO;
        option.synchronous = YES;
        
        [[PHCachingImageManager defaultManager] requestImageDataForAsset:asset options:option resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
            result = imageData ? YES : NO;
        }];
    return result;
}

**Comment by longitachi** [comment]
你用的什么版本？2.7.0版本已经把所有资源图片加上了前缀

**Comment by Lzs402835236** [comment]
刚才我又试了11.4.1然后发现可以成功选择图片,然后我又用模拟器试11.4系统,结果发现也选择成功了,然后我就去看我们的6p测试机,我发现他的iCloudID和APPID不一致,我很怀疑是ID不一致导致的问题!然后我想尽办法复现iCloud和APPid不一致的情况,发现还是可以选择成功!然后我个人觉得可能还是账号不一致,导致图片被标识后,虽然是同一个手机上的照片,可是却使用不了,但是问题我没复现成功,感觉很郁闷!导航栏返回用的是最新的版本,还是出现重复样式!
![5fbc4a26efa02f63833d820c5259728c](https://user-images.githubusercontent.com/24582891/42920095-a7bae38e-8b47-11e8-9445-fd98e247a084.png)

**Comment by Lzs402835236** [comment]
大神跪求解决问题啊,试了各种办法都没解决.怎么直接把他隐藏掉呢或者不要返回按钮图片!求帮助啊!
