### ISSUE TITLE
小调查：框架内滤镜效果是否多余

### ISSUE THREAD

**Issue by longitachi** [longitachi/ZLPhotoBrowser#288]
最近收到一些朋友提的issue，说想要编辑功能回到之前没有滤镜的版本。

所以想做一个小调查，希望查阅issue的朋友看到的话在此条下进行回复是否需要滤镜这个功能。多谢。

ps.由于滤镜效果依赖了`GPUImage`，所以暂时无法支持`Carthage`，如果取消滤镜效果，框架可以支持`Carthage`，这也是一个可以选择的地方。

**Comment by eric1202** [comment]
不多余 只是相应的增加了包体积而已 
pod 用户还是多一些

**Comment by wanyongjian** [comment]
感谢作者做的这个强大的框架。
个人认为这几个滤镜都是很平常一般没人用的，建议开放接口可以自己指定editType。
刚才就是改了代码去掉滤镜.....
ZLImageEditType editType = ZLImageEditTypeClip | ZLImageEditTypeRotate;

**Comment by longitachi** [comment]
@wanyongjian 这个接口是会开放的，有人提说没什么用建议去掉这个功能，然后支持下carthage。现在因为有GPUImage这个框架，不能支持carthage

**Comment by mgv5** [comment]
建议去掉吧, 这几个滤镜一般很少用到. 去掉GPUImage还可以减小包体积.

**Comment by CoderLT** [comment]
建议去掉, 使用场景很少. 建议可以 开放一个接口出来.  有需要的小伙伴, 自己集成.

**Comment by ruiq** [comment]
感觉可选更好，毕竟GPUImage这个框架挺大的，对于包体积敏感的项目可能影响比较大。

**Comment by TabCen** [comment]
及其多余

**Comment by YaoWeiCheng** [comment]
真的很多余，非常建议去掉

**Comment by longitachi** [comment]
已删除滤镜功能
