### ISSUE TITLE
如何设置多选图片时候的已选图片提示arrSelectedAssets

### ISSUE THREAD

**Issue by eric1202** [longitachi/ZLPhotoBrowser#289]
arrSelectedAssets 设置了 从

[_photoActionSheet setSelectImageBlock:^(NSArray<UIImage *> * _Nullable images, NSArray<PHAsset *> * _Nonnull assets, BOOL isOriginal) {
                //            _imageArray = images.mutableCopy;
                [weakSelf.imageArray removeAllObjects];
                [weakSelf.imageArray addObjectsFromArray:images];
                weakSelf.photoActionSheet.arrSelectedAssets = assets.mutableCopy;

            }];

然而下次        
[_photoActionSheet showPreviewAnimated:YES];
依旧是没有打勾

**Comment by longitachi** [comment]
不要再这个block里给`arrSelectedAssets`赋值，因为回调给你后，清空了已选择的照片，你在`showPreviewAnimated `之前赋值
