### ISSUE TITLE
发现第一次进去到多相册选择的时候代码会崩溃到以下代码，请问如何解决？

### ISSUE THREAD

**Issue by ErShaoYeLiu** [longitachi/ZLPhotoBrowser#29]
- (void)pushThumbnailVCWithIndex:(NSInteger)index animated:(BOOL)animated
  {
  ZLPhotoAblumList *ablum = _arrayDataSources[index];//开始请求权限的时候，会奔溃到这句
  
  ZLThumbnailViewController *tvc = [[ZLThumbnailViewController alloc] initWithNibName:@"ZLThumbnailViewController" bundle:kZLPhotoBrowserBundle];
  tvc.title = ablum.title;
  tvc.maxSelectCount = self.maxSelectCount;
  tvc.isSelectOriginalPhoto = self.isSelectOriginalPhoto;
  tvc.assetCollection = ablum.assetCollection;
  tvc.arraySelectPhotos = self.arraySelectPhotos.mutableCopy;
  tvc.sender = self;
  tvc.DoneBlock = self.DoneBlock;
  tvc.CancelBlock = self.CancelBlock;
  [self.navigationController pushViewController:tvc animated:animated];
  }

**Comment by ErShaoYeLiu** [comment]
数组为空

**Comment by longitachi** [comment]
你调用时候是直接进入相册的模式还是先显示预览视图的模式？

**Comment by ErShaoYeLiu** [comment]
没有获取权限的时候和进入设置开启权限的时候，直接进入都会崩溃，已经亲测

**Comment by longitachi** [comment]
已解决

**Comment by longitachi** [comment]
进入设置开启权限的那个，是系统导致的重启，这个暂时无法解决

**Comment by ErShaoYeLiu** [comment]
请问你是怎么解决的？我也解决了，方法是：在权限回调方法里面做跳转不要在外部判断，不然也会崩溃

**Comment by longitachi** [comment]
差不多，权限回调跳转只是首次授权时候才执行一次。  我在show的时候判断了一下权限

**Comment by ErShaoYeLiu** [comment]
后续使用有问题，我会及时与你沟通，合作愉快！
