### ISSUE TITLE
视频上传问题

### ISSUE THREAD

**Issue by hotdog12345a** [longitachi/ZLPhotoBrowser#294]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

cocopoads 版本 2.7.1

您好，上传视频时用得到的lastSelectAssets 获取到PHASSET  然后用 exportVideoForAsset 转换成MOV 得到exportFilePath    NSURL *path = [NSURL fileURLWithPath:exportFilePath]; 
 然后上传 这个path  服务器不能接收， 然后传图片 或者是工程目录里的 视频时可以成功的。  
 十分困扰  尝试了把PHASSET 进行其他方法 转码 依旧上传不了。

               [ZLPhotoManager exportVideoForAsset: lastSelectAssets[0] type:ZLExportVideoTypeMov complete:^(NSString *exportFilePath, NSError *error) {
                            NSURL *path = [NSURL fileURLWithPath:exportFilePath];
                            [formData appendPartWithFileURL:path name:@"request" fileName:str mimeType:@"application/octet-stream" error:nil];

在模拟器上打印了这个exportFilePath 是 可以播放的MOV

谢谢

**Comment by longitachi** [comment]
是不是 `mimeType` 传的类型不对？ 试试`video/mov`，或者导出成`mp4`格式用`video/mp4`

**Comment by longitachi** [comment]
你把路径的视频转成data，用这个方法传下`[formData appendPartWithFileData:name:fileName:mimeType:`

**Comment by hotdog12345a** [comment]
这种方法也试过了，也不行
只有方法5上传成功了，猜测应该是强行转换成image了  然后服务器下载后播放不了。

===========1
 PHAsset *myAsset = filePath[0];
//            PHVideoRequestOptions *options = [[PHVideoRequestOptions alloc] init];
//            [[PHImageManager defaultManager] requestAVAssetForVideo:myAsset options:options resultHandler:^(AVAsset * _Nullable asset, AVAudioMix * _Nullable audioMix, NSDictionary * _Nullable info) {
//                NSURL *fileRUL = [asset valueForKey:@"URL"];
//
//                NSData *beforeVideoData = [NSData dataWithContentsOfURL:fileRUL];//未压缩的视频流
//                [formData appendPartWithFileData:beforeVideoData name:@"request" fileName:str mimeType:@"video/mov"];
//            }];

===============2
 PHAsset *phAsset = filePath[0];
//            if (phAsset.mediaType == PHAssetMediaTypeVideo) {
//                PHVideoRequestOptions *options = [[PHVideoRequestOptions alloc] init];
//                options.version = PHImageRequestOptionsVersionCurrent;
//                options.deliveryMode = PHVideoRequestOptionsDeliveryModeAutomatic;
//
//                PHImageManager *manager = [PHImageManager defaultManager];
//                [manager requestAVAssetForVideo:phAsset options:options resultHandler:^(AVAsset * _Nullable asset, AVAudioMix * _Nullable audioMix, NSDictionary * _Nullable info) {
//                    AVURLAsset *urlAsset = (AVURLAsset *)asset;
//
//                    NSURL *url = urlAsset.URL;
//                    NSData *data = [NSData dataWithContentsOfURL:url];
//                    [formData appendPartWithFileData:data name:@"request" fileName:str mimeType:@"application/octet-stream"];
//
//
//                    NSLog(@"%@",data);
//                }];
//            }

==============3
  [[PHCachingImageManager defaultManager] requestPlayerItemForVideo:filePath[0] options:nil resultHandler:^(AVPlayerItem * _Nullable playerItem, NSDictionary * _Nullable info) {
//                NSString *str =  info[@"PHImageFileSandboxExtensionTokenKey"];
//                NSString *fenge = @";/";
//                NSArray *arr =  [str componentsSeparatedByString:fenge];
//                NSString *endstr = [NSString  stringWithFormat:@"/%@",arr[1]];
//                NSLog(@"%@",arr);
//                        NSURL *path = [NSURL fileURLWithPath:endstr];
//                    NSLog(@"%d",[formData appendPartWithFileURL:path name:@"request" fileName:str mimeType:@"application/octet-stream" error:nil]);
//
//
//
//            }];

==================4

 PHImageManager *manager = [PHImageManager defaultManager];
            NSLog(@"ccccccccc%@",filePath);
            [manager requestAVAssetForVideo:filePath[0] options:options resultHandler:^(AVAsset * _Nullable asset, AVAudioMix * _Nullable audioMix, NSDictionary * _Nullable info) {
                AVURLAsset *urlAsset = (AVURLAsset *)asset;
                NSURL *url = urlAsset.URL;
                NSData *data = [NSData dataWithContentsOfURL:url];
                 [formData appendPartWithFileData:data name:@"request" fileName:str mimeType:@"application/octet-stream"];
            }];
            

=============5 
/            [[PHImageManager defaultManager] requestImageDataForAsset: filePath[0]
//                                                              options: options
//                                                        resultHandler: ^(NSData * imageData, NSString * dataUTI, UIImageOrientation orientation, NSDictionary * info) {
//                                                            NSLog(@"%@",imageData);
//                                                            //这里的imageData就是视频数据;
//                                                            [formData appendPartWithFileData:imageData name:@"request" fileName:str mimeType:@"video/mov"];
//
//                                                        }];

**Comment by ouhuiju** [comment]
@hotdog12345a 你好，请问最后问题解决了吗？我貌似也遇到这个问题了
