### ISSUE TITLE
隐藏选择图片的左上角返回

### ISSUE THREAD

**Issue by eric1202** [longitachi/ZLPhotoBrowser#295]
_photoActionSheet = [[ZLPhotoActionSheet alloc] init]
 _photoActionSheet.sender = self.
[_photoActionSheet showPreviewAnimated:YES];

如上代码操作 导航栏会显示对应返回button （和readme的图类似）
点击了 会隐藏 但并不会dismiss 当前contoller 
请问如何设置 方能隐藏导航栏的第一级返回键呢？

**Comment by eric1202** [comment]
![1](https://user-images.githubusercontent.com/11612443/43395273-0fc85b50-9430-11e8-8911-c45c34a990cd.png)
![2](https://user-images.githubusercontent.com/11612443/43395274-10f951d2-9430-11e8-9c5a-b0ce3105f6ed.png)
![3](https://user-images.githubusercontent.com/11612443/43395276-11c74f10-9430-11e8-9b35-b962472da194.png)
逻辑大概是点击选择 这样子的 因为是present 出来的 所以左上角的back 点击没有作用？

**Comment by longitachi** [comment]
present界面时候，套了一个导航，所以与外界的导航是没有关联的，不过你这个左右按钮为什么都没了，是你有修改东西吗

**Comment by eric1202** [comment]
就是点击了 那个套的导航栏的左边按钮 就变成了两边都消失了 难道是有runtime？

**Comment by eric1202** [comment]
左上角的返回 理应是回到相册album列表之类的吧

**Comment by longitachi** [comment]
你说的这种情况，在demo里也会这样吗？

**Comment by eric1202** [comment]
demo 是没问题的 后来我用swizzle 解决了下 pop的问题 估计是某第三方代码冲突了
