### ISSUE TITLE
我选择完照片之后,或者我选择取消之后,我底部的textView控件就会消失,请问怎么办哦,谢谢!!

### ISSUE THREAD

**Issue by 360573078** [longitachi/ZLPhotoBrowser#30]

**Comment by longitachi** [comment]
不懂你的意思，配个图吧

**Comment by TaoistKing** [comment]
我也遇到这个问题，就是聊天页面，类似微信的那种，底部是文字输入框，还有一个按钮（选择图片、表情等的按钮），点击按钮后后弹出ZLPhotoActionSheet，ZLPhotoActionSheet dismiss之后，底部的输入框和那些按钮也消失了。
我的聊天页面用的是JSQMessagesViewController，很多人应该都用这个。
@360573078 你这边解决了吗？

**Comment by longitachi** [comment]
能配一个gif图吗？我现在看下

**Comment by TaoistKing** [comment]
正常情况下，在聊天界面里，底部的TabbarController的底部的导航条是隐藏的，但是调用ZLPhotoActionSheet之后，底部的导航条显示了出来，遮住了应该显示的输入框。

**Comment by longitachi** [comment]
这个最新版本解决了。更新下最新的版本。

**Comment by TaoistKing** [comment]
我是今天刚下载的。。用的Pod，
> Installing ZLPhotoBrowser (1.1.0)

**Comment by longitachi** [comment]
。。。pod还没更新。。。现在更新下吧

**Comment by longitachi** [comment]
可以了，update一下

**Comment by TaoistKing** [comment]
@longitachi 已验证，完美！
