### ISSUE TITLE
图片模糊

### ISSUE THREAD

**Issue by shen456** [longitachi/ZLPhotoBrowser#304]
我在使用的时候 上传图片模糊
#pragma mark - 请求所选择图片、回调
- (void)requestSelPhotos:(UIViewController *)vc data:(NSArray<ZLPhotoModel *> *)data hideAfterCallBack:(BOOL)hide
我是在这个方法里获取的图片  因为项目需求 我就修改了一下大神你的代码 在这方法里获取的图片

是不是我还少些代码 请指教 怎么解决图片模糊

**Comment by longitachi** [comment]
你修改了哪个方法的代码，贴出来一下看看

**Comment by shen456** [comment]
- (void)requestSelPhotos:(UIViewController *)vc data:(NSArray<ZLPhotoModel *> *)data hideAfterCallBack:(BOOL)hide
{
    
  
    NSLog(@"这是图片吗 ---------- %@ --------- %@",data, vc);
    NSLog(@"我回调过来了 咱走下一个页面可好");
    ZLProgressHUD *hud = [[ZLProgressHUD alloc] init];
    [hud show];
    if (!self.configuration.shouldAnialysisAsset) {
        NSMutableArray *assets = [NSMutableArray arrayWithCapacity:data.count];
        for (ZLPhotoModel *m in data) {
            [assets addObject:m.asset];
        }
        [hud hide];
        if (self.selectImageBlock) {
            self.selectImageBlock(nil, assets, self.isSelectOriginalPhoto);
            [self.arrSelectedModels removeAllObjects];
        }
        if (hide) {
            
            
            [self hide];
            [vc dismissViewControllerAnimated:YES completion:nil];
        }
        return;
    }
    
    __block NSMutableArray *photos = [NSMutableArray arrayWithCapacity:data.count];
    __block NSMutableArray *assets = [NSMutableArray arrayWithCapacity:data.count];
    
    NSMutableArray *picArry = [NSMutableArray array];
    for (int i = 0; i < data.count; i++) {
        [photos addObject:@""];
        [assets addObject:@""];
    }

    zl_weakify(self);
    for (int i = 0; i < data.count; i++) {
        ZLPhotoModel *model = data[i];
        [ZLPhotoManager requestSelectedImageForAsset:model isOriginal:self.isSelectOriginalPhoto allowSelectGif:self.configuration.allowSelectGif completion:^(UIImage *image, NSDictionary *info) {
            //NSData *mydata=UIImageJPEGRepresentation(image , 0.5);
//            [picArry addObject:image];
            if ([[info objectForKey:PHImageResultIsDegradedKey] boolValue]) return;

            zl_strongify(weakSelf);
            if (image) {
                [photos replaceObjectAtIndex:i withObject:[ZLPhotoManager scaleImage:image original:strongSelf->_isSelectOriginalPhoto]];
                [assets replaceObjectAtIndex:i withObject:model.asset];
             
            }

            for (id obj in photos) {
                NSLog(@"%@",obj);
                if ([obj isKindOfClass:[NSString class]]) return;
            }

           [hud hide];
            if (strongSelf.selectImageBlock) {
                
                strongSelf.selectImageBlock(photos, assets, strongSelf.isSelectOriginalPhoto);
                [strongSelf.arrSelectedModels removeAllObjects];
             
            }
            if (hide) {
              
                [strongSelf.arrDataSources removeAllObjects];
                [strongSelf hide];
                [vc dismissViewControllerAnimated:YES completion:nil];
               // [self.navigationController popViewControllerAnimated:YES];
            }
        }];
    }
    
    NSLog(@"====%@",picArry);
    NSArray *picarry = [[NSArray alloc]initWithArray:picArry];
    NSLog(@"=====%@",picarry);



    SJReleaseViewController *VC = [[SJReleaseViewController alloc]init];
    VC.picArry = picarry;
    [self.navigationController pushViewController:VC animated:YES];
  
}
我是直接从这里拿到的图片

**Comment by longitachi** [comment]
这里拿到的是模糊的图片(请求的缩略图) block中这个是判断缩略图的`if ([[info objectForKey:PHImageResultIsDegradedKey] boolValue]) return;`，而且你这么改会有问题，block中是异步请求的图片，你直接在for循环外面写你的逻辑，是拿不到图片的

**Comment by shen456** [comment]
我知道了 找到了 现在拿到了  谢谢
