### ISSUE TITLE
gif获取以后数据格式不正确

### ISSUE THREAD

**Issue by bigFishZhang** [longitachi/ZLPhotoBrowser#306]
**我在相册里面获取gif图时，有时返回的数据格式不正确：**

gifImage	UIImage *	0x6080002a39c0	0x00006080002a39c0
NSObject	NSObject	
isa	Class	UIImage	0x0000000108125b48
_imageRef	__NSCFType *	0x6080001d3740	0x00006080001d3740
_scale	double	1
_flipsForRightToLeftLayoutDirection	bool	false
_traitCollection	UITraitCollection *	0x6080002e5500	0x00006080002e5500
_vectorImageSupport	id	0x0	0x0000000000000000
_imageAsset	id	0x0	0x0000000000000000

**正常的数据格式：**

image	_UIAnimatedImage *	0x1c42ce000	0x00000001c42ce000
UIImage	UIImage	
_images	__NSFrozenArrayM *	0x1c444db60	0x00000001c444db60
_duration	double	9.7900000000000115

**Comment by CocoaML** [comment]
> **我在相册里面获取gif图时，有时返回的数据格式不正确：**
> 
> gifImage	UIImage *	0x6080002a39c0	0x00006080002a39c0
> NSObject	NSObject
> isa	Class	UIImage	0x0000000108125b48
> _imageRef	__NSCFType *	0x6080001d3740	0x00006080001d3740
> _scale	double	1
> _flipsForRightToLeftLayoutDirection	bool	false
> _traitCollection	UITraitCollection *	0x6080002e5500	0x00006080002e5500
> _vectorImageSupport	id	0x0	0x0000000000000000
> _imageAsset	id	0x0	0x0000000000000000
> 
> **正常的数据格式：**
> 
> image	_UIAnimatedImage *	0x1c42ce000	0x00000001c42ce000
> UIImage	UIImage
> _images	__NSFrozenArrayM *	0x1c444db60	0x00000001c444db60
> _duration	double	9.7900000000000115

您好，请问您找到解决办法了吗？
