### ISSUE TITLE
选择iCloud图片时能否像微信一样，先选择小图，发送时再下载大图，不然用户就等在下载大图的页面什么也干不了。我这边的实际情况是根本就发不了iCloud图片，只有先到相册里面下载大图才行。

### ISSUE THREAD

**Issue by rainzhou** [longitachi/ZLPhotoBrowser#309]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by niunaruto** [comment]
+1

**Comment by longitachi** [comment]
3.0.2已支持选择iCloud照片，可以选择获取asset之后，自行解析`shouldAnialysisAsset`置为`NO`即可，也可等框架下载好返回给你
