### ISSUE TITLE
很好用,集成也特别简单, 就是有bug,不稳定

### ISSUE THREAD

**Issue by KouRouRunQuickly** [longitachi/ZLPhotoBrowser#31]
进入相册选择完相片后, 再进入相册选择相片, 确定按钮有一定几率不能用, 需要取消后,重新进入相册才能用.

**Comment by longitachi** [comment]
收到，谢谢提的bug，由于直接进入相册的功能是最近才加的，可能没仔细测，今天有空就给改了

**Comment by heyode** [comment]
我也遇到了，第一次进入相册没问题，第二次进入选完照片后，点确定无反应，打了断点了了发现，strongself是nil。
- (IBAction)btnPhotoLibrary_Click:(id)sender
{
    if (![self judgeIsHavePhotoAblumAuthority]) {
        [self showNoAuthorityVC];
    } else {
        self.animate = NO;
        
        ZLPhotoBrowser *photoBrowser = [[ZLPhotoBrowser alloc] initWithStyle:UITableViewStylePlain];
        photoBrowser.maxSelectCount = self.maxSelectCount;
        photoBrowser.arraySelectPhotos = self.arraySelectPhotos.mutableCopy;
        
        weakify(self);
        __weak typeof(photoBrowser) weakPB = photoBrowser;
        [photoBrowser setDoneBlock:^(NSArray<ZLSelectPhotoModel *> *selPhotoModels, BOOL isSelectOriginalPhoto) {
            strongify(weakSelf);
            __strong typeof(weakPB) strongPB = weakPB;
            strongSelf.isSelectOriginalPhoto = isSelectOriginalPhoto;
            [strongSelf.arraySelectPhotos removeAllObjects];
            [strongSelf.arraySelectPhotos addObjectsFromArray:selPhotoModels];
            [strongSelf requestSelPhotos:strongPB];
        }];
        
        [photoBrowser setCancelBlock:^{
            strongify(weakSelf);
            [strongSelf hide];
        }];
        
        [self presentVC:photoBrowser];
    }
}

**Comment by longitachi** [comment]
你好，这个已经修改过了，请更新最新版本
