### ISSUE TITLE
预览大图片崩溃

### ISSUE THREAD

**Issue by dong136279559** [longitachi/ZLPhotoBrowser#310]
加载网络图片时,失去连接,导致崩溃.

图片尺寸:1600 x 6500 
大小:1.4M

![a7004b7c-4cad-4764-b82d-a798ee99c6e4](https://user-images.githubusercontent.com/20337504/45021660-b550f500-b064-11e8-9588-0d413520dd84.png)

命令行打印:
PBItemCollectionServicer connection disconnected.

**Comment by longitachi** [comment]
这个是你的USB连接线断了吧，电脑和手机的链接断了

**Comment by dong136279559** [comment]
不是,应该加载大图片导致的内存问题,加载小的图片就没有问题,大图片不可以.

**Comment by longitachi** [comment]
你运行后，把线拔掉在运行试试看。我在demo里面的网络图片都是十几兆的，我这边没出现崩溃。你先试一下

**Comment by dong136279559** [comment]
我不知道为什么,我在你的demo中测试是没有问题的,当我项目中配置跟demo一样,就是有这个崩溃的问题,很奇怪,搞了一上午,不知道哪出问题了.
