### ISSUE TITLE
选择比较多的图片的时候闪退

### ISSUE THREAD

**Issue by a407184508** [longitachi/ZLPhotoBrowser#312]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

![image](https://user-images.githubusercontent.com/9278515/45662391-55fae680-bb34-11e8-9d67-28ee3b56d1e4.png)

strongSelf = nil

**Comment by a407184508** [comment]
而且选择很多的时候内存暴增

**Comment by longitachi** [comment]
选择很多时候，框架已经提供了解决办法，就是不要直接在点确定时候全部解析。看下这个`shouldAnialysisAsset`

**Comment by a407184508** [comment]
haode
