### ISSUE TITLE
视频加水印有些视频会报错Error Domain=AVFoundationErrorDomain Code=-11841 "Operation Stopped" UserInfo=0x1625b960 {NSLocalizedDescription=Operation Stopped, NSLocalizedFailureReason=The video could not be composed.}

### ISSUE THREAD

**Issue by Ming79432303** [longitachi/ZLPhotoBrowser#314]
#warning 修改 原为 assetVideoTrack 后改为videoTrack 发现可以解决 error code=-11841
    AVMutableVideoCompositionLayerInstruction *layerInstruction = [AVMutableVideoCompositionLayerInstruction videoCompositionLayerInstructionWithAssetTrack:videoTrack];

**Comment by longitachi** [comment]
改过之后没出现过错误了吗

**Comment by Ming79432303** [comment]
> 改过之后没出现过错误了吗

是的目前没发现有啥问题

**Comment by xxxIxxxx** [comment]
因为我的视频不是来自相册，所以我将此方法暴露出来。
调用发现水印添加不成功。没有报错，输出的有地址。

```
+ (void)export:(AVAsset *)asset range:(CMTimeRange)range type:(ZLExportVideoType)type presetName:(NSString *)presetName renderSize:(CGSize)renderSize watermarkImage:(UIImage *)watermarkImage watermarkLocation:(ZLWatermarkLocation)location imageSize:(CGSize)imageSize effectImage:(UIImage *)effectImage birthRate:(NSInteger)birthRate velocity:(CGFloat)velocity complete:(void (^)(NSString *exportFilePath, NSError *error))complete;

``` 
@longitachi

**Comment by Ming79432303** [comment]
> 因为我的视频不是来自相册，所以我将此方法暴露出来。
> 调用发现水印添加不成功。没有报错，输出的有地址。
> 
> ```
> + (void)export:(AVAsset *)asset range:(CMTimeRange)range type:(ZLExportVideoType)type presetName:(NSString *)presetName renderSize:(CGSize)renderSize watermarkImage:(UIImage *)watermarkImage watermarkLocation:(ZLWatermarkLocation)location imageSize:(CGSize)imageSize effectImage:(UIImage *)effectImage birthRate:(NSInteger)birthRate velocity:(CGFloat)velocity complete:(void (^)(NSString *exportFilePath, NSError *error))complete;
> ```
> 
> 调用方法参数如下
> 
> ```
> 
> [ZLPhotoManager export:fileAsset range:CMTimeRangeMake(kCMTimeZero, kCMTimePositiveInfinity) type:ZLExportVideoTypeMp4 presetName:AVAssetExportPresetPassthrough renderSize:CGSizeMake(CGFLOAT_MAX, CGFLOAT_MAX) watermarkImage:[UIImage imageNamed:@"plc_12"] watermarkLocation:ZLWatermarkLocationTopLeft imageSize:CGSizeMake(100, 100) effectImage:nil birthRate:0 velocity:0 complete:^(NSString *exportFilePath, NSError *error) {
> NSSLog(@"exportFilePath == %@",exportFilePath);
>     }];
> ```
> 
> @longitachi
水印图片要用.jpg格式的

**Comment by longitachi** [comment]
> > 因为我的视频不是来自相册，所以我将此方法暴露出来。
> > 调用发现水印添加不成功。没有报错，输出的有地址。
> > ```
> > + (void)export:(AVAsset *)asset range:(CMTimeRange)range type:(ZLExportVideoType)type presetName:(NSString *)presetName renderSize:(CGSize)renderSize watermarkImage:(UIImage *)watermarkImage watermarkLocation:(ZLWatermarkLocation)location imageSize:(CGSize)imageSize effectImage:(UIImage *)effectImage birthRate:(NSInteger)birthRate velocity:(CGFloat)velocity complete:(void (^)(NSString *exportFilePath, NSError *error))complete;
> > ```
> > 调用方法参数如下
> > ```
> > 
> > [ZLPhotoManager export:fileAsset range:CMTimeRangeMake(kCMTimeZero, kCMTimePositiveInfinity) type:ZLExportVideoTypeMp4 presetName:AVAssetExportPresetPassthrough renderSize:CGSizeMake(CGFLOAT_MAX, CGFLOAT_MAX) watermarkImage:[UIImage imageNamed:@"plc_12"] watermarkLocation:ZLWatermarkLocationTopLeft imageSize:CGSizeMake(100, 100) effectImage:nil birthRate:0 velocity:0 complete:^(NSString *exportFilePath, NSError *error) {
> > NSSLog(@"exportFilePath == %@",exportFilePath);
> >     }];
> > ```
> > @longitachi
> > 水印图片要用.jpg格式的
> 
> 不行。。

@xxxIxxxx 你把视频导入相册，然后用demo试一下看是否能成功添加水印，图片格式jpg和png应该都行
