### ISSUE TITLE
选取单个视频的编辑问题

### ISSUE THREAD

**Issue by ynnynn** [longitachi/ZLPhotoBrowser#317]
设置了
maxSelectCount = 1
allowEditVideo = YES
maxVideoDuration = 300
maxEditVideoTime = 60
editAfterSelectThumbnailImage = YES
这些参数

发现如果选取的视频小于60秒，没有任何后续反馈（既不回调setSelectImageBlock里面的也不push视频编辑页）

**Comment by longitachi** [comment]
emmm，有个逻辑就是如果视频小于最大编辑时长的话（即你设置的60s），是不允许编辑的
