### ISSUE TITLE
预览大图，使用canInteractivePop=yes时崩溃 —— 2.7.6 fixed

### ISSUE THREAD

**Issue by KONGFANJI** [longitachi/ZLPhotoBrowser#319]
![image](https://user-images.githubusercontent.com/15827720/48388076-149d4680-e733-11e8-80dc-cf74065d5e77.png)

预览大图，使用canInteractivePop=yes时崩溃

**Comment by longitachi** [comment]
如果选择完成后，调用`previewSelectedPhotos:assets:index:isOriginal:`或者`previewPhotos:index:hideToolBar:complete:`预览时候，设置`canInteractivePop=yes`就是会崩溃，因为动画写在 通过导航`push`到`ZLShowBigImgViewController` 的基础上的

**Comment by KONGFANJI** [comment]
> 如果选择完成后，调用`previewSelectedPhotos:assets:index:isOriginal:`或者`previewPhotos:index:hideToolBar:complete:`预览时候，设置`canInteractivePop=yes`就是会崩溃，因为动画写在 通过导航`push`到`ZLShowBigImgViewController` 的基础上的

谢谢回复，怎么能避免的？

**Comment by longitachi** [comment]
最近会更新下动画，支持下present
