### ISSUE TITLE
模拟器8.4，第二次查看大图必蹦

### ISSUE THREAD

**Issue by YanLYM** [longitachi/ZLPhotoBrowser#324]
模拟器 8.4系统 ，在相册中选择图片，点击查看大图，第一次进入大图正常，第二次就必蹦
 *** -[ZLShowBigImgViewController navigationController:animationControllerForOperation:fromViewController:toViewController:]: message sent to deallocated instance 0x7fd70888f4f0
Message from debugger: Terminated due to signal 9
![image](https://user-images.githubusercontent.com/28438058/49201997-0cedcb00-f3de-11e8-9ed4-a2074219a870.png)
没有iOS 8的真机，想测试看下的，然后就crash了，麻烦大佬看下什么情况

**Comment by longitachi** [comment]
之前不会，现在确实会啊。我看下。

**Comment by YanLYM** [comment]
好的，我看demo里面也是会蹦的
