### ISSUE TITLE
相册预览的界面选择了一张照片,之后点击照片进入大图查看,点击右上角取消选中这张照片,点击左上角返回,此时最初选择的照片右上角还是有选中的情况.希望我的表达能让作者重现一下 应该算个是小bug吧

### ISSUE THREAD

**Issue by cengjiahao** [longitachi/ZLPhotoBrowser#325]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
感谢提出
