### ISSUE TITLE
iOS8.1.2运行Demo崩溃

### ISSUE THREAD

**Issue by lintongSD** [longitachi/ZLPhotoBrowser#331]
手机型号:iPhone6
系统:8.1.2
问题:下载demo-->选择相册-->选中单张图片-->进入详情-->返回-->查看另一张图片详情崩溃
![崩溃位置](https://github.com/lintongSD/imageSource/blob/master/ZLPhoto/position.png?raw=true)

**Comment by KKKGit** [comment]
iPhone 5 
8.4.1
同样的测试方法崩溃位置相同。
