### ISSUE TITLE
图片选择以后返回数组的问题

### ISSUE THREAD

**Issue by lilovexin** [longitachi/ZLPhotoBrowser#34]
你现在的是选择照片以后返回的数据，是根据照片在相册里面的先后次序返回的。我现在需要的是我选择的照片的先后顺序来返回数据，这个该怎么改才能实现呢？？最近在做项目很急。

**Comment by longitachi** [comment]
现在就是选择的先后顺序吧

**Comment by lilovexin** [comment]
strongSelf.arrDataSources = selectPhotos;  这一句返回的图片也是按照选择的先后顺序返回的？？

**Comment by lilovexin** [comment]
strongSelf.arrDataSources = selectPhotos;
strongSelf.lastSelectMoldels = selectPhotoModels;

我验证了一下，selectPhotos是按照相册库展示的先后顺序显示的，selectPhotoModels是按照选择的先后顺序显示的

**Comment by longitachi** [comment]
你去试一下吧，试一下demo，跑手机上，我试过了。按选择顺序

**Comment by longitachi** [comment]
不行的话你就截几张图发来

**Comment by lilovexin** [comment]
第一张我是从右向左选择的但是读取的时候从左到右读去的。

        ZLPhotoActionSheet *actionSheet = [[ZLPhotoActionSheet alloc] init];
        //设置照片最大选择数
        actionSheet.maxSelectCount = 20;
        weakify(self);
        [actionSheet showPhotoLibraryWithSender:self lastSelectPhotoModels:self.lastSelectMoldels completion:^(NSArray<UIImage *> * _Nonnull selectPhotos, NSArray<ZLSelectPhotoModel *> * _Nonnull selectPhotoModels) {
            strongify(weakSelf);
            strongSelf.arrDataSources = selectPhotos;
            strongSelf.lastSelectMoldels = selectPhotoModels;
            [selectImageArray  addObjectsFromArray:selectPhotos];
            
            for (UIImage *image in selectPhotos) {
                [_postView addNewImage:image];
            }
           这是我的加载代码，for循环是加载显示的方法
        }];

**Comment by lilovexin** [comment]
谢谢你，我知道原因了

**Comment by longitachi** [comment]
嗯，解决就好，虽然我还没明白你说的- -

**Comment by lilovexin** [comment]
如何根据要删除的image 来移除lastSelectMoldels所对应的ZLSelectPhotoModel 呢 ？？

**Comment by longitachi** [comment]
暂时没有这个功能

**Comment by lilovexin** [comment]
好吧，谢谢咯。

**Comment by lilovexin** [comment]
ZLPhotoActionSheet *actionSheet = [[ZLPhotoActionSheet alloc] init];
        
        weakify(self);
        [actionSheet showPreviewPhotoWithSender:self animate:YES lastSelectPhotoModels:nil completion:^(NSArray<UIImage *> * _Nonnull selectPhotos, NSArray<ZLSelectPhotoModel *> * _Nonnull selectPhotoModels) {
            strongify(weakSelf);     }];


6plus 10.2不走上面的方法
