### ISSUE TITLE
ZLThumbnailViewController.m崩溃bug

### ISSUE THREAD

**Issue by PengChJ** [longitachi/ZLPhotoBrowser#342]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [x] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by PengChJ** [comment]
ZLThumbnailViewController.m中arrDataSources的懒加载方法会造成936行[self.arrDataSources insertObject:model atIndex:0]崩溃
懒加载方法中，当_albumListModel为空时，采用了异步方法初始化arrDataSources。如果是由于执行[self.arrDataSources insertObject:model atIndex:0]这行代码触发arrDataSources懒加载，并且_albumListModel也为空时，-[NSArray insertObject:atIndex:]方法会因为调用对象为空而导致crash。
这个崩溃问题调试了好久才发现，debug时程序直接崩溃，控制台没有崩溃日志，最后用崩溃收集插件才收集到了崩溃信息。

**Comment by longitachi** [comment]
是一定复现吗？或者怎么能复现出来

**Comment by PengChJ** [comment]
具体出现情况我也不是很清楚，我只在debug时出现了一次，因为控制台没有错误打印信息，所以查看了bugly收集的崩溃信息。
![image](https://user-images.githubusercontent.com/21098335/52925522-c53b6780-336c-11e9-9f31-4d73c200c38f.png)
我搜索-[__NSArrayM insertObject:atIndex:]方法才找到这里有可能造成调用对象为空的情况
