### ISSUE TITLE
ZLPhotoActionSheet初始化崩溃

### ISSUE THREAD

**Issue by FunnyFzl** [longitachi/ZLPhotoBrowser#343]
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIView 0x14b904d80> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key baseView.'
*** First throw call stack:
(0x1932691b8 0x191ca055c 0x193268e80 0x193c9d8f0 0x19942011c 0x199621af8 0x193188034 0x1996204cc 0x199622768 0x102e68a5c 0x1001bd450 0x1001bc544 0x1001bafa0 0x1001b9678 0x10014b01c 0x1995b912c 0x1995b99c8 0x19946a130 0x19946d8b0 0x199245be8 0x1991575b8 0x1991570dc 0x199156ef8 0x1965c57e8 0x103b91218 0x103b96280 0x193216810 0x1932143fc 0x1931422b8 0x194bf6198 0x1991897fc 0x199184534 0x10029ca3c 0x1921255b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by longitachi** [comment]
我这边通过代码,pod,carthage 集成均不会有以上错误啊？
