### ISSUE TITLE
关于相册GIF图的支持  

### ISSUE THREAD

**Issue by DemonLover** [longitachi/ZLPhotoBrowser#35]
上传相册图片  但是选中的有GIF,你这个不支持

**Comment by longitachi** [comment]
iPhone系统相册都不支持gif吧，你用QQ的试下，也不支持吧。 gif保存到系统相册之后就成静态的了

**Comment by DemonLover** [comment]
我试过了qq 微信的都可以  虽然在相册是静止的图片 （ 因为系统的原因 ）但是发出去之后就是动图 如果发出去之后不是动图那么可能保存的时候对图片做了修改  只获取了第一帧  我在网上查找过 说是要用Data数据获取图片资源

**Comment by longitachi** [comment]
已经支持视频和gif图的选择
