### ISSUE TITLE
3.0.0版本运行提示20个错误：ZLPhotoConfiguration.h里提示Duplicate interface definition for class 'ZLPhotoConfiguration'和变量Property has a previous declaration

### ISSUE THREAD

**Issue by ysysbaobei** [longitachi/ZLPhotoBrowser#351]
3.0.0版本运行提示20个错误：ZLPhotoConfiguration.h里提示Duplicate interface definition for class 'ZLPhotoConfiguration'和变量Property has a previous declaration

步骤：
1、下载3.0.0版本，终端里执行：carthage update --platform iOS
2、打开ZLPhotoBrowser.xcworkspace，运行提示20个错误：
1）ZLPhotoConfiguration.h里提示Duplicate interface definition for class 'ZLPhotoConfiguration'
2）很多成员变量，比如：
@property (nonatomic, assign) UIStatusBarStyle statusBarStyle;
@property (nonatomic, assign) NSInteger maxSelectCount;
@property (nonatomic, assign) NSInteger maxPreviewCount;
提示：Property has a previous declaration
3）log里这样提示的
In file included from /Users/xxx/Downloads/ZLPhotoBrowser-master/ZLPhotoBrowser/PhotoBrowser/ZLShowBigImgViewController.m:14:
In file included from /Users/xxx/Downloads/ZLPhotoBrowser-master/ZLPhotoBrowser/PhotoBrowser/ZLAlbumListController.h:11:
/Users/xxx/Downloads/ZLPhotoBrowser-master/ZLPhotoBrowser/PhotoBrowser/ZLPhotoConfiguration.h:122:36: error: property has a previous declaration
@property (nonatomic, assign) BOOL allowSlideSelect;
                                   ^
In module 'ZLPhotoBrowser' imported from /Users/xxx/Downloads/ZLPhotoBrowser-master/ZLPhotoBrowser/PhotoBrowser/ZLPhotoConfiguration.h:11:
/Users/xxx/Downloads/ZLPhotoBrowser-master/ZLPhotoBrowser/PhotoBrowser/ZLPhotoConfiguration.h:122:36: note: property declared here
@property (nonatomic, assign) BOOL allowSlideSelect;
                                   ^                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.

**Comment by Sunxb** [comment]
同问

**Comment by Henry519** [comment]
最简单的方法：打开工程，删除PhotoBrowser文件夹-->Remove References 然后再添加到工程里面就OK了

**Comment by longitachi** [comment]
先按照楼上方法
