### ISSUE TITLE
接上使用后确实发现有内存问题

### ISSUE THREAD

**Issue by ynnynn** [longitachi/ZLPhotoBrowser#352]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

作者你好，使用过程中确实发现有内存漲高问题，翻了遍issue，看到相关问题都是没有下文的，所以我这边提一下，环境是xCode10，真机iPhoneX iOS12
情况就是，调用showPhotoLibrary后，内存先漲10m，然后点击取消，内存长时间都没下降（这里我可以排除因为自身调用而引起，因为都是定义个局部变量调用showPhotoLibrary）
另外，如果在showPhotoLibrary后（内存漲10m)，不点击取消，随便点一张图进行预览（进入ZLShowBigImgViewController)，内存再网上漲20m
从进入ZLPhotoBrowser到退出，返回自身app，内存消耗最高超过30m，这时候如果重复刚刚描述的操作，内存却又不会持续上涨的，虽然如此，但是心里面总觉得旮沓，希望作者检查下

**Comment by ChandHsu** [comment]
我实测了一下,没有发现题主的问题

**Comment by longitachi** [comment]
我这边也没有遇到所提到的问题。。后面在跟进吧
