### ISSUE TITLE
封装方法

### ISSUE THREAD

**Issue by ZClee128** [longitachi/ZLPhotoBrowser#357]
- (void)showPreview:(BOOL)preview animate:(BOOL)animate可以把这个公开吗，不是每个项目都需要显示那个collectionview的，你都写死了，怎么弄

**Comment by longitachi** [comment]
没明白什么意思。。。

**Comment by ZClee128** [comment]
就是不想要弹出那个顶部的collectionview，只想要拍照相册取消这三个按钮，不过我已经在xib上把collectionview隐藏了

**Comment by longitachi** [comment]
/*
/**
 预览图最大显示数 默认20张，该值为0时将不显示上方预览图，仅显示 '拍照、相册、取消' 按钮
 */
@property (nonatomic, assign) NSInteger maxPreviewCount;
*/
你看下这个参数
