### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hatjs880328s** [longitachi/ZLPhotoBrowser#358]
建议bundle里面的图片能压缩一下。
每次CI时，都等这个库，
作者代码很棒，但pod速度不敢恭维。

**Comment by hatjs880328s** [comment]
sd升级了最新版，你的podspec没有指定版本，导致编译失败。

**Comment by AmadeusSys** [comment]
坐等作者修复

**Comment by longitachi** [comment]
图片压缩过了，sd暂时先制定了 4.4.6版本
