### ISSUE TITLE
[NSBundle mainBundle].localizedInfoDictionary取不到值，导致无法取到kAPPName。

### ISSUE THREAD

**Issue by handsomeliangliang** [longitachi/ZLPhotoBrowser#359]
现象：在相册中点击拍照处理的时候，提示保存失败。
出错代码：在ZLPhotoManager的getDestinationCollection方法中获取KAPPName为nil。
![image](https://user-images.githubusercontent.com/17999561/55702533-72476d80-5a09-11e9-841e-8c7934e972c9.png)
原因：[NSBundle mainBundle].localizedInfoDictionary取不到值，导致无法取到APPName。
尝试处理：修改ZLDefine.h文件
#define kInfoDict [NSBundle mainBundle].infoDictionary
这样就能解决问题，请问作者这是我工程问题，还是这里现在需要修改？

**Comment by longitachi** [comment]
[NSBundle mainBundle].localizedInfoDictionary 是为了获取app名字适配了多语言的情况，如果app没配置多语言，这个取到的应该是空，现在是这么定义的
```
#define kInfoDict [NSBundle mainBundle].localizedInfoDictionary ?: [NSBundle mainBundle].infoDictionary
#define kAPPName [kInfoDict valueForKey:@"CFBundleDisplayName"] ?: [kInfoDict valueForKey:@"CFBundleName"]
```
应该不会遇到nil的情况吧

**Comment by handsomeliangliang** [comment]
> [NSBundle mainBundle].localizedInfoDictionary 是为了获取app名字适配了多语言的情况，如果app没配置多语言，这个取到的应该是空，现在是这么定义的
> 
> ```
> #define kInfoDict [NSBundle mainBundle].localizedInfoDictionary ?: [NSBundle mainBundle].infoDictionary
> #define kAPPName [kInfoDict valueForKey:@"CFBundleDisplayName"] ?: [kInfoDict valueForKey:@"CFBundleName"]
> ```
> 应该不会遇到nil的情况吧

我这边取到的[NSBundle mainBundle].localizedInfoDictionary的值为:{}，不是nil

**Comment by handsomeliangliang** [comment]
> [NSBundle mainBundle].localizedInfoDictionary 是为了获取app名字适配了多语言的情况，如果app没配置多语言，这个取到的应该是空，现在是这么定义的
> 
> ```
> #define kInfoDict [NSBundle mainBundle].localizedInfoDictionary ?: [NSBundle mainBundle].infoDictionary
> #define kAPPName [kInfoDict valueForKey:@"CFBundleDisplayName"] ?: [kInfoDict valueForKey:@"CFBundleName"]
> ```
> 应该不会遇到nil的情况吧

如果取到的值是空字典，后面就取不到值了呀。是不是应该判断[NSBundle mainBundle].localizedInfoDictionary.count 呢？
