### ISSUE TITLE
在横屏界面的时候，拍照功能使用不了，求解决

### ISSUE THREAD

**Issue by swesome** [longitachi/ZLPhotoBrowser#361]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by swesome** [comment]
权限已经全部添加了，只有当界面变为竖屏的时候，就可以正常拍照

**Comment by longitachi** [comment]
我测试了下横屏时候点击拍照是可以的啊，只不过拍照界面仅支持竖屏操作，不过跟这个没关系
