### ISSUE TITLE
粒子效果我试了下，怎么视频里面没有呢

### ISSUE THREAD

**Issue by CoderLinLee** [longitachi/ZLPhotoBrowser#362]
![粒子效果](https://user-images.githubusercontent.com/11660590/56024542-d0928a00-5d42-11e9-93b8-792957fdd48e.png)

**Comment by longitachi** [comment]
我试了下，`presetName`为`AVAssetExportPresetPassthrough`的时候确实没有效果，你可以换成其他的参数，我试了下是正常的
