### ISSUE TITLE
关于作者遗留的焦距调整问题建议

### ISSUE THREAD

**Issue by ChandHsu** [longitachi/ZLPhotoBrowser#363]
![image](https://user-images.githubusercontent.com/10771362/56077053-3269f700-5e0a-11e9-9ea7-8cd81e22c2cf.png)
然后再去解决手势冲突的问题,把拍照按钮改成按钮或者修改UI层级达到效果,我已经在本地修复,这里就不做演示了,供作者参考

**Comment by longitachi** [comment]
谢谢给出建议，这个问题当时丢那就没看了，刚才看了下给解决了，具体如下。
1.给pan手势添加 如下参数设置 `pan.maximumNumberOfTouches = 1;`
2.添加tap手势，并设置delegate为self
3.实现`UIGestureRecognizerDelegate`协议中如下方法
```
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
{
    return YES;
}
```
