### ISSUE TITLE
sdwebimage 5的支持 —— 3.0.3 已支持

### ISSUE THREAD

**Issue by eric1202** [longitachi/ZLPhotoBrowser#364]
ZLPhotoBrowser (= 3.0.1) was resolved to 3.0.1, which depends on
      SDWebImage (~> 4.4.6)

**Comment by FunnyFzl** [comment]
SDWebImage 已经升级到5.0.1 了

**Comment by FunnyFzl** [comment]
> ZLPhotoBrowser (= 3.0.1) was resolved to 3.0.1, which depends on
> SDWebImage (~> 4.4.6)

SDWebImage 已经升级到5.0.1 了

**Comment by sinneryun** [comment]
ZLPhotoBrowser (~> 3.0.1) was resolved to 3.0.1, which depends on
SDWebImage (~> 4.4.6) 
升级到3.0.1.  依旧冲突 看前面issues有修复.还是不ok

**Comment by CoffeeKe** [comment]
你指的的不是最新版

**Comment by niunaruto** [comment]
尽快解决

**Comment by longitachi** [comment]
3.0.2已支持
