### ISSUE TITLE
关于使用 ZLCustomCamera 的 bug

### ISSUE THREAD

**Issue by friendsheeps** [longitachi/ZLPhotoBrowser#371]
1、选择ZLCustomCamera拍照功能后弹出拍照页面，不做任何操作，直接点取消，拍照页面消失之后1秒左右StatusBar才会显现出来，而且ActionSheet也没有弹下去，整个页面看上去就像向下跳动了一下，感觉不是很友好；

2、选择ZLCustomCamera拍照功能后弹出拍照页面，点击拍摄，再点击确定，拍照页面弹下，在editAfterSelectThumbnailImage = YES 的模式下会再次弹出编辑页面，此时不做处理，直接点击左上角取消，编辑页面弹下，页面会卡在一个没有StatusBar且ActionSheet没有弹下去的状态(附图)；
![WechatIMG143](https://user-images.githubusercontent.com/13128046/57835348-dfaca200-77f0-11e9-98f0-cbb52a87f948.jpeg)

建议：使用ZLCustomCamera的时候能否在dismiss之前先将StatusBar显示出来并且在dismiss的同时将ActionSheet弹下

**Comment by longitachi** [comment]
感谢提出bug。

1.首先你说的这种情况 actionSheet没有弹下去，是本身的逻辑，拍照后还有选择其他照片的需求，不能拍照后直接不让选择其他照片了。

2.拍照界面弹下去后状态栏1s后才显示，是因为状态栏状态更改在`viewDidDisappear`中，这个我改下，放到`viewWillDisappear`中就好了。

3.拍照后直接编辑状态栏没消失这个是个bug，我改下
