### ISSUE TITLE
编辑图片页面等按钮可不可以稍微增大一点宽高，不太好点击

### ISSUE THREAD

**Issue by lvcode** [longitachi/ZLPhotoBrowser#376]
编辑图片等按钮可不可以增加一些宽高，测试同事说不是很好点击。
我已经改了自己的代码，还是希望您觉得合适的话，修改一下。谢谢啦
![屏幕快照 2019-05-30 下午5 51 49](https://user-images.githubusercontent.com/16863736/58626401-52487200-8307-11e9-8098-f3bfab054a60.png)

**Comment by longitachi** [comment]
好的，下个版本会改一下

**Comment by lvcode** [comment]
谢谢🙏
