### ISSUE TITLE
多选图片之后右上角的序号问题 —— 3.0.6 已支持

### ISSUE THREAD

**Issue by muyang00** [longitachi/ZLPhotoBrowser#380]
![IMG_0251](https://user-images.githubusercontent.com/16149500/59749848-5d604380-92b0-11e9-83e8-349c30e2c986.jpg)
作者你好，右上角选择后显示数字，这样用户在选择时就有了顺序，是个不错的用户体验

**Comment by longitachi** [comment]
3.0.6 已支持
