### ISSUE TITLE
demo无法运行

### ISSUE THREAD

**Issue by WIndFate** [longitachi/ZLPhotoBrowser#382]
直接下载的demo无法运行？丢失sdwebimage库

<img width="275" alt="スクリーンショット 2019-06-21 13 39 23" src="https://user-images.githubusercontent.com/14509638/59898100-59583100-942a-11e9-9213-3779d9ce9826.png">

**Comment by longitachi** [comment]
请查看下readme第一行，有详细介绍

**Comment by TzyTman** [comment]
> 请查看下readme第一行，有详细介绍

看到了执行没用啊？
