### ISSUE TITLE
想请教一下视频跟照片选择的问题~~~

### ISSUE THREAD

**Issue by SchNei** [longitachi/ZLPhotoBrowser#383]
我现在设置了如下配置：
        actionSheet.configuration.maxSelectCount = 9
        actionSheet.configuration.allowMixSelect = false
        actionSheet.configuration.maxVideoSelectCountInMix = 1

现在的情况是，单单选择图片的情况下，max9张没问题。单单选视频的情况下，需求是只能选1个，请问如何设置可以实现？？

**Comment by muyang00** [comment]
目前这个库在  
非 混合选择的情况下，设置的maxSelectCount  即是 图片数，也是选择的视频数；；；
在混合选择情况下， maxVideoSelectCountInMix 和 minVideoSelectCountInMix 才有效；；；

像你想要的这个需求 ， 可能需要作者 在  非 混合选择的情况，maxSelectCount 可能还要细化成   MaxImagesSelectCount  和  MaxVideoSelectCount；；；

在混合选择情况下已经细化区分了，就不要再担心。

**Comment by longitachi** [comment]
@SchNei 你描述的这种情况，现在框架是不支持的。
