### ISSUE TITLE
单选某个视频，回调返回的数组count为0

### ISSUE THREAD

**Issue by wang0458** [longitachi/ZLPhotoBrowser#388]
选取视频的时候，绝大多数视频都回调正常。当我选取一个2017年的视频的时候（非icloud视频），回调里的两个数组都为空。我追踪了一下
`  

 [ZLPhotoManager requestSelectedImageForAsset:model isOriginal:self.isSelectOriginalPhoto allowSelectGif:self.configuration.allowSelectGif completion:^(UIImage *image, NSDictionary *info) {
            @zl_strongify(self);
            if (!self) return;
            
            if (isTimeOut || [[info objectForKey:PHImageResultIsDegradedKey] boolValue]) return;
            
            doneCount++;
            
            if (image) {
                [photos replaceObjectAtIndex:i withObject:[ZLPhotoManager scaleImage:image original:self->_isSelectOriginalPhoto]];
                [assets replaceObjectAtIndex:i withObject:model.asset];
            } else {
                [errorAssets addObject:model.asset];
                [errorIndexs addObject:@(i)];
            }`是这个方法里返回的image为空，大神这是什么原因

**Comment by longitachi** [comment]
那是解析图片失败了吧。 有什么报错吗？

**Comment by wang0458** [comment]
没有报错，而且是只有那个视频回调的image参数为nil

**Comment by longitachi** [comment]
有可能是iCloud照片下载失败了吧？没有日志也盲猜不到原因。

**Comment by yuanjunxiao** [comment]
> 没有报错，而且是只有那个视频回调的image参数为nil

我也遇到这个问题了，现在选择视频返回的都是空数据，你是怎么处理的？

**Comment by longitachi** [comment]
> > 没有报错，而且是只有那个视频回调的image参数为nil
> 
> 我也遇到这个问题了，现在选择视频返回的都是空数据，你是怎么处理的？

选择视频返回的都是空数据？所有视频都是吗

**Comment by yuanjunxiao** [comment]
> > > 没有报错，而且是只有那个视频回调的image参数为nil
> > 
> > 
> > 我也遇到这个问题了，现在选择视频返回的都是空数据，你是怎么处理的？
> 
> 选择视频返回的都是空数据？所有视频都是吗

不是所有的视频，手机里获取视频时是很早以前拍摄的视频，获取不到，新拍摄的视频就是好的。
