### ISSUE TITLE
swift怎么设置arrSelectedAssets,我要么类型转换失败要么赋值不了。还有拍1s内视频没回调

### ISSUE THREAD

**Issue by 6jk** [longitachi/ZLPhotoBrowser#391]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
swift 直接复制一个 [PHAsset]类型的数组就可以了吧

1s内视频没回调，是因为有一个逻辑
```
if (CMTimeGetSeconds(output.recordedDuration) < 1) {
        if (self.allowTakePhoto) {
            //视频长度小于1s 允许拍照则拍照，不允许拍照，则保存小于1s的视频
            ZLLoggerDebug(@"视频长度小于1s，按拍照处理");
            [self onTakePicture];
            return;
        }
    }
```

**Comment by jupeng123** [comment]
@longitachi 能先解决1s内视频没有照片回调？

**Comment by longitachi** [comment]
@jupeng123 我看下

**Comment by longitachi** [comment]
3.1.0 已把1s限制修改为0.3s
