### ISSUE TITLE
iOS13.0测试版打开速度比较慢

### ISSUE THREAD

**Issue by lintongSD** [longitachi/ZLPhotoBrowser#392]
SDK版本2.6.7和3.0.0(其它的没有试) iPhone7   系统：iOS13.0测试版
第一次打开相册比较慢，第二次就好了

<img width="1087" alt="控制台日志" src="https://user-images.githubusercontent.com/19474665/61613779-cadb0780-ac94-11e9-89b6-279e84aefe66.png">

这里提出issue，只是希望大佬有时间的时候可以测试一下，尽早兼容新系统

**Comment by lintongSD** [comment]
刚测了一下拍照，图片旋转了
ZLCaptureSessionPreset1920x1080
也是测试版有问题，正式版可以

**Comment by longitachi** [comment]
打开慢可能是开了相册内拍照实时预览那个属性。可以吧下面这个属性置为`NO`
```
/**
 是否在相册内部拍照按钮上面实时显示相机俘获的影像 默认 YES
 */
@property (nonatomic, assign) BOOL showCaptureImageOnTakePhotoBtn;
```

**Comment by longitachi** [comment]
图片旋转了是什么意思？有图吗？发一个看下

**Comment by lintongSD** [comment]
打开相册慢时实时预览功能已经关闭了（而且只有iOS13会有这个问题）


        actionSheet.sender = self;
        //        actionSheet.configuration.editType = .clip
        actionSheet.configuration.allowSelectGif = false
        actionSheet.configuration.allowRecordVideo = false
        actionSheet.configuration.allowSelectVideo = false
        actionSheet.configuration.allowTakePhotoInLibrary = false
        actionSheet.configuration.showCaptureImageOnTakePhotoBtn = false 

拍照旋转也是只有beta版才会出现
![IMG_1035](https://user-images.githubusercontent.com/19474665/61844322-956f2d80-aed1-11e9-9d33-d31685a05b80.PNG)
![IMG_1037](https://user-images.githubusercontent.com/19474665/61844323-9607c400-aed1-11e9-9515-175ade9db358.PNG)

**Comment by longitachi** [comment]
我用iOS13模拟器试了下，倒没出现打开慢的问题，到时present用了系统默认的`pageSheet`，这个需要改下。拍照这个等到iOS13正式版出了在试一下
