### ISSUE TITLE
当ToastUtils show 之后导航事件失效问题

### ISSUE THREAD

**Issue by menhui222** [longitachi/ZLPhotoBrowser#393]
可能由于我改动了导航但是目前确实存在这个问题建议
![屏幕快照 2019-07-23 下午2 36 35](https://user-images.githubusercontent.com/12657294/61688431-954b2280-ad57-11e9-9765-7e15f9631b81.png)

**Comment by menhui222** [comment]
加[toastView removeFromSuperview];

**Comment by longitachi** [comment]
好的，我添加上。不过还没遇到过这个问题
