### ISSUE TITLE
希望支持SDWebImage 5.1.0

### ISSUE THREAD

**Issue by Wanglw2015** [longitachi/ZLPhotoBrowser#397]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by FunnyFzl** [comment]
希望支持SDWebImage 5.1.0

**Comment by longitachi** [comment]
这个这几天升级下

**Comment by longitachi** [comment]
5.1.0有升级什么api吗，我这边升级5.1.0没有遇到什么错误啊

**Comment by kinarobin** [comment]
[https://github.com/SDWebImage/SDWebImage/releases/tag/5.1.0](https://github.com/SDWebImage/SDWebImage/releases/tag/5.1.0)

**Comment by Wanglw2015** [comment]
SDWebImage 5.1.0修改了部分方法,其他的第三方使用了这些方法
你的podspec中s.dependency 'SDWebImage', '~> 5.0.2'

**Comment by longitachi** [comment]
@Wanglw2015 已经指定 ~> 5.1.0

**Comment by Wanglw2015** [comment]
@longitachi podspec里面还是 s.dependency 'SDWebImage', '~> 5.0.2'

**Comment by longitachi** [comment]
@Wanglw2015 还没发办，现在更新3.0.8
