### ISSUE TITLE
directory not found、Failed to read file or folder at

### ISSUE THREAD

**Issue by McodeYG** [longitachi/ZLPhotoBrowser#399]
按照readMe里的操作了，总是报错这个。 
directory not found for option '-F/Users/userName/Downloads/ZLPhotoBrowser-master/Carthage/Build/iOS'

Failed to read file or folder at /Users/userName/Downloads/ZLPhotoBrowser-master/Carthage/Build/iOS/SDWebImage.framework
Command PhaseScriptExecution failed with a nonzero exit code
不知道是个什么意思

**Comment by longitachi** [comment]
你这个有执行 `carthage update` 成功了吗

**Comment by McodeYG** [comment]
我一直用cocopods。作者用的 carthage。安装 carthage环境一直没安装好，执行carthage update 的时候，发现没有Carthage/Build/iOS'这个目录文件，后来重新装了一下carthage ，才成功的。费死个劲！折腾好了，git库又出了问题，重新安装了git才完，还不如一开始就把作者的demo改成cocopods的

**Comment by longitachi** [comment]
@McodeYG 运行demo时候吗？ 要同时支持carthage和cocopods，框架只能用carthage来依赖三方库（我搜资料后是这样认为的）
