### ISSUE TITLE
图片备注

### ISSUE THREAD

**Issue by 0753** [longitachi/ZLPhotoBrowser#4]
支持对图片加备注么？

**Comment by longitachi** [comment]
你好，现在是没有这个功能的。

**Comment by 0753** [comment]
后期能否加上？感觉发图片时有文字对图片解说比较好一点

**Comment by longitachi** [comment]
怎么说呢，这个框架只是提供了选择图片的功能，像你说的发图片时候加上文字解说这个步骤，感觉可以放到拿到所选照片之后自己去做一个处理
