### ISSUE TITLE
保存图片之后自动到第一页

### ISSUE THREAD

**Issue by changpk** [longitachi/ZLPhotoBrowser#400]
场景：
展示4个图片，从第1张进入，滑动到第3张，点击保存则会自动回滚到第1张图片。查看是发现
在保存图片之后会自动调用viewDidLayoutSubviews，而其中的
`    [_collectionView setContentOffset:CGPointMake((kViewWidth+kItemMargin)*_indexBeforeRotation, 0)];
`由于_indexBeforeRotation是0，所以会总是自动把ContentOffset重置为0。
这个值是否应该在滑动过程中也，把_indexBeforeRotation进行重新赋值

**Comment by longitachi** [comment]
保存时网络图片吧，保存应该不会触发`viewDidLayoutSubviews`这个方法啊。不能再滑动过程中就赋值，因为旋转的时候，会先触发`collectionView`的滚动方法，这时候去获取的page是错的，然后才走`viewDidLayoutSubviews`
