### ISSUE TITLE
ZLPhotoManager方法 requestOriginalImageForAsset:completion:中的info无PHImageFileURLKey

### ISSUE THREAD

**Issue by YGEqual** [longitachi/ZLPhotoBrowser#402]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by YGEqual** [comment]
ZLPhotoManager方法 requestOriginalImageForAsset:completion:中的info无PHImageFileURLKey，导致检索出来的图片没有path，没有fileName

**Comment by longitachi** [comment]
你手机系统是多少？我这边用iOS13 beta 的系统是存在这个key的

**Comment by YGEqual** [comment]
系统版本：iOS 12.1.4 iPhone 8 Plus。大部分图片是存在着这个key，但是某个图片是没有的，那个有问题的图片是从微博保存的，不是live photo，也不是iCloud的照片（只有个别照片有问题），没有找到规律

**Comment by longitachi** [comment]
刚从微博保存了一张图片是有这个key的，🤦‍♂️我觉的吧。。是不是苹果爸爸的问题- -
