### ISSUE TITLE
-[ZLTakePhotoCell setShowIndexLabel:]: unrecognized selector sent to instance 0x7fc882915900

### ISSUE THREAD

**Issue by syq7970** [longitachi/ZLPhotoBrowser#405]
由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ x ] 我已经查阅了已有的issue，没有找到相同的
- [ x ] 我想提出一个建议或bug，而不是问一个问题

configuration.sortAscending 设置为NO以后，重复点击相片报错崩溃。

**Comment by longitachi** [comment]
多谢提出bug，已经修复
