### ISSUE TITLE
视频录制

### ISSUE THREAD

**Issue by shen456** [longitachi/ZLPhotoBrowser#406]
大神，现在想弄成微信那样，看您的效果图有拉近拉远功能，是需要添加那些代码吗？ 
 // 直接调用相机
    ZLCustomCamera *camera = [[ZLCustomCamera alloc] init];
    
    camera.allowTakePhoto = NO;
    camera.doneBlock = ^(UIImage *image, NSURL *videoUrl) {
        // 自己需要在这个地方进行图片或者视频的保存
        self->videoImg = [self getVideoPreViewImage:videoUrl];
        self->pathStr = videoUrl;
        [self.collectionView reloadData];
    };
    
    [self showDetailViewController:camera sender:nil];

这样直接调用相机实现不了您录制的效果

**Comment by longitachi** [comment]
拉近拉远，手指在屏幕上向上滑动就好了
