### ISSUE TITLE
什么时候会适配 iOS 13

### ISSUE THREAD

**Issue by wangxiaocan** [longitachi/ZLPhotoBrowser#407]
在iOS 13上跑了一下，相册界面弹出时会超出屏幕，导致图片无法选取

**Comment by lansexin** [comment]
可以在:ZLImageNavigationController.m中30行中加入:
`if (NSFoundationVersionNumber >= NSFoundationVersionNumber_iOS_8_0) {
            self.modalPresentationStyle = UIModalPresentationOverCurrentContext;
        }else{
            self.modalPresentationStyle = UIModalPresentationCurrentContext;
        }`

**Comment by wangxiaocan** [comment]
> 可以在:ZLImageNavigationController.m中30行中加入:
> `if (NSFoundationVersionNumber >= NSFoundationVersionNumber_iOS_8_0) { self.modalPresentationStyle = UIModalPresentationOverCurrentContext; }else{ self.modalPresentationStyle = UIModalPresentationCurrentContext; }`

嗯，谢谢，这个我知道，但是在 iOS 13.0 下拍摄照片或者选择照片时会一直停留在“正在处理”

**Comment by longitachi** [comment]
我看下

**Comment by longitachi** [comment]
3.1.0版本已发布，解决present相关问题

**Comment by wangxiaocan** [comment]
谢谢了
