### ISSUE TITLE
提个裁剪功能的建议

### ISSUE THREAD

**Issue by gaoyz** [longitachi/ZLPhotoBrowser#408]
在裁剪的时候，有的业务场景需要对图片进行放大后再进行裁剪，不知可否在未来的版本中新增此功能；目前固定图片大小进行裁剪，有时候需要某个小块区域操作，并不是非常好操作。

**Comment by longitachi** [comment]
4.0.0版本已由swift重构，增强了编辑裁剪功能（仿微信），并添加了涂鸦功能
