### ISSUE TITLE
更新IOS13问题    

### ISSUE THREAD

**Issue by zhangyutao12** [longitachi/ZLPhotoBrowser#410]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/43404074/65592185-ae26bd00-dfc0-11e9-9eb5-b28a556d326e.png">
此处在子线程更新UI会报警告更新IOS13以后 还有你那个弹出视图的话IOS13得东西

**Comment by longitachi** [comment]
这个在处理了

**Comment by longitachi** [comment]
3.1.0版本已发布，可更新下
