### ISSUE TITLE
ios13 适配问题

### ISSUE THREAD

**Issue by xrefLee** [longitachi/ZLPhotoBrowser#411]
调用showPhotoLibrary 我看里面是 presentviewcontroller 弹出的视图，iOS13 版本默认弹出的不是全屏的，请修复
运行环境：xcode11 ，iPhone XR iOS13

**Comment by Cristin777888** [comment]
什么时候解决啊，急需

**Comment by wangziwu** [comment]
给大家一个临时解决方案https://github.com/wangziwu/ZWFixBugiOS13
并期待大佬快点更新版本

**Comment by longitachi** [comment]
今天更新下版本吧 @Cristin777888
