### ISSUE TITLE
新发布3.1.0版本依然存在全屏适配问题

### ISSUE THREAD

**Issue by wangziwu** [longitachi/ZLPhotoBrowser#413]
照片库中点开照相功能，依然不是全屏模式，但是底部按钮适配没问题。希望放开自定义字段，可以自主选择

**Comment by longitachi** [comment]
我这边测试的iOS13.1的系统，拍照时自定义相机是正常的全屏啊。

**Comment by wangziwu** [comment]
![21569755440_ pic_hd](https://user-images.githubusercontent.com/9216697/65831505-da0daf80-e2ec-11e9-872c-48dc25e716ae.jpg)
从相册选择界面最下方的视频框点开，这样展示的相机非全屏

**Comment by wangziwu** [comment]
iOS13和iOS13.1均展示如此

**Comment by 623034345** [comment]
> 我这边测试的iOS13.1的系统，拍照时自定义相机是正常的全屏啊。
> 你说的底部按钮是什么意思，自定义相机界面吗？

![image](https://user-images.githubusercontent.com/21259873/66792566-ecfac380-ef2b-11e9-8db3-76f5d7829c1f.png)
我这边最新系统也不是全屏 出来就少一截,导致下面布局及按钮无法正常使用

**Comment by 623034345** [comment]
> 我这边测试的iOS13.1的系统，拍照时自定义相机是正常的全屏啊。
> 你说的底部按钮是什么意思，自定义相机界面吗？

找你present的方法找了半天没找到 今天直接用runtime解决的
![image](https://user-images.githubusercontent.com/21259873/66793444-f128e000-ef2f-11e9-81ed-abeedd063fa6.png)

**Comment by wangziwu** [comment]
> > 我这边测试的iOS13.1的系统，拍照时自定义相机是正常的全屏啊。
> > 你说的底部按钮是什么意思，自定义相机界面吗？
> 
> 找你present的方法找了半天没找到 今天直接用runtime解决的
> ![image](https://user-images.githubusercontent.com/21259873/66793444-f128e000-ef2f-11e9-81ed-abeedd063fa6.png)
我这边的临时解决 https://github.com/wangziwu/ZWFixBugiOS13

**Comment by 623034345** [comment]
> > > 我这边测试的iOS13.1的系统，拍照时自定义相机是正常的全屏啊。
> > > 你说的底部按钮是什么意思，自定义相机界面吗？
> > 
> > 
> > 找你礼物的方法找了半天没找到今天直接用runtime解决的
> > 我这边的临时解决[https：](https://github.com/wangziwu/ZWFixBugiOS13) // [：//github.com/wangziwu/ZWFixBugiOS13](https://github.com/wangziwu/ZWFixBugiOS13)
> > ![图片](https://user-images.githubusercontent.com/21259873/66793444-f128e000-ef2f-11e9-81ed-abeedd063fa6.png)[](https://github.com/wangziwu/ZWFixBugiOS13)

谢谢回复 我这边也解决了 用的runtime

**Comment by longitachi** [comment]
demo也是这样吗，我已经设置了fullScreen了，用demo是正常的。
