### ISSUE TITLE
弹框的语言国际化没做好

### ISSUE THREAD

**Issue by zhangyutao12** [longitachi/ZLPhotoBrowser#414]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/43404074/65682989-ba794b80-e08e-11e9-8881-933126b40ad5.png">
显示的是国际化用的KEy

**Comment by longitachi** [comment]
你用demo试一下，我跑demo，效果是正常的

**Comment by zhangyutao12** [comment]
会不会是因为我这边做了语言国际化的问题导致的    目前已经更新到最新的版本了  还是出现一样的问题

**Comment by zhangyutao12** [comment]
![0544C94CBCA24B0CF6E55A9BD6891DEA](https://user-images.githubusercontent.com/43404074/66894509-29f5b180-f023-11e9-9312-a436912dd91b.jpg)
你看一下 这是我在做了语言国际化以后  选择中文的时候出现的

**Comment by zhangyutao12** [comment]
上次就调试了  并且打印了   这个值
