### ISSUE TITLE
点击导航栏返回按钮会闪退

### ISSUE THREAD

**Issue by CoderYLM** [longitachi/ZLPhotoBrowser#416]
（Xcode11  iOS13）点击导航栏返回按钮会闪退，老版本和最新版本都会闪退。iOS13以下没有问题，希望大神能帮忙看一下。
![B80FF3F5-AF9E-4E14-98A5-2C385C02E418](https://user-images.githubusercontent.com/55923063/65829639-0d930e80-e2da-11e9-9cd7-ce330fac5166.png)
![3AF126AB-4FFE-4FB7-901A-CC28D7D5D809](https://user-images.githubusercontent.com/55923063/65829641-0ff56880-e2da-11e9-8d32-da29ddb400dc.png)

**Comment by longitachi** [comment]
我手机iOS13.1，没出现你说的情况。
怎么感觉你第一张图图的导航条不太对啊？

**Comment by chenhengstar** [comment]
同样遇到这个问题,楼主解决了吗

**Comment by longitachi** [comment]
@chenhengstar 是进入相册，然后点击返回进入相册列表界面时候闪退？

**Comment by CoderYLM** [comment]
> 我手机iOS13.1，没出现你说的情况。
> 怎么感觉你第一张图图的导航条不太对啊？

导航条没有执行你的initNavView方法，不知道是为什么

**Comment by CoderYLM** [comment]
> @chenhengstar 是进入相册，然后点击返回进入相册列表界面时候闪退？



> > 我手机iOS13.1，没出现你说的情况。
> > 怎么感觉你第一张图图的导航条不太对啊？
> 
> 导航条没有执行你的initNavView方法，不知道是为什么

我自己重新定义了返回按钮和返回方法，可以解决闪退的问题
