### ISSUE TITLE
UI API called on a background thread: -[UIViewController navigationController]

### ISSUE THREAD

**Issue by puhahalx** [longitachi/ZLPhotoBrowser#418]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
3.1.0
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）
Main Thread Checker: UI API called on a background thread: -[UIViewController navigationController]
PID: 4613, TID: 433862, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   ZLPhotoBrowser                      0x0000000102023c10 __43-[ZLThumbnailViewController arrDataSources]_block_invoke_2 + 108
5   ZLPhotoBrowser                      0x000000010200a004 +[ZLPhotoManager getCameraRollAlbumList:allowSelectImage:complete:] + 148
6   ZLPhotoBrowser                      0x0000000102023b28 __43-[ZLThumbnailViewController arrDataSources]_block_invoke + 320
7   libdispatch.dylib                   0x00000001020c1828 _dispatch_call_block_and_release + 24
8   libdispatch.dylib                   0x00000001020c2c04 _dispatch_client_callout + 16
9   libdispatch.dylib                   0x00000001020c5300 _dispatch_queue_override_invoke + 872
10  libdispatch.dylib                   0x00000001020d4168 _dispatch_root_queue_drain + 376
11  libdispatch.dylib                   0x00000001020d4a90 _dispatch_worker_thread2 + 156
12  libsystem_pthread.dylib             0x00000001ba709f64 _pthread_wqthread + 212
13  libsystem_pthread.dylib             0x00000001ba70cae0 start_wqthread + 8

![image](https://user-images.githubusercontent.com/28496967/66468849-6f612e80-eab9-11e9-9092-2f81866c5195.png)
手机:13.1.2  xcode:11.0

**Comment by puhahalx** [comment]
![image](https://user-images.githubusercontent.com/28496967/66470442-2d85b780-eabc-11e9-9690-820ab7cec218.png)
还有ios13.1.2刚打开相册时左上角返回按钮颜色不是白色

**Comment by puhahalx** [comment]
还有iphonex系列的机型 拍照右上角翻转摄像头的按钮很难按 位置不对
![image](https://user-images.githubusercontent.com/28496967/66488150-0e008600-eae0-11e9-8e97-b944f7856428.png)

**Comment by longitachi** [comment]
这两天发版3.1.1解决
