### ISSUE TITLE
页面跳转问题

### ISSUE THREAD

**Issue by jianqingyu** [longitachi/ZLPhotoBrowser#420]
有个问题比较棘手、因为这个SDK查看大图是presented出来的。如果我是导航栏加tabbar模式、这时候要切换tabbar、必须dismiss才能跳转、要不然没反应。有啥更好的办法吗？
UITabBarController *rootVC = (UITabBarController *)[UIApplication sharedApplication].keyWindow.rootViewController;
    // 修复查看大图时不能跳转 但是会dismiss一些页面
    if ([rootVC presentedViewController]) {
        [rootVC dismissViewControllerAnimated:NO completion:nil];
    }
    if (rootVC && [rootVC isKindOfClass:[UITabBarController class]]) {
        if (rootVC.viewControllers.count > 1) {
            rootVC.selectedIndex = 1;

**Comment by longitachi** [comment]
这个确实麻烦，因为框架不能确保使用者本身app就有导航，所以只能采用present方式，不过查看大图的话，一般app都会全屏查看吧，没有必要显示tabbar

**Comment by jianqingyu** [comment]
我的意思是如果present出来、必须dismiss才能切换tabbar。否则没反应
