### ISSUE TITLE
将shouldAnialysisAsset设置为NO时 在真机上相册有大量图片的情况下 获取图片仍然很慢

### ISSUE THREAD

**Issue by 623034345** [longitachi/ZLPhotoBrowser#421]
在模拟器上只有几张图片的时候很快   在真机上使用其他第三方的时候获取相册图片并显示很快 
shouldAnialysisAsset设为NO的时候 从点击按钮 到显示图片需要大概5s甚至更长的时间

**Comment by longitachi** [comment]
shouldAnialysisAsset 是选择照片后是否解析后返回给用户，跟显示没有关系。 你说的这个显示是什么意思。打开相册速度？

**Comment by longitachi** [comment]
我这边刚才给设备导入了1w多张照片，也没有你说的那么慢啊
```
2019-10-17 11:56:40.711970+0800 Example[1028:930664] ---- start 127078.100841
2019-10-17 11:56:41.126454+0800 Example[1028:930664] ---- end 127078.515328
```

**Comment by longitachi** [comment]
你是不是把相册内部拍照按钮实时预览打开了，那个打开的话会慢一点

**Comment by 623034345** [comment]
是因为那个吗？ 明天我关了试试&nbsp;

繁华乱世沧桑了谁的容颜,又剥夺了谁的懵懂?

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "long"<notifications@github.com&gt;; 
发送时间: 2019年10月17日(星期四) 中午12:02
收件人: "longitachi/ZLPhotoBrowser"<ZLPhotoBrowser@noreply.github.com&gt;; 
抄送: "冯英杰"<623034345@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [longitachi/ZLPhotoBrowser] 将shouldAnialysisAsset设置为NO时 在真机上相册有大量图片的情况下 获取图片仍然很慢 (#421)




你是不是把相册内部拍照按钮实时预览打开了，那个打开的话会慢一点

**Comment by 623034345** [comment]
> 你是不是把相册内部拍摄按钮实时预览打开了，那个打开的话会慢一点

我的是iPhone 7plus 刚把拍摄实时预览关了  一千多张图片  首次打开相册高达十秒   
![image](https://user-images.githubusercontent.com/21259873/67073403-960a1e00-f1b9-11e9-907c-934e52868b51.png)
这是我的所有代码   把gif和视频资源全部筛出去了 只显示图片

**Comment by longitachi** [comment]
@623034345 我测试导入的1w多张照片就是在7plus里。
1. 你用demo打开也是十几秒吗？还是只在你的项目里这么慢？
2. 其他机型呢？速度咋样

**Comment by 623034345** [comment]
demo我没跑  直接根据文档用的  我这边代码有问题吗?

**Comment by 623034345** [comment]
![image](https://user-images.githubusercontent.com/21259873/67177589-c8a65780-f401-11e9-9325-de6786fc702d.png)
我刚试了一下 demo很快  为啥我这个很慢  打开的时候这是输出的日志  我需要做其他操作吗?

**Comment by 623034345** [comment]
难道是pod导入的原因导致的? 像这种demo比较快  到项目中就很慢的原因怎么解决?

**Comment by 623034345** [comment]
我发现和写的没问题  只要是pod的就会出现很慢的问题  pod的版本有问题应该是

**Comment by longitachi** [comment]
你试了下pod集成会很慢？代码直接拖进去就会快？
这个明天我试下。 pod你安装的是最新的版本吗？

**Comment by 623034345** [comment]
是最新版本



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: long <notifications@github.com&gt;
发送时间: 2019年10月28日 19:49
收件人: longitachi/ZLPhotoBrowser <ZLPhotoBrowser@noreply.github.com&gt;
抄送: 623034345 <623034345@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[longitachi/ZLPhotoBrowser] 将shouldAnialysisAsset设置为NO时 在真机上相册有大量图片的情况下 获取图片仍然很慢 (#421)
