### ISSUE TITLE
iOS13+系统，选择视频后回调的PHAsset对象，请求封面图或者请求视频FileURL都失败

### ISSUE THREAD

**Issue by Jean1992** [longitachi/ZLPhotoBrowser#422]
请求封面图的错误信息
{
    PHImageErrorKey = "Error Domain=NSCocoaErrorDomain Code=-1 \"(null)\"";
    PHImageResultIsDegradedKey = 0;
    PHImageResultRequestIDKey = 76;
}
请求FileURL的错误信息
{
    PHImageResultIsDegradedKey = 0;
    PHImageResultRequestIDKey = 78;
}
error: Execution was interrupted, reason: EXC_BREAKPOINT (code=1, subcode=0x1ad6c3598).
The process has been returned to the state before expression evaluation.

**Comment by Jean1992** [comment]
iOS13以下系统

**Comment by Jean1992** [comment]
请求封面信息info
{
    PHImageFileOrientationKey = 0;
    PHImageResultDeliveredImageFormatKey = 9999;
    PHImageResultIsDegradedKey = 0;
    PHImageResultIsInCloudKey = 0;
    PHImageResultIsPlaceholderKey = 0;
    PHImageResultRequestIDKey = 32;
    PHImageResultWantedImageFormatKey = 9999;
}
请求FileURLInfo
{
    PHImageFileSandboxExtensionTokenKey = "3a671b147b88ee17a9c0f45f0d4220c61293dd5b;00;00000000;00000000;00000000;000000000000001b;com.apple.avasset.read-only;01;01000004;0000000001d5409f;01;/private/var/mobile/Media/DCIM/102APPLE/IMG_2133.MP4";
    PHImageResultDeliveredImageFormatKey = 20000;
    PHImageResultIsInCloudKey = 0;
    PHImageResultWantedImageFormatKey = 20002;
}
file:///var/mobile/Media/DCIM/102APPLE/IMG_2133.MP4

**Comment by longitachi** [comment]
请提供一下版本号，以及demo是否会出现问题

**Comment by Jean1992** [comment]
> 请提供一下版本号，以及demo是否会出现问题

解决了，13+系统不要使用requestAVAssetForVideo，要使用requestExportSessionForVideo，callback里面有个exportSession对象，那个asset才有值

**Comment by longitachi** [comment]
@Jean1992 没太明白你说的哪个方法。 能提供下代码吗？如果有bug的话我fixI下。或者在这里给其他人提供下解决思路

**Comment by Jean1992** [comment]
`
#import "PHAsset+CM.h"

@implementation PHAsset (CM)

- (void)getVideoUrl:(void(^)(NSURL *url))completion {
    if (self.mediaType == PHAssetMediaTypeVideo) {
        PHVideoRequestOptions *options = [[PHVideoRequestOptions alloc] init];
        options.version = PHImageRequestOptionsVersionCurrent;
        options.deliveryMode = PHVideoRequestOptionsDeliveryModeAutomatic;
        PHImageManager *manager = [PHImageManager defaultManager];
        if (@available(iOS 13, *)) {
            [manager requestExportSessionForVideo:self options:options exportPreset:AVAssetExportPresetMediumQuality resultHandler:^(AVAssetExportSession * _Nullable exportSession, NSDictionary * _Nullable info) {
                AVURLAsset *urlAsset = (AVURLAsset *)exportSession.asset;
                [NSThread safeThread:^{
                    !completion ?: completion(urlAsset.URL);
                }];
            }];
        } else {
            [manager requestAVAssetForVideo:self options:options resultHandler:^(AVAsset * _Nullable asset, AVAudioMix * _Nullable audioMix, NSDictionary * _Nullable info) {
                AVURLAsset *urlAsset = (AVURLAsset *)asset;
                [NSThread safeThread:^{
                    !completion ?: completion(urlAsset.URL);
                }];
            }];
        }
    }
}
- (void)getVideoPreview:(void (^)(UIImage *))completion {
    PHImageRequestOptions *option = [[PHImageRequestOptions alloc] init];
    option.resizeMode = PHImageRequestOptionsResizeModeExact;
    
    if (@available(iOS 13, *)) {
        [PHImageManager.defaultManager requestImageDataForAsset:self options:option resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
            UIImage *image = [UIImage imageWithData:imageData];
            [NSThread safeThread:^{
                !completion ?: completion(image);
            }];
        }];
    } else {
        [[PHImageManager defaultManager] requestImageForAsset:self targetSize:PHImageManagerMaximumSize contentMode:PHImageContentModeAspectFill options:option resultHandler:^(UIImage * _Nullable result, NSDictionary * _Nullable info) {
            
            UIImage *image = result;
            [NSThread safeThread:^{
                !completion ?: completion(image);
            }];
        }];
    }
}
`

**Comment by Jean1992** [comment]
```
#import "PHAsset+CM.h"

@implementation PHAsset (CM)

- (void)getVideoUrl:(void(^)(NSURL *url))completion {
    if (self.mediaType == PHAssetMediaTypeVideo) {
        PHVideoRequestOptions *options = [[PHVideoRequestOptions alloc] init];
        options.version = PHImageRequestOptionsVersionCurrent;
        options.deliveryMode = PHVideoRequestOptionsDeliveryModeAutomatic;
        PHImageManager *manager = [PHImageManager defaultManager];
        if (@available(iOS 13, *)) {
            [manager requestExportSessionForVideo:self options:options exportPreset:AVAssetExportPresetMediumQuality resultHandler:^(AVAssetExportSession * _Nullable exportSession, NSDictionary * _Nullable info) {
                AVURLAsset *urlAsset = (AVURLAsset *)exportSession.asset;
                [NSThread safeThread:^{
                    !completion ?: completion(urlAsset.URL);
                }];
            }];
        } else {
            [manager requestAVAssetForVideo:self options:options resultHandler:^(AVAsset * _Nullable asset, AVAudioMix * _Nullable audioMix, NSDictionary * _Nullable info) {
                AVURLAsset *urlAsset = (AVURLAsset *)asset;
                [NSThread safeThread:^{
                    !completion ?: completion(urlAsset.URL);
                }];
            }];
        }
    }
}
- (void)getVideoPreview:(void (^)(UIImage *))completion {
    PHImageRequestOptions *option = [[PHImageRequestOptions alloc] init];
    option.resizeMode = PHImageRequestOptionsResizeModeExact;
    
    if (@available(iOS 13, *)) {
        [PHImageManager.defaultManager requestImageDataForAsset:self options:option resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
            UIImage *image = [UIImage imageWithData:imageData];
            [NSThread safeThread:^{
                !completion ?: completion(image);
            }];
        }];
    } else {
        [[PHImageManager defaultManager] requestImageForAsset:self targetSize:PHImageManagerMaximumSize contentMode:PHImageContentModeAspectFill options:option resultHandler:^(UIImage * _Nullable result, NSDictionary * _Nullable info) {
            
            UIImage *image = result;
            [NSThread safeThread:^{
                !completion ?: completion(image);
            }];
        }];
    }
}
```

**Comment by Jean1992** [comment]
不是你的bug，是拿到PHAsset后的一些后续操作，关系不大
