### ISSUE TITLE
下载的demo,无法运行 —— 请查看README

### ISSUE THREAD

**Issue by guruifeng** [longitachi/ZLPhotoBrowser#425]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
请看readme，下载完Demo请执行carthage update --platform iOS （运行时候请选择 Example target）
你有执行吗？

**Comment by Michaelyb520** [comment]
执行了 `carthage update --platform iOS `还是有问题，工程配置要修改一下？
运行环境：Xcode 11。

**Comment by longitachi** [comment]
@Michaelyb520 好的，我回头自己试下

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by longitachi** [comment]
我试了下，下载完执行 `carthage update --platform iOS` 之后是可以运行的，`SDWebImage.framework` 和 `SDWebImageMapKit.framework` 路径如果报错的话，关掉项目，重新打开即可

**Comment by TzyTman** [comment]
我也遇到同样的问题

**Comment by JianWenXie** [comment]
我也遇到问题
