### ISSUE TITLE
设置实时捕获相机画面后点击视频编辑后崩溃

### ISSUE THREAD

**Issue by Elon-Programmer** [longitachi/ZLPhotoBrowser#428]
一个很难发现的Bug,当设置showCaptureImageOnTakePhotoBtn属性为YES后，点击视频编辑后直接报错崩溃:

报错内容：

> [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
> [MC] Reading from public effective user settings.
> Message from debugger: Terminated due to memory issue

**Comment by longitachi** [comment]
我试了下demo里，并没有出现你说的这种情况。请问你是怎么复现的。
