### ISSUE TITLE
ios8 系统运行时候报 dyld: Symbol not found: _OBJC_CLASS_$_PHLivePhotoRequestOptions 

### ISSUE THREAD

**Issue by plus7ky** [longitachi/ZLPhotoBrowser#429]
requestLivePhotoForAsset 里面调用的PHLivePhotoRequestOptions 能在ios 13 sdk编译通过，但是在ios8.0 的系统上跑就会崩溃，报错

dyld: Symbol not found: _OBJC_CLASS_$_PHLivePhotoRequestOptions
  Referenced from: /private/var/mobile/Containers/Bundle/Application/D9063E28-D55E-474B-AFD2-XXXXXXXXX/{myapp}.app/{myapp}
  Expected in: /System/Library/Frameworks/Photos.framework/Photos
 in /private/var/mobile/Containers/Bundle/Application/D9063E28-D55E-474B-AFD2-XXXXXXXXX/{myapp}.app/{myapp}

可以参考这个改一下
http://temp1.ssl.broadcast.pub/douxindong/QMUI_iOS/commit/93c59515b2cdc336f9fa4fbd26f40c36e96ab93e

**Comment by longitachi** [comment]
iOS8上面不会走到livephoto这个方法啊，代码内有判断的。有断点看到crash的地方吗

**Comment by plus7ky** [comment]
编译没有问题，工程里也没有调用livephoto相关的接口，在应用运行时一点开就crash，没有断点，console显示上面的错误

**Comment by longitachi** [comment]
demo不会闪退，pod集成项目里面会？

**Comment by plus7ky** [comment]
> demo不会闪退，pod集成项目里面会？

是的，pod 集成的方式。

**Comment by longitachi** [comment]
那就奇怪了，demo不会闪退，你集成后会闪退，demo也是从 iOS8 开始支持的，iOS9以下的机型就不会走到请求livephoto，你确定你集成后demo就调了requestLivePhotoForAsset这个方法？

**Comment by plus7ky** [comment]
> 那就奇怪了，demo不会闪退，你集成后会闪退，demo也是从 iOS8 开始支持的，iOS9以下的机型就不会走到请求livephoto，你确定你集成后demo就调了requestLivePhotoForAsset这个方法？

没有调用，项目里只用了ZLPhotoBrowser

**Comment by plus7ky** [comment]
后来我在自己的spec文件把Photos.frameworks改为optional, 这个错误就没有了
`  s.weak_frameworks  = 'Photos'`
