### ISSUE TITLE
能否跟朋友圈一样混合选择时，选择了图片就不能选择视频，选择了视频就不能选择图片

### ISSUE THREAD

**Issue by wangcheng-ios** [longitachi/ZLPhotoBrowser#430]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
设置选择图片时候不能选择视频就好了，反之一样。

**Comment by wangcheng-ios** [comment]
混合选择，动态的，因为可以选择多个资源，当选中的一张图片时，还没有完成全部选择，视频就不能点击选择了

**Comment by wangcheng-ios** [comment]
不是选择前设置，只选择图片或者视频

**Comment by longitachi** [comment]
这个现在是不支持的
