### ISSUE TITLE
闪退问题 数组中有nil

### ISSUE THREAD

**Issue by CoMeLyQ** [longitachi/ZLPhotoBrowser#431]
多调用几次【ac showPreviewAnimated】此处崩溃！Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
初步估计是记录上次的右上标有问题
闪退时m.asset为空 ，求大神解决
+ (void)markSelectModelInArr:(NSArray<ZLPhotoModel *> *)dataArr selArr:(NSArray<ZLPhotoModel *> *)selArr
{
    NSMutableArray *selIdentifiers = [NSMutableArray array];
    for (ZLPhotoModel *m in selArr) {
        [selIdentifiers addObject:m.asset.localIdentifier];
    }
    for (ZLPhotoModel *m in dataArr) {
        if ([selIdentifiers containsObject:m.asset.localIdentifier]) {
            m.selected = YES;
        } else {
            m.selected = NO;
        }
    }
}

**Comment by longitachi** [comment]
怎么能复现？现在只做了一个判断 `m.asset.localidentifier` 是否为空的判断
