### ISSUE TITLE
请问怎么隐藏icloud视频照片

### ISSUE THREAD

**Issue by jianqingyu** [longitachi/ZLPhotoBrowser#432]

**Comment by longitachi** [comment]
emmm，没有这个功能。

**Comment by jianqingyu** [comment]
我选择icloud视频失败，请问选择icloud视频做了什么处理吗、在线下载？

**Comment by longitachi** [comment]
没什么特殊处理，只是下载了期图片，你选择的时候，cell会有一个progress进度，进度走完了即可

**Comment by jianqingyu** [comment]
那这样就挺麻烦的、既不能隐藏icloud视频，选完这种视频又不能播放，那就是个bug啊。没什么好办法解决一下吗
