### ISSUE TITLE
打开->ZLPhotoBrowser-master-ZLPhotoBrowser.xcworkspace 运行时报错

### ISSUE THREAD

**Issue by TzyTman** [longitachi/ZLPhotoBrowser#435]
error: /Users/mzxf/Desktop/ZLPhotoBrowser-master/Carthage/Build/iOS/SDWebImageMapKit.framework: No such file or directory (in target 'Example' from project 'Example')

**Comment by TzyTman** [comment]
难道只能真机调试么？

**Comment by longitachi** [comment]
你看下readme里面介绍。应该是你carthage安装完后，这俩framework路径错误了，重新导入下就好了

**Comment by longitachi** [comment]
#436

**Comment by TzyTman** [comment]
谢谢大佬 你那个视频剪切滑动可不可以添加秒数提示 例如0-60 我最近用您的这个库有这个需求。改您的源码 把后续您更新有覆盖了谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: long <notifications@github.com&gt;
发送时间: 2019年11月14日 11:45
收件人: longitachi/ZLPhotoBrowser <ZLPhotoBrowser@noreply.github.com&gt;
抄送: tuzhengyao <905430956@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[longitachi/ZLPhotoBrowser] 打开-&gt;ZLPhotoBrowser-master-ZLPhotoBrowser.xcworkspace 运行时报错 (#435)

**Comment by longitachi** [comment]
什么意思没明白。怎么个提示法

**Comment by TzyTman** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    给您附件了 您看一下
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                905430956
                            
                    
                        
                            
                                    905430956@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年11月14日 11:49，long<notifications@github.com> 写道： 


什么意思没明白。怎么个提示法



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by TzyTman** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    大概是这个意思
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                905430956
                            
                    
                        
                            
                                    905430956@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年11月14日 11:53，905430956<905430956@qq.com> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    给您附件了 您看一下
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                905430956
                            
                    
                        
                            
                                    905430956@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年11月14日 11:49，long<notifications@github.com> 写道： 


什么意思没明白。怎么个提示法



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
