### ISSUE TITLE
下载完Demo请执行carthage update --platform iOS （运行时候请选择 Example target）SDWebImage.framework 和 SDWebImageMapKit.framework 路径如果报错的话，关掉项目，重新打开即可

### ISSUE THREAD

**Issue by TzyTman** [longitachi/ZLPhotoBrowser#436]
下载完Demo请执行carthage update --platform iOS （运行时候请选择 Example target）SDWebImage.framework 和 SDWebImageMapKit.framework 路径如果报错的话，关掉项目，重新打开即可  ？ 重新打开还是报错啊！

**Comment by longitachi** [comment]
你看下这两个framework的路径，不行的话就去项目里重新添加一下 framework目录在这里`Carthage`->`Build`->`iOS`

**Comment by TzyTman** [comment]
已经可以了 谢谢大佬



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: long <notifications@github.com&gt;
发送时间: 2019年11月14日 11:43
收件人: longitachi/ZLPhotoBrowser <ZLPhotoBrowser@noreply.github.com&gt;
抄送: tuzhengyao <905430956@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[longitachi/ZLPhotoBrowser] 下载完Demo请执行carthage update --platform iOS （运行时候请选择 Example target）SDWebImage.framework 和 SDWebImageMapKit.framework 路径如果报错的话，关掉项目，重新打开即可 (#436)




你看下这两个framework的路径，不行的话就去项目里重新添加一下 framework目录在这里Carthage-&gt;Build-&gt;iOS
