### ISSUE TITLE
NIMKit冲突

### ISSUE THREAD

**Issue by kennenfromchina** [longitachi/ZLPhotoBrowser#438]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [NIMKit冲突] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
pod --version
1.8.4
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

项目中集成了云信的聊天NIMKit，里面指定了SDWebImage的版本号为4.2.3，我不指定ZLPhotoBrowser的版本号，可以pod install成功，但是在
ZLBigImageCell.h
中报错：
'SDWebImage/SDAnimatedImageView.h' file not found
请问如何兼容一下？
我之前用手动导入的方式引入ZLPhotoBrowser库，但是在iOS13中有bug，就想升级到最新，发现了上述问题，可以提供支持SDWebImage 4.2.3版本的iOS13修复版本吗？

**Comment by longitachi** [comment]
这个怎么提供。。云信的版本太老了。我要指定4.2.3，那这个框架也跟着他等于不更新了
