### ISSUE TITLE
关于设置预览图放大比例

### ISSUE THREAD

**Issue by wangziwu** [longitachi/ZLPhotoBrowser#44]
图片展示，你框架是放大到屏幕大小，能否设置系数？

**Comment by longitachi** [comment]
怎么会是放大到屏幕大小，框架默认是放大三倍。 暂没有接口设置，你可以在ZLBigImageCell里面的如下方法中修改，把scale改成你需要的。
- (void)doubleTapAction:(UITapGestureRecognizer *)tap
{
    UIScrollView *scrollView = (UIScrollView *)tap.view;
    
    CGFloat scale = 1;
    if (scrollView.zoomScale != 3.0) {
        scale = 3;
    } else {
        scale = 1;
    }
    CGRect zoomRect = [self zoomRectForScale:scale withCenter:[tap locationInView:tap.view]];
    [scrollView zoomToRect:zoomRect animated:YES];
}
