### ISSUE TITLE
这个 scale 为什么要设置为2了？

### ISSUE THREAD

**Issue by TzyTman** [longitachi/ZLPhotoBrowser#442]
- (CGSize)requestImageSize:(PHAsset *)asset
{
    CGFloat scale = 2;
    CGFloat width = MIN(kViewWidth, kMaxImageWidth); //获取最小值
    CGSize size = CGSizeMake(width*scale, width*scale*asset.pixelHeight/asset.pixelWidth);
    return size;
}

**Comment by longitachi** [comment]
这是取了一个相对好点的值，如果太大，会导致图片加载太慢，太小会导致模糊
