### ISSUE TITLE
 bug：无法运行

### ISSUE THREAD

**Issue by YongruiDuan** [longitachi/ZLPhotoBrowser#443]
pod版本 1.8.3

pod 文件：
pod 'SDWebImage/GIF' #gif加载
pod 'SDWebImage'  #图片加载
pod 'ZLPhotoBrowser', '~> 3.1.2'

#import <SDWebImage/SDAnimatedImageView.h>报错，找不到类，请问何时更新一下

**Comment by ngng1024GH** [comment]
ZLPhotoBrowser里面依赖了SDWebImage5.0 
你把你自己的SDWebImage版本更新下 或者去掉都可以

> pod版本 1.8.3
> 
> pod 文件：
> pod 'SDWebImage/GIF' #gif加载
> pod 'SDWebImage' #图片加载
> pod 'ZLPhotoBrowser', '~> 3.1.2'
> 
> #import <SDWebImage/SDAnimatedImageView.h>报错，找不到类，请问何时更新一下

ZLPhotoBrowser里面依赖了SDWebImage5.0 
你把你自己的SDWebImage版本更新下 或者去掉都可以
