### ISSUE TITLE
仅使用拍照功能的时候，可否在拍照完成后进入编辑界面，允许对照片进行编辑

### ISSUE THREAD

**Issue by ipad4** [longitachi/ZLPhotoBrowser#444]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
1.8.0
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）
仅使用拍照功能的时候，可否在拍照完成后进入编辑界面，允许对照片进行编辑，像微信拍照一样

**Comment by 740629515** [comment]
同问啊, 仅仅使用拍照功能的话, 拍完怎么进入编辑页面

**Comment by longitachi** [comment]
当前版本是不支持直接调用编辑图片的。下个版本会添加上直接调用编辑图片界面的功能。
