### ISSUE TITLE
选择视频的时候为什么不进入编辑界面

### ISSUE THREAD

**Issue by mozhangshuyumo** [longitachi/ZLPhotoBrowser#452]
设置了视频最大时长10秒，选择大于10秒的视频就不能选，让用户怎么去编辑呢？还有设置什么模式能进入视频编辑，上面的按钮模式来来回回选了半天，点击视频都不进入编辑模式

**Comment by longitachi** [comment]
#449

**Comment by longitachi** [comment]
上面issue里设置是单选直接进入编辑界面，如果多选时候，必须手动点击编辑
