### ISSUE TITLE
能否增加一个最大视频个数选择的参数，目前图片和视频都是maxSelectCount

### ISSUE THREAD

**Issue by LSPBoy** [longitachi/ZLPhotoBrowser#453]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by LSPBoy** [comment]
能否做成，如果选择了视频，就应该像微信一样，直接跳转到编辑，视频只让选择一个

**Comment by daniusite** [comment]
能否增加一个最大视频个数选择的参数，目前图片和视频都是maxSelectCount

**Comment by longitachi** [comment]
@daniusite 
```
/**
 混合选择时 视频最大数量，默认等同最大选择数 9
 */
@property (nonatomic, assign) NSInteger maxVideoSelectCountInMix;

/**
 混合选择时 视频最小数量，默认为0
 */
@property (nonatomic, assign) NSInteger minVideoSelectCountInMix;
```

**Comment by longitachi** [comment]
@LSPBoy 这个功能暂时不行。感觉改动太大。还没想好怎么弄

**Comment by LSPBoy** [comment]
好的，您有时间了，可以看看，总之你这个框架太强大了，全是参数配置化，真心佩服。

**Comment by BestLeeSinCN** [comment]
急切需要这个功能, app需求图片可以选三张但是视频只能选择一个, 且不能同时选择..

**Comment by xuzhenguo** [comment]
大神们  怎么通过配置实现 ：如果选择了视频还能单选的功能

**Comment by longitachi** [comment]
3.2.0已添加该功能
