### ISSUE TITLE
拍照之后能不能在内部增加一个编辑图片的功能，目前没有这个功能，我的实现方式只能通过这种方式。

### ISSUE THREAD

**Issue by JudeGGT** [longitachi/ZLPhotoBrowser#456]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [x] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（ #如有可能，请尽量详细描述，建议附上截图）
![Snip20191227_1](https://user-images.githubusercontent.com/13214549/71498118-06a67880-2896-11ea-98d1-2f70152be8bb.png)

**Comment by longitachi** [comment]
下个版本会新增一个接口，可直接调用编辑图片
```
- (void)editImageWithAsset:(PHAsset *)asset success:(void (^)(UIImage *result, PHAsset *asset))success cancel:(void (^)(void))cancel;
```
