### ISSUE TITLE
用户没有开启权限，点击图片，进行大图浏览，弹出访问您的图片的弹框，选择好，会崩溃在ZLPhotoModel.asset为nil,选择不允许不会崩溃。

### ISSUE THREAD

**Issue by baishitong** [longitachi/ZLPhotoBrowser#458]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
![A4BB7A65-0A97-41F6-A751-C6DBB02921B7](https://user-images.githubusercontent.com/16411379/71959009-a962dd80-322c-11ea-8db8-2e80af50ef26.png)

1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by baishitong** [comment]
我的版本为3.0.0

**Comment by longitachi** [comment]
没有开启权限的话，是进不去选择界面和预览大图界面的吧

**Comment by baishitong** [comment]
老版的只要首次打开app中的图就会弹出权限，且是大图。
最新版的大图弹出来的时候，并没有弹出相册权限，只有在长按的时候才会弹出权限，且下方弹出action。
崩溃的原因在于就是上方的那个nil。现在新版的好像不崩溃 了
