### ISSUE TITLE
拍摄后的视频地址转成data为nil

### ISSUE THREAD

**Issue by BestLeeSinCN** [longitachi/ZLPhotoBrowser#459]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by BestLeeSinCN** [comment]
file:///private/var/mobile/Containers/Data/Application/FD9D6E64-9EE8-445D-A007-D7D8216A9A5F/tmp/21298669-5c83-4c30-950c-f2b57859e87f.mov

这是文件路径, 不知道怎么把这个路径转成data

**Comment by Arya-Wang** [comment]
@BestLeeSinCN 请问解决了么   我也遇到这个问题  转换出来data是空的
