### ISSUE TITLE
分辨率能让我们自定义拓展吗？

### ISSUE THREAD

**Issue by myDonghao** [longitachi/ZLPhotoBrowser#464]
问就是产品的问题😭！
他们觉得960x540比较好，我感觉这tm就是针对我
我现在是改了源码，添加了960x540

**Comment by longitachi** [comment]
emmm，深表同情，这个是枚举暂不支持扩展，下个版本我会把之前差的几个分辨率添加进去 `320x240` 和 `960x540`

**Comment by myDonghao** [comment]
感谢大大添加了这个分辨率，但是ZLCustomCamera这里还需要添加一下对系统分辨率的映射
<img width="843" alt="image" src="https://user-images.githubusercontent.com/20014338/76738921-74cc4e80-67a6-11ea-9b09-7b5f30f8257a.png">
