### ISSUE TITLE
查看所有文件夹能做成类型微信那种吗？

### ISSUE THREAD

**Issue by 13970821754** [longitachi/ZLPhotoBrowser#465]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

目前查看所有文件夹要切换页面，不是很方便，能不能做成类似微信那种弹出一个蒙版。

![1](https://user-images.githubusercontent.com/11360890/74549349-75e14480-4f8a-11ea-9d3f-a21fa36e1f93.jpg)

**Comment by longitachi** [comment]
这个应该不会，之前就是按照微信的做的，微信下次如果在改版，又会有人提出在改版。。。。所以应该不会做
