### ISSUE TITLE
手机摄像头损坏导致无法获取到视频流的crash

### ISSUE THREAD

**Issue by liaohui2015** [longitachi/ZLPhotoBrowser#468]
ZLCustomCamera类中，setupCamera方法中，将视频输入流添加到session中，缺少判断条件，如果手机摄像头损坏，videoInput为nil，会直接导致crash。
<img width="401" alt="image" src="https://user-images.githubusercontent.com/15357905/75218362-fe56b500-57d4-11ea-87f6-320c417b9f59.png">

**Comment by longitachi** [comment]
这个可以现在`viewDidLoad`中加个判断
```
// 摄像头不可用状态
    if (![UIImagePickerController isSourceTypeAvailable:UIImagePickerControllerSourceTypeCamera]) {
        // alert 提示
        return;
    }
```
