### ISSUE TITLE
版本3.1.2，本地化文件，设置-隐私-相机，书写有误

### ISSUE THREAD

**Issue by JinghuangLiu** [longitachi/ZLPhotoBrowser#469]
如下，所有都是“设置-隐私-相机”，跟前面的key对应不上

"ZLPhotoBrowserNoCameraAuthorityText" = "请在iPhone的\"设置-隐私-相机\"选项中，允许%@访问你的相机";
"ZLPhotoBrowserNoAblumAuthorityText" = "请在iPhone的\"设置-隐私-相机\"选项中，允许%@访问你的照片";
"ZLPhotoBrowserNoMicrophoneAuthorityText" = "请在iPhone的\"设置-隐私-相机\"选项中，允许%@访问你的麦克风";

**Comment by JinghuangLiu** [comment]
@longitachi

**Comment by longitachi** [comment]
好的，我改下
