### ISSUE TITLE
编辑视频的问题

### ISSUE THREAD

**Issue by friendsheeps** [longitachi/ZLPhotoBrowser#470]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本.  3.1.3
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

当前设置为maxSelectCount = 1; allowSelectVideo = YES; editAfterSelectThumbnailImage = YES;
出现的问题是选择10s以上的视频可直接进入编辑视频页，选择10s以下的视频无响应；
请问在 editAfterSelectThumbnailImage = YES 下能否实现10s以上的图片进入编辑页，10s以下的图片直接返回。

**Comment by longitachi** [comment]
这个暂时不可以，小于10s的视频不能编辑，我看下好不好修改成小于10s的也可以编辑

**Comment by longitachi** [comment]
`ZLPhotoConfiguration` 中限制了10s以下视频不能编辑，你可以改下代码先，把10改的小点，然后设置一个值
```
- (void)setMaxEditVideoTime:(NSInteger)maxEditVideoTime
{
    _maxEditVideoTime = MAX(maxEditVideoTime, 10);
}
```
