### ISSUE TITLE
iOS8系统使用了PHLivePhotoRequestOptions造成崩溃?

### ISSUE THREAD

**Issue by haokunjiang** [longitachi/ZLPhotoBrowser#474]
Symbol not found: _OBJC_CLASS_$_PHLivePhotoRequestOptions
PHLivePhotoRequestOptions是iOS9.1之后才有的，而项目是支持到iOS8，所以用户使用iOS8打开会崩溃，请及时修正，感谢。
使用的版本为：  pod 'ZLPhotoBrowser','3.1.3'

**Comment by longitachi** [comment]
```
- (void)setAllowSelectLivePhoto:(BOOL)allowSelectLivePhoto
{
    if (@available(iOS 9.0, *)) {
        _allowSelectLivePhoto = allowSelectLivePhoto;
    } else {
        _allowSelectLivePhoto = NO;
    }
}
```
有这个限制，iOS9以下用户应该走不到对应代码，能给出哪个地方crash了吗？ （9.0 我下个版本会改成9.1

**Comment by haokunjiang** [comment]
从苹果crash中查找到的崩溃bug如下： YIMIProject:   Symbol not found: _OBJC_CLASS_$_PHLivePhotoRequestOptions + 0，详情在附近图片上。













在 2020-04-03 15:14:31，"long" <notifications@github.com> 写道：

- (void)setAllowSelectLivePhoto:(BOOL)allowSelectLivePhoto

{

    if (@available(iOS 9.0, *)) {

        _allowSelectLivePhoto = allowSelectLivePhoto;

    } else {

        _allowSelectLivePhoto = NO;

    }

}



有这个限制，iOS9以下用户应该走不到对应代码，能给出哪个地方crash了吗？ （9.0 我下个版本会改成9.1
