### ISSUE TITLE
重要：拍照之后没有编辑图片功能

### ISSUE THREAD

**Issue by 13970821754** [longitachi/ZLPhotoBrowser#476]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

自定义相机拍完照片以后，能不能加上编辑功能？

**Comment by longitachi** [comment]
具体怎么一个流程？你都设置了哪些参数？

**Comment by 13970821754** [comment]
使用流程：在【照片图库】或【拍照】选择照片后，编辑图片保存为头像。现在的问题是【照片图库】选择图片以后可以跳转到编辑页面，【拍照】照片后直接返回了，没有编辑功能。

调用代码：
 ZLCustomCamera *camera = [[ZLCustomCamera alloc] init];
    camera.allowTakePhoto = YES;
    camera.allowRecordVideo = NO;
    camera.doneBlock = ^(UIImage *image, NSURL *videoUrl) {
           ZLProgressHUD *hud = [[ZLProgressHUD alloc] init];
           [hud show];
           [ZLPhotoManager saveImageToAblum:image completion:^(BOOL suc, PHAsset *asset) {
               if (suc){
               }
               else
                   ZLLoggerDebug(@"图片保存失败");
               [hud hide];
           }];
    };
    [webView showDetailViewController:camera sender:nil];
![2](https://user-images.githubusercontent.com/11360890/78741880-1b160900-798d-11ea-8a3a-80bdbe2cbc2c.png)

**Comment by longitachi** [comment]
直接拍照的话，需要成功后，在回调中自己再跳转。
