### ISSUE TITLE
下载之后报错SDWebImage/SDAnimatedImageView.h' file not found

### ISSUE THREAD

**Issue by Haohaizi20101016** [longitachi/ZLPhotoBrowser#477]
报错：SDWebImage/SDAnimatedImageView.h' file not found.   
用cocoapods导入pod search SDWebImage，再 pod install 报错：[!] Unable to find a target named `ZLPhotoBrowser-master` in project `ZLPhotoBrowser.xcodeproj`, did find `ZLPhotoBrowserFramework`.   反复是了很多次，还是这样，能给个完整的demo么，谢谢~

**Comment by longitachi** [comment]
你查看Readme第一行。需要用carthage进行安装
