### ISSUE TITLE
选择原图后，在浏览界面切换上一张下一张的时候 原图的尺寸不会变

### ISSUE THREAD

**Issue by deanli08** [longitachi/ZLPhotoBrowser#479]
#### 关于 Issue
1. 3.1.4版本
2. 在预览图片的时候选中下面的原图，比如显示（0.7M），然后左右切换图片，下面的显示的一直是0.7M
除非在选中在关闭。

**Comment by longitachi** [comment]
原图大小是已选择照片的总大小
