### ISSUE TITLE
可否增加图片或视频大小限制 

### ISSUE THREAD

**Issue by zhangqibin** [longitachi/ZLPhotoBrowser#480]
在做即时通讯的时候,三方即时通讯会限制文件的大小,建议增加类似于微信在选择的时候会提示文件太大.

感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
这个后边看下吧。视频的加的话可以，图片估计不太会加

**Comment by zhangqibin** [comment]
感谢

**Comment by ZClee128** [comment]
大佬，还是希望可以增加图片大小现在

**Comment by longitachi** [comment]
> 大佬，还是希望可以增加图片大小现在

可以使用`canSelectAsset`来做

**Comment by ZClee128** [comment]
> > 大佬，还是希望可以增加图片大小现在
> 
> 可以使用`canSelectAsset`来做

可以给一下示例吗，我看了canSelectAsset这个需要传PHAsset

**Comment by longitachi** [comment]
```swift
ZLPhotoConfiguration.default()
	.canSelectAsset { asset in
	    if asset.mediaType == .image,
	       let size = ZLPhotoManager.fetchAssetSize(for: asset) {
	        return size < 1000
	    } else {
	        return true
	    }
	}
```
