### ISSUE TITLE
请问我要在编辑图片的时候扩展一下涂鸦的功能，应该在哪个类里扩展呢？

### ISSUE THREAD

**Issue by tianguanghui** [longitachi/ZLPhotoBrowser#485]
现在的图片编辑功能只有裁切，我想扩展一下简单的涂鸦功能，应该在哪里改呢？

**Comment by tianguanghui** [comment]
我看源码ZLImageEditTools貌似是有涂鸦的类ZLDrawItem，现在这个类是不能用么？

**Comment by tianguanghui** [comment]
ZLImageEditTypeDraw|ZLImageEditTypeMosaic
这两种类型，是没有实现么？

**Comment by tianguanghui** [comment]
涂鸦和旋转同事打开的话，有个bug，我改了，回头用梯子，我提交一下代码，还请大神合并一下下。

现在，梯子暂时坏了。。。

**Comment by longitachi** [comment]
嗯，当时是准备写，不过后来写的时候涂鸦遇到了点问题解决不了。。后来就搁置了

**Comment by longitachi** [comment]
4.0.0版本已增强图片编辑功能，添加了涂鸦，完善了裁剪功能
