### ISSUE TITLE
请问能直接编辑沙盒的小视频吗？

### ISSUE THREAD

**Issue by tianguanghui** [longitachi/ZLPhotoBrowser#489]
我用了这个库，发出去视频之后，视频存在沙盒中，然后想直接调用编辑。

我看了源码，好像编辑视频的类只支持从相册直接选择的视频文件？

**Comment by longitachi** [comment]
原理上是可以的。只不过现在没支持直接调用编辑，这几天改下源码支持一下

**Comment by longitachi** [comment]
3.2.0已添加
