### ISSUE TITLE
我在控制器中有一个imageView,我要调用相册里面的图片放到imageView中展示，为什么不行呢

### ISSUE THREAD

**Issue by Mr-lins** [longitachi/ZLPhotoBrowser#49]
![0eff7daa-97ae-41dc-a6f9-36069e13727e](https://cloud.githubusercontent.com/assets/26573094/24996361/2d797cbe-2065-11e7-8a34-132ecb83a956.png)

**Comment by Mr-lins** [comment]
代码截图在上面 大神   能帮我解答下嘛？路过大大神也指导下。谢谢了

**Comment by longitachi** [comment]
你打断点调试一下，看获取到的图片有没有，然后你的 _PhotoImage 有添加到 self.view上面吗

**Comment by Mr-lins** [comment]
有加载View上面的，打断点也有走这里，数据源数组也有值。直接赋值就是展示不出来图片。NSLog Photolmage.image 为空！  是不能这样直接赋值嘛？

**Comment by longitachi** [comment]
_arrDataSource里面直接就是UIImage对象，不是名字

**Comment by Mr-lins** [comment]
_PhotoImage.image = [UIImage imageNamed:[NSString stringWithFormat:@"%@",_arrDataSources[0]]];     我这样转换是不对的嘛？ 有点懵逼了

**Comment by longitachi** [comment]
。。。。。。 我已经说的很清楚了，你自己看看，
“ _arrDataSource里面直接就是UIImage对象，不是名字”
所以你赋值为什么要用名字去赋值，直接等就好了

**Comment by Mr-lins** [comment]
_PhotoImage.image = selectPhotos; 程序就崩掉了哦
