### ISSUE TITLE
选择图片怎么弹出全屏 

### ISSUE THREAD

**Issue by loss99** [longitachi/ZLPhotoBrowser#491]
选择图片怎么弹出全屏

**Comment by sysworker** [comment]
是的，我发现并没有解决这个问题，还是存在
![image](https://user-images.githubusercontent.com/16078882/82517086-eaf68400-9b4e-11ea-9c7a-c8ab51d2a9a1.png)

**Comment by longitachi** [comment]
代码中已经设置了`nav.modalPresentationStyle = UIModalPresentationFullScreen`，iOS13下present应该是全屏的，这个截图看起来不像是这个框架的截图

**Comment by sysworker** [comment]
对不起、是我搞错了！这个是这个框架


在2020年06月04日 18:41，long 写道：

代码中已经设置了nav.modalPresentationStyle = UIModalPresentationFullScreen，iOS13下present应该是全屏的，这个截图看起来不像是这个框架的截图
