### ISSUE TITLE
调用 预览用户已选择的照片“原图”功能没有反应

### ISSUE THREAD

**Issue by fanlilinSaber** [longitachi/ZLPhotoBrowser#492]
/**
 提供 预览用户已选择的照片，并可以取消已选择的照片 （需先设置 sender 参数）

 @param photos 已选择的uiimage照片数组
 @param assets 已选择的phasset照片数组
 @param index 点击的照片索引
 @param isOriginal 是否为原图
 */
- (void)previewSelectedPhotos:(NSArray<UIImage *> *)photos assets:(NSArray<PHAsset *> *)assets index:(NSInteger)index isOriginal:(BOOL)isOriginal;

在调用这个方法后 可以操作原图的选项，但是返回的 isOriginal 一直都是NO，如果说这个预览不支持修改是否原图返回，可以把这个预览功能中的原图功能去掉

**Comment by longitachi** [comment]
好的，看到了，现在是一直返回的NO，我修改下
