### ISSUE TITLE
3.2.0混合选择时候没办法控制视频的个数吗？

### ISSUE THREAD

**Issue by deanli08** [longitachi/ZLPhotoBrowser#495]
#### 关于 Issue
升级到最新版本后无法控制可选择视频数量了。
需求：
我们现在用户可以上传三张图片，其中一个可以是视频。
也就是1个视频、2张图片。或者3个图片。
但是目前如果设置mutuallyExclusiveSelectInMix=NO话，可以选择多个视频。
如果设置为mutuallyExclusiveSelectInMix=YES ，maxSelectCount = 3的话，就只能选择视频就没办法选择图片了。
@longitachi 请求作者有办法吗？还是需要降级旧版本

**Comment by longitachi** [comment]
现在3.2.0版本比较像微信朋友圈那种选择，这个也是issue里提的比较多的，但是如果又要像微信这种，又要像之前一样控制混合选择时候视频最大最小数量就会特别麻烦，所以3.2.0版本选择了issue里提的较多的。
你这个需求可以先用上个版本，之后如果有空的话我这边会考虑能不能加上视频数量的控制
