### ISSUE TITLE
当图片选择超过100之后，数字会显示不全

### ISSUE THREAD

**Issue by liuzhao** [longitachi/ZLPhotoBrowser#496]
如题，当多选超过100之后，数字会显示不全。
另外如果选的图片较多时，比如100以上时，选择原图，会很容易造成内存溢出而崩溃（demo也是如此）。这个有解决办法吗？
<img width="249" alt="WX20200614-100135@2x" src="https://user-images.githubusercontent.com/1237508/84583026-6aae0080-ae26-11ea-86fd-fb1fa3afedcd.png">

**Comment by longitachi** [comment]
内存溢出崩溃，是选择了很多张，然后点确定之后崩溃了吗？
