### ISSUE TITLE
支持已选中的图片 标记吗？

### ISSUE THREAD

**Issue by devyunji** [longitachi/ZLPhotoBrowser#5]
选择完照片 回到主页面 显示已选择的照片 当我再次点相册的时候 能不能标识 已选中的图片？？？

**Comment by longitachi** [comment]
可以，不过你需要做一下修改。 首先把ZLPhotoActionSheet声明为类变量，之后在ZLPhotoActionSheet.m中找到如下方法，把第三~五行注释掉就好了
- (void)resetSubViewState
{
    self.hidden = NO;
    self.baseView.hidden = NO;
//    [self.arraySelectPhotos removeAllObjects];
//    [self.btnCamera setTitle:@"拍照" forState:UIControlStateNormal];
//    [self.btnCamera setTitleColor:[UIColor blackColor] forState:UIControlStateNormal];
    [self.collectionView setContentOffset:CGPointZero];
}

**Comment by longitachi** [comment]
把注释掉的三行删掉，换成这个。if (self.arraySelectPhotos.count == 0) {
        [self.btnCamera setTitle:@"拍照" forState:UIControlStateNormal];
        [self.btnCamera setTitleColor:[UIColor blackColor] forState:UIControlStateNormal];
    } else {
        [self.btnCamera setTitle:[NSString stringWithFormat:@"确定(%ld)", self.arraySelectPhotos.count] forState:UIControlStateNormal];
        [self.btnCamera setTitleColor:[UIColor colorWithRed:19/255.0 green:153/255.0 blue:231/255.0 alpha:1] forState:UIControlStateNormal];
    }

**Comment by devyunji** [comment]
谢谢大哥。万分感谢。用了这么多库。。只有您这个库不卡的。。。。

**Comment by devyunji** [comment]
还有一个问题 想咨询下大哥您。

就是 怎么实现  点击 选择照片 的时候 不要弹出 ZLPhotoActionSheet

我想直接进入相册?? 求帮助。谢谢大哥。

**Comment by longitachi** [comment]
在ZLPhotoActionSheet.m做如下修改：
- (void)showWithSender:(UIViewController *)sender animate:(BOOL)animate completion:(void (^)(NSArray<UIImage *> *))completion
{
    if (![self judgeIsHavePhotoAblumAuthority]) {
        
    }
    
    _handler = completion;
    _animate = animate;
    _sender  = sender;
    
//    [self loadPhotoFromAlbum];
//    [self show];
    [self btnPhotoLibrary_Click:nil];
}
即注释了两行代码，直接显示相册。 如果出现什么未知的bug，请在留言

**Comment by devyunji** [comment]
不好意思啊 大哥。周末休息 没及时回复。按照您的方法去搞。真的可以了。万分感谢。新年快乐。谢谢

**Comment by devyunji** [comment]
再次感谢 作者。谢谢
