### ISSUE TITLE
只能拍照一次，这里在很多场景使用是逻辑不通的

### ISSUE THREAD

**Issue by LightningTiger** [longitachi/ZLPhotoBrowser#50]
如果我希望发送现拍的n张照片（比如朋友圈这种类似功能），按照demo中选中“选择照片（预览）”就行不通；建议在ZLPhotoActionSheet还加一行“确定”做相关处理或者在选中的照片不为零时将“取消”按钮变成“拍照”入口

**Comment by longitachi** [comment]
已修改为可拍照多次，相册内部也增加了拍照按钮
