### ISSUE TITLE
mutuallyExclusiveSelectInMix 属性未能完全关闭混选

### ISSUE THREAD

**Issue by gdxud2016** [longitachi/ZLPhotoBrowser#501]
/**
混合选择时，照片和视频是否只能选择一种，默认NO
 e.g. 希望选择视频（最多1个）后不能选择其他图片，或者选择图片（最多9张）后不能选择视频
 设置如下参数即可
 allowSelectImage = YES
 allowSelectVideo = YES
 maxSelectCount = 9
 mutuallyExclusiveSelectInMix = YES
 */
@property (nonatomic, assign) BOOL mutuallyExclusiveSelectInMix;

如果这样设置以后，我先选一个视频之后，仍然可以选8张图片，如此就不符合关闭混选的效果

**Comment by longitachi** [comment]
`mutuallyExclusiveSelectInMix  = NO`的时候，视频类型cell上没有选择按钮，所以你描述的这个情况应该不存在。你可以试下demo，demo中把混合选择开关关闭即可。

**Comment by gdxud2016** [comment]
ZLPhotoConfiguration 这个类里能不能添加allowTakePhoto字段，ZLCustomCamera类的属性可以使用一个ZLPhotoConfiguration对象配置

**Comment by BestLeeSinCN** [comment]
mutuallyExclusiveSelectInMix = NO
allowSelectImage = NO
allowSelectVideo = YES
这个情况下, 点击预览中的视频,进入预览页面 然后滑动依旧可以看到图片并且选择

而且怎么禁用拍照按钮呢？预览的sheet会有拍照, 进入相册后依旧有拍照

**Comment by longitachi** [comment]
> ZLPhotoConfiguration 这个类里能不能添加allowTakePhoto字段，如果这样ZLCustomCamera类的属性可以使用一个ZLPhotoConfiguration对象配置

`ZLCustomCamera`中如果是从相册传递过去的话，直接根据`configuration.allowSelectImage`字段确定了，再加一个字段，感觉有点多余了

**Comment by longitachi** [comment]
> mutuallyExclusiveSelectInMix = NO
> allowSelectImage = NO
> allowSelectVideo = YES
> allowTakePhotoInLibrary = NO
> 这个情况下, 点击预览中的视频,进入预览页面 然后滑动依旧可以看到图片并且选择
> 
> 而且怎么禁用拍摄按钮呢？预览的sheet会有拍摄

1.依旧可以看到图片这个是bug，之后改下
2.预览禁用拍照按钮这个，这部分逻辑没有写，预览这个功能感觉用的人少，没太注意😅
