### ISSUE TITLE
requestAssetFileUrl获取的路径转成data为空

### ISSUE THREAD

**Issue by BestLeeSinCN** [longitachi/ZLPhotoBrowser#502]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by BestLeeSinCN** [comment]
NSData * data1 = [NSData dataWithContentsOfFile:filePath];

**Comment by BestLeeSinCN** [comment]
[ZLPhotoManager exportVideoForAsset:[assets lastObject] type:ZLExportVideoTypeMov complete:^(NSString * _Nonnull exportFilePath, NSError * _Nonnull error) {
            
            NSData * data = [NSData dataWithContentsOfFile:exportFilePath];
        }];

用这个方法才能成功

**Comment by longitachi** [comment]
获取路径这个方法本身没有问题的对吧

**Comment by BestLeeSinCN** [comment]
其实还是有点小问题, 因为我们app是做视频的. 当用户选择一个较大的视频的时候, exportVideoForAsset这个方法导出来路径很慢大概要十几秒到二十秒左右. 所以我觉得这个选择完视频或者image要不然就直接给data或者直接给能够直接转data的路径是最好的.

**Comment by longitachi** [comment]
我暂时没找到直接获取视频类型PHAsset的data方法。
```
[[PHCachingImageManager defaultManager] requestPlayerItemForVideo:asset options:option resultHandler:^(AVPlayerItem * _Nullable playerItem, NSDictionary * _Nullable info) {

}];
```
系统提供关于video相关的并没有直接能拿到data的

**Comment by longitachi** [comment]
我暂时没找到直接获取视频类型PHAsset的data方法。
```
[[PHCachingImageManager defaultManager] requestPlayerItemForVideo:asset options:option resultHandler:^(AVPlayerItem * _Nullable playerItem, NSDictionary * _Nullable info) {

}];
```
系统提供关于video相关的并没有直接能拿到data的
