### ISSUE TITLE
iPad 分屏适配问题

### ISSUE THREAD

**Issue by xiaoojun** [longitachi/ZLPhotoBrowser#504]
版本 3.2.0
问题：iPad使用分屏功能时，相册列表底部栏显示不全，大佬空了可以适配下吗？应该是UIscreen和UIWindow尺寸问题

**Comment by demoker** [comment]
同上

**Comment by demoker** [comment]
同上 @longitachi

**Comment by longitachi** [comment]
看下最新版本有没有这个问题了，我在模拟器上试的没什么问题
![simulator_screenshot_B84429DF-55A6-4B13-A7B4-CA149000F31F](https://user-images.githubusercontent.com/11711768/93052078-140bc900-f698-11ea-867b-85c5c156064c.png)
