### ISSUE TITLE
View controller-based status bar appearance 置为YES的情况下怎么修改statusBar的颜色

### ISSUE THREAD

**Issue by friendsheeps** [longitachi/ZLPhotoBrowser#505]
版本3.2.0，

因为项目已经成熟，info.plist里将View controller-based status bar appearance置为YES，statusBar交给不同VC处理，如果设置为NO对项目影响较大，怎么在不改变设置的情况下单独把ZLAlbumListController的statusBarStyle设置为UIStatusBarStyleDefault？

**Comment by longitachi** [comment]
你是想要把选择照片界面的状态栏显示成黑色的？

**Comment by longitachi** [comment]
在`ZLImageNavigationController`里面加下面代码即可，下个版本我更新下
```
@implementation ZLImageNavigationController

...

- (UIStatusBarStyle)preferredStatusBarStyle
{
    return self.configuration.statusBarStyle;
}

@end
```
