### ISSUE TITLE
编辑视频功能能否自定义剪裁视频的时长

### ISSUE THREAD

**Issue by summer87279149** [longitachi/ZLPhotoBrowser#506]
![image](https://user-images.githubusercontent.com/17060521/90467577-19ccc800-e147-11ea-8a6b-95934bb6770f.png)
当前maxEditVideoTime只表示"所选视频时长必须大于等于该值才允许进行编辑",而无法自由设置裁剪时间,并且文档释义也有歧义

**Comment by longitachi** [comment]
这个问题将在会在下个版本解决

**Comment by longitachi** [comment]
4.0.1版本已优化视频编辑功能，`maxEditVideoTime`只限制最大编辑时间，小于该时间的视频也可编辑
