### ISSUE TITLE
我发现一个问题  当使用了FDFullscreenPopGesture这个库时  页面会显示导航栏

### ISSUE THREAD

**Issue by Mikansan** [longitachi/ZLPhotoBrowser#510]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by Mikansan** [comment]
- 
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-09 at 09 29 54](https://user-images.githubusercontent.com/33869137/92549776-ac670f80-f28c-11ea-9922-ecb08faed515.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-09 at 09 29 51](https://user-images.githubusercontent.com/33869137/92549785-b12bc380-f28c-11ea-92da-a0f355dbe694.png)

**Comment by longitachi** [comment]
下个版本会解决。 暂时可在`ZLThumbnailViewController`的`viewWillAppear`方法中添加`self.navigationController?.navigationBar.isHidden = true`解决

**Comment by Mikansan** [comment]
更新版本能否通知一下  我的app都有用到这个库

在 2020年9月9日，下午2:09，long <notifications@github.com> 写道：

﻿
下个版本会解决。 暂时可在ZLThumbnailViewController的viewWillAppear方法中添加self.navigationController?.navigationBar.isHidden = true解决

**Comment by longitachi** [comment]
`4.0.4`版本已解决该问题

**Comment by Mikansan** [comment]
> `4.0.4`版本已解决该问题

依然没有解决。。
