### ISSUE TITLE
关于 #413 自定义拍照界面 上面有一截黑色区域  问题仍然没有解决  

### ISSUE THREAD

**Issue by keepyounger** [longitachi/ZLPhotoBrowser#511]
关于 #413 问题仍然没有解决 Demo也有同样的问题
iOS 13.5 iPhone 7p
ZLPhotoBrowser 4.0.2
![1599619294805](https://user-images.githubusercontent.com/6264752/92548314-4462fa00-f289-11ea-8edb-69200a381d8f.jpg)

**Comment by longitachi** [comment]
这个不是bug，你用微信应该也是一样的吧，图片按照`scaleAspectFit`进行显示，就会这样，因为相机拍照的比例和屏幕比例不一样

**Comment by keepyounger** [comment]
微信不是这样的 下面是微信的页面
![WechatIMG312](https://user-images.githubusercontent.com/6264752/93070886-02371f80-f6b2-11ea-9b2b-32209df085a9.jpeg)

**Comment by longitachi** [comment]
emm，我理解错了，这个问题我改下

**Comment by longitachi** [comment]
更新呢`4.0.5`版本即可
