### ISSUE TITLE
只支持选择照片，还能长按拍摄视频

### ISSUE THREAD

**Issue by nightlight89** [longitachi/ZLPhotoBrowser#512]
#511 ## 关于 Issue
1. 当前所使用的cocoapods版本 
    4.0.2
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）
    就是在设置只能选择照片，支持相册内拍摄照片；这时候拍摄照片时还能长按拍摄视频，这时候就不能支持长按拍摄视频了应该只可以拍摄照片才对

**Comment by longitachi** [comment]
可先将该参数`allowRecordVideo`设置为`false`。后续会进行优化

**Comment by longitachi** [comment]
`4.0.4`版本已针对该问题进行优化
