### ISSUE TITLE
编辑-调整图片大小后 旋转方向未记录之前选中的大小。

### ISSUE THREAD

**Issue by longjianjiang** [longitachi/ZLPhotoBrowser#515]
如标题～

**Comment by longitachi** [comment]
issue描述的功能最新代码均已实现，将随`4.0.3`发布

**Comment by longjianjiang** [comment]
是否可以添加一些固定的长宽比，这样可以快速点击。

**Comment by longjianjiang** [comment]
```swift
    func getResizeFrame(whScale: CGFloat) -> CGRect {
        var adjustResizeW: CGFloat = 0
        var adjustResizeH: CGFloat = 0
        
        if whScale >= 1 {
            adjustResizeW = maxClipFrame.width
            adjustResizeH = adjustResizeW / whScale
            if adjustResizeH > maxClipFrame.height {
                adjustResizeH = maxClipFrame.height
                adjustResizeW = maxClipFrame.height * whScale
            }
        } else {
            adjustResizeH = maxClipFrame.height
            adjustResizeW = adjustResizeH * whScale
            if adjustResizeW > maxClipFrame.width {
                adjustResizeW = maxClipFrame.width
                adjustResizeH = adjustResizeW / whScale
            }
        }
        let adjustResizeX = maxClipFrame.origin.x + (maxClipFrame.width - adjustResizeW) * 0.5
        let adjustResizeY = maxClipFrame.origin.y + (maxClipFrame.height - adjustResizeH) * 0.5
        
        return CGRect(x: adjustResizeX, y: adjustResizeY, width: adjustResizeW, height: adjustResizeH)
    }
```

```swift
let three2FourRect = getResizeFrame(whScale: 9.0/16.0)
changeClipBoxFrame(newFrame: three2FourRect)
```

我加了一个方法，试了1:1, 3:4, 4:3 都是正常的，使用9:16 的时候，截出来的图宽度未全屏。

**Comment by longitachi** [comment]
图片宽度未全屏是啥意思，没明白。裁剪宽高比这个功能后边看下，有空了会加上的

**Comment by longjianjiang** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-09-15 at 12 04 13](https://user-images.githubusercontent.com/15277239/93164216-9c977180-f74b-11ea-99cb-914cb0c0407f.png)

还有发现一个问题，我使用`ZLPhotoPreviewViewController`的时候，尝试将phasset获取到的image进行按`3/4`的形式进行显示，效果和上图一样，图变小了，宽度没有全屏。处理成`3/4`的代码如下，我写了个demo固定的imageView大小是正常的。

```swift
extension UIImage {
     
    //将图片裁剪成指定比例（多余部分自动删除）
    func crop(ratio: CGFloat) -> UIImage {
        //计算最终尺寸
        var newSize:CGSize!
        if size.width/size.height > ratio {
            newSize = CGSize(width: size.height * ratio, height: size.height)
        }else{
            newSize = CGSize(width: size.width, height: size.width / ratio)
        }
     
        ////图片绘制区域
        var rect = CGRect.zero
        rect.size.width  = size.width
        rect.size.height = size.height
        rect.origin.x    = (newSize.width - size.width ) / 2.0
        rect.origin.y    = (newSize.height - size.height ) / 2.0
         
        //绘制并获取最终图片
        UIGraphicsBeginImageContext(newSize)
        draw(in: rect)
        let scaledImage = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
         
        return scaledImage!
    }
}
```

**Comment by longjianjiang** [comment]
我刚试了下，一张比较小的图，现在用`ZLPhotoPreviewViewController` 打开就是没有全屏展示的。
![small](https://user-images.githubusercontent.com/15277239/93201975-82c65080-f784-11ea-93d2-c70820b10a13.jpg)

**Comment by longitachi** [comment]
现在布局时候是采用了`min(image.size.width, cell.width)`，具体点这里
https://github.com/longitachi/ZLPhotoBrowser/blob/3f3155f050f5ad8d2b3999d0e0dabbe2f6ad3788/Sources/General/ZLPhotoPreviewCell.swift#L769-L808
我看了下微信，貌似都是撑开了，下次发版时候我修改下

**Comment by longjianjiang** [comment]
![longImage](https://user-images.githubusercontent.com/15277239/93342112-84197b00-f861-11ea-98c8-1888a84358a6.jpg)

发现一个问题，这种图裁剪的时候，图片是模糊的。

**Comment by longitachi** [comment]
好的，超长图模糊这个问题会在下个版本一起处理下

**Comment by longjianjiang** [comment]
exceededMaxSelectCount 选中图片超过最大选中后，这个提示显示好想没有。

**Comment by longitachi** [comment]
这个最新代码已经添加了，这两天把最近的`issue`处理下，明天发布`4.0.5`版本就好了

**Comment by longjianjiang** [comment]
刚拉了最新的代码：
1. exceededMaxSelectCount 选中图片超过最大选中后，这个提示显示还是没有；
2. 图片现在全屏展示了；
3. 长图正常了；

**Comment by longitachi** [comment]
第一个：选中最大数量后，其他cell会自动变成不可选（建议先将`showInvalidMask`设为`true`)
第三个：你自己修改了部分代码，我也不太清楚你咋改的，你可以自己先调试下

**Comment by longjianjiang** [comment]
好的，刚看了下config里面好想没有提供过滤视频格式的选项，是不是自带相册就不允许将不支持的视频存储？

**Comment by longitachi** [comment]
https://developer.apple.com/documentation/avfoundation/avfiletype
应该还有一个 `.3GPP2`，框架选择了常用的两个

**Comment by longjianjiang** [comment]
今天自己测试的发现，设置选中数量为1，同时不显示右边的那个⭕️，双击偶现右边⭕️被选中的效果。我简单看了下代码，好想没看到双击的手势。

**Comment by longitachi** [comment]
> 今天自己测试的发现，设置选中数量为1，同时不显示右边的那个⭕️，双击偶现右边⭕️被选中的效果。我简单看了下代码，好想没看到双击的手势。

测了下没复现这个问题。应该不会出现才对，不显示导航右边选择按钮时候，按钮处于隐藏状态。
