### ISSUE TITLE
git图片只有一帧会崩溃

### ISSUE THREAD

**Issue by she1323** [longitachi/ZLPhotoBrowser#516]
gifProperties uninitialized
<img width="737" alt="截屏2020-09-14 下午6 07 22" src="https://user-images.githubusercontent.com/43979259/93073234-2a744d80-f6b5-11ea-98cb-60482bdd06db.png">

**Comment by longitachi** [comment]
话说这个只有1帧的图片，应该不是GIF了吧- -，如果系统判定为GIF图的话，能帮看下`let count = CGImageSourceGetCount(source)`这个`count`是多少吗，是1吗？

**Comment by she1323** [comment]
count == 2, 但是gifPropertie确实初始化失败了，所以我把gifPropertie 定义成了Optional类型，暂时没有出现什么问题
<img width="622" alt="截屏2020-09-16 下午4 15 10" src="https://user-images.githubusercontent.com/43979259/93310818-d645a680-f837-11ea-8bae-32edca1e2127.png">
