### ISSUE TITLE
iOS14,相册权限有变化

### ISSUE THREAD

**Issue by she1323** [longitachi/ZLPhotoBrowser#517]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
变化这个是系统层级的，跟框架没什么大的关系
ps: Xcode GM版本的模拟器有bug，如果选择了`limit`权限，会出现没获得读取权限的照片显示空白的问题。真机没啥

**Comment by she1323** [comment]
当重新打开app,每次重新调用相册时，系统会提示用户是否给其他未授权的图片授权，如果产生了授权行为，相册列表不会发生刷新，需要退出相册重进才会获取到新的图片

**Comment by she1323** [comment]
如果我在重新授权的时候把以前授权的图片取消，相册列表也不会发生刷新，所以，会有用户看得到当前图片但是无法获取的结果

**Comment by longitachi** [comment]
@she1323 刚看了下demo，我添加了`Prevent limited photos access alert`这个。。下个版本会改下。应该这周日会发一版，把已知问题都改一下
