### ISSUE TITLE
4.0.4版本设置最大视频选择时长，非混合模式下视频预览页面出现HUD超时阻塞

### ISSUE THREAD

**Issue by MFunZero** [longitachi/ZLPhotoBrowser#518]
如题，超过视频最大时长出现HUD 超长显示

**Comment by longitachi** [comment]
这个视频是在`iCloud`上吗，时长大约是多少，有没有超时的效果图，方便上传一下吗

**Comment by MFunZero** [comment]
不是iCloud的 
![IMG_2439](https://user-images.githubusercontent.com/13399486/93551177-d8c31000-f99f-11ea-8e7b-ef1494098e3d.PNG)
debug到
nav.selectImageBlock = { [weak self, weak nav] in
            self?.isSelectOriginal = nav?.isSelectedOriginal ?? false
            self?.arrSelectedModels.removeAll()
            self?.arrSelectedModels.append(contentsOf: nav?.arrSelectedModels ?? [])
            // 如果所选视频时超过最大时长，接下来会出现HUD显示过长时间
                self?.requestSelectPhoto(viewController: nav)
        }

**Comment by longitachi** [comment]
好的，这周末发版会解决下该问题

**Comment by longitachi** [comment]
更新`4.0.5`版本即可
