### ISSUE TITLE
帮忙看一下问题

### ISSUE THREAD

**Issue by ChengQiRen** [longitachi/ZLPhotoBrowser#52]
你好,最近集成了您的框架. 但是选择一张图片可以,但是多张为什么不行了呢?,一直显示正在处理,您的demo里面也是这种情况.

**Comment by longitachi** [comment]
好的，我晚上回去看一下

**Comment by longitachi** [comment]
可以了，请更新一下。这次改版忽视了一个地方，谢谢提出
