### ISSUE TITLE
选择图片后是否可以不跳转ZLPhotoPreviewViewController？（问题询问，非Issue。）

### ISSUE THREAD

**Issue by HelloHchen** [longitachi/ZLPhotoBrowser#520]
进入选择，点击后是否可以不进入预览ZLPhotoPreviewViewController二次确认？

**Comment by longitachi** [comment]
是小图界面点击后直接选择，不进预览大图界面的意思吗？（现在不支持这样选择的

**Comment by longitachi** [comment]
@HelloHchen 最新代码新增了几个参数，可控制是否允许预览大图，可先手动导入使用

**Comment by HelloHchen** [comment]
好的吧，谢谢你。直接拖的话那我就可以更改源代码。也能实现^_^
