### ISSUE TITLE
选中多张照片后，点击照片取消选中的所有照片，返回的images 和assets 数组还保留一个内容

### ISSUE THREAD

**Issue by 19chengguo** [longitachi/ZLPhotoBrowser#522]
是在 ZLPhotoPreviewSheet 视图中 里面的右上角 取消选择

**Comment by longitachi** [comment]
这个就是这样子的逻辑，可参考微信，没有选中任何照片时候，点击确定会选中当前的一张照片

**Comment by 19chengguo** [comment]
> 这个就是这样子的逻辑，可参考微信，没有选中任何照片时候，点击确定会选中当前的一张照片

噢噢，我明白作者大大的意思了，确实是如此。假设如实现朋友圈的逻辑，有提供这方面api吗？

**Comment by longitachi** [comment]
下个版本就可以了，使用`ZLPhotoPreviewSheet`的`previewAssets(sender:assets:index:isOriginal:showBottomViewAndSelectBtn:)`方法，传入已选择的asset，可进行删除操作

**Comment by 19chengguo** [comment]
您好，前辈，我看到你更新了 “新增是否允许预览大图功能; 新增是否允许预览已选择照片功能”，请问这个功能点如何体现呢？我测试了demo发现自己找不出如何 “预览”，我仅发现了点击取消图片的时候，图片会删除了呢，不会保留一个。
麻烦前辈能否解答一下这个功能点场景

**Comment by 19chengguo** [comment]
如果说差别点话，选择照片下角那边多了 预览。

**Comment by longitachi** [comment]
```swift
/// 是否允许预览已选择的照片 (小图界面预览按钮)
    @objc public var allowPreviewSelectedPhotos = true
    
/// 是否允许进入预览大图界面 (即点击小图后是否允许进入大图界面)
@objc public var allowPreviewPhotos = true
```
`allowPreviewSelectedPhotos` 控制小图界面左下角是否显示预览按钮
`allowPreviewPhotos` 控制点击小图后是否允许进入大图界面
每个参数上面都有注释，可以仔细看下

至于你后面说的`我测试了demo发现自己找不出如何 “预览”，我仅发现了点击取消图片的时候，图片会删除了呢，不会保留一个`，我没明白你具体是什么意思

**Comment by 19chengguo** [comment]
> ```swift
> /// 是否允许预览已选择的照片 (小图界面预览按钮)
> @objc public var allowPreviewSelectedPhotos = true
>     
> /// 是否允许进入预览大图界面 (即点击小图后是否允许进入大图界面)
> @objc public var allowPreviewPhotos = true
> ```
> 
> `allowPreviewSelectedPhotos` 控制小图界面左下角是否显示预览按钮
> `allowPreviewPhotos` 控制点击小图后是否允许进入大图界面
> 每个参数上面都有注释，可以仔细看下
> 
> 至于你后面说的`我测试了demo发现自己找不出如何 “预览”，我仅发现了点击取消图片的时候，图片会删除了呢，不会保留一个`，我没明白你具体是什么意思，是在哪个界面点击取消图片删除了一个，没有保留一个？还有你想要什么样的效果？

抱歉前辈我没有表达好意思，就是`点击小图预览的时候，进入预览页面右上角不是有个取消的吗？之前是取消所有选中，会自动保留一个。现改为所有都取消。`。我以为前辈会跟朋友圈一样，会提供一个预览页面，让我们开发者添加自己需求，例如删除、上传。

**Comment by 19chengguo** [comment]
```
/// 是否允许预览已选择的照片 (小图界面预览按钮)
@objc public var allowPreviewSelectedPhotos = true
    
/// 是否允许进入预览大图界面 (即点击小图后是否允许进入大图界面)
@objc public var allowPreviewPhotos = true
```
后辈不才，还是无法模拟出实际使用它的场景

**Comment by longitachi** [comment]
`previewAssets(sender:assets:index:isOriginal:showBottomViewAndSelectBtn:)`这个方法你可以理解为简单的图片浏览器，可以在里面浏览你已经选择的照片。 右上角的按钮可以对你已选择的照片进行取消选择，你如果都取消选择了，点击确定后自然全部都取消了。
没有像朋友圈那样直接删除的功能，至于上传，这个属于你们自己的业务了。

```swift
/// 是否允许预览已选择的照片 (即是否显示小图界面左下角预览按钮)
@objc public var allowPreviewSelectedPhotos = true
    
/// 是否允许进入预览大图界面 (即点击小图后是否允许进入大图界面)
@objc public var allowPreviewPhotos = true
```
这两个参数用不上就没必要纠结了

**Comment by 19chengguo** [comment]
> `previewAssets(sender:assets:index:isOriginal:showBottomViewAndSelectBtn:)`这个方法你可以理解为简单的图片浏览器，可以在里面浏览你已经选择的照片。 右上角的按钮可以对你已选择的照片进行取消选择，你如果都取消选择了，点击确定后自然全部都取消了。
> 没有像朋友圈那样直接删除的功能，至于上传，这个属于你们自己的业务了。
> 
> ```swift
> /// 是否允许预览已选择的照片 (即是否显示小图界面左下角预览按钮)
> @objc public var allowPreviewSelectedPhotos = true
>     
> /// 是否允许进入预览大图界面 (即点击小图后是否允许进入大图界面)
> @objc public var allowPreviewPhotos = true
> ```
> 
> 这两个参数用不上就没必要纠结了

谢谢前辈解答，就是后辈希望能提供api可以让我们自定义修改 预览修改 的方式。以上就这些疑问。
