### ISSUE TITLE
iOS14  图片预览时不显示图片，OC项目如何升级库

### ISSUE THREAD

**Issue by gdxud2016** [longitachi/ZLPhotoBrowser#523]
iOS 14 图片预览黑屏，不显示图片

**Comment by longitachi** [comment]
我这边创建了个oc项目，pod集成后显示正常。没有什么需要做特殊处理的。具体使用看这个[Wiki](https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(objc))

**Comment by gdxud2016** [comment]
我的用的是ZLPhotoBrowser_objc 项目了，可是预览图片时还是黑屏，选择图片功能正常，截图如下
![IMG_0275](https://user-images.githubusercontent.com/20318631/94355418-7b714200-00b6-11eb-92a2-54b4bdf3d534.png)

**Comment by longitachi** [comment]
那是`SDWebImage`的问题，升级最新版本就行了

**Comment by gdxud2016** [comment]
SDWebImage 升级到最新的5.9.1版本，仍然黑屏

**Comment by gdxud2016** [comment]
问题解决了，升级库之后，把App删除重装就解决了，👍👍👍
