### ISSUE TITLE
Swift Package Manager中如何添加bundle资源

### ISSUE THREAD

**Issue by longitachi** [longitachi/ZLPhotoBrowser#525]
求一个完善 `Package.swift` 写法的 `pr`，解决 `SPM` 安装后无法读取资源文件的问题

**Comment by jackiehu** [comment]
我也发现你这个读取多语种的问题了，可以参考我的这两个类
https://github.com/jackiehu/SwiftBrick/blob/master/Package.swift
https://github.com/jackiehu/SwiftBrick/blob/master/Sources/SwiftBrick/Util/Loader.swift
我试了试这样支持图片资源库还有bundle库

给Bundle扩展
`
extension Bundle {
    
    #if !ENABLE_SPM
    private class _BundleClass { }
    #endif
    
    static var current: Bundle {
        #if ENABLE_SPM
        return Bundle.module
        #else
        return Bundle(for: _BundleClass.self)
        #endif
    }
}
`
读取
`
public struct L{
    
    static var bundle: Bundle = {
        let path = Bundle.current.path(forResource: "SwiftBrick", ofType: "bundle", inDirectory: nil)
        let bundle = Bundle(path: path ?? "")
        return bundle ?? Bundle.current
    }()
}
`
这样可以适配pod spm以及本地调试，全适配

**Comment by jackiehu** [comment]
https://github.com/jackiehu/SwiftBrick/blob/master/Package.swift
https://github.com/jackiehu/SwiftBrick/blob/master/Sources/SwiftBrick/Util/Loader.swift
可以参考下，这个库可以同时支持本地调试，pod安装，SwiftPM安装的时候读取资源文件

**Comment by longitachi** [comment]
行，我参考下
