### ISSUE TITLE
iOS2.2 ZLThumbnailViewController 崩溃，现在已经更新到ZLPhotoBrowser的4.0.7版本了

### ISSUE THREAD

**Issue by sunWaterMood** [longitachi/ZLPhotoBrowser#526]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [x] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 当前所使用的cocoapods版本
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）

**Comment by longitachi** [comment]
我这边测试demo，和创建项目集成后没问题，可以的话请附上截图和`ZLPhotoConfiguration`配置代码

**Comment by sunWaterMood** [comment]
` ZLPhotoPreviewSheet *ac = [[ZLPhotoPreviewSheet alloc]initWithSelectedAssets:[NSArray array]];
               // 相册参数配置，configuration有默认值，可直接使用并对其属性进行修改
                ZLPhotoConfiguration *config = [[ZLPhotoConfiguration alloc]init];
                config.maxSelectCount = 1;
                config.maxPreviewCount = 10;
                // 选择回调
                [ac setSelectImageBlock:^(NSArray<UIImage *> * _Nonnull images, NSArray<PHAsset *> * _Nonnull assets, BOOL isOriginal) {
                   
                }];
                // 调用相册
                [ac showPhotoLibraryWithSender:self];`

**Comment by sunWaterMood** [comment]
你看下，我在gitHub回复你了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "longitachi/ZLPhotoBrowser"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月29日(星期二) 下午2:49
收件人:&nbsp;"longitachi/ZLPhotoBrowser"<ZLPhotoBrowser@noreply.github.com&gt;;
抄送:&nbsp;"阳光下你的眼眸"<1095143828@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [longitachi/ZLPhotoBrowser] iOS2.2 ZLThumbnailViewController 崩溃，现在已经更新到ZLPhotoBrowser的4.0.7版本了 (#526)





 
我这边测试demo，和创建项目集成后没问题，可以的话请附上截图和ZLPhotoConfiguration配置代码

**Comment by longitachi** [comment]
你可以下载demo看有没有问题，没有问题的话你自己debug下，提供下crash截图，在哪个地方crash了之类的，目前你给的信息看不出来什么问题。
