### ISSUE TITLE
xcode12,ios14 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by arccos2002** [longitachi/ZLPhotoBrowser#527]
'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.
![image](https://user-images.githubusercontent.com/3265954/94534625-2f1f3100-0273-11eb-99c6-0e1dc677c16b.png)

**Comment by longitachi** [comment]
Setting `Require Only App-Extension_safe API` to `No` inside your Pods project for the `ZLPhotoBrowser` target.
