### ISSUE TITLE
previewAssets函数中的选中phasset问题

### ISSUE THREAD

**Issue by KerwinCheung** [longitachi/ZLPhotoBrowser#528]
version4.0.7里,当传入数组有相同的资源时,逻辑存在重复选中和删除的问题.
简单查看了一下在选中和删除函数中使用了遍历查找的逻辑,会存在多个匹配的情况,本人只是使用浏览图组的功能,简单粗暴的修改了一下直接用index来操作,作者有空的话建议整体逻辑整理一下再修改一下.

**Comment by longitachi** [comment]
好的，下个版本会做一下去重
