### ISSUE TITLE
点击自定义相机报主线程警告（iPhone Xs Max 12.0.1）

### ISSUE THREAD

**Issue by devchena** [longitachi/ZLPhotoBrowser#529]
<img width="757" alt="截屏2020-10-09 下午2 00 19" src="https://user-images.githubusercontent.com/15935903/95548516-d6505500-0a37-11eb-8bab-1281d6ee5f04.png">

**Comment by longitachi** [comment]
我看了下demo中是不会报这个警告的，你可以检查下你调用的地方是不是在子线程中调用的

**Comment by devchena** [comment]
我就是用demo跑的，是不是和设备有关，因为我用iPhone Xs Max 12.0.1就这样，用iPhone 7 14.0就没线程警告
