### ISSUE TITLE
`showSelectedPhotoPreview `属性设置为NO导致崩溃

### ISSUE THREAD

**Issue by Lazyloadingg** [longitachi/ZLPhotoBrowser#532]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 请附上当前所使用的cocoapods版本
   cocoapods版本: 1.9.3
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）
   crash截图:
<img width="966" alt="截屏2020-10-10 下午7 55 26" src="https://user-images.githubusercontent.com/18608397/95654434-8efabf00-0b32-11eb-878d-40eb5de54a7d.png">

3. `ZLPhotoConfiguration`配置代码
   ```
    ZLPhotoConfiguration * config = [ZLPhotoConfiguration default];
    config.maxPreviewCount = 10;
    config.maxSelectCount = 1;
    config.allowSelectVideo = NO;
    config.allowTakePhotoInLibrary = NO;
    config.showSelectedPhotoPreview = NO;
   ```
4. 手机：6S ,系统：iOS13

**Comment by longitachi** [comment]
感谢提出的bug，下个版本会解决这个问题
