### ISSUE TITLE
oc版本

### ISSUE THREAD

**Issue by ZClee128** [longitachi/ZLPhotoBrowser#533]
升级到swift版本，oc版本怎么使用呢

**Comment by ZClee128** [comment]
oc项目怎么用这个swift版本

**Comment by longitachi** [comment]
点这个链接：https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(objc)

ps: Readme中有提到详细使用方法可查看Wiki

**Comment by ZClee128** [comment]
是这样的，但是找不#import <ZLPhotoBrowser/ZLPhotoBrowser-Swift.h>这个

**Comment by ZClee128** [comment]
知道问题了因为需要加use_frameworks!这个，但是腾讯有个框架不允许加这个，所以无缘你这个库了吗？

**Comment by longitachi** [comment]
是哪个框架不允许加这个？发下链接看看

**Comment by ZClee128** [comment]
TXIMSDK_TUIKit_iOS这个
use_modular_headers!
inhibit_all_warnings!
他是需要加这两个
但是要注释use_frameworks！这个

**Comment by longitachi** [comment]
#588
