### ISSUE TITLE
有个问题想请教一下

### ISSUE THREAD

**Issue by wdq123550** [longitachi/ZLPhotoBrowser#535]
这是图片/视频选择框架？我能不能当成图片/视频浏览器来用？有专门的只查看图片和视频的功能吗？

**Comment by longitachi** [comment]
现在只能浏览`PHAsset`，不能浏览本地及网络图片/视频

**Comment by longitachi** [comment]
4.0.9 版本可预览PHAsset、本地图片/视频、网络图片/视频。
