### ISSUE TITLE
单选图片后直接到裁剪页面

### ISSUE THREAD

**Issue by millsZCJ** [longitachi/ZLPhotoBrowser#536]
你好，请问现在有配置能单选图片后直接进入到裁剪页面吗？点击取消后能返回到小图选择页面吗？

**Comment by longitachi** [comment]
```swift
/// 在小图界面选择 图片/视频 后直接进入编辑界面
    /// - discussion: 编辑图片 仅在allowEditImage为YES 且 maxSelectCount为1 的情况下，置为YES有效，
    /// 编辑视频则在 allowEditVideo为YES 且 maxSelectCount为1情况下，置为YES有效
    @objc public var editAfterSelectThumbnailImage = false
```
`ZLPhotoConfiguration` 中每个参数都有详细注释，可仔细查看参数定义

**Comment by LoadingMx** [comment]
> ```swift
> /// 在小图界面选择 图片/视频 后直接进入编辑界面
> /// - discussion: 编辑图片 仅在allowEditImage为YES 且 maxSelectCount为1 的情况下，置为YES有效，
> /// 编辑视频则在 allowEditVideo为YES 且 maxSelectCount为1情况下，置为YES有效
> @objc public var editAfterSelectThumbnailImage = false
> ```
> 
> `ZLPhotoConfiguration` 中每个参数都有详细注释，可仔细查看参数定义

用上边的方法单选图片后跳转到 'ZLEditImageViewController' 控制器，是否可以直接跳转到 'ZLClipImageViewController' 控制器、显示选择裁剪框？

**Comment by longitachi** [comment]
当前版本不可以，下个版本会添加一个`showClipDirectlyIfOnlyHasClipTool`参数来支持直接跳转裁剪界面

**Comment by longitachi** [comment]
4.0.9版本已支持 该功能

**Comment by linsyorozuya** [comment]
这个场景其实是单选列表中的小图后，不跳转预览页面直接进入编辑页面。现在 showClipDirectlyIfOnlyHasClipTool 还是要跳转的预览页面再点编辑。

**Comment by longitachi** [comment]
@linsyorozuya  可以看下这两个参数`editAfterSelectThumbnailImage` 和 `showClipDirectlyIfOnlyHasClipTool` 定义，应该能满足你的需求

**Comment by JanzTam** [comment]
@longitachi 请问支持选择完图片，跳到编辑图片页，默认选中一个 tool 吗？

例如我当前支持这些tools【.clip, .mosaic, .filter, .adjust, .textSticker,】，可以有个属性设置默认跳到mosaic 或者 filter 的编辑器。然后点击左下角的关闭，可以返回 ZLEditImageViewController

**Comment by longitachi** [comment]
@JanzTam 不支持设置默认编辑工具

**Comment by ZClee128** [comment]
> @linsyorozuya 可以看下这两个参数`editAfterSelectThumbnailImage` 和 `showClipDirectlyIfOnlyHasClipTool` 定义，应该能满足你的需求

满足不了，应该是点击小图直接进入裁剪页面

**Comment by ZClee128** [comment]
错怪作者了，确实可以满足要求，
![image](https://github.com/user-attachments/assets/7e1fb072-2627-4b7a-bb68-787f48bf260b)
guang关键代码
