### ISSUE TITLE
查看大图的时候  图片 不显示  视频的时候是可以的，怎么解决

### ISSUE THREAD

**Issue by 77521** [longitachi/ZLPhotoBrowser#537]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 请附上以下信息
   cocoapods版本: 
   设备:
   系统版本:
   Xcode版本:

2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）
   问题截图:

3. `ZLPhotoConfiguration` 配置代码

   ```
   paste your code
   ```

**Comment by 77521** [comment]
![WechatIMG7](https://user-images.githubusercontent.com/18029525/96325864-58570400-105e-11eb-89c9-fe1c826851fc.png)

**Comment by longitachi** [comment]
请完善issue中所需信息。
看界面样式，你应该用的是oc版本，oc版本的话是`SDwebImage`的bug，升级下`SDWebimage`就行了
