### ISSUE TITLE
iCloud视频有时候需要点两次确定选图界面才消失

### ISSUE THREAD

**Issue by woheduole** [longitachi/ZLPhotoBrowser#538]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 请附上以下信息
   cocoapods版本:  4.0.8
   设备:   iPone 8
   系统版本:  iPhone OS 14.0.1
   Xcode版本:  12.0.1

2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）
   问题截图:

   选中iCloud视频之后点确定会出现正在处理的提示，等到视频下载完成这时候正在处理的弹框会消失，但是选图界面没有消失，这时候如果再点击一次确定，选图界面才会消失掉。demo和我自己通过cocoapods导入的版本都有这个问题。

3. `ZLPhotoConfiguration` 配置代码

   ```
   paste your code
   ```

**Comment by longitachi** [comment]
进入iCloud视频，然后点击确定选中吗？我这边测试demo不会这个问题，倒是之前iCloud视频处理播放没有处理好，没加载完成时候按钮图片应该置灰的。
