### ISSUE TITLE
使用cocoapod集成，多选照片报错

### ISSUE THREAD

**Issue by liaohui2015** [longitachi/ZLPhotoBrowser#54]
使用cocoapod集成，多选照片报错（PS：手动集成就没有问题），报错如下：
[Generic] Creating an image format with an unknown type is error.
希望能够解决。

**Comment by yangzheng006** [comment]
我也出现这种问题了大哥你是怎么解决的

**Comment by longitachi** [comment]
等明天我cocoapods更新下版本就好了
