### ISSUE TITLE
 iOS 13.6.1   iphone se  、 iphone6 拍照和拍视频的时候顶部20左右的黑屏

### ISSUE THREAD

**Issue by cuixiaocun** [longitachi/ZLPhotoBrowser#540]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作

#### 关于 Issue
1. 请附上以下信息
   设备: iOS 13.6.1   iphone se  、 iphone6 拍照和拍视频的时候顶部20左右的黑屏
   Xcode版本:12.0.1
2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）
   问题截图:iphone se  、 iphone6 等非刘海屏拍照和拍视频的时候顶部20左右的黑屏
![821603433402_ pic](https://user-images.githubusercontent.com/16298306/96962477-74b0e000-1539-11eb-8269-5898bbbbb92c.jpg)
检查代码发现  ZLCustomCamera.swift第205行
   if #available(iOS 11.0, *) {
            insets = self.view.safeAreaInsets
        }
非刘海屏的就会多一块儿

**Comment by cuixiaocun** [comment]
截屏 https://user-images.githubusercontent.com/16298306/96962477-74b0e000-1539-11eb-8269-5898bbbbb92c.jpg

**Comment by longitachi** [comment]
代码中设置了隐藏状态栏
```swift
public override var prefersStatusBarHidden: Bool {
    return true
}
```
你可以检查下你代码中是不是对状态栏做了什么全局的修改，导致状态栏没有隐藏。demo运行是没有问题的

**Comment by longitachi** [comment]
下个版本会处理下，不在根据 `self.view.safeAreaInsets` 做判断
