### ISSUE TITLE
您好，请问一下，使用pod导入后，ZLGeneralDefine.swift定义的方法怎么才能使用它

### ISSUE THREAD

**Issue by LYluyu** [longitachi/ZLPhotoBrowser#541]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 请附上以下信息
   cocoapods版本: 
   设备:
   系统版本:
   Xcode版本:

2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）
   问题截图:

3. `ZLPhotoConfiguration` 配置代码

   ```
   paste your code
   ```

**Comment by longitachi** [comment]
你要使用里面的什么方法呢？这个文件都是框架内一些内部方法，没有添加 `public`，所以访问不到。
