### ISSUE TITLE
您好，想请教一下，框架里选择原图和不选择原图，在图片的data上有什么区别？貌似并没有进行压缩，框架是否有提供压缩图片的方法？

### ISSUE THREAD

**Issue by HemingTai** [longitachi/ZLPhotoBrowser#542]

**Comment by longitachi** [comment]
仅采用了`jpegData(compressionQuality:)`该方法对图片`data`大小进行了压缩，并未进行`size`的压缩。
当前版本原图和非原图压缩时候传入了不同的`scale`值。

下个版本考虑将不对原图进行任何压缩，由开发者自己进行适当的压缩。

**Comment by HemingTai** [comment]
感谢指导
