### ISSUE TITLE
请问编辑图片的时候可以添加文字吗

### ISSUE THREAD

**Issue by IseeUDenis** [longitachi/ZLPhotoBrowser#543]
dispatch_async(dispatch_get_main_queue(), ^{
    UIImage *image = [[UIImage alloc] initWithContentsOfFile:path];
    
    [ZLPhotoConfiguration default].editImageClipRatios = @[ZLImageClipRatio.custom, ZLImageClipRatio.wh1x1, ZLImageClipRatio.wh3x4, ZLImageClipRatio.wh16x9, [[ZLImageClipRatio alloc] initWithTitle:@"1 : 2" whRatio:1.0 / 2.0]];
    ZLEditImageViewController *editVC = [[ZLEditImageViewController alloc] initWithImage:image editModel:nil];
    editVC.editFinishBlock = ^(UIImage * _Nonnull image, ZLEditImageModel * _Nonnull editModel) {
      NSData *data= UIImageJPEGRepresentation(image, 1.0);
      BOOL result = [[NSFileManager defaultManager] createFileAtPath:path contents:data attributes:NULL];
      if(result && callBack) {
        callBack(@[]);
      }
    };
    editVC.modalPresentationStyle = UIModalPresentationFullScreen;
    
    UIViewController *vc = [[UIApplication sharedApplication].delegate window].rootViewController;
    [vc showDetailViewController:editVC sender:nil];
  });

**Comment by longitachi** [comment]
现在是没有这个功能的。

**Comment by IseeUDenis** [comment]
> 现在是没有这个功能的。

好的谢谢，期待后续有新功能加上
