### ISSUE TITLE
您好，想请教一下关于不允许选择LivePhoto图片的问题

### ISSUE THREAD

**Issue by HemingTai** [longitachi/ZLPhotoBrowser#544]
现象：我设置了不允许选择`LivePhoto`，但是点击导航栏相册列表时，列表里面还是会有`LivePhoto`的`cell`，此时点击`LivePhoto`并选择一张图片时，由于`PHImageResultIsDegradedKey`的值为`true`，所以在`ZLFetchImageOperation.swift`的133行`if !isDegraded {
                    self?.completion(self?.scaleImage(image), nil)
                    self?.fetchFinish()
                }
`判断为false，就不会进行回调，也没有任何的报错。

问题：对于上述问题，想问一下，是否可以隐藏`LivePhoto`选项，或者隐藏导航栏相册列表，只显示所有支持的图片？或者有关于该问题的其他解决方案？

**Comment by longitachi** [comment]
`allowSelectLivePhoto` 这个参数只会控制照片是否已`LivePhoto`的形式展示，如果不允许选择则会以普通照片的形式展示。
解析照片时候，系统会返回多次，前面几次返回的都是缩略图，这时候`isDegraded`为`false`，所以要等到这个值为`true`时候在进行回调，从而保证回调的图片不是缩略图。

**Comment by HemingTai** [comment]
但是选完之后hud一直在转，直到消失，后面也没有回调，这个需要怎么处理？多次回调是指我多次选择还是单次选择？

**Comment by HemingTai** [comment]
用户选择图片之后如果没有回调或者是相关报错，就会一直停留在选择图片页面，会显得很突兀，想请教一下有没有好点的解决方案？

**Comment by longitachi** [comment]
> 但是选完之后hud一直在转，直到消失，后面也没有回调，这个需要怎么处理？多次回调是指我多次选择还是单次选择？

你选择一张照片时候
```swift
PHImageManager.default().requestImage(for: asset, targetSize: size, contentMode: .aspectFill, options: option) { (image, info) in
    var downloadFinished = false
    if let info = info {
        downloadFinished = !(info[PHImageCancelledKey] as? Bool ?? false) && (info[PHImageErrorKey] == nil)
    }
    let isDegraded = (info?[PHImageResultIsDegradedKey] as? Bool ?? false)
    if downloadFinished {
        completion(image, isDegraded)
    }
}
```
系统这个方法，会回调多次。你先选择一张照片，然后确定，打点`ZLPhotoManager`的`fetchImage`方法看下，这个downloadFinished是不是一直是false，没有走到回调。

**Comment by longitachi** [comment]
还有一种可能就是你这个图片是在iCloud上，然后请求超时了。超时时间默认20s，可在`ZLPhotoConfiguration`中设置。

**Comment by HemingTai** [comment]
> > 但是选完之后hud一直在转，直到消失，后面也没有回调，这个需要怎么处理？多次回调是指我多次选择还是单次选择？
> 
> 你选择一张照片时候
> 
> ```swift
> PHImageManager.default().requestImage(for: asset, targetSize: size, contentMode: .aspectFill, options: option) { (image, info) in
>     var downloadFinished = false
>     if let info = info {
>         downloadFinished = !(info[PHImageCancelledKey] as? Bool ?? false) && (info[PHImageErrorKey] == nil)
>     }
>     let isDegraded = (info?[PHImageResultIsDegradedKey] as? Bool ?? false)
>     if downloadFinished {
>         completion(image, isDegraded)
>     }
> }
> ```
> 
> 系统这个方法，会回调多次。你先选择一张照片，然后确定，打点`ZLPhotoManager`的`fetchImage`方法看下，这个downloadFinished是不是一直是false，没有走到回调。
> 
> 另外你试下demo，我这边测试demo没有问题。

我就是用的demo测试的，`downloadFinished`是`true`，`isDegraded`也是`true`

**Comment by longitachi** [comment]
你先单选一张有你说的这个问题的照片，最后走到timeout了吗？timeout的话会弹框提示请求超时

**Comment by HemingTai** [comment]
> 你先单选一张有你说的这个问题的照片，最后走到timeout了吗？timeout的话会弹框提示请求超时

没有timeout

**Comment by longitachi** [comment]
> 现象：我设置了不允许选择`LivePhoto`，但是点击导航栏相册列表时，列表里面还是会有`LivePhoto`的`cell`，此时点击`LivePhoto`并选择一张图片时，由于`PHImageResultIsDegradedKey`的值为`true`，所以在`ZLFetchImageOperation.swift`的133行`if !isDegraded { self?.completion(self?.scaleImage(image), nil) self?.fetchFinish() } `判断为false，就不会进行回调，也没有任何的报错。
> 
> 问题：对于上述问题，想问一下，是否可以隐藏`LivePhoto`选项，或者隐藏导航栏相册列表，只显示所有支持的图片？或者有关于该问题的其他解决方案？

那我就不明白你的问题了，你的问题是`isDegraded`一直是`true`，所以没有回调。那如果没有回调的话，20s后肯定会弹`alert`提示超时。

**Comment by longitachi** [comment]
没有timeout弹框这个，有点bug，我会处理下。你说的这个`isDegraded `一直是true的问题，我能想到的就是在iCloud上没load下来，你看下你这个照片是在iCloud上吗？

**Comment by HemingTai** [comment]
> 没有timeout弹框这个，有点bug，我会处理下。你说的这个`isDegraded `一直是true的问题，我能想到的就是在iCloud上没load下来，你看下你这个照片是在iCloud上吗？

我确认一下，如果是iCloud上没load下来应该会timeout吧？

**Comment by longitachi** [comment]
现在弹框有bug，刚更新了下demo，你拉下最新的demo试下。超时会有弹框。另外如果确实在iCloud上，你可以先在系统相册打开这张照片，看能否下载下来。如果能下载下来的话，然后再去demo试试能不能选择

**Comment by HemingTai** [comment]
确实是iCould上的，现在有超时弹窗了，感谢帮助
