### ISSUE TITLE
设置了不可混选图片和视频时，在未选择任何图片的情况下，录制视频后的问题

### ISSUE THREAD

**Issue by dong4255** [longitachi/ZLPhotoBrowser#546]
设置了
allowMixSelect = false
allowSelectImage = true
allowSelectVideo = true
这时视频的cell应该是不会出现选中样式的

但在未选中图片的情况下去点击照相机录制视频，完成后拍摄好的视频cell会有选中样式，且可以选择其他图片

![IMG_1608](https://user-images.githubusercontent.com/27190409/97409074-06ed2580-1938-11eb-960a-fcd247cd39bd.PNG)
![IMG_1613](https://user-images.githubusercontent.com/27190409/97409081-094f7f80-1938-11eb-9c4c-e8a962c9934a.PNG)

**Comment by longitachi** [comment]
应该是不能出现的，现在的实现逻辑是不能混选的情况下，视频只能选择一个。至于录制视频后视频cell显示了选择按钮这个是个bug，将在下个版本解决

**Comment by longitachi** [comment]
4.0.9已解决该问题
