### ISSUE TITLE
swift compiler error

### ISSUE THREAD

**Issue by Will-ZJ** [longitachi/ZLPhotoBrowser#547]
![51604286340_ pic_hd](https://user-images.githubusercontent.com/22385702/97826324-47fc8580-1cfc-11eb-9885-15e268600138.jpg)

   cocoapods版本: 1.10.0.beta.1
   设备: i 7
   系统版本: 10.15.6
   Xcode版本: 11.3

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser#requirements
