### ISSUE TITLE
allowSelectGif = NO; 依然能选中 gif 图

### ISSUE THREAD

**Issue by uldh** [longitachi/ZLPhotoBrowser#551]
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。

由于框架内参数相对来说比较多，如果想要实现某种操作
* 请阅读README中相关功能介绍，查看是否有描述；
* 请翻阅下`ZLPhotoConfiguration`类中所定义的属性，每个属性均有详细的注释；

- [x] 我已经查阅了已有的issue，没有找到相同的
- [x] 我想提出一个建议或bug，而不是问一个问题

#### 关于 Issue
1. 请附上以下信息
   cocoapods版本: ZLPhotoBrowser (3.2.0)
   设备: iphone x
   系统版本: ios14
   Xcode版本: Version 12.0

2. 所遇到的问题（如有可能，请尽量详细描述，建议附上截图）
   问题截图: 

3. `ZLPhotoConfiguration` 配置代码

   ```
  ac.configuration.allowSelectGif = NO;
依然能选中 gif 图
   ```

**Comment by longitachi** [comment]
`allowSelectGif `不控制是否显示GIF图片，如果不允许选择，GIF图片会以普通图片形式展示，并且不会显示`GIF`标识。
你说的依然能选中GIF图是没问题的，选中之后返回给你的图片是静态图片。

3.2.0是之前的oc老版本，更多功能可以升级至swift重构后的最新版本

**Comment by uldh** [comment]
好的，不过还是希望可以有不显示的选项
