### ISSUE TITLE
关于选择界面多语言布局错乱问题

### ISSUE THREAD

**Issue by HemingTai** [longitachi/ZLPhotoBrowser#553]
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-20 at 17 30 39](https://user-images.githubusercontent.com/13804911/99788086-8fd43700-2b5b-11eb-9a0b-65459690ec15.png)
在俄语情况下，底部的button重叠了，是不是考虑上下布局或者其他方案能让文字显示出来，项目要上线，期盼修复，感谢

**Comment by longitachi** [comment]
可先使用自定义语言解决
```
// 判断俄语状态
if language == "russian" {
    ZLPhotoConfiguration.default().customLanguageKeyValue = [ZLLocalLanguageKey.preview: "Предпросмотр"]
} else {
    ZLPhotoConfiguration.default().customLanguageKeyValue = [:]
}
```

**Comment by longitachi** [comment]
微信设置俄语时，预览的语言为"Предпросмотр"，可先修改自定义语言为这个。[使用方法](https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(Swift)#Customize-language)
