### ISSUE TITLE
非混选模式下图片视频数量限制

### ISSUE THREAD

**Issue by cnjsyyb** [longitachi/ZLPhotoBrowser#554]
#### Description and Steps
allowMixSelect关闭状态下，只能现在可选图片最大数，可选视频最多只能一个，希望可以给个相关参数
比如图片最多9张，视频最多3个
#### Info
   ZLPhotoBrowser version:  e.g. 4.0.9
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

**Comment by longitachi** [comment]
```
/// This block will be called before selecting an image, the developer can first determine whether the asset is allowed to be selected.
/// Only control whether it is allowed to be selected, and will not affect the selection logic in the framework.
/// - Tips: If the choice is not allowed, the developer can toast prompt the user for relevant information.
@objc public var canSelectAsset: ( (PHAsset) -> Bool )?
```
可通过这个参数实现，框架内每次选择之前都会首先调用该block，你可以自己记录当前选择的asset类型及个数，从而实现不同的效果。

**Comment by cnjsyyb** [comment]
好的谢谢 2015_test 邮箱：2015_test@sina.com 签名由 网易邮箱大师 定制 在2020年11月22日 20:37，long 写道： /// This block will be called before selecting an image, the developer can first determine whether the asset is allowed to be selected.

/// Only control whether it is allowed to be selected, and will not affect the selection logic in the framework.

/// - Tips: If the choice is not allowed, the developer can toast prompt the user for relevant information.

@objc public var canSelectAsset: ( (PHAsset) -> Bool )?

 可通过这个参数实现，框架内每次选择之前都会首先调用该block，你可以自己记录当前选择的asset类型及个数，从而实现不同的效果。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by longitachi** [comment]
4.1.0 已添加 `minVideoSelectCount` 和 `maxVideoSelectCount` 两个参数
