### ISSUE TITLE
回调图片和视频地址

### ISSUE THREAD

**Issue by cnjsyyb** [longitachi/ZLPhotoBrowser#555]
#### Description and Steps

点击确定之前可以加个获取图片和视频地址的方法不，希望可以在内部选择完可以得到所有的沙盒path
#### Info
   ZLPhotoBrowser version:  e.g. 4.0.9
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

**Comment by longitachi** [comment]
ZLPhotoManager 中提供了`fetchAssetFilePath`方法可获取路径
