### ISSUE TITLE
Crash when preview images with zooming

### ISSUE THREAD

**Issue by wjling** [longitachi/ZLPhotoBrowser#556]
### Issue Description
Crash in `ZLPhotoPreviewCell.swift`
#### Description and Steps

Just clone the project and run "Example" target. 
1. Select "Preview local and net image"
2. Zoom in the image
3. Scroll to next image, then crashed

![image](https://user-images.githubusercontent.com/4201777/100059016-55bdaa80-2e65-11eb-8785-4ba66c2d41ef.png)

#### Info
   ZLPhotoBrowser version:  4.1.0
   Device:  Simulator
   Device version:  iOS 14.0
   Xcode version:  Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
Thanks for report this bug, it will be fixed in the next version.
