### ISSUE TITLE
贴图功能运行无法显示

### ISSUE THREAD

**Issue by cctv888** [longitachi/ZLPhotoBrowser#559]
#### Description and Steps

添加了 imageSticker 功能但是不显示贴图功能，使用默认方式也无法显示贴图功能
运行效果中没有贴图功能图标，新版本上删除了此功能吗？
搜索了之前没有发现相同问题

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.1
   Device:  e.g. iPhone 12
   Device version:  e.g. iOS 14.2
   Xcode version:  e.g. Xcode 12.2
#### Configuration code of `ZLPhotoConfiguration`

   ```
        ZLPhotoConfiguration.default().editImageTools = [.draw, .clip, .imageSticker, .textSticker, .mosaic]
        ZLPhotoConfiguration.default().editImageClipRatios = [.custom, .wh1x1, .wh3x4, .wh16x9, ZLImageClipRatio(title: "1 : 2", whRatio: 1 / 2)]
        let editVC = ZLEditImageViewController(image: photoView.image!)
        editVC.editFinishBlock = { [weak self] (images, editModel) in
            self?.photoView.image = images
            PhotoPickerConfig.saveImage = images
        }
        editVC.modalPresentationStyle = .fullScreen
        self.showDetailViewController(editVC, sender: nil)
   ```
![test](https://user-images.githubusercontent.com/24907309/101115170-e0e53000-361d-11eb-9718-e9d38665c269.png)

**Comment by cctv888** [comment]
已经解决，原来没有初始化

**Comment by hai3343** [comment]
怎么初始化呀

**Comment by hai3343** [comment]
> 已经解决，原来没有初始化

怎么初始化呀，运行demo也没有贴图功能啊

**Comment by longitachi** [comment]
@hai3343 Swift版本更新到最新4.1.2版本

**Comment by hai3343** [comment]
> @hai3343 Swift版本更新到最新4.1.2版本

已经更新到4.1.2版本，但还是没有贴纸功能，需要再做什么配置吗？

        ZLPhotoConfiguration.default().editImageClipRatios = [.custom, .wh1x1, .wh3x4, .wh16x9, ZLImageClipRatio(title: "1 : 2", whRatio: 1 / 2)]
        ZLPhotoConfiguration.default().editImageTools = [.draw, .clip, .imageSticker, .textSticker, .mosaic, .filter]
        
        ZLEditImageViewController .showEditImageVC(parentVC: vc, animate: false, image: img, editModel: nil) { (imge, model) in
            if (self.imageEidetBlock != nil) {
                self.imageEidetBlock!(imge,model!)
            }
        }

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(Swift)#use-image-editor
