### ISSUE TITLE
iOS10系统状态栏和导航栏重合，可以解决吗？

### ISSUE THREAD

**Issue by GitHubXuLiying** [longitachi/ZLPhotoBrowser#561]
![image](https://user-images.githubusercontent.com/16660305/101448146-828fb880-3961-11eb-8093-1df4a3d63c81.png)

**Comment by longitachi** [comment]
可以先fork下，然后在`ZLThumbnailViewController`中作如下修改
```swift
override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()
    
    // 修改 var insets = UIEdgeInsets.zero 为
    var insets = UIEdgeInsets(top: UIApplication.shared.statusBarFrame.height, left: 0, bottom: 0, right: 0)
    
    ...
}
```

**Comment by GitHubXuLiying** [comment]
你好，所有的insets修改后出现了选择按钮被遮挡的问题。

![image](https://user-images.githubusercontent.com/16660305/101608144-56973480-3a40-11eb-89b8-44e33672910a.png)
