### ISSUE TITLE
滑动选择时，当手势滑动到collectionView 顶部或者底部的时候，应该让collectionView自动滚动。参考iPhone相册多选功能

### ISSUE THREAD

**Issue by XiongYanY** [longitachi/ZLPhotoBrowser#562]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.1
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
感觉跟相册不同的是，相册能选很多张，但是日常app应用中，一般都是9张，所以感觉这个功能有点鸡肋

**Comment by XiongYanY** [comment]
当你需要备份自己相册，到私有存储设备时，如果需要9张一次的选择，就太痛苦了，我相信很多人相册都是上千张

**Comment by XiongYanY** [comment]
我尝试在pan手势change时，[self.collectionView scrollToItemAtIndexPath:indexPath atScrollPosition:UICollectionViewScrollPositionCenteredVertically animated:YES];但是效果不理想。

else if (pan.state == UIGestureRecognizerStateChanged) {
        if (!_beginSelect ||
            !indexPath ||
            indexPath.row == _lastSlideIndex ||
            [cell isKindOfClass:ZLTakePhotoCell.class] ||
            _selectType == SlideSelectTypeNone) return;
        
        _lastSlideIndex = indexPath.row;
        
        NSInteger minIndex = MIN(indexPath.row, _beginSlideIndexPath.row);
        NSInteger maxIndex = MAX(indexPath.row, _beginSlideIndexPath.row);
        
        BOOL minIsBegin = minIndex == _beginSlideIndexPath.row;
        dispatch_async(dispatch_queue_create("net.bujige.testQueue", DISPATCH_QUEUE_CONCURRENT), ^{
            for (NSInteger i = self->_beginSlideIndexPath.row;
                 minIsBegin ? i<=maxIndex: i>= minIndex;
                 minIsBegin ? i++ : i--) {
                if (i == self->_beginSlideIndexPath.row) continue;
                NSIndexPath *p = [NSIndexPath indexPathForRow:i inSection:0];
                if (![self.arrSlideIndexPath containsObject:p]) {
                    [self.arrSlideIndexPath addObject:p];
                    NSInteger index = asc ? i : i-1;
                    ZLPhotoModel *m = self.arrDataSources[index];
                    [self.dicOriSelectStatus setValue:@(m.isSelected) forKey:@(p.row).stringValue];
                }
            }
            for (NSIndexPath *path in self.arrSlideIndexPath) {
                NSInteger index = asc ? path.row : path.row-1;
                //是否在最初和现在的间隔区间内
                BOOL inSection = path.row >= minIndex && path.row <= maxIndex;
                ZLPhotoModel *m = self.arrDataSources[index];
                switch (self->_selectType) {
                    case SlideSelectTypeSelect: {
                        dispatch_async(dispatch_get_main_queue(), ^{
                            if (inSection &&
                                !m.isSelected &&
                                [self canAddModel:m]) {
                                m.selected = YES;
                            }
                        });
                    }
                        break;
                    case SlideSelectTypeCancel: {
                        if (inSection) m.selected = NO;
                    }
                        break;
                    default:
                        break;
                }
                
                if (!inSection) {
                    //未在区间内的model还原为初始选择状态
                    m.selected = [self.dicOriSelectStatus[@(path.row).stringValue] boolValue];
                }
                
                //判断当前model是否已存在于已选择数组中
                BOOL flag = NO;
                NSMutableArray *arrDel = [NSMutableArray array];
                for (ZLPhotoModel *sm in nav.arrSelectedModels) {
                    if ([sm.asset.localIdentifier isEqualToString:m.asset.localIdentifier]) {
                        if (!m.isSelected) {
                            [arrDel addObject:sm];
                        }
                        flag = YES;
                        break;
                    }
                }
                
                [nav.arrSelectedModels removeObjectsInArray:arrDel];
                
                if (!flag && m.isSelected) {
                    [nav.arrSelectedModels addObject:m];
                }
                dispatch_async(dispatch_get_main_queue(), ^{
                    ZLCollectionCell *c = (ZLCollectionCell *)[self.collectionView cellForItemAtIndexPath:path];
                    c.btnSelect.selected = m.isSelected;
                    c.maskView.hidden = configuration.showSelectedMask ? !m.isSelected : YES;
                    [self refreshCellIndex];
                    [self refreshCellMaskView];
                    [self resetBottomBtnsStatus:NO];
                    [self.collectionView scrollToItemAtIndexPath:indexPath atScrollPosition:UICollectionViewScrollPositionCenteredVertically animated:YES];

                });
            }
        });
        
    }

**Comment by longitachi** [comment]
等有时间了会研究下，不过看你用的还是oc版本，oc版本不维护了，所以就算加这个功能也是swift版本，所以可以切换到swift的版本

**Comment by longitachi** [comment]
最新代码已支持该功能，提供了如下两个参数
```swift
/// When slide select is active, will auto scroll to top or bottom when your finger at the top or end.
@objc public var autoScrollWhenSlideSelectIsActive = true
    
/// The max speed of auto scroll.
@objc public var autoScrollMaxSpeed: CGFloat = 600
```

**Comment by XiongYanY** [comment]
昨天体验了一把，很给力！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "longitachi/ZLPhotoBrowser"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 晚上7:06
收件人:&nbsp;"longitachi/ZLPhotoBrowser"<ZLPhotoBrowser@noreply.github.com&gt;;
抄送:&nbsp;"熊岩"<292215607@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [longitachi/ZLPhotoBrowser] 滑动选择时，当手势滑动到collectionView 顶部或者底部的时候，应该让collectionView自动滚动。参考iPhone相册多选功能 (#562)





 
最新代码已支持该功能，提供了如下两个参数
 /// When slide select is active, will auto scroll to top or bottom when your finger at the top or end. @objc public var autoScrollWhenSlideSelectIsActive = true      /// The max speed of auto scroll. @objc public var autoScrollMaxSpeed: CGFloat = 600
