### ISSUE TITLE
showSelectBtnWhenSingleSelect 无效

### ISSUE THREAD

**Issue by wangchaodong** [longitachi/ZLPhotoBrowser#563]
#### Info
   ZLPhotoBrowser version:  4.1.1
   Device:  iPhone 11
   Device version:   iOS 14.0
   Xcode version:   Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`
        ZLPhotoConfiguration.default().showSelectBtnWhenSingleSelect = true
        ZLPhotoConfiguration.default().maxSelectCount = 1

**Comment by longitachi** [comment]
我刚测试了下demo是没有说的这个问题，按照issue中的`ZLPhotoConfiguration `设置，下方是有”预览，原图和确定“这一栏的

**Comment by wangchaodong** [comment]
> 我刚测试了下demo是没有说的这个问题，按照issue中的`ZLPhotoConfiguration `设置，下方是有”预览，原图和确定“这一栏的

        ZLPhotoConfiguration.default().maxSelectCount = 1
        ZLPhotoConfiguration.default().allowSelectImage = true
        ZLPhotoConfiguration.default().allowTakePhotoInLibrary = false
        ZLPhotoConfiguration.default().allowSelectOriginal = true
        ZLPhotoConfiguration.default().allowSelectGif = true
        ZLPhotoConfiguration.default().allowSelectLivePhoto = true

        ZLPhotoConfiguration.default().allowEditImage = true
        ZLPhotoConfiguration.default().editImageTools = [.clip]
        ZLPhotoConfiguration.default().editImageClipRatios = [.wh1x1]
        ZLPhotoConfiguration.default().editAfterSelectThumbnailImage = true
        ZLPhotoConfiguration.default().saveNewImageAfterEdit = false
        ZLPhotoConfiguration.default().showClipDirectlyIfOnlyHasClipTool = true
        //video
        ZLPhotoConfiguration.default().allowSelectVideo = false

        // index
        ZLPhotoConfiguration.default().showSelectedIndex = true
        ZLPhotoConfiguration.default().allowSlideSelect = true
        ZLPhotoConfiguration.default().showSelectedMask = true
        ZLPhotoConfiguration.default().showSelectBtnWhenSingleSelect = true

上面是我完整的config配置代码， 这个问题是存在的

**Comment by longitachi** [comment]
那是因为你设置了`editAfterSelectThumbnailImage = true`，点击后会立即进入编辑界面，所以隐藏底部toolbar

**Comment by wangchaodong** [comment]
thx, 改成editAfterSelectThumbnailImage  = false后就能显示toolbar了.  建议可以在展示toolbar的时候 点击底部确定后再判定需要进入编辑界面。

**Comment by longitachi** [comment]
> thx, 改成editAfterSelectThumbnailImage = false后就能显示toolbar了. 建议可以在展示toolbar的时候 点击底部确定后再判定需要进入编辑界面。

这个就看个人需求了，像选择头像之类的是需要点击之后立即编辑的，`editAfterSelectThumbnailImage `这个参数的本意也是针对这种需求的
