### ISSUE TITLE
只进行拍照，不允许它进行录制视频，如何设置？因为我不想授权访问麦克风

### ISSUE THREAD

**Issue by czmCWH** [longitachi/ZLPhotoBrowser#564]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.1
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by czmCWH** [comment]
源码里找到设置方法了，ZLPhotoConfiguration.default().allowRecordVideo  = false
可以在使用文档里写一下

**Comment by longitachi** [comment]
emmm，`ZLPhotoConfiguration` 中参数太多了，每个参数均有详细注释，文档就不一一介绍了，只介绍相关用法，具体需求均可查看`ZLPhotoConfiguration`中参数进行配置
