### ISSUE TITLE
themeColorDeploy.albumListCountColor 参数设置无效

### ISSUE THREAD

**Issue by huaqixue** [longitachi/ZLPhotoBrowser#565]
### Issue Description

右上角 count label的 颜色不改变

#### Description and Steps

设置ZLPhotoConfiguration.default().themeColorDeploy.albumListCountColor = .red ， 但是count 颜色不变 

![image](https://user-images.githubusercontent.com/31527909/102306231-b3dd3980-3f9c-11eb-9931-82b0ab786fd3.png)

#### Info
   ZLPhotoBrowser version:  4.0.8
   Device: simulator iPhone 11 Pro
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
       let configDefault = ZLPhotoConfiguration.default()
        configDefault.allowSelectVideo = false
        configDefault.allowTakePhotoInLibrary = false
        configDefault.themeColorDeploy.albumListCountColor = .red
        configDefault.allowSelectGif = false
        configDefault.maxSelectCount = importImagesLimit
        let ps = ZLPhotoPreviewSheet()
        ps.selectImageBlock = { [weak self] (images, assets, isOriginal) in
            guard let self = self else {
                return
            }
        }
        ps.showPhotoLibrary(sender: self)
   ```

**Comment by longitachi** [comment]
index label颜色对应的是`indexLabelBgColor`。`albumListCountColor`对应的是相册列表中最右边的count label颜色，即选择相册时候的列表

**Comment by huaqixue** [comment]
@longitachi 感觉解答，已经解决
