### ISSUE TITLE
韩语的支持问题

### ISSUE THREAD

**Issue by huaqixue** [longitachi/ZLPhotoBrowser#566]
### Issue Description

![image](https://user-images.githubusercontent.com/31527909/102319690-37efeb00-3fb6-11eb-955e-86a04d1c1184.png)

#### Description and Steps

我看支持的语言，是有韩语包含的，但是将手机切换至韩语之后，这个页面的文字就没有任何显示了

#### Info
   ZLPhotoBrowser version:  e.g. 4.0.3
   Device:  simulator iPhone 11 Pro
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
           let configDefault = ZLPhotoConfiguration.default()
        configDefault.allowSelectVideo = false
        configDefault.allowTakePhotoInLibrary = false
        configDefault.allowSelectGif = false
        configDefault.allowSelectLivePhoto = false
        configDefault.maxSelectCount = importImagesLimit
        configDefault.themeColorDeploy.indexLabelBgColor = UIColor.hex("0092E8", alpha: 1)
        configDefault.themeColorDeploy.bottomToolViewBtnNormalBgColor = UIColor.hex("0092E8", alpha: 1)
        configDefault.languageType = .system
   ```

**Comment by longitachi** [comment]
如果是`Swift Package Manager`安装最低支持版本为`4.0.9`，`cocoapods`和`carthage`应该没有这个问题

**Comment by huaqixue** [comment]
@longitachi  说错版本了，我是pod安装，`Installing ZLPhotoBrowser (4.0.8)` 应该是4.0.8版本

**Comment by huaqixue** [comment]
@longitachi 是需要进一步，升到4.0.9，支持的韩语嘛？

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/releases/tag/4.0.9
4.0.9才开始支持韩语

**Comment by huaqixue** [comment]
@longitachi 好的，感谢！

**Comment by longitachi** [comment]
直接更新到`4.1.2`版本就好了
