### ISSUE TITLE
屏幕旋转后界面布局异常

### ISSUE THREAD

**Issue by wmadao11** [longitachi/ZLPhotoBrowser#568]
### Issue Description

图片预览、编辑、裁剪等页面，在进入界面后，发生屏幕旋转，布局异常。

#### Description and Steps

以竖屏(横屏)状态进入这些页面，旋转到另一方向，界面布局没有更新到正确状态。可能跟 #558 类似。
因为是我这边项目需要支持iPad，希望能进一步处理下横竖屏以及切换的逻辑，感谢

#### Info
   ZLPhotoBrowser version: 4.1.1
   Device:  iPad Air(4th generation)
   Device version:  iOS 14.2
   Xcode version:  Xcode 12.2

#### Configuration code of `ZLPhotoConfiguration`

demo工程的选择图片示例

#### 图
![Simulator Screen Shot - iPad Air (4th generation) - 2020-12-18 at 19 31 39](https://user-images.githubusercontent.com/16165094/102611111-4b8f8300-4169-11eb-9b6f-023d8273a2d5.png)

![Simulator Screen Shot - iPad Air (4th generation) - 2020-12-18 at 19 31 57](https://user-images.githubusercontent.com/16165094/102611168-619d4380-4169-11eb-8a27-3f44306b2bc8.png)

![Simulator Screen Shot - iPad Air (4th generation) - 2020-12-18 at 19 32 20](https://user-images.githubusercontent.com/16165094/102611191-6b26ab80-4169-11eb-8ce0-a6af5162e91b.png)

**Comment by longitachi** [comment]
好的，这周有空了会看下iPad情况。上面截图是Demo效果吗？还是pod `4.1.1` 版本

**Comment by wmadao11** [comment]
> 好的，这周有空了会看下iPad情况。上面截图是Demo效果吗？还是pod `4.1.1` 版本

截图是截的当前master分支(到#3bb980c)的demo。pod`4.1.1`版本的问题差不多

**Comment by longitachi** [comment]
这个屏幕旋转布局错乱的真奇怪，iPhone上没问题，iPad上就会乱
