### ISSUE TITLE
混合选择视频图片，先选图片，然后多选视频，使用视频PHAsset获取mediaType出现类型不一致的问题

### ISSUE THREAD

**Issue by devchena** [longitachi/ZLPhotoBrowser#569]
#### Description and Steps

1.打开图片选择器；
2.第一张选图片，然后连选几个视频；
3.通过PHAsset获取mediaType，发现类型不一致

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.1
   Device:  e.g. iPhone Xs Max
   Device version:  e.g. iOS 12.0.1
   Xcode version:  e.g. Xcode 12.2

#### Configuration code of `ZLPhotoConfiguration`

   ```
           let config = ZLPhotoConfiguration.default()
        config.maxSelectCount = 8
        config.allowMixSelect = true
        config.allowSelectImage = true
        config.allowSelectVideo = true
        config.allowSelectGif = false
        config.allowEditImage = true
        config.allowEditVideo = true
        
        let photoPreviewSheet = ZLPhotoPreviewSheet()
        photoPreviewSheet.selectImageBlock = { [weak self] (images, assets, isOriginal) in
            
        }
        photoPreviewSheet.showPhotoLibrary(sender: self)

ZLPhotoManager.fetchAssetFilePath(asset: asset) { (filePath) in
                filePathArray.append(filePath)
                
                if filePathArray.count == assets.count {
                    for (index, filePath) in filePathArray.enumerated() {
                        guard let filePath = filePath, let fileURL = URL(string: filePath) else {
                            continue
                        }
                        guard let imageData = images[index].jpegData(compressionQuality: 1.0) else {
                            continue
                        }
                        
                        let isVideo = asset.mediaType == .video
                        let fileName: String
                        
                        
                        if let value = filePath.components(separatedBy: "/").last {
                            fileName = value
                        } else {
                            let time = Date().toString(format: "yyyyMMdd_HHmmss_SSS")
                            fileName = time + (isVideo ? ".mp4" : ".jpg")
                        }
                        
                        print("fileName: \(fileName)")
                        print("isVideo: \(isVideo)")

                        let duration = Int(asset.duration)
                        let localPHAsset = LocalPHAsset(fileURL: fileURL, fileName: fileName,
                                                        imageData: imageData, duration: duration, isVideo: isVideo)
                        assetInfoArray.append((assets[index], localPHAsset))
                    }
    
                    completion(assetInfoArray)
                }
            }
   ```
   
   
![A014C40F-E8FB-46B3-B840-823D7B6808EC](https://user-images.githubusercontent.com/15935903/102842463-ff329480-4441-11eb-86c2-47101172649b.png)

**Comment by longitachi** [comment]
看了下感觉像是你的写法有错误，我测试选了两个图片和两个视频，结果如下
```
func fetchAssetType(assets: [PHAsset]) {
        for asset in assets {
            ZLPhotoManager.fetchAssetFilePath(asset: asset) { (filePath) in
                let isVideo = asset.mediaType == .video
                let fileName: String
                if let value = filePath?.components(separatedBy: "/").last {
                    fileName = value
                } else {
                    fileName = "video" + (isVideo ? ".mp4" : ".jpg")
                }
                debugPrint("fileName: \(fileName)")
                debugPrint("isVideo: \(isVideo)")
            }
        }
}


"fileName: IMG_0985.PNG"
"isVideo: false"
"fileName: IMG_0984.PNG"
"isVideo: false"
"fileName: IMG_0785.MP4"
"isVideo: true"
"fileName: IMG_0784.MP4"
"isVideo: true"
```

**Comment by longitachi** [comment]
你为啥要加`if filePathArray.count == assets.count ` 这个判断呢？

**Comment by devchena** [comment]
我看着ZLPhotoManager.fetchAssetFilePath的回调有可能返回为nil，为nil的话也会放到数组里，用于判断所有的asset是否都执行获取路径操作

**Comment by devchena** [comment]
private static func fetchMaterialInfo(with assets: [PHAsset],
                                          images: [UIImage],
                                          completion: @escaping ([LocalMaterialInfo]) -> Void) {
    
        var materialInfoArray: [LocalMaterialInfo] = []
        var filePathArray: [String?] = []

        for asset in assets {
            ZLPhotoManager.fetchAssetFilePath(asset: asset) { (filePath) in
                filePathArray.append(filePath)
                
                if filePathArray.count == assets.count {
                    for (index, filePath) in filePathArray.enumerated() {
                        guard let filePath = filePath, let fileURL = URL(string: filePath) else {
                            continue
                        }
                        guard let imageData = images[index].jpegData(compressionQuality: 1.0) else {
                            continue
                        }
                        
                        let isVideo = asset.mediaType == .video
                        let fileName: String
                        
                        if let value = filePath.components(separatedBy: "/").last {
                            fileName = value
                        } else {
                            let time = Date().toString(format: "yyyyMMdd_HHmmss_SSS")
                            fileName = time + (isVideo ? ".mp4" : ".jpg")
                        }

                        let duration = Int(asset.duration)
                        let localMaterial = LocalMaterial(fileURL: fileURL, fileName: fileName,
                                                          imageData: imageData, duration: duration, isVideo: isVideo)
                        materialInfoArray.append((assets[index], localMaterial))
                    }
    
                    completion(materialInfoArray)
                }
            }
        }
    }

**Comment by devchena** [comment]
很抱歉，是我这边的问题，filePathArray和assets两个数组的对应顺序并不一致
