### ISSUE TITLE
页面右滑返回的时候，选择的图片没有变化

### ISSUE THREAD

**Issue by wells1013** [longitachi/ZLPhotoBrowser#57]
![image](https://cloud.githubusercontent.com/assets/5172252/26096462/e8454b88-3a53-11e7-851c-dd9b00660c12.png)
![image](https://cloud.githubusercontent.com/assets/5172252/26096469/ebcfcd8c-3a53-11e7-92e2-16a488f03000.png)
我最多选择3张，在ZLShowBigImgViewController这个页面选中，然后右滑，返回，ZLThumbnailViewController这个页面选中状态不会变化，然后就如同上面图片所显示的。

**Comment by longitachi** [comment]
已更新，谢谢
