### ISSUE TITLE
打包编译报错

### ISSUE THREAD

**Issue by wangdexter** [longitachi/ZLPhotoBrowser#570]
/// 分割线颜色
    class var separatorColor: UIColor {
        ZLPhotoConfiguration.default().themeColorDeploy.separatorColor
}
报错信息:
Getter for 'separatorColor' with Objective-C selector 'separatorColor' conflicts with getter for 'separator' with the same Objective-C selector

**Comment by longitachi** [comment]
应该跟你项目中的对`UIColor`的扩展参数名字有冲突，这个参数没有加`@objc`应该不会出这个错误。下个版本我处理下

**Comment by wangdexter** [comment]
好的~是跟项目其他第三方的参数名冲突了，去掉@objc还是会报错，我暂时修改了这个参数名，修改之后没有问题了
