### ISSUE TITLE
（必现问题）系统相册里，新建文件里的相簿获取不到

### ISSUE THREAD

**Issue by AndyZZhz** [longitachi/ZLPhotoBrowser#571]
#### 复现步骤如下：
（1）系统相册里，新建文件，新建相簿1

（2）使用这个方法获取图片
    class func getPhotoAlbumList(ascending: Bool, allowSelectImage: Bool, allowSelectVideo: Bool, completion: ( ([ZLAlbumListModel]) -> Void )) 

（3）相簿1获取不到

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.2
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.2
   Xcode version:  e.g. Xcode 12.2

**Comment by longitachi** [comment]
感谢反馈，下个版本会处理下这个问题
