### ISSUE TITLE
Avplayer黑屏问题和其他播放问题

### ISSUE THREAD

**Issue by Hxh10141993** [longitachi/ZLPhotoBrowser#573]
1、性能差的手机有1~5不等的预解码黑屏问题如何优化
2、有时候获取的视频地址是xxxx.medium.mp4如何播放（好像是iCloud很久之前的视图2，3个月前的）

**Comment by longitachi** [comment]
预解码是iCloud视频？

通过`ZLPhotoManager.fetchAssetFilePath(asset:)`获取的视频地址应该是无法直接播放的，要么直接用PHAsset相关方法播放，要么将PHAsset对应视频导出到沙盒，然后播放

**Comment by Hxh10141993** [comment]
1、我视频是手机刚录制的，avPlayer.play() 在性能差的手机上会黑屏，例如iPhone6上面会有这个问题，在x手机上没有问题。有什么可以优化的方法吗？
2、xxxx.medium.mp4 直接通过你的预览页面进行播放，所以有无法播放可能。
ps：这是两个不同的问题,

**Comment by longitachi** [comment]
1.第一个暂时没考虑-_-

2.你说的这个xxxx.medium.mp4视频是哪里来的，是我上面说的通过`ZLPhotoManager.fetchAssetFilePath(asset:)`获取到的吗？如果是的话，无法通过`ZLImagePreviewController`提供的方法播放，这个地址并不是本地沙盒视频地址或者网络视频地址，所以还是需要传入PHAsset进行播放
```swift
/// - Parameters:
///   - datas: Must be one of PHAsset, UIImage and URL, will filter ohers in init function.
///   - index: Index for first display.
///   - urlType: Tell me the url is image or video.
///   - urlImageLoader: Called when cell will display, cell will layout after callback when image load finish. The first block is progress callback, second is load finish callback.
@objc public init(datas: [Any], index: Int = 0, showSelectBtn: Bool = true, urlType: ( (URL) -> ZLURLType )? = nil, urlImageLoader: ( (URL, UIImageView, @escaping ( (CGFloat) -> Void ),  @escaping ( () -> Void )) -> Void )? = nil) {
    ...
}
```

**Comment by Hxh10141993** [comment]
是通过ZLPhotoManager.fetchAssetFilePath(asset:)获取的，
