### ISSUE TITLE
当可选择最大数量为1时，出现选中标记

### ISSUE THREAD

**Issue by liujiesss** [longitachi/ZLPhotoBrowser#575]
### Issue Description
当可选择最大数量为1时，点击图片不放并且水平方向滑动，会出现最多数量>1时图片没有预览时的选中状态
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.2
   Device:  e.g. iPhone SE
   Device version:  e.g. iOS 13.4
   Xcode version:  e.g. Xcode 12.3

#### Configuration code of `ZLPhotoConfiguration`

![IMG_0116](https://user-images.githubusercontent.com/33110770/104816586-228d0b80-5857-11eb-9230-3394b0868306.PNG)

**Comment by longitachi** [comment]
感谢反馈，下个版本会处理下

**Comment by yanmingLiu** [comment]
> 感谢反馈，下个版本会处理下

1张的时候，滑动出现的
