### ISSUE TITLE
多选图片时，放大图片不显示

### ISSUE THREAD

**Issue by developer-poplar** [longitachi/ZLPhotoBrowser#578]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.2
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
请描述下具体复现步骤

**Comment by developer-poplar** [comment]
> 请描述下具体复现步骤

多图选择模式，也就是当maxSelectCount大于1的时候，进入相册列表，点击图片，放大没有图片
![IMG_5599](https://user-images.githubusercontent.com/68727894/105445320-a5282780-5caa-11eb-8a3c-353241a29f1d.PNG)

**Comment by developer-poplar** [comment]
> 请描述下具体复现步骤


![Uploading RPReplay_Final1611289120 - 01.gif…]()

**Comment by developer-poplar** [comment]
> 请描述下具体复现步骤
![RPReplay_Final1611289120 - 01](https://user-images.githubusercontent.com/68727894/105446175-89be1c00-5cac-11eb-8f35-99f008eb371f.gif)

**Comment by longitachi** [comment]
这应该是很老的版本了吧，swift重构之前的，更新到4.1.2版本即可

**Comment by developer-poplar** [comment]
> 这应该是很老的版本了吧，swift重组之前的，更新到4.1.2版本即可

为什么我只能更新到3.1.2呢

**Comment by longitachi** [comment]
你Podfile怎么写的，执行下`pod repo update` 试试

**Comment by developer-poplar** [comment]
> 你Podfile怎么写的，执行下`pod repo update`试试

pod 'ZLPhotoBrowser'， 不显示的问题我更新到3.1.2已经解决了

**Comment by longitachi** [comment]
更新4.1.2版本的话，可以先执行`pod repo update`，修改`Podfile`为`pod 'ZLPhotoBrowser', '4.1.2'`

**Comment by developer-poplar** [comment]
> 更新4.1.2版本的话，可以先执行`pod repo update`，修改`Podfile`为`pod 'ZLPhotoBrowser', '4.1.2'`

好的，非常感谢。
