### ISSUE TITLE
showAlertAndDismissAfterDoneAction 是否可以自定义

### ISSUE THREAD

**Issue by LuckyRoc** [longitachi/ZLPhotoBrowser#579]
![image](https://user-images.githubusercontent.com/10631829/105441383-68a4fd80-5ca3-11eb-9aea-15788e6f6856.png)

这个弹出框是否可以自定义？增加跳转设置的按钮

**Comment by longitachi** [comment]
当前版本不支持自定义，后面我看下添加一个回调
