### ISSUE TITLE
遇到一个问题，我想拍照的时候，只想拍照，不需要长按录制。

### ISSUE THREAD

**Issue by JianWenXie** [longitachi/ZLPhotoBrowser#580]
遇到一个问题，我想拍照的时候，只想拍照，不需要长按录制，能不能开放个接口出来

**Comment by longitachi** [comment]
`@objc public var allowRecordVideo: Bool` 设置为 `false` 即可

**Comment by JianWenXie** [comment]
刚看到，谢谢大大！
