### ISSUE TITLE
是否可以自定义cell？？？？

### ISSUE THREAD

**Issue by RuYiChenIT** [longitachi/ZLPhotoBrowser#581]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.2
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
现在不支持自定义cell，顺便问下是对哪部分cell有自定义需求？

**Comment by RuYiChenIT** [comment]
photoCell




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "longitachi/ZLPhotoBrowser"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月25日(星期一) 上午10:33
收件人:&nbsp;"longitachi/ZLPhotoBrowser"<ZLPhotoBrowser@noreply.github.com&gt;;
抄送:&nbsp;"45233951"<45233951@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [longitachi/ZLPhotoBrowser] 是否可以自定义cell？？？？ (#581)





 
现在不支持自定义cell，顺便问下是对哪部分cell有自定义需求？

**Comment by longitachi** [comment]
。。。。。所以photocell是哪个？？？

**Comment by RuYiChenIT** [comment]
我想自定义照片cell，或者说有入口能够继承ZLPreviewBaseCell




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "longitachi/ZLPhotoBrowser"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月25日(星期一) 上午10:41
收件人:&nbsp;"longitachi/ZLPhotoBrowser"<ZLPhotoBrowser@noreply.github.com&gt;;
抄送:&nbsp;"45233951"<45233951@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [longitachi/ZLPhotoBrowser] 是否可以自定义cell？？？？ (#581)





 
。。。。。所以photocell是哪个？？？
