### ISSUE TITLE
请问下，我设置了navBarColor和albumListBgColor为白色

### ISSUE THREAD

**Issue by SAO-Asuna** [longitachi/ZLPhotoBrowser#582]
版本：目前最新
模拟器：ios14.4
我设置了navBarColor和albumListBgColor为白色，但是在模拟器上看还是有一层深灰色，请问是什么原因呢？
![Simulator Screen Shot - iPhone 12 - 2021-02-13 at 01 59 38](https://user-images.githubusercontent.com/35756695/107804689-28670580-6d9f-11eb-8931-a524043395fa.png)

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/98dda354e4637da183bff8de92a24c635024d6b8/Sources/General/ZLPhotoConfiguration.swift#L405-L408

有一个了blueEffect的效果，可设置为nil

**Comment by SAO-Asuna** [comment]
> https://github.com/longitachi/ZLPhotoBrowser/blob/98dda354e4637da183bff8de92a24c635024d6b8/Sources/General/ZLPhotoConfiguration.swift#L405-L408
> 
> 有一个blueEffect的效果，可设置为nil

好的，知道了，谢谢
