### ISSUE TITLE
必现Crash  ZLPhotoBrowser/ZLCustomCamera.swift, line 625

### ISSUE THREAD

**Issue by Marcusias** [longitachi/ZLPhotoBrowser#586]
#### Description and Steps
1.授权相册
2.不授权相机
3.点击拍照，在权限弹窗弹出之前，点击拍照 crash

#### Info
   ZLPhotoBrowser version: 最新
   Device:  e.g. iPhone 11
   Device version:  e.g. iOS 14.2

代码未做权限判断，弹窗弹出前点击拍照会崩

**Comment by Marcusias** [comment]
@longitachi  podspec 还有 release tag 麻烦更新下～

**Comment by longitachi** [comment]
@Marcusias 等这两天看下有没有新的需要更新的，就会发一个新版

**Comment by longitachi** [comment]
4.1.3版本已发布

**Comment by Marcusias** [comment]
> 4.1.3版本已发布

thanks
