### ISSUE TITLE
关于预览ZLImagePreviewController的一个问题~

### ISSUE THREAD

**Issue by SAO-Asuna** [longitachi/ZLPhotoBrowser#587]
![image](https://user-images.githubusercontent.com/35756695/108664574-00e60a80-750e-11eb-9790-f6d6dca7b7dc.png)
如上图，如果我在预览初始化ZLImagePreviewController的时候
let previewVC = ZLImagePreviewController(datas: images, index: indexPath.row, showSelectBtn: false)
设置showSelectBtn为false，则这里会隐藏掉上面的选择按钮和下面的bottomView，但是在我点击图片沉浸式预览图片，再点击图片返回时，bottomView就会再次展示，猜测是在tapPreviewCell【退出预览方法里】
![image](https://user-images.githubusercontent.com/35756695/108664813-82d63380-750e-11eb-955a-8af9003952f9.png)
设置回了fasle展示，可以帮忙修复一下吗？建议可以在选择showSelectBtn为false的时候只隐藏selectBtn不隐藏bottomView

**Comment by longitachi** [comment]
感谢反馈，这两天发版会更新下这个

**Comment by longitachi** [comment]
更新4.1.3版本即可
https://github.com/longitachi/ZLPhotoBrowser/blob/f110f4e8c24553e103f60e8abb3e0798274aea01/Sources/General/ZLImagePreviewController.swift#L91-L97
