### ISSUE TITLE
关于导入问题

### ISSUE THREAD

**Issue by q32784307** [longitachi/ZLPhotoBrowser#588]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.3
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

作者您好，麻烦请教一下，我的工程是OC的，现在我想导入最新的版本4.1.3，然后根据文档pod导入，添加use_frameworks!。pod会报错
<img width="576" alt="image" src="https://user-images.githubusercontent.com/18424637/108816667-87bfe380-75f1-11eb-95ef-b62415e9d18c.png">
这个该怎么处理？冲突的SDK是pod 'TXIMSDK_TUIKit_iOS'

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/issues/533
`TXIMSDK_TUIKit_iOS`这个库是需要注释掉`use_frameworks!`的
`Swift`现在支持静态库了，所以`ZLPhotoBrowser`不需要添加`use_frameworks!`也可以安装

**Comment by q32784307** [comment]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/18424637/108819970-7f1ddc00-75f6-11eb-850a-fd582f360ec9.png">
额....然后在工程里就报这么一堆的错误

**Comment by longitachi** [comment]
emmm，好吧，我刚才创建了个swift项目测试的，如果导入到oc项目里应该还是需要`use_frameworks!`的。所以如果要使用的话，应该只能手动导入了

**Comment by q32784307** [comment]
<img width="273" alt="image" src="https://user-images.githubusercontent.com/18424637/108821239-467f0200-75f8-11eb-8f33-a8e9e3a2cdcd.png">
<img width="242" alt="image" src="https://user-images.githubusercontent.com/18424637/108821263-4bdc4c80-75f8-11eb-98d2-80514be4b825.png">
嗯...手动导入然后就这个鬼样子了...


Multiple commands produce '/Users/success/Library/Developer/Xcode/DerivedData/StudyRoom-cqxfdgkdsxcmsfguygqcdhmrqdho/Build/Products/Debug-iphoneos/番鱼.app/Info.plist':
1) Target 'StudyRoom' (project 'StudyRoom') has copy command from '/Users/success/Desktop/番鱼/StudyRoom/StudyRoom/Sources/Info.plist' to '/Users/success/Library/Developer/Xcode/DerivedData/StudyRoom-cqxfdgkdsxcmsfguygqcdhmrqdho/Build/Products/Debug-iphoneos/番鱼.app/Info.plist'
2) Target 'StudyRoom' (project 'StudyRoom') has process command with output '/Users/success/Library/Developer/Xcode/DerivedData/StudyRoom-cqxfdgkdsxcmsfguygqcdhmrqdho/Build/Products/Debug-iphoneos/番鱼.app/Info.plist'
这是完整的报错信息

**Comment by q32784307** [comment]
emmm....好家伙的,困难重重，搞了2个多小时。谢谢
