### ISSUE TITLE
请问Swift版本如何支持iOS9

### ISSUE THREAD

**Issue by Dannyzheng831** [longitachi/ZLPhotoBrowser#589]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.3
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
`cocoapods` `carthage` `SPM` 均是10.0以上版本，所以要支持iOS9的话，可以手动导入代码进行测试，看在iOS9上有没有bug

**Comment by adolph-suntao** [comment]
修改了代码试了一下， iOS 9下报错一大堆啊。。。。

**Comment by longitachi** [comment]
确实要改的有点多
1. Timer写法要自行修改下
```swift
Timer.scheduledTimer(withTimeInterval: duration, repeats: true, block: { _ in })
```
上面写法要替换为
```swift
Timer.scheduledTimer(timeInterval: duration, target: self, selector: #selector(), userInfo: nil, repeats: true)
```
2. 所有使用到`LivePhoto`的地方要添加`@available(iOS 9.1, *)`
例如
```
/// 类前添加
@available(iOS 9.1, *)
class ZLLivePhotoPreviewCell: ZLPreviewBaseCell {
    ...
}

/// 方法前添加
@available(iOS 9.1, *)
class func fetchLivePhoto(for asset: PHAsset, completion: @escaping ( (PHLivePhoto?, [AnyHashable: Any]?, Bool) -> Void )) {
   ...
}

/// 方法内部使用到的地方
func reloadCurrentCell() {
    guard let cell = self.collectionView.cellForItem(at: IndexPath(row: self.currentIndex, section: 0)) else {
        return
    }
    if let cell = cell as? ZLGifPreviewCell {
        cell.loadGifWhenCellDisplaying()
    } else if #available(iOS 9.1, *), let cell = cell as? ZLLivePhotoPreviewCell {
        // 做版本判断
        cell.loadLivePhotoData()
    }
}
```
iOS10之前可以禁用选择`LivePhoto`、自定义相机、相册内部拍照等功能

**Comment by Dannyzheng831** [comment]
非常感谢！

> 确实要改的有点多
> 
> 1. Timer写法要自行修改下
> 
> ```swift
> Timer.scheduledTimer(withTimeInterval: duration, repeats: true, block: { _ in })
> ```
> 
> 上面写法要替换为
> 
> ```swift
> Timer.scheduledTimer(timeInterval: duration, target: self, selector: #selector(), userInfo: nil, repeats: true)
> ```
> 
> 1. 所有使用到`LivePhoto`的地方要添加`@available(iOS 9.1, *)`
>    例如
> 
> ```
> /// 类前添加
> @available(iOS 9.1, *)
> class ZLLivePhotoPreviewCell: ZLPreviewBaseCell {
>     ...
> }
> 
> /// 方法前添加
> @available(iOS 9.1, *)
> class func fetchLivePhoto(for asset: PHAsset, completion: @escaping ( (PHLivePhoto?, [AnyHashable: Any]?, Bool) -> Void )) {
>    ...
> }
> 
> /// 方法内部使用到的地方
> func reloadCurrentCell() {
>     guard let cell = self.collectionView.cellForItem(at: IndexPath(row: self.currentIndex, section: 0)) else {
>         return
>     }
>     if let cell = cell as? ZLGifPreviewCell {
>         cell.loadGifWhenCellDisplaying()
>     } else if #available(iOS 9.1, *), let cell = cell as? ZLLivePhotoPreviewCell {
>         // 做版本判断
>         cell.loadLivePhotoData()
>     }
> }
> ```
> 
> iOS10之前可以禁用选择`LivePhoto`、自定义相机、相册内部拍照等功能

**Comment by Dannyzheng831** [comment]
非常感谢！！
