### ISSUE TITLE
一些相机拍的照片不显示

### ISSUE THREAD

**Issue by XHTeng** [longitachi/ZLPhotoBrowser#59]
传到手机里之后   选择的时候没有这个照片

**Comment by longitachi** [comment]
相册里面有吗，在哪个相册名字下？

**Comment by burring55yali** [comment]
我也发现这个问题了 还有屏幕快照 也不显示  在所有照片目录下也不显示
<img width="441" alt="2017-10-18 10 56 40" src="https://user-images.githubusercontent.com/13936964/31699115-b5363882-b3f3-11e7-9b56-fb276477fff8.png">

**Comment by longitachi** [comment]
@burring55yali 图一是什么？屏幕快照是有显示的吧，我这边真机上都可以，人物这个相册倒是没有取，所以并没有这个

**Comment by burring55yali** [comment]
@longitachi  图一是用这个图片选着器进去的相册 图二是从系统照片点进去的相册 图二可以看到《所有照片》目录下有1156张 但是从选择器 进去只能显示了图一的1张  还有一些相册没读到 用系统的imagepicker的话是能显示出来的

**Comment by longitachi** [comment]
这个图一不是我这个框架的效果吧？

**Comment by longitachi** [comment]
这种情况是在什么版本的系统上出现的

**Comment by burring55yali** [comment]
这个问题我找到原因了 如果选择了优化iPhone储存空间的话 系统相册里的图片会以缩略图的形式保存在本地浏览的时候再进行加载 这种情况下ZL这个选择器是没有读取到缩率图状态下这些图片 想读取到的话需要去系统的照片里浏览下这张照片 （状态栏上会有菊花转动）然后再去用zl选择器选图的时候就会读取到
使用iCloud的情况下 从 设置>照片与相机>优化iPhone储存空间 可以找到这个优化储存的选项
