### ISSUE TITLE
建议增加个oc版本的demo，swift实在整不明白，oc项目pod进去使用各种报错

### ISSUE THREAD

**Issue by jacky8293676** [longitachi/ZLPhotoBrowser#590]
#### Description and Steps

建议增加个oc版本的demo，swift实在整不明白，oc项目pod进去使用各种报错

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.3
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
具体使用可查看[Wiki](https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(objc))

**Comment by jacky8293676** [comment]
感谢作者大佬的回复，我要实现如下效果图，但现在遇到一些问题
1、实现图片和视频同时显示，但只能二选一，不知道要怎么设置
2、我需要在显示列表是导航栏是白色，点击进去预览页是黑色的想过，但目前看好像是全局一个变量来决定？或者能怎么解决么
![image](https://user-images.githubusercontent.com/3843632/109757901-a8a5bb80-7c25-11eb-822e-23c413a31882.png)

**Comment by longitachi** [comment]
第一个设置`allowMixSelect = false`即可
第二个现在导航和底部toolbar是统一的，你可以自己fork改下代码，或者跟你们的设计争取下统一黑色
