### ISSUE TITLE
ZLThumbnailColViewFooter 样式看起来不像是点击的样式

### ISSUE THREAD

**Issue by lionnner** [longitachi/ZLPhotoBrowser#592]
是否考虑这种样式呢？现有的样式大多数用户不知道是可以点击的。
![657BF282-3008-4533-9911-5336EB98A6FA](https://user-images.githubusercontent.com/19425203/110204088-27ac2580-7eac-11eb-9c43-f526d4fcc465.png)

**Comment by longitachi** [comment]
好的，这个提示会参考微信做一个优化，在下个版本发布时会添加这个功能

**Comment by longitachi** [comment]
4.1.4版本已更新，优化了limit权限下"去设置"的提示
