### ISSUE TITLE
OC数组不支持基本数据类型，editImageTools调不了

### ISSUE THREAD

**Issue by kai-liu** [longitachi/ZLPhotoBrowser#593]
### Issue Description

为什么不用处理裁剪比例的方式处理可选编辑类型呢

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.4
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
裁剪比例要开发者自己传入title，宽高比，所以选择用了class（oc数组也没办法添加struct，不然就用struct了- -）。编辑类型则更适合用一个enum类型。
oc数组不支持enum类型，要使用的话可能麻烦点。。。可以创建一个swift文件专门用于调用`ZLPhotoBrowser`
