### ISSUE TITLE
关于配置类的问题

### ISSUE THREAD

**Issue by LiuSky** [longitachi/ZLPhotoBrowser#594]
### Issue Description
 假设我在A界面设置了editImageClipRatios为2:1，但是我其他的界面还想保持原有的，我必须得在其他的界面把他设置为默认值才可以，有没有一种办法不影响到全局的这个配置。或者恢复初始状态？
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.4
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
暂时没有恢复初始状态的方法，你举的这个例子可以将`configuration`的配置代码写在调用框架的方法里，如
```swift
func callPhotoLibrary() {
    // 初始化配置
    let config = ZLPhotoConfiguration.default()
    config.editImageClipRatios = [.wh2x1]
    ...
    // 调用相册
    ...
}
```

**Comment by LiuSky** [comment]
嗯，后续考虑增加下，因为场景是我的项目有3个地方，每个地方的设置都不一样，然后我要设置A，我就要知道BC设置了那些，然后并且把它们重置，反之BC也一样，以后再来一个D我就要知道这些地方的设置，才可以。不然就会影响到。目前我自己封装了一层来重置。可以考虑下。

**Comment by longitachi** [comment]
哪个地方调用哪个地方直接设置，为什么A地方调用时候要知道B和C设置了哪些呢？

**Comment by LiuSky** [comment]
我A设置了编辑为2:1.但是在B的地方要恢复过来，如果我不设置，他会延续着A的2:1.😄

**Comment by longitachi** [comment]
```
class A {
    func callPhotoLibrary() {
        // 初始化配置
        let config = ZLPhotoConfiguration.default()
        config.editImageClipRatios = [.wh2x1]
        ...
        // 调用相册
        ...
    }
}
```
```
class B {
    func callPhotoLibrary() {
        // 初始化配置
        let config = ZLPhotoConfiguration.default()
        config.editImageClipRatios = [.custom]
        ...
        // 调用相册
        ...
    }
}
```
```
class C {
    func callPhotoLibrary() {
        // 初始化配置
        let config = ZLPhotoConfiguration.default()
        config.editImageClipRatios = [.wh2x1, .custom, .wh1x1]
        ...
        // 调用相册
        ...
    }
}
```
配置代码这么写这样不就好了吗

**Comment by LiuSky** [comment]
那是不是我上面说的。我的裁剪用的是你的默认值，只有一个地方是自定义2:1， 而且只是一个属性我就要这样子记住，重点是我用了3-4个，我都要重置。没事，我自己修改了一份。你内部能提供最好。不能提供也没事😂

**Comment by longitachi** [comment]
> 那是不是我上面说的。我的裁剪用的是你的默认值，只有一个地方是自定义2:1， 而且只是一个属性我就要这样子记住，重点是我用了3-4个，我都要重置。没事，我自己修改了一份。你内部能提供最好。不能提供也没事😂

好的，理解你的意思了，后面我考虑下

**Comment by LiuSky** [comment]
> > 那是不是我上面说的。我的裁剪用的是你的默认值，只有一个地方是自定义2:1， 而且只是一个属性我就要这样子记住，重点是我用了3-4个，我都要重置。没事，我自己修改了一份。你内部能提供最好。不能提供也没事😂
> 
> 好的，理解你的意思了，后面我考虑下

那我先关闭了。

**Comment by chinghoi** [comment]
> ```
> class A {
>     func callPhotoLibrary() {
>         // 初始化配置
>         let config = ZLPhotoConfiguration.default()
>         config.editImageClipRatios = [.wh2x1]
>         ...
>         // 调用相册
>         ...
>     }
> }
> ```
> 
> ```
> class B {
>     func callPhotoLibrary() {
>         // 初始化配置
>         let config = ZLPhotoConfiguration.default()
>         config.editImageClipRatios = [.custom]
>         ...
>         // 调用相册
>         ...
>     }
> }
> ```
> 
> ```
> class C {
>     func callPhotoLibrary() {
>         // 初始化配置
>         let config = ZLPhotoConfiguration.default()
>         config.editImageClipRatios = [.wh2x1, .custom, .wh1x1]
>         ...
>         // 调用相册
>         ...
>     }
> }
> ```
> 
> 配置代码这么写这样不就好了吗

因为这样很不swift😂

**Comment by longitachi** [comment]
已经提供了 `resetConfiguration` 进行配置类的重置
