### ISSUE TITLE
fetchImage 为什么会执行两次？

### ISSUE THREAD

**Issue by ChristingLi** [longitachi/ZLPhotoBrowser#595]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.4
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```
不知到什么原因fetchImage会执行两次？？

**Comment by NickMeepo** [comment]
func fetchImage(for asset: PHAsset) {
        let option = PHImageRequestOptions()
        option.resizeMode = resizeMode
        option.isNetworkAccessAllowed = true
}
option需要再设置option.isSynchronous = true
否则回调会执行两次。

**Comment by ChristingLi** [comment]
> ```swift
> static func fetchImage(for asset: PHAsset) {
>     let option = PHImageRequestOptions()
>     option.resizeMode = resizeMode
>     option.isNetworkAccessAllowed = true
>     // Need fixed to add: option.isSynchronous = true
> }
> ```
> 
> option需要再设置option.isSynchronous = true
> 否则回调会执行两次。

感谢。已经查到了原因。
除此之外指定 deliveryMode 也可以解决这个问题。
