### ISSUE TITLE
图片预览放大后滑动到其他图片再回来，图片缩放比例错误。【见视频】

### ISSUE THREAD

**Issue by WUYUEZONG** [longitachi/ZLPhotoBrowser#596]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.4
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
  见视频
   ```

https://user-images.githubusercontent.com/19921783/112921184-e7ebfd00-913c-11eb-9ced-ca1ad414bf54.mov

**Comment by longitachi** [comment]
好的，会在下个版本进行修复
