### ISSUE TITLE
怎样显示url图片或者视频？怎样混合处理image，url，PHAsset资源？

### ISSUE THREAD

**Issue by mc3747** [longitachi/ZLPhotoBrowser#598]
### Issue Description
问题1：
相册中怎样显示url图片，或者视频？
问题2：
相册中既有相册PHAsset资源，又有image资源，又有url资源的时候，怎样混合显示和筛选？
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.5
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(Swift)#Preview-PHAsset-local-image-local-video-network-image-network-video-together

**Comment by mc3747** [comment]
好的，谢谢，有点思路了：可以在相册中自己生成一张url视频预览图片，点击后将url传入ZLImagePreviewController
