### ISSUE TITLE
相机问题

### ISSUE THREAD

**Issue by guo11154** [longitachi/ZLPhotoBrowser#599]
### Issue Description
每次启动程序，第一次打开相机页面发白，然后翻转摄像头发白情况更严重，重复直至相机页面全是白色！
然后关闭摄像头重新打开相机就好了。
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  4.1.5
   Device:  iPhone XS Max
   Device version:  iOS 14.3
   Xcode version:   Xcode 12.3

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
你把`ZLCustomCamera.swift`类中的第686行代码改成这个试下`self.focusCamera(mode: .continuousAutoFocus, exposureMode: .continuousAutoExposure, point: cameraPoint)`

**Comment by guo11154** [comment]
> 你把`ZLCustomCamera.swift`类中的第686行代码改成这个试下`self.focusCamera(mode: .continuousAutoFocus, exposureMode: .continuousAutoExposure, point: cameraPoint)`

好了
