### ISSUE TITLE
图片预览问题

### ISSUE THREAD

**Issue by feaskters** [longitachi/ZLPhotoBrowser#600]
### Issue Description

图片预览的时候放大图片，并左右滑动，会闪退

#### Description and Steps

example中也存在此问题。
1. 点击preview local and net image
2. 双指放大一张图片
3. 滑动到另一张图片
4. 报错  Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file ZLPhotoBrowser/ZLPhotoPreviewCell.swift, line 1071

#### Info
   ZLPhotoBrowser version:  4.1.5
   Device: iPhone XR
   Device version:  iOS 14.4.2
   Xcode version: Xcode 12.4

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
你说的应该是这个bug，#556 `4.1.1`版本已经修复，升级下版本就可以了
