### ISSUE TITLE
通过pod导入4.1.5版本，找不到ZLPhotoConfiguration.default().cameraConfiguration

### ISSUE THREAD

**Issue by SurvivalBest** [longitachi/ZLPhotoBrowser#604]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.5
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
这个是暂未发版的功能，`4.1.5`对相机的配置可已使用`ZLPhotoConfiguration.default().sessionPreset` `ZLPhotoConfiguration.default().flashMode`等
