### ISSUE TITLE
建议：希望能增加个直接进入相机拍照或录视频的入口

### ISSUE THREAD

**Issue by jun-hui** [longitachi/ZLPhotoBrowser#605]
如题

**Comment by longitachi** [comment]
直接使用相机可参考[wiki](https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(Swift)#Use-custom-camera)
`ZLCameraConfiguration`为未发布功能，当前版本可使用`ZLPhotoConfiguration.default().sessionPreset`、``ZLPhotoConfiguration.default().flashMode` 等进行设置

**Comment by jun-hui** [comment]
使用ZLCustomCamera录了视频后能返回封面图image吗？或者PHAsset也行，现在只返回了一个NSURL

**Comment by longitachi** [comment]
可以参考下demo，录制后需要你自己对视频进行保存，相机本身不提供保存到相册功能

**Comment by jun-hui** [comment]
好吧，谢谢
