### ISSUE TITLE
自定义相机能否加配置项，拍照之后可选是否编辑，以及是否需要长按拍摄视频的功能

### ISSUE THREAD

**Issue by simpleLiYu** [longitachi/ZLPhotoBrowser#608]
作者你好。请问自定义相机能否加配置项，拍照之后可选是否编辑，以及是否需要长按拍摄视频的功能。

**Comment by longitachi** [comment]
`@objc public var allowEditImage = true`
`@objc public var allowRecordVideo: Bool`
更多参数可查看`ZLPhotoConfiguration`

**Comment by simpleLiYu** [comment]
单独使用自定义相机的时候这个配置可以使用吗，还望指导一下感谢
let camera = ZLCustomCamera()
这样调出自定义相机是不是没办法配置呢

**Comment by longitachi** [comment]
单独使用也是用`ZLPhotoConfiguration`进行配置的，`ZLPhotoConfiguration`是全局的，对整个`framework`有效
