### ISSUE TITLE
提点建议

### ISSUE THREAD

**Issue by DemonLover** [longitachi/ZLPhotoBrowser#61]
您写的正不错,提一个小小的建议:拍照的那个按钮背景支持相机预览(就是相册里第一个拍照按钮的背景上显示的是相机的预览图层和一个小相机图标)我之前见过一个App有这么一个功能 想不起来是哪个了 好尴尬。

**Comment by longitachi** [comment]
是简书吧，我也看到了，挺不错的，谢谢。会考虑加进去的
