### ISSUE TITLE
oc调用swift报错 

### ISSUE THREAD

**Issue by a85265656** [longitachi/ZLPhotoBrowser#612]
-Swif.h 文件内报错。 使用的最新版4.1.6
资料查了不少 折腾一整天 没有任何解决方法。。。。。。
Cannot find protocol declaration for 'PHPhotoLibraryChangeObserver'
Cannot find protocol declaration for 'AVCapturePhotoCaptureDelegate'
Expected a type
求提点。。。。

**Comment by longitachi** [comment]
是按照这个[链接](https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(objc)#How-to-import-header)导入的吗？
