### ISSUE TITLE
请问有在ZLPhotoConfiguration中有闭关选择iCould选择的属性吗？

### ISSUE THREAD

**Issue by YWDrenched** [longitachi/ZLPhotoBrowser#614]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.6
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
现在是没有的，如果手机开启了将照片上传到iCloud的话，相片应该都会在iCloud上（iCloud备份空间足够的话），那样几乎所有照片都会被限制选择了

**Comment by YWDrenched** [comment]
那我自己需要实现这样的需求，是否可以将fetchVideo中的isNetworkAccessAllowed改为false

**Comment by longitachi** [comment]
是的，`isNetworkAccessAllowed`是控制是否取网络图片的，可以配合`@objc public var canSelectAsset: ( (PHAsset) -> Bool )?`控制是否可选
