### ISSUE TITLE
carthage update以后报错

### ISSUE THREAD

**Issue by theLastCc** [longitachi/ZLPhotoBrowser#615]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 3.2.0
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.5
   Xcode version:  e.g. Xcode 12.5

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

执行 carthage update --platform iOS   

提示有相同的架构(arm64)，不能输出相同文件，如何解决

*** Building scheme "SDWebImage" in SDWebImage.xcodeproj
A shell task (/usr/bin/xcrun lipo -create /Users/xx/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5_12E262/SDWebImage/5.11.1/Build/Intermediates.noindex/ArchiveIntermediates/SDWebImage/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SDWebImage.framework/SDWebImage /Users/xx/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5_12E262/SDWebImage/5.11.1/Build/Products/Release-iphonesimulator/SDWebImage.framework/SDWebImage -output /Users/xx/Desktop/ZLPhotoBrowser-3.2.0/Carthage/Build/iOS/SDWebImage.framework/SDWebImage) failed with exit code 1:
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/xx/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5_12E262/SDWebImage/5.11.1/Build/Intermediates.noindex/ArchiveIntermediates/SDWebImage/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SDWebImage.framework/SDWebImage and /Users/xx/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5_12E262/SDWebImage/5.11.1/Build/Products/Release-iphonesimulator/SDWebImage.framework/SDWebImage have the same architectures (arm64) and can't be in the same fat output file

Building universal frameworks with common architectures is not possible. The device and simulator slices for "SDWebImage" both build for: arm64
Rebuild with --use-xcframeworks to create an xcframework bundle instead.
xxdeiMac:ZLPhotoBrowser-3.2.0 xx$

**Comment by longitachi** [comment]
你使用的是oc版本的吗？建议使用swift版本吧。oc版本不维护了。

**Comment by theLastCc** [comment]
> 你使用的是oc版本的吗？建议使用swift版本吧。oc版本不维护了。

我要用他的代码，需要跑起来看看是如何实现的。 运行不起来，不好跟踪。

**Comment by longitachi** [comment]
使用这个`carthage update --use-xcframeworks --platform iOS`
