### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by MrBugDou** [longitachi/ZLPhotoBrowser#619]
### Issue Description
场景是这样的，我们的用户可以上传图片到用户相册（只能单张上传，并且需要裁剪到固定比例，重点是还需要用户选择是否属于阅后即焚图片）

如图（设计稿）
![image](https://user-images.githubusercontent.com/12947653/121465123-c01ede00-c9a4-11eb-8923-618a3145e523.png)

我想请问一下，如何自定义下面这一块的 toolbar呢？
我尝试了做扩展，但是似乎没有作用，请问有别的办法么能够实现，曲线救国一下么😂，加在裁剪的视图上也可以，但是ZLClipImageViewController 这个类好像不是公开的

#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  4.1.6

#### Configuration code of `ZLPhotoConfiguration`

        let config = ZLPhotoConfiguration.default()
        config.allowEditImage = true
        config.editImageClipRatios = [.init(title: "相册", whRatio: 0.6)]
        config.editAfterSelectThumbnailImage = true
        config.showClipDirectlyIfOnlyHasClipTool = true
        config.maxSelectCount = maxSelectCount
        config.saveNewImageAfterEdit = false
        config.allowSelectVideo = false
        config.editImageTools = [.clip]
        config.allowSelectImage = true
        config.allowMixSelect = true

        let ps = ZLPhotoPreviewSheet()
        ps.selectImageBlock = block
        ps.showPhotoLibrary(sender: self)

**Comment by longitachi** [comment]
tabbar样式暂不支持自定义，不过图片和文字还有颜色可以自定义，具体看这个[链接](https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(Swift)#Customize-image-resource) 原图使用的图片名字是`zl_btn_original_circle`和`zl_btn_original_selected`，你这个要把原图功能看成阅后即焚就行了。。。 不过原图返回的图片资源较大，可根据需要进行压缩

**Comment by MrBugDou** [comment]
好的，我试试看，还有个问题就是，我怎么才能取到ZLThumbnailViewController和ZLPhotoPreviewController这两个控制器呢，因为我看demo使用的是ZLPhotoPreviewSheet，没有直接使用上面的两个类
