### ISSUE TITLE
关于单击图片显示预览

### ISSUE THREAD

**Issue by LearnerTi** [longitachi/ZLPhotoBrowser#620]
怎么像微信图片浏览那样，单击图片全屏显示，可以左右滑动，再单击全屏的图片可以返回？如果非要单击返回按钮或者完成按钮才能返回，图片预览操作性是不是差一点。

**Comment by longitachi** [comment]
你说的应该是图片浏览器，这个框架是进入相册选择图片的，微信朋友圈那种图片浏览的可以搜一个图片浏览器的框架

**Comment by LearnerTi** [comment]
有没有推荐的图片浏览器啊...这个框架增加图片浏览的功能会不会很麻烦

**Comment by longitachi** [comment]
后期看下，等有空了可以提供一个图片浏览器的功能，最近太忙了- -

**Comment by LearnerTi** [comment]
非常感谢。Star 👍 💯
