### ISSUE TITLE
当相册权限选择“选中的照片”时每次进入相册都会弹出申请权限的弹框，可以不弹出这个弹框吗？（用户已经选择了）

### ISSUE THREAD

**Issue by GitHubXuLiying** [longitachi/ZLPhotoBrowser#622]
#### Description and Steps

1. 相册权限选择“选中的照片”
2. 进入相册
3. 会弹出申请相册权限的弹框

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.6
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

![image](https://user-images.githubusercontent.com/16660305/123397403-f67b7080-d5d4-11eb-8402-37b8449adbe8.png)

**Comment by longitachi** [comment]
`info.plist` 添加 `PHPhotoLibraryPreventAutomaticLimited` 值设置为 `YES` 就好了，这个是系统的行为
