### ISSUE TITLE
在UISplitController中使用无法点击Cancel Btn和Done Btn

### ISSUE THREAD

**Issue by kanehaday** [longitachi/ZLPhotoBrowser#623]
#### Info
   ZLPhotoBrowser version:  e.g. 4.1.6
   Device:  iPad
   Device version:  e.g. iOS 14.5
   Xcode version:  e.g. Xcode 12.5.1

#### Configuration code of `ZLPhotoConfiguration`

  let ps = ZLPhotoPreviewSheet()
        
        ps.selectImageBlock = { [weak self] (images, assets, isOriginal) in
            print("done")
        }
        
        ps.cancelBlock = {
            debugPrint("cancel select")
        }
        
        ps.showPhotoLibrary(sender: self)

请教一下大佬，我在UISplitController中使用ZLPhotoBrowser，在detail控制器中用以上代码调用相册，照片选择器页面出现后可以正常选择照片，可以点击左下角preview按钮，可以点击Full Image，也可以切换相册分组。但是cancel和done都无法点击，打印的内容断点也没进去

**Comment by longitachi** [comment]
能提供个demo吗，没这么用过

**Comment by kanehaday** [comment]
Hi,大佬
    demo是我项目里的一个页面，运行在iPad上的，我在DetailViewController类的第159行调用了ZLPhotoBrowser，运行起来的话在tableview第一个cell里有一个相机按钮。目前还是Cancel按钮和Done按钮不能点击，但是另外的按钮都正常。可能是UISplitViewController的导航控制器的限制，但是我不太确定。
另外就是因为我这个项目需要保持横屏，预览edit照片的时候会报一个屏幕旋转的崩溃，我是不是可以在预览的相关类里吧autoRotate置为false呢。
















在 2021-06-28 18:55:33，"long" ***@***.***> 写道：

能提供个demo吗，没这么用过

**Comment by longitachi** [comment]
现在编辑图片`ZLEditImageViewController` 有声明只支持竖屏
```swift
public override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
    return .portrait
}
```
crash可能跟这个有关，你可以自己fork代码改一下，另外你可以新建个项目，只把你的问题简单的写个demo上传一下，或者直接发我邮件 495181165@qq.com

**Comment by kanehaday** [comment]
demo我已经发到大佬邮箱了

**Comment by longitachi** [comment]
这个应该是你的用法问题
调用相册前，你的splitvc的 `viewControllers` 是 `[<UINavigationController: 0x7f858b015c00>, <UINavigationController: 0x7f858981b800>]`
相册出来后变成了 `[<UINavigationController: 0x7f858b015c00>, <ZLPhotoBrowser.ZLImageNavController: 0x7f8588857400>]`
之前的vc释放了，导致了后续的问题

**Comment by kanehaday** [comment]
我改了一下showThumbnailViewController这个方法，showDetailViewController改成present之后正常了，谢谢大佬解答
