### ISSUE TITLE
在ZLImagePreviewController中，如何去掉右下角的“确定”按钮？

### ISSUE THREAD

**Issue by aluzi992** [longitachi/ZLPhotoBrowser#626]
1、我使用ZLImagePreviewController去浏览器一组指定的网络图片，但是我发现ZLImagePreviewController中，右下角有一个确定按钮，右上角还有一个圆圈，请问如何将这些按钮去掉？
2、如果想增加一个按钮（实现“保存到相册”的功能），是否必须继承ZLImagePreviewController做一个自定义的类？有更便捷的方法吗？
![QQ20210701-140840](https://user-images.githubusercontent.com/73816915/124074320-e3a1e980-da75-11eb-8280-4e2b5a19178e.png)

**Comment by longitachi** [comment]
1. `ZLImagePreviewController` 的初始化方法参数看下，支持不显示bottomBar和右上角选择按钮的 配置
```swift
/// - Parameters:
///   - datas: Must be one of PHAsset, UIImage and URL, will filter ohers in init function.
///   - showBottomView: If showSelectBtn is true, showBottomView is always true.
///   - index: Index for first display.
///   - urlType: Tell me the url is image or video.
///   - urlImageLoader: Called when cell will display, cell will layout after callback when image load finish. The first block is progress callback, second is load finish callback.
@objc public init(datas: [Any], index: Int = 0, showSelectBtn: Bool = true, showBottomView: Bool = true, urlType: ( (URL) -> ZLURLType )? = nil, urlImageLoader: ( (URL, UIImageView, @escaping ( (CGFloat) -> Void ),  @escaping ( () -> Void )) -> Void )? = nil) {
}
```
2. 暂不支持自定义按钮，继承这个类的话，应该拿不到内部的一些参数，你可以试下，不行的话就fork下

**Comment by aluzi992** [comment]
谢谢，修改启动参数之后确定按钮可以隐藏了。
另外我尝试继承ZLImagePreviewController，结果提示说这个类不是开放的，无法继承...
Cannot inherit from non-open class 'ZLImagePreviewController' outside of its defining module

然后我发现在ZLImagePreviewController里面，长按图片会出现保存选项，但问题：
1、保存按钮是灰色的，虽然可以点，但会让用户以为不能点...为什么它是灰色的呢？
2、保存之后没有提示
希望能像微信查看图片的时候，右下角直接有一个保存按钮好了！

最后，请问如何手工安装ZlPhotoBrowser？我尝试将Source文件夹添加到工程里面，编译就报错说“Multiple commands produce”。我希望手工安装的原因是想修改部分代码，实现客户的一些特殊需求。

**Comment by longitachi** [comment]
`Source`文件夹拖进去，要把里面的`info.plist`文件删除，报错信息应该报的有吧
