### ISSUE TITLE
在无网络时选择视频问题

### ISSUE THREAD

**Issue by WhiteRainbow** [longitachi/ZLPhotoBrowser#627]
在没有网络的情况下选择相册的视频，会提示“正在处理...”之后就提示"请求超时"。这里有网络请求吗？Demo里也会这样

**Comment by longitachi** [comment]
如果视频在iCloud上就会请求网络

**Comment by WhiteRainbow** [comment]
> 如果视频在iCloud上就会请求网络

这个可以设置吗。 直接获取相册选中的图片或视频就好

**Comment by longitachi** [comment]
在iCloud上的asset没法获取图片或者视频封面图，如果只需要asset对象，不需要框架解析，`shouldAnialysisAsset` 设置为 `false` 就好了

**Comment by WhiteRainbow** [comment]
这个属性确实有用，但我发现设置false之后，图片编辑受到了影响，编辑了完成之后拿到的还是编辑前的图...

**Comment by WhiteRainbow** [comment]
这个属性设置false之后有个其他问题，就是图片编辑后获取到的还是编辑前的图片

**Comment by longitachi** [comment]
因为不允许解析，所以直接把asset返回了，没返回编辑后的图片，这是一个bug，后续看下，你既然能编辑，说明能请求网络，所以干嘛禁掉shouldAnialysisAsset呢。。

**Comment by WhiteRainbow** [comment]
因为是在内网，没连接互联网。但是选了图片之后又可能需要剪裁，所有有了以上的问题

**Comment by longitachi** [comment]
编辑图片时候是需要请求网络拿到稍微大点的图，没有连接互联网，那应该请求不下来吧，或者说你的图片都是在本地吗

**Comment by WhiteRainbow** [comment]
不是对从相册选取的图片进行编辑吗。场景是内网，不考虑iCloud上的图片。
