### ISSUE TITLE
OC版本是否有传入网络URL，浏览图片的功能？

### ISSUE THREAD

**Issue by LinJiaXing1102** [longitachi/ZLPhotoBrowser#628]
OC版本是否有传入网络URL，浏览图片的功能？

**Comment by longitachi** [comment]
有的
https://github.com/longitachi/ZLPhotoBrowser-objc/blob/53509aca73c507ed409de5a9971fe26a775018c5/ZLPhotoBrowser/PhotoBrowser/ZLPhotoActionSheet.h#L93-L103

**Comment by LinJiaXing1102** [comment]
也是醉了，居然没看到，时间紧迫，参照代码写了一个浏览器😹
