### ISSUE TITLE
ZLPhotoPreviewController 页面闪退

### ISSUE THREAD

**Issue by zk12345** [longitachi/ZLPhotoBrowser#629]
机型：iPhone7  iOS14.1 
从相册列表点击图片进入ZLPhotoPreviewController查看大图，然后在图片上手指滑动会闪退，报错代码是
        if ZLPhotoConfiguration.default().showSelectedPhotoPreview {
            let nav = self.navigationController as! ZLImageNavController
            if !nav.arrSelectedModels.isEmpty {
                showSelPhotoPreview = true
                bottomViewH += ZLPhotoPreviewController.selPhotoPreviewH
                self.selPhotoPreview?.frame = CGRect(x: 0, y: 0, width: self.view.frame.width, height: ZLPhotoPreviewController.selPhotoPreviewH)
            }
        }

中的  let nav = self.navigationController as! ZLImageNavController

**Comment by longitachi** [comment]
看这个代码是在`refreshBottomViewFrame`这个方法里手指上滑不会走这个方法，是不是crash定位错了？

**Comment by zk12345** [comment]
确实是这里，但很奇怪的是我们这里的俩个iphone7都会在这里报错。
其他机型不会，并且确实不走这个方法

**Comment by zk12345** [comment]
![Uploading 1625706492714.jpg…]()

**Comment by zk12345** [comment]
![1625706492714](https://user-images.githubusercontent.com/13864286/124847224-029c0080-dfcd-11eb-8768-ec57bdbf0290.jpg)

**Comment by longitachi** [comment]
是哪个版本？你在这个地方打下断点，看下 self.navigationController 是什么类，你调试下看看，我这边没有这个设备，得下个模拟器看

**Comment by zk12345** [comment]
最新版本4.1.6，self.navigationController = nil

**Comment by longitachi** [comment]
下载了个iOS14.1的模拟器，机型最低只有iPhone8，试了下不会闪退，这个地方我修改下强解包吧
