### ISSUE TITLE
选择一张照片 点击预览 进去预览界面 点击左上角 取消选中状态 在点击设置选择 程序崩溃

### ISSUE THREAD

**Issue by hongsechengzi** [longitachi/ZLPhotoBrowser#63]
问题没有解决, 拍照图片点击预览,还是数组越界

**Comment by yangyang2015** [comment]
的确会闪退诶

**Comment by longitachi** [comment]
能详细说下步骤吗，  我现在步骤是“进入相册->直接点击拍照(拍照后默认选择已拍照的)->然后直接点击预览->预览界面直接左上角返回->取消选择刚才拍照的照片->再次选择刚才拍照的照片” 我这边没有问题

**Comment by longitachi** [comment]
已解决
