### ISSUE TITLE
在系统14.6情况下，使用视频选择框架，视频压缩失败

### ISSUE THREAD

**Issue by sysworker** [longitachi/ZLPhotoBrowser#630]
#### Description and Steps

在iOS14.5或者其他系统上面使用没有问题，iOS14.6上会压缩失败，无法获取data

                [ZLPhotoManager exportVideoForAsset:assets.firstObject type:ZLExportVideoTypeMp4 complete:^(NSString *exportFilePath, NSError *error) {
                    NSData *data = [NSData dataWithContentsOfFile:exportFilePath];
}];

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.6
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by sysworker** [comment]
今天来发现是因为在iOS14.6上面使用iCloud视频会导致闪退

**Comment by longitachi** [comment]
看代码是oc版本的吧。抽空我看下吧，oc版本后续基本不再维护了，有空了我会把导出视频的功能加到Swift版本上面

**Comment by longitachi** [comment]
oc版本已修复，更新1.0.4即可

**Comment by sysworker** [comment]
我更新后OC最新版本是3.2.0，还是有这个问题存在，是我这操作问题吗？

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser-objc  OC版本迁出去了，看这个repo

**Comment by sysworker** [comment]
谢谢，我目前修改了发送模式
