### ISSUE TITLE
统计到一个Crash，Exception 6, Code 16380696, Subcode 8。ZLThumbnailViewController.photoLibraryDidChange ZLThumbnailViewController.swift:1183

### ISSUE THREAD

**Issue by GitHubXuLiying** [longitachi/ZLPhotoBrowser#632]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.6
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
有重现步骤吗

**Comment by zhengziyan19** [comment]
@longitachi  是因为本地相册有变动时会触发photoLibraryDidChange回调，如果此时用户已选择完成，退出界面。   ZLThumbnailViewController的1208行异步运行还对self.navigationController 做强转引用。导致转换失败。这里应可选转换，不成功代表页面已收起，后续刷新逻辑就不用执行了

**Comment by longitachi** [comment]
@zhengziyan19 好的，感谢提出，后续修改下强转的地方

**Comment by longitachi** [comment]
升级版本即可，强转的问题之前已经修复过了
