### ISSUE TITLE
请教一下拍照照片有点模糊是什么原因 系统照相机很清晰

### ISSUE THREAD

**Issue by KerwinCheung** [longitachi/ZLPhotoBrowser#633]
请教一下
seesion我尝试了设置
.hd1280x720,.hd4K3840x2160,.photo
他们出来的image都是一样的...

**Comment by longitachi** [comment]
在选择照片时候调用相机拍照，然后确认选择的时候，通过PHAsset获取照片后会对照片进行一个压缩。你试下直接调用相机，然后看下通过回调获取的照片质量，这里是直接返回的照片，没有压缩

**Comment by longitachi** [comment]
![image](https://user-images.githubusercontent.com/11711768/127092056-a147ae2a-1d25-4c6a-8132-807e924c474c.png)
验证了下，直接通过相机拿到的图片是没有压缩的

**Comment by KerwinCheung** [comment]
在做别的事情忘记回复了，我研究过了 和你这段代码没有关系 我在camera那边output断点查看未经处理的图像。
问题在imageoutput函数，我不知道新版本有没有修改 iOS11以上用 output photo这个代理函数输出的图像 比新函数清晰很多。
我下载的那个包的函数是iOS11以下的outputdata。
作者可以优化一下
感谢作者帮忙查找问题

**Comment by longitachi** [comment]
用的这个`AVCapturePhotoCaptureDelegate`里面的回调方法
```swift
    public func photoOutput(_ output: AVCapturePhotoOutput, didFinishProcessingPhoto photoSampleBuffer: CMSampleBuffer?, previewPhoto previewPhotoSampleBuffer: CMSampleBuffer?, resolvedSettings: AVCaptureResolvedPhotoSettings, bracketSettings: AVCaptureBracketedStillImageSettings?, error: Error?) {
        if photoSampleBuffer == nil || error != nil {
            zl_debugPrint("拍照失败 \(error?.localizedDescription ?? "")")
            return
        }
        
        if let data = AVCapturePhotoOutput.jpegPhotoDataRepresentation(forJPEGSampleBuffer: photoSampleBuffer!, previewPhotoSampleBuffer: previewPhotoSampleBuffer) {
            self.session.stopRunning()
            self.takedImage = UIImage(data: data)?.fixOrientation()
            self.takedImageView.image = self.takedImage
            self.takedImageView.isHidden = false
            self.resetSubViewStatus()
        } else {
            zl_debugPrint("拍照失败，data为空")
        }
    }
```

**Comment by KerwinCheung** [comment]
那个我详细说一下我遇到的模糊的问题是什么..
-------
`  public func photoOutput(_ output: AVCapturePhotoOutput, didFinishProcessingPhoto photo: AVCapturePhoto, error: Error?) {
        let cgImage = photo.cgImageRepresentation()?.takeUnretainedValue()
        let tempImg = UIImage.init(cgImage: cgImage!)
}`

` public func photoOutput(_ output: AVCapturePhotoOutput, didFinishProcessingPhoto photoSampleBuffer: CMSampleBuffer?, previewPhoto previewPhotoSampleBuffer: CMSampleBuffer?, resolvedSettings: AVCaptureResolvedPhotoSettings, bracketSettings: AVCaptureBracketedStillImageSettings?, error: Error?) {
        if photoSampleBuffer == nil || error != nil {
            zl_debugPrint("拍照失败 \(error?.localizedDescription ?? "")")
            return
        }
        
        if let data = AVCapturePhotoOutput.jpegPhotoDataRepresentation(forJPEGSampleBuffer: photoSampleBuffer!, previewPhotoSampleBuffer: previewPhotoSampleBuffer) {
            self.session.stopRunning()
            self.takedImage = UIImage(data: data)?.fixOrientation()
            
            self.takedImage = self.takedImage?.resize(CGSize(width: screenWidth, height: screenHeight - navHeight() - bottomHeight() - 100))
            
            self.takedImageView.image = self.takedImage
            self.takedImageView.isHidden = false
            self.resetSubViewStatus()
        } else {
            zl_debugPrint("拍照失败，data为空")
        }
    }`

photoOutput photo这个是iOS11以上才有的代理方法
对比了这2个函数里的image,确实 photoOutput photo函数里的图像清晰一点,说实话我一开始是没发现 photoOutputbuffer的图像有点不清晰...是设计看出来的 确实是有一点点的模糊了.
我是在这里输出的照片所以没有涉及到zlmanagerSavePhoto那段代码的问题,没有涉及到图片压缩的问题.
