### ISSUE TITLE
请问如何在拍照之后编辑照片？

### ISSUE THREAD

**Issue by aluzi992** [longitachi/ZLPhotoBrowser#634]
我看了wiki的代码，发现：
ZLPhotoConfiguration.default().cameraConfiguration
报错，已经没有“cameraConfiguration”属性了？
貌似已经整合到“ZLPhotoConfiguration.default()”里面？
但是里面有些属性找不到，所以最新的wiki有吗？

然后，请问在拍照之后能否直接编辑照片？
版本是：4.1.5

**Comment by longitachi** [comment]
[4.1.6](https://github.com/longitachi/ZLPhotoBrowser/releases/tag/4.1.6)才添加的`cameraConfiguration `
拍照后直接编辑照片，设置`ZLPhotoConfiguration.default().allowEditImage = true`就行了，拍照后左下角有个编辑按钮

**Comment by ZLXIAOXU** [comment]
拍完照之后不能直接进入裁剪界面吗？

**Comment by lionnner** [comment]
拍照之后确实无法直接进入编辑界面
这种业务场景无非就是一定要长宽达到某个比例的照片

**Comment by longitachi** [comment]
```swift
config.showClipDirectlyIfOnlyHasClipTool = true
config.editImageTools = [.clip]
```
这样设置拍照后可直接进裁剪界面，不过4.1.9版本有点bug，demo已修复

**Comment by ZClee128** [comment]
我发现拍照还是无法直接进入裁剪页面，4.5.4版本

**Comment by lingstart** [comment]
ZLPhotoConfiguration.default().allowEditImage = true
                ZLPhotoConfiguration.default().editImageConfiguration.clipRatios = [.wh1x1]
                ZLPhotoConfiguration.default().editImageConfiguration.tools = [.clip]
                ZLPhotoConfiguration.default().editImageConfiguration.showClipDirectlyIfOnlyHasClipTool = true
