### ISSUE TITLE
ZLPhotoPreviewSheet 的collectionView高度问题

### ISSUE THREAD

**Issue by devYoungyang** [longitachi/ZLPhotoBrowser#635]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.6
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.2
   Xcode version:  e.g. Xcode 12.5.1

#### Configuration code of `ZLPhotoConfiguration`

   ```
  let config = ZLPhotoConfiguration.default()
  config.maxSelectCount = 1
  config.maxPreviewCount = 0
  let ps = ZLPhotoPreviewSheet()
  ps.showPreview(animate: true, sender: self)

   ```
第一次会出现如下图现象，后面会正常，不知道出现这种状况的原因是什么
![IMG_0961](https://user-images.githubusercontent.com/17973681/127591602-c9bb7d86-f506-4b56-b7c2-0080da05c636.PNG)

**Comment by longitachi** [comment]
你可以尝试断点调试下，看哪个地方高度计算错误了，或者写个demo把复现场景写出来传一下。

**Comment by devYoungyang** [comment]
可能与我的代码哪里有冲突造成的，demo不能复现此问题
