### ISSUE TITLE
使用showPhotoLibrary显示相册的时候，能否默认选中一张指定照片？

### ISSUE THREAD

**Issue by aluzi992** [longitachi/ZLPhotoBrowser#637]
版本：4.1.5
我在控制器里面自己用PHAsset.fetchAssets等方法显示最近的照片供用户选择（因为要整合UI，所以不能用showPreview方法），用户还可以点击“相册”按钮，此时才会用showPhotoLibrary方法来显示相册。
但问题是，如果之前用户已经在控制器里面选中了一张照片，在打开相册之后，能否让这张照片默认就处于选中的状态呢？

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/2a93645e1dc0048b849808cbadcec72b8b31d951/Sources/General/ZLPhotoPreviewSheet.swift#L102-L103
传入已选中`PHAsset`对象即可

**Comment by aluzi992** [comment]
谢谢，确认OK！
