### ISSUE TITLE
选择图片时选中按钮变大

### ISSUE THREAD

**Issue by WcjiOS** [longitachi/ZLPhotoBrowser#639]
ZLPhotoBrowser version:  4.1.7
   Device version:  iOS 14.2
   Xcode version: Xcode 12.5.1

[选中图片后选中按钮放大后不会缩小
![WechatIMG6](https://user-images.githubusercontent.com/16459344/128451556-9aae75d3-2e31-477b-b5f4-47303adf5c40.jpeg)

**Comment by longitachi** [comment]
是直接运行的Demo吗？

**Comment by WcjiOS** [comment]
> 是直接运行的Demo吗？
不是 是放在项目内运行的
这是我的代码
let config = ZLPhotoConfiguration.default()

        config.languageType = .chineseSimplified
        config.allowSelectGif = false
        config.allowSelectVideo = false
        config.allowTakePhotoInLibrary = false
        config.allowSelectOriginal = false
        let ac = ZLPhotoPreviewSheet(selectedAssets:[])

        ac.selectImageBlock = { [weak self] (images, assets, isOriginal) in
          
        }
            ac.showPhotoLibrary(sender: self)

**Comment by longitachi** [comment]
用你这部分代码在最新版本Demo中测试了下，没发现问题。你提供下使用的框架版本和手机型号及系统。 
你先自己调试下，看是不是和项目中其他代码冲突了。

**Comment by WcjiOS** [comment]
> 用你这部分代码在最新版本Demo中测试了下，没有发现问题。你提供下使用的框架版本和手机型号及系统。
> 你自己先调试下，看是不是和项目中其他代码冲突了。

ZLPhotoBrowser 版本：4.1.7
设备版本：iOS 14.2
Xcode 版本：Xcode 12.5.1
手机型号 XSMax

我跑demo也看没问题 
但是在项目中就出现了这情况
我没想到哪里会发生冲突😭

**Comment by WcjiOS** [comment]
选中后变大 再点击进入预览界面返回后选中按钮就会恢复正常

**Comment by longitachi** [comment]
可先设置 `config.animateSelectBtnWhenSelect = false` 试试，不展示选择动画

**Comment by WcjiOS** [comment]
这个我试过了，只是不展示动画了，选中还是放大状态

**Comment by longitachi** [comment]
那你先在你项目里调试下吧，集成个FLEX 打断点啥的

**Comment by WcjiOS** [comment]
是代码冲突了，已经改过了
