### ISSUE TITLE
缩略图已勾选, 预览大图却显示图未勾选

### ISSUE THREAD

**Issue by yangyang2015** [longitachi/ZLPhotoBrowser#64]
打开相册
-->勾选随意勾选一张图
-->点击确定
-->再次打开相册
-->刚才第一次勾选的图片, 已经处于被勾选状态, 但是点击预览此张图片时,
预览大图中, 并未勾选. 
--> 在预览大图中手动勾选, 点击确定, 添加成功(重复了)

**Comment by longitachi** [comment]
我按照你说的步骤，没有出现这种情况啊。
