### ISSUE TITLE
Camera cannot turning on while calling

### ISSUE THREAD

**Issue by huseyinmetin** [longitachi/ZLPhotoBrowser#641]
### Issue Description
While I'm on calling, I wanna take a photo on camera but cannot turn on camera. it's stucking black screen. 
How can I solve this problem?

#### Description and Steps
1- Call to someone with GSM
2- Launch app
3- Select photo with image button in the app
4- Tap camera cell in thumbnail collection view

#### Info
   ZLPhotoBrowser version: 4.1.7
   Device: iPhone XS Max
   Device version: iOS 14.7
   Xcode version: Xcode 12.5.1

![Unknown](https://user-images.githubusercontent.com/30692724/129377153-42145577-7012-4f0e-bc10-6a107fe7211f.jpg)

**Comment by longitachi** [comment]
Fixed by this [commit](https://github.com/longitachi/ZLPhotoBrowser/commit/1f35073c41434070bc90d11892ceecdf538ea70b)

**Comment by huseyinmetin** [comment]
> Fixed by this [commit](https://github.com/longitachi/ZLPhotoBrowser/commit/1f35073c41434070bc90d11892ceecdf538ea70b)

Thank you so much!
