### ISSUE TITLE
预览网络视频的时候，如何设置用户身份验证信息？

### ISSUE THREAD

**Issue by aluzi992** [longitachi/ZLPhotoBrowser#642]
版本：4.1.5
请问，使用ZLImagePreviewController去预览网上的视频（mp4），视频需要用户名和密码才可以下载，我应该如何将用户验证信息（例如cookie或者密码）传给你？我用如下代码：
        let videoSuffixs = ["mp4", "mov", "avi", "rmvb", "rm", "flv", "3gp", "wmv", "vob", "dat", "m4v", "f4v", "mkv"] // and more suffixs
        let vc = ZLImagePreviewController(datas: datas, index: index, showSelectBtn: false) { (url) -> ZLURLType in
            if let sf = url.absoluteString.split(separator: ".").last, videoSuffixs.contains(String(sf)) {
                return .video
            } else {
                return .image
            }
        }
        urlImageLoader: {......}

预览视频的时候，黑屏没显示。查看过HTTP复服务器的日志，确认你请求视频文件的时候，并没有通过用户验证
如果是图片的话，按照你的例子，可以用kf去加载，而kf有设置身份验证的接口，但是视频应该怎么设置呢？

**Comment by longitachi** [comment]
你先在 `ZLPhotoPreviewCell` 中的 728 行代码 (`ZLNetVideoPreviewCell` 这个类)做如下修改看是否可以正常播放
```swift
func configureCell() {
    ...

    let asset = AVURLAsset(url: self.videoUrl, options: ["AVURLAssetHTTPHeaderFieldsKey": headers])
    let item = AVPlayerItem(asset: asset)
    self.player = AVPlayer(playerItem: item)

    ...
}
```
将你的token放到这个headers里，如果可以的话，我这边支持下。

**Comment by aluzi992** [comment]
我用SwiftPackage安装的，代码不能修改，要怎么才可以修改呢？
