### ISSUE TITLE
拍照或者录制视频时，麦克风权限问题

### ISSUE THREAD

**Issue by cp3hnu** [longitachi/ZLPhotoBrowser#643]
#### Description and Steps
ZLPhotoBrowser是一个很好用的库，非常感谢您们开源了这个库。
但是我用的时候遇到了一个问题。当我想拍照或者录制视频时，如果没有授权麦克风权限，不让我拍摄，直接退出了，麦克风权限只是录取声音，拍照和录制视频不应该依赖于它，录取视频时应该提示用户没有麦克风权限，不能录取声音，而不是直接退出录制。

例如这样
![IMG_4731](https://user-images.githubusercontent.com/6104542/131242033-f4ce3355-aa0a-479e-b45d-4c6fae026bd5.PNG)

**Comment by longitachi** [comment]
感谢建议，下个版本优化下这个

**Comment by cp3hnu** [comment]
非常感谢您的回复
