### ISSUE TITLE
预览图片的时候能否旋转图片？

### ISSUE THREAD

**Issue by aluzi992** [longitachi/ZLPhotoBrowser#646]
版本：4.1.5
我使用ZLImagePreviewController去预览一些图片，我的APP是固定竖向的，但是希望看图片的时候能够让图片以横向显示，所以能否加个旋转按钮？

**Comment by longitachi** [comment]
这个功能不支持，还没见过你描述的这种形式的图片浏览器，你可以fork下自己添加下
