### ISSUE TITLE
mediaSubtypes判断LivePhoto问题

### ISSUE THREAD

**Issue by skytoup** [longitachi/ZLPhotoBrowser#648]
https://github.com/longitachi/ZLPhotoBrowser/blob/3ee2715be793722e3c47ef2ec159f9a1ee7288e8/Sources/General/ZLPhotoModel.swift#L116

在一台`iPhone 11 Pro Max`发现`LivePhoto`的`mediaSubtypes` = 520, 导致无法识别`LivePhoto`

`mediaSubtypes`是`OptionSet`, 为什么不使用`mediaSubtypes.contains(.photoLive)`这种方式判断`LivePhoto`?

**Comment by longitachi** [comment]
emmm，没这么写是之前oc版本翻译过来的😂，你那边测试下如果改成这样是不是就好了
```swift
if asset.mediaSubtypes.contains(.photoLive) {
    return .livePhoto
}
```

**Comment by skytoup** [comment]
抄了被测试发现某些手机完全不识别的问题😂
测试了是可以的

**Comment by longitachi** [comment]
那我下个版本改成这样判断
