### ISSUE TITLE
Crash when cropping image on ZLThumbnailViewController

### ISSUE THREAD

**Issue by akshayskycap** [longitachi/ZLPhotoBrowser#649]
My app is crashing when I crop an image on ZLThumbnailViewController, I have no steps to reproduce this issue. 
PFA screenshot which will help you find out crash easily.

![Screenshot 2021-09-15 at 7 58 00 PM](https://user-images.githubusercontent.com/61276314/133452489-199e8057-8a89-4785-ad0b-15b798e8226e.png)
![Screenshot 2021-09-15 at 11 17 30 AM](https://user-images.githubusercontent.com/61276314/133452506-30ca2210-724c-42f1-8edb-f5b72444f33a.png)

**Comment by parulgarg004** [comment]
@longitachi can you please help?

**Comment by longitachi** [comment]
Does this bug recur every time?

**Comment by akshayskycap** [comment]
> Does this bug recur every time?

@longitachi Issue is fixed, Thanks for you response
