### ISSUE TITLE
4.1.8版本 AppStore 审核被拒CallKit —— 请先使用4.1.7版本

### ISSUE THREAD

**Issue by zhaoquntao** [longitachi/ZLPhotoBrowser#650]
AppStore 审核被拒 
Guideline 5.0 - Legal

Recently, the Chinese Ministry of Industry and Information Technology (MIIT) requested that CallKit functionality be deactivated in all apps available on the China App Store.

During our review, we found that your app currently includes CallKit functionality and has China listed as an available territory in App Store Connect.

   ```

**Comment by longitachi** [comment]
先使用上个版本吧

**Comment by a1906404** [comment]
哪个版本没callkit呢？

**Comment by longitachi** [comment]
@a1906404 4.1.7

**Comment by CoderMaurice** [comment]
我也被拒了，为啥突然加一个Callkit？

**Comment by longitachi** [comment]
@CoderMaurice 这个[issue](https://github.com/longitachi/ZLPhotoBrowser/issues/641) 会尽快修复，先暂时用4.1.7版本吧，不好意思

**Comment by meilbn** [comment]
Pod 上搜到的只有 4.1.8 版本的，没有 4.1.9，请问作者 push 成功了吗？
本地更新过 pods 了，pod update
