### ISSUE TITLE
您好，ZLPhotoConfiguration里是否有我进行相机拍照，拍照完成后不需要 再次dismiss 到相册页，页面直接全部dismiss掉，给予image回调结果即可？

### ISSUE THREAD

**Issue by dahhd** [longitachi/ZLPhotoBrowser#651]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.6
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 13.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
你的意思应该是直接调用相机对吧？是的话看这个[wiki](https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(Swift)#Use-custom-camera)

**Comment by birdmichael** [comment]
不是。。。照片后可以直接使用这张照片吗?
在使用ZLPhotoPreviewSheet这个模式

**Comment by longitachi** [comment]
先进相册再调用相机不支持这种操作

**Comment by birdmichael** [comment]
用户逻辑是这样的。。 
直接进去相册。然后旁边有拍照。。
其实这个拍照是作为选择照片的一部分。应该直接进去编辑页面或者成功回调了。。
但是现在还是留在相册界面。

**Comment by huhaharui** [comment]
请问解决这问题了吗？

**Comment by longitachi** [comment]
这个需求逻辑不太清楚，现在从相册界面进去相机是不支持的。
按照 @birdmichael 所描述的
1.如果未选择任何照片，拍照后返回所拍照的照片
2.如果已经选择部分照片，那拍照后是只返回拍照的照片还是携带之前已选择的照片

**Comment by longitachi** [comment]
这个功能不好实现，现在相机拍照和录像后只是返回了结果，还需要上层进行保存处理，所以避免不了相机`dismiss`后先显示相册界面
