### ISSUE TITLE
在指定选择图片模式 点击拍照/录像 确定后 dismiss后  底部确定按钮位置偏移 

### ISSUE THREAD

**Issue by Miles-Matheson** [longitachi/ZLPhotoBrowser#657]
在指定选择图片模式 点击拍照/录像 确定后 dismiss后  底部确定按钮位置偏移 

   ZLPhotoBrowser version:  e.g. 4.1.9
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 15.0.1
   Xcode version:  e.g. Xcode 13.0

**Comment by longitachi** [comment]
补一下配置代码和偏移的截图吧

**Comment by Miles-Matheson** [comment]
下面是配置代码
![image](https://user-images.githubusercontent.com/19796675/141389571-69c2e2ee-5c93-42d9-a6d4-efe66f18b411.png)

![IMG_0932](https://user-images.githubusercontent.com/19796675/141389555-34fb687d-7233-4855-b6b7-099094c8f262.PNG)
