### ISSUE TITLE
单张选择，选择原图，然后取消原图，返回也无法进行其他图片的选择，4.1.9

### ISSUE THREAD

**Issue by itcastheima** [longitachi/ZLPhotoBrowser#659]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.9
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
补充下config代码吧，好排查

**Comment by GitHub-DaHai** [comment]
> 

我也遇到相同问题，
config如下
let pcDefault = ZLPhotoConfiguration.default()
            pcDefault.maxSelectCount = 1
            pcDefault.allowEditVideo = false
            pcDefault.allowSelectVideo = false
            pcDefault.allowRecordVideo = false
            
            let ps = ZLPhotoPreviewSheet()
            ps.selectImageBlock = { (images, assets, isOriginal) in
                // your code
                if images.count > 0 {
                    self.uploadHeadImage(image: images[0])
                }
            }
            ps.showPhotoLibrary(sender: self)

**Comment by longitachi** [comment]
@GitHub-DaHai 更新4.2.0版本即可
