### ISSUE TITLE
先选择视频，再选择图片，会报“ZLPhotoBrowser: error configuration”

### ISSUE THREAD

**Issue by YangEhz** [longitachi/ZLPhotoBrowser#660]
![image](https://user-images.githubusercontent.com/4738555/140715127-9952e940-8bd8-46fe-b07b-f20b14c8956f.png)

**Comment by longitachi** [comment]
因为你选择视频时候把`allowSelectImage`设置为`false`，然后选择图片时候把`allowSelectVideo`也设置成了`false`，所以你参数配置错了，不允许选择图片也不允许选择视频。你要在选择图片时候把`allowSelectImage`设置为`true`

**Comment by YangEhz** [comment]
> 因为你选择视频时候把`allowSelectImage`设置为`false`，然后选择图片时候把`allowSelectVideo`也设置成了`false`，所以你参数配置错了，不允许选择图片也不允许选择视频。你要在选择图片时候把`allowSelectImage`设置为`true`

啊，突然反应过来了XD，谢谢大神回复
