### ISSUE TITLE
Captured photo distortion

### ISSUE THREAD

**Issue by huseyinmetin** [longitachi/ZLPhotoBrowser#661]
### Issue Description
While we've been capturing a photo, captured photo distorted as you can see below. This distortions are leftmost and rightmost at picture from up to down. When we took a photo from stock camera app, there is no problem. The problem is in ZLCustomCamera class but we don't know the reason. What do you think about this problem?

![Image from iOS](https://user-images.githubusercontent.com/30692724/142234068-6cf09d33-a488-4fc5-965b-3c0c619ad2be.jpg)

#### Description and Steps
   Zoom a bit and take photo with iPhone 13 Pro. May not happen every time :(.

#### Info
   ZLPhotoBrowser version:  4.1.8
   Device:  **iPhone 13 Pro**

#### Configuration code of `ZLCameraConfiguration`

   ```
        let cameraConfig = ZLCameraConfiguration()
        cameraConfig.videoExportType = .mp4
        ZLPhotoConfiguration.default().cameraConfiguration = cameraConfig
   ```

**Comment by longitachi** [comment]
I have no idea why it happen. I test it with iPhone 13 Pro, but it is not happen.
Can you set `useCustomCamera = false` and test again (take the same picture). Does this problem also occur when using the system camera?

**Comment by huseyinmetin** [comment]
I'm closing this issue that have not occurred again. I have used `useCustomCamera = false`. 
Thank you.
