### ISSUE TITLE
关于类的权限是否能定义为open

### ISSUE THREAD

**Issue by lczalh** [longitachi/ZLPhotoBrowser#663]
ZLEditImageViewController需要继承这个类来单独定义部分UI
ZLClipImageViewController需要单独使用

**Comment by longitachi** [comment]
下个版本看下

**Comment by longitachi** [comment]
已修改类和部分UI相关控件相关权限

**Comment by lczalh** [comment]
> 类和部分UI相关控件的权限已修改
谢谢
