### ISSUE TITLE
点击选相册崩溃

### ISSUE THREAD

**Issue by Tang-Hai** [longitachi/ZLPhotoBrowser#666]
![image](https://user-images.githubusercontent.com/13147415/144713731-bf614387-03f3-415f-932e-148204ccc850.png)
用户描述再点击选相册后崩溃了，我没能看出问题来，想请教一下大佬。
还有在用户授权为 《选择部分照片》时会立马崩溃。

**Comment by longitachi** [comment]
这个信息有点少。。我在iPhone12  15.1系统上没遇到崩溃，下午升级下系统试试

**Comment by Tang-Hai** [comment]
选相册后崩溃的次数不多，但是在用户授权为 《选择部分照片》时会立马崩溃，产生了非常多的崩溃。

**Comment by longitachi** [comment]
你在你们的项目里调试下吧，看按照你说的情况，崩溃到哪里的，提供点更详细的信息。我也在测下
