### ISSUE TITLE
canSelectAsset 是否可以返回当前已经选择的

### ISSUE THREAD

**Issue by hydyy** [longitachi/ZLPhotoBrowser#667]
需求是9图1视频, 这种需求就必须知道当前已经选择的都是什么

**Comment by longitachi** [comment]
可以用参数控制实现
```swift
ZLPhotoConfiguration.default()
            .maxSelectCount(10)
            .maxVideoSelectCount(1)
            .minVideoSelectCount(1)
```

**Comment by hydyy** [comment]
这样就可以选择10张图了

**Comment by longitachi** [comment]
选不了10张图，限制了最小视频选择数为1

**Comment by foxempire** [comment]
请问如果只选1条视频 或者 5张图能否实现？

**Comment by longitachi** [comment]
@foxempire 同理，改参数就行，可以实现

**Comment by foxempire** [comment]
> 

如果配置成最大一个视频或者5张图片，在选了1张图片后也是可以再选视频的。如果像选了图片就不能选视频怎么配？

**Comment by longitachi** [comment]
> > 
> 
> 如果配置成最大一个视频或者5张图片，在选了1张图片后也是可以再选视频的。如果像选了图片就不能选视频怎么配？

`allowMixSelect = false`就行了，不允许图片和视频一起选择，就会默认视频单选，图片按照设置的数量进行选择，仿微信朋友圈的一个逻辑
