### ISSUE TITLE
关于自定义image的问题，api中传入一个数组，然后代码取值是UIImage(named: named)

### ISSUE THREAD

**Issue by zhangxiongwen** [longitachi/ZLPhotoBrowser#668]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.2.0
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

func getImage(_ named: String) -> UIImage? {
    if ZLCustomImageDeploy.deploy.contains(named) {
        return UIImage(named: named)
    }
    return UIImage(named: named, in: Bundle.zlPhotoBrowserBundle, compatibleWith: nil)
}

关于自定义image的问题，api中传入一个数组，然后代码取值是UIImage(named: named)，但是我的项目是组件化的，传入的图片名称通过UIImage(named: named)取不到值，能否修改api，传入[String: UIImage]这种类型的字典呢？

**Comment by longitachi** [comment]
好的，下个版本完善下这块功能
