### ISSUE TITLE
demo9存在复用问题

### ISSUE THREAD

**Issue by UknowHui** [longitachi/ZLPhotoBrowser#669]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.2.0
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
请详细描述下问题，并提供相册配置代码、复现步骤，或者问题代码，
