### ISSUE TITLE
内存泄漏的厉害，进入相册选择上下滑动

### ISSUE THREAD

**Issue by RabbitHan** [longitachi/ZLPhotoBrowser#67]
如题，进入相册选择滑动 内存泄漏的厉害 可以关注一下 我的leak真机老崩溃 没办法定位 坐着可以试试找一下问题

**Comment by longitachi** [comment]
已经做了优化

**Comment by dream5788** [comment]
群主有没有简书或者微博

**Comment by longitachi** [comment]
简书：http://www.jianshu.com/u/a02909a8a93b  微博太乱，纯属娱乐
