### ISSUE TITLE
bugly收集到的崩溃

### ISSUE THREAD

**Issue by hjh920722** [longitachi/ZLPhotoBrowser#672]
#### Description and Steps

一个SIGTRAP崩溃，出错堆栈截图如下
![image](https://user-images.githubusercontent.com/15206689/146702252-e41928e7-1dba-47f4-bd36-6a2c02294954.png)
一个NSInternalInconsistencyException崩溃，attempt to delete item 14 from section 0 which only contains 14 items before the update，出错堆栈截图如下：
![image](https://user-images.githubusercontent.com/15206689/146702391-495c97fa-dcd7-4c4c-9d72-cfd571cde5cf.png)

#### Info
   ZLPhotoBrowser version:  4.1.9
   Device:  iPhone 13
   Device version:  iOS 15.2(19C57)
   Xcode version:   Xcode 12.5

#### Configuration code of `ZLPhotoConfiguration`

   ```
   ZLPhotoConfiguration.default().allowEditImage = false
   ZLPhotoConfiguration.default().allowSelectGif = false
   ZLPhotoConfiguration.default().allowSelectVideo = false
   ZLPhotoConfiguration.default().columnCount = 3
   ZLPhotoConfiguration.default().allowPreviewPhotos = false
   ```

**Comment by longitachi** [comment]
涉及到删除的，目前能想到的就是，访问部分照片的权限，然后修改了可访问照片的数量。 测试了下预览模式和相册中的情况，暂时没有遇到崩溃。 后续再看看吧
