### ISSUE TITLE
如何拉取自定义相册相机权限的？

### ISSUE THREAD

**Issue by Runyalsj** [longitachi/ZLPhotoBrowser#680]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.2.1
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
调用直接是唤起的系统info配置的权限，能自定义权限内容吗
   ```

**Comment by longitachi** [comment]
没看明白你的意思。。调用直接唤起系统info配置的权限啥意思，还有自定义什么权限内容，
