### ISSUE TITLE
超过8000张图片的手机启动可能会闪退

### ISSUE THREAD

**Issue by maxfong** [longitachi/ZLPhotoBrowser#684]
### Issue Description
超过8000张图片的手机可能会引起闪退,而且闪退后再次打开100%闪退

#### Description and Steps

调用`[ps showPhotoLibraryWithSender:sender];`就闪退

机型和系统包含:
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/3784855/149090278-5f0e6338-2f32-49e1-b965-3fe12acac978.png">
闪退的代码在:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/3784855/149090678-171f3df7-8049-4b0d-85e5-062f5be000a9.png">
```
public func refetchPhotos() {
        let models = ZLPhotoManager.fetchPhoto(in: self.result, ascending: ZLPhotoConfiguration.default().sortAscending, allowSelectImage: ZLPhotoConfiguration.default().allowSelectImage, allowSelectVideo:  ZLPhotoConfiguration.default().allowSelectVideo)
        self.models.removeAll()
        self.models.append(contentsOf: models)    <-----这一行,应该是models内对象被释放?但是查不到是哪个
    }
```

#### Configuration code of `ZLPhotoConfiguration`

   ```
ZLPhotoConfiguration *config = [ZLPhotoConfiguration default];
        config.editImageConfiguration.clipRatios = @[[ZLImageClipRatio wh9x16], [ZLImageClipRatio wh3x4], [ZLImageClipRatio wh1x1], [ZLImageClipRatio wh4x3], [ZLImageClipRatio wh16x9]];
        config.allowSelectVideo = NO;
        config.allowSelectGif = NO;
        config.allowRecordVideo = NO;
   ```

**Comment by maxfong** [comment]
```
//            DispatchQueue.global().async {
                self.albumList.refetchPhotos()
                ZLMainAsync {
                    self.arrDataSources.removeAll()
                    self.arrDataSources.append(contentsOf: self.albumList.models)
                    markSelected(source: &self.arrDataSources, selected: &nav.arrSelectedModels)
                    hud.hide()
                    self.collectionView.reloadData()
                    self.scrollToBottom()
                }
//            }
```

注释异步能解决这个闪退

**Comment by longitachi** [comment]
最近有点忙，我抽空给手机多导入点图片试下

**Comment by maxfong** [comment]
> 最近有点忙，我抽空给手机多导入点图片试下

辛苦了,不仅是图片多,还可能包含icloud图片,`refetchPhotos()`移到主线程暂时没问题,性能也没发现有影响

**Comment by LemonChao** [comment]
8000张？！太狠了，作者说我头发都没这么多😅

**Comment by FanYouXin** [comment]
我遇到的问题应该就是这个。 客户相册有18000多张图片，iCloud图片。打开相册失败。目前还没有日志。。

**Comment by longitachi** [comment]
@dls007 能录个屏吗，是100%崩溃吗。我在手机里导入了8000多张图片了，暂没有复现。准备继续在导入几千张测试下

**Comment by dls007** [comment]
> @dls007 能录个屏吗，是100%崩溃吗。我在手机里导入了8000多张图片了，暂没有复现。准备继续在导入几千张测试下
//            DispatchQueue.global().async {
                self.albumList.refetchPhotos()
                ZLMainAsync {
                    self.arrDataSources.removeAll()
                    self.arrDataSources.append(contentsOf: self.albumList.models)
                    markSelected(source: &self.arrDataSources, selected: &nav.arrSelectedModels)
                    hud.hide()
                    self.collectionView.reloadData()
                    self.scrollToBottom()
                }
//            }
暂时也是这样处理 但是又遇到一个新问题 捕获页面的时候 有概率性画面卡住 但是没崩

**Comment by FanYouXin** [comment]
不是100%，客户的云端照片比较多。还有视频文件。 客户没有提供视频，只有截图。








502873213
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "longitachi/ZLPhotoBrowser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月12日(星期二) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [longitachi/ZLPhotoBrowser] 超过8000张图片的手机启动可能会闪退 (Issue #684)





  
@dls007 能录个屏吗，是100%崩溃吗。我在手机里导入了8000多张图片了，暂没有复现。准备继续在导入几千张测试下
 //            DispatchQueue.global().async {
 self.albumList.refetchPhotos()
 ZLMainAsync {
 self.arrDataSources.removeAll()
 self.arrDataSources.append(contentsOf: self.albumList.models)
 markSelected(source: &amp;self.arrDataSources, selected: &amp;nav.arrSelectedModels)
 hud.hide()
 self.collectionView.reloadData()
 self.scrollToBottom()
 }
 //            }
 暂时也是这样处理 但是又遇到一个新问题 捕获页面的时候 有概率性画面卡住 但是没崩
