### ISSUE TITLE
iOS15上，上边的导航栏左边的返回按钮没有了

### ISSUE THREAD

**Issue by liyanpp5** [longitachi/ZLPhotoBrowser#685]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.2.2
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
麻烦提供下相册`config`配置代码及相关截图
