### ISSUE TITLE
allowMixSelect设置为false后，多选视频无效

### ISSUE THREAD

**Issue by Blackvision2021** [longitachi/ZLPhotoBrowser#686]
#### Description and Steps

在设置`allowMixSelect = false`后，无论`maxVideoSelectCount`设置多大，都只能单选一个视频

#### Info
   ZLPhotoBrowser version:  4.2.2
   Device:   iPhone XR
   Device version:   iOS 14.8
   Xcode version:  e.g. Xcode 13.1

#### Configuration code of `ZLPhotoConfiguration`

   ```
   let config = ZLPhotoConfiguration.default()
        config.allowMixSelect = false
        config.maxVideoSelectCount = 9
        config.minVideoSelectCount = 1
        config.allowSelectGif = false
        config.allowSelectImage = false
        config.allowSelectLivePhoto = false
        config.allowSelectOriginal = false
   ```

**Comment by longitachi** [comment]
```swift
/// Whether photos and videos can be selected together. Default is true.
/// If set to false, only one video can be selected. Defaults to true.
@objc public var allowMixSelect = true
```
是这么个逻辑，当时主要是参照微信朋友圈的一个功能，视频只能单选。

你既然设置了`allowSelectImage = false`，就没必要设置`allowMixSelect  = false`了

**Comment by Blackvision2021** [comment]
> ```swift
> /// Whether photos and videos can be selected together. Default is true.
> /// If set to false, only one video can be selected. Defaults to true.
> @objc public var allowMixSelect = true
> ```
> 
> 是这么个逻辑，当时主要是参照微信朋友圈的一个功能，视频只能单选。
> 
> 你既然设置了`allowSelectImage = false`，就没必要设置`allowMixSelect = false`了

感谢回复，看ZLPhotoConfiguration测试功能的时候没注意看上面的描述。
