### ISSUE TITLE
你好，请教一个问题。

### ISSUE THREAD

**Issue by jjzjx118** [longitachi/ZLPhotoBrowser#69]
如果要实现多次选择，即第一次选择1张图，第二次再次进入相册页面的时候需要把第一次选择的照片筛选出来，并且在相册里打上勾。这个有什么接口可以实现吗？

**Comment by longitachi** [comment]
/**已选择的asset对象数组*/
@property (nonatomic, strong) NSMutableArray<PHAsset *> *arrSelectedAssets;

再次进入相册时候，给ZLPhotoActionSheet对象传入这个数组就好了，demo里面有的

**Comment by jjzjx118** [comment]
抱歉没有仔细看Demo，已经解决了。谢谢：）

**Comment by jjzjx118** [comment]
另外不好意思，再请问一下，如果我想在选择好的图片上直接加上小x，点击后删除而不进入相册去删除。请问有这样的接口吗？因为要更新arrSelectedAssets，但是这里面是PHAsset类，而这个类似乎只在从相册选择图片点击Done才能回调到。如果是自定义的预览控件请问有什么办法在选好的图片预览控件删除照片吗？谢谢了。

**Comment by longitachi** [comment]
自定义预览控件的话，你可以吧返回的uiimage和phasset以某种方式关联起来，删除的时候更新arrSelectedAssets数组

**Comment by jjzjx118** [comment]
嗯，我试了一下已经实现了。非常感谢！
