### ISSUE TITLE
ZLImagePreviewController预览图片支持拖拽关闭

### ISSUE THREAD

**Issue by TouchGuoGuo** [longitachi/ZLPhotoBrowser#690]
能否向ZLPhotoPreviewController一样在预览图片的时候支持拖拽关闭

**Comment by haofanning** [comment]
附议，目前的关闭方式不适合大屏操作

**Comment by Louis-Zeng** [comment]
这个提议这么久了怎么还没改啊，复制粘贴改几下而已，很快的啊

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/commit/0e84dfae7ee9966601cfee3b60b497e70669b1fe
