### ISSUE TITLE
no such module 'ZLPhotoBrowser'

### ISSUE THREAD

**Issue by izqutcom** [longitachi/ZLPhotoBrowser#691]
#### Info
   ZLPhotoBrowser version:  e.g. 4.2.2
   Device:  e.g. iPhone 13
   Device version:  e.g. iOS 15.2
   Xcode version:  e.g. Xcode 13.2.1

no such module 'ZLPhotoBrowser'

**Comment by longitachi** [comment]
通过什么方式集成的？

**Comment by aroundCHOU** [comment]
@longitachi 我直接拖源码进项目里，也出现了这个问题。

**Comment by zwh123214** [comment]
> 使用SwiftPM集成也是有这个问题，我的版本是4.5.2

清楚缓存就行了
