### ISSUE TITLE
相机配置设置为高分辨率时，在低分辨率手机上使用崩溃

### ISSUE THREAD

**Issue by yinsenlee** [longitachi/ZLPhotoBrowser#692]
集成方式为OC集成Swift库
调用方式cameraConfiguration.sessionPreset = CaptureSessionPresetHd4K3840x2160;

问题：在iPhone 6s Plus机型上无法使用相机

报错：
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** -[AVCapturePhotoOutput capturePhotoWithSettings:delegate:] No active and enabled video connection'
*** First throw call stack:
(0x1826de364 0x181924528 0x1880e3c98 0x1085fcfb8 0x1085fd044 0x18c25ccd0 0x18c2612c4 0x18bd39aa8 0x18bbf0c38 0x18c24ab34 0x18c24a6a4 0x18c249800 0x18bbeef44 0x18bbbff64 0x18c51531c 0x18c5178a8 0x18c5107c0 0x18268697c 0x1826868fc 0x182686184 0x182683d5c 0x1825a3e58 0x184450f84 0x18bc2367c 0x10088e958 0x1820c056c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by yinsenlee** [comment]
建议增加一个自动枚举项，根据能支持的最大分辨率自动识别

**Comment by yinsenlee** [comment]
当前版本有办法解决这个问题吗？

**Comment by longitachi** [comment]
你可以先判断下机型和当前机型是否支持分辨率，然后再给`cameraConfiguration.sessionPreset`进行赋值

**Comment by yinsenlee** [comment]
> 

好的，已解决问题！

**Comment by longitachi** [comment]
```
let preset = ZLPhotoConfiguration.default().cameraConfiguration.sessionPreset.avSessionPreset
if self.session.canSetSessionPreset(preset) {
        self.session.sessionPreset = preset
} else {
        self.session.sessionPreset = .hd1280x720
}
```
看了下代码，框架内部有判断分辨率支持问题，应该不会crash才对啊
