### ISSUE TITLE
视频导入时，不是原生Photo应用编辑后的视频，而是原版

### ISSUE THREAD

**Issue by AFKGr** [longitachi/ZLPhotoBrowser#695]
如果用户在原生的Photo应用里编辑了视频，比如改视频大小，这个变化没有带入ZL的相册；通过ZL选择的视频还是原版，而不是编辑后的，因为用户可能喜欢先用原生Photo应用来剪辑视频，然后再发布到别的社交应用上，请问这个咋办 谢谢大神！

**Comment by longitachi** [comment]
我试了下demo，先进入相册小图预览界面，比如现在有一个视频是`60s`，我这时候在iPhone相册里编辑这个视频编辑成`10s`，然后切回demo，点进去播放视频，视频会同步成`10s`。
但是如果demo中直接先点进去播放视频界面，再去iPhone相册里编辑视频到`10s`，切回demo，这时候视频还是能播放`60s`，但是点击确定选择后，外面在预览选择的视频，实际上是只有`10s`的
测试了下微信，效果一样

**Comment by baiyidjp** [comment]
我也遇见了这个问题，在预览页时正常的，去编辑页面就是原长度的视频了

**Comment by baiyidjp** [comment]
> 我也遇见了这个问题，在预览页时正常的，去编辑页面就是原长度的视频了

预览播放的时候是获取的 AVPlayerItem，编辑视频的时候是获取的 AVAsset，是因为这样才导致编辑时展示的原视频吗

**Comment by longitachi** [comment]
这个视频大小最开始理解错了，理解成长度了，应该是尺寸，这个已修复，参考 #766
