### ISSUE TITLE
customImageNames设置图片的方式感觉不合理

### ISSUE THREAD

**Issue by haofanning** [longitachi/ZLPhotoBrowser#696]
现在稍微大点儿的项目基本都是CocoaPod组件化方案了，图片资源可能分散在组件内，只传递同名图片名仅能取到mainbundle的图片，是取不到其他bundle的图片的

**Comment by longitachi** [comment]
可以试下这个`public var customImageForKey: [String: UIImage?] = [:]`

**Comment by haofanning** [comment]
可以，但是换个尺寸稍微大点的图就成这样子了
![Snip20220311_1](https://user-images.githubusercontent.com/9473376/157783409-329390fe-4960-424d-8d08-6fb59208be4a.png)

**Comment by longitachi** [comment]
下个版本优化一下，但是图片资源大小还是单倍图尽量不要超过 `34*34`，现在可以修改下这个地方解决
https://github.com/longitachi/ZLPhotoBrowser/blob/5f9578a9463c0d2d314dcbee5eaf6a19ff1a3a01/Sources/General/ZLThumbnailViewController.swift#L273
```swift
let originBtnW = originalTitle.boundingRect(font: ZLLayout.bottomToolTitleFont, limitSize: CGSize(width: CGFloat.greatestFiniteMagnitude, height: 30)).width + (originalBtn.currentImage?.size.width ?? 18) + 12
```

**Comment by haofanning** [comment]
好的，非常感谢
