### ISSUE TITLE
notAllowMixSelect 有定义，但是没有被任何代码调用

### ISSUE THREAD

**Issue by hstdt** [longitachi/ZLPhotoBrowser#697]
能否加一个开关，置灰的时候，控制是否点击进行提示

**Comment by longitachi** [comment]
这个属于遗留代码，`allowMixSelect`设置为`false`时候，选中图片后，视频直接不可选择，所以不需要这个提示了

**Comment by hstdt** [comment]
> 这个属于遗留代码，`allowMixSelect`设置为`false`时候，选中图片后，视频直接不可选择，所以不需要这个提示了
@longitachi 
不过如果先选择了视频，图片还是可以选择，没有置灰。且选择图片后视频被替换。逻辑上有些不一致。

**Comment by longitachi** [comment]
`allowMixSelect = false`时候，视频就只能单选，视频的右上角就没有选择按钮，应该不会出现你说的这种选了视频还能选图片的。你参数应该设置错了

**Comment by hstdt** [comment]
@long
选择了视频A之后，点击确定，关闭PhotoLibrary。然后使用ZLPhotoPreviewSheet重新拉起PhotoLibrary，图片变为了可选择的。通过这种方式选择了图片B、C之后，之前选择的视频A会被反选(selectImageBlock)。

但是如果是先选择了图片A，然后关闭Picker。重新使用ZLPhotoPreviewSheet拉起，视频还是不可选择的灰色状态。

```
let ac = ZLPhotoPreviewSheet(selectedAssets: selectedAssets)
ac.showPhotoLibrary(sender: self)
```

就是我上面说的先选图片，和先选视频，在allowMixSelect上的逻辑不太一致。

**Comment by longitachi** [comment]
没啥逻辑不一样的，你先选择了视频，就算已选择的视频通过`selectedAssets`携带进来，也会直接给过滤掉
https://github.com/longitachi/ZLPhotoBrowser/blob/3c77d926d085e1e3f4f3f0fa493ea88737e760d7/Sources/General/ZLPhotoPreviewSheet.swift#L128-L130
`allowMixSelect = false`是视频单选，你携带进来，选择其他视频时，返回新选择的视频。 选择图片时，仅返回图片，如果图片和视频一起返回了，那和`allowMixSelect = false`不就冲突了
