### ISSUE TITLE
拍照后无法重新选择图片

### ISSUE THREAD

**Issue by HuajingZeng** [longitachi/ZLPhotoBrowser#698]
let _ = ZLPhotoConfiguration.default().then{
            $0.allowSelectImage = true
            $0.allowSelectLivePhoto = true
            $0.allowEditVideo = false
            $0.allowEditImage = true
            $0.maxSelectCount = 1
            $0.showClipDirectlyIfOnlyHasClipTool = true
            $0.editImageTools = [.clip]
            $0.editImageClipRatios = [.wh1x1]
        }
1、拍第一张照后，其他照片被锁定无法选择，是默认只能选择新拍的照片？
2、可连续拍多张照片，但只有拍摄的第一张照片是可选状态，其他新拍的照片也被锁定无法选择。

建议拍摄后可以自由选择

**Comment by longitachi** [comment]
`maxSelectCount ` 你设置成 `1`，拍照后默认选中，所以其他图片不可选择，你继续再拍图片，因为已经达到最大选择量 `1` 了，所以后续拍的没有被选中

**Comment by HuajingZeng** [comment]
> `maxSelectCount ` 你设置成 `1`，拍照后默认选中，所以其他图片不可选择，你继续再拍图片，因为已经达到最大选择量 `1` 了，所以后续拍的没有被选中

有办法优化么？比如提供参数取消拍照后默认选中？maxSelectCount = 1时也支持取消选中？

**Comment by longitachi** [comment]
```swift
/// In single selection mode, whether to display the selection button. Defaults to false.
@objc public var showSelectBtnWhenSingleSelect = false
```
把这个属性设置为`true`，就能显示选择框了
