### ISSUE TITLE
滑动选择的时候，有的图片莫名其妙变小了

### ISSUE THREAD

**Issue by xhp281** [longitachi/ZLPhotoBrowser#7]
滑动选择的时候，有的图片莫名其妙变小了。

**Comment by longitachi** [comment]
在查看大图界面？我测试时候还没遇到过这情况。可以把相册的图和该程序的效果图发给我下吗。495181165@qq.com

**Comment by longitachi** [comment]
看过你发的邮件了，那不是变小了，是显示方式设置为等比缩放的。可以去和QQ的对比下显示效果。
