### ISSUE TITLE
xcode13.3 carthage打包动态库xcframework出错

### ISSUE THREAD

**Issue by 12207480** [longitachi/ZLPhotoBrowser#701]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.2.4
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 15.4
   Xcode version:  e.g. Xcode 13.3

#### Configuration code of `ZLPhotoConfiguration`

@objc public protocol ZLImageStickerContainerDelegate **where Self: UIView**
where Self: UIView 改成:NSObjectProtocol可以打包成功

**Comment by 12207480** [comment]
![image](https://user-images.githubusercontent.com/6346030/159214866-3d81ab9a-7310-467f-b6e3-9b269fef3857.png)

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/issues/719
