### ISSUE TITLE
ZLImagePreviewController长按事件能开放出来吗

### ISSUE THREAD

**Issue by haofanning** [longitachi/ZLPhotoBrowser#703]
因为会有一些定制化需求，目前长按会有保存选项，但我们还想在此基础上添加一个收藏选项做一些业务上的操作，现在只能通过修改源码实现，希望开放长按事件，支持自定义扩展。

**Comment by longitachi** [comment]
如果开放出去，需要框架回调出去哪些参数？

**Comment by haofanning** [comment]
当前页面的index或者图片资源都可以

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/15b5ce63427651bedb88b855d5725008e8433c2d/Sources/General/ZLImagePreviewController.swift#L81
4.3.0版本已支持
