### ISSUE TITLE
在present的情况下拍照确认会关闭当前ViewController

### ISSUE THREAD

**Issue by smallsevenk** [longitachi/ZLPhotoBrowser#705]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.2.5
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
补一下相关代码吧。然后具体描述下问题，看标题没看明白
