### ISSUE TITLE
字体不能自定吗？

### ISSUE THREAD

**Issue by jiangxiaopeng** [longitachi/ZLPhotoBrowser#706]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.2.5
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/2ca5c95f143b71c76862aaed53d6bb6118e9073f/Sources/General/ZLPhotoConfiguration.swift#L456-L461
