### ISSUE TITLE
贴纸和帖的文字 可以添加旋转和动态改变大小吗

### ISSUE THREAD

**Issue by Michael-lu-ke** [longitachi/ZLPhotoBrowser#707]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.2.5
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
双指可以旋转可缩放

**Comment by Michael-lu-ke** [comment]
大佬， 能否考虑支持配置成   旋转图标 和 删除图标

**Comment by longitachi** [comment]
> 大佬， 能否考虑支持配置成 旋转图标 和 删除图标

应该不会考虑~，工作量太大了。。
