### ISSUE TITLE
照片编辑EditTool能不能改成支持OC的方式，OC代码也能自定义编辑工具

### ISSUE THREAD

**Issue by yinsenlee** [longitachi/ZLPhotoBrowser#713]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.2.5
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by yinsenlee** [comment]
/// Edit image tools. (Default order is draw, clip, imageSticker, textSticker, mosaic, filtter)
    /// Because Objective-C Array can't contain Enum styles, so this property is invalid in Objective-C.
    /// - warning: If you want to use the image sticker feature, you must provide a view that implements ZLImageStickerContainerDelegate.
    public var tools: [ZLEditImageConfiguration.EditTool]

**Comment by longitachi** [comment]
下个版本会给提供个支持oc调用的属性，对编辑工具进行自定义
