### ISSUE TITLE
有限制选择视频大小的功能吗？

### ISSUE THREAD

**Issue by nol876** [longitachi/ZLPhotoBrowser#714]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.2.5
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/51e7de203199aceaf51efc11e6134f94f3973710/Sources/General/ZLPhotoConfiguration.swift#L218-L222
可以限制视频时长，不能限制data大小
