### ISSUE TITLE
怎么设置选择iCloud的视频和图片？

### ISSUE THREAD

**Issue by huchangyao** [longitachi/ZLPhotoBrowser#715]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.2.5
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
不用设置，当你选中图片后会从iCloud上预下载大图，默认支持
