### ISSUE TITLE
ZLProgressHUD这个类和我们自己的库一个类名相同，oc里边编译不通过。

### ISSUE THREAD

**Issue by jiangxiaopeng** [longitachi/ZLPhotoBrowser#716]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.0
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
fork下自己改下吧，已经加了前缀了，难免有重名的。

**Comment by jiangxiaopeng** [comment]
ok
