### ISSUE TITLE
现在里面的ui是绿色的跟微信一样 比如确定按钮的背景颜色  能否自定义颜色

### ISSUE THREAD

**Issue by iOSluozhiping** [longitachi/ZLPhotoBrowser#718]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.0
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/6587641d33d10d468c04da70b82e3b59ef3b7e65/Sources/General/ZLPhotoUIConfiguration.swift#L213-L243
更多颜色自定义可以看注释
