### ISSUE TITLE
@objc public protocol ZLImageStickerContainerDelegate where Self: UIView  在 xcode13.3.1打包报错

### ISSUE THREAD

**Issue by chaserr** [longitachi/ZLPhotoBrowser#719]
@objc public protocol ZLImageStickerContainerDelegate where Self: UIView
在xcode13.3.1 会被自动生成
@objc public protocol ZLImageStickerContainerDelegate : UIKit.UIView 
导致报错。
![image](https://user-images.githubusercontent.com/10346215/165691068-a7522a57-820e-47cd-bf91-6d3d4a1a276a.png)

**Comment by longitachi** [comment]
今天发一版会去掉这个
