### ISSUE TITLE
设置allowSelectOriginal为false后，希望可以添加默认为原图的选项

### ISSUE THREAD

**Issue by Water-zi** [longitachi/ZLPhotoBrowser#720]
在设置allowSelectOriginal为false后，目前版本会默认压缩图片。

通过修改ZLPhotoPreviewSheet.swift和ZLImageNavController.swift文件中的
`private var isSelectOriginal = false`
为
`private var isSelectOriginal = true`
（ZLImageNavController.swift中没有Private，但在外部没有找到便捷的方法可以调用它）
可以让它默认为原图。

请问是否有不修改源码的方法可以实现这个功能呢？
如果没有，能麻烦添加一些接口吗？因为更新或者重新安装Pod的时候，这些修改就复原了。
感谢！

**Comment by longitachi** [comment]
可以设置`shouldAnialysisAsset = false`，框架不会解析图片，直接返回，然后自行将`PHAsset`解析成原图。
或者fork下进行修改

**Comment by Water-zi** [comment]
> 框架不会解析图片，直接返回，然后自行将

谢谢指导

**Comment by longitachi** [comment]
4.3.3版本已支持该功能
https://github.com/longitachi/ZLPhotoBrowser/blob/6fdcb893d35abada424c2ce1022e28b6621d82c9/Sources/General/ZLPhotoConfiguration.swift#L177-L179
