### ISSUE TITLE
Numerical Computation Problems

### ISSUE THREAD

**Issue by HatsuneMikuV** [longitachi/ZLPhotoBrowser#724]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/14038743/168413257-c450a36d-c7dc-4c1c-8625-263ace71cccd.png">

The value of d should also be adjusted. By default, the export operation is performed, which is not necessary.

**Comment by longitachi** [comment]
现在没想到更好的方法去做数值对比，后面加一个0.01的误差判断

**Comment by HatsuneMikuV** [comment]
round(d) == round(CGFloat(self.avAsset.duration.seconds)) ，it's work

**Comment by longitachi** [comment]
round(8.5) 和 round(9.49) 会有一秒的误差~
