### ISSUE TITLE
我有个小问题

### ISSUE THREAD

**Issue by sprother** [longitachi/ZLPhotoBrowser#73]
为什么要限制同时选择照片和GIF啊 希望能开放 本质上都是图片 很少有项目会有这样的限制吧 本想使用你的框架 这个坑 我得去修改你内部代码 这样会破坏原有结构 也不方便以后升级

**Comment by longitachi** [comment]
好的，近期比较忙，之后考虑添加这个同时选择的功能

**Comment by longitachi** [comment]
已开放同时选择image、gif、livephoto、video功能，更新最新版本即可
