### ISSUE TITLE
阿语适配问题

### ISSUE THREAD

**Issue by wutiaorong** [longitachi/ZLPhotoBrowser#731]
系统语言是阿语的情况下，选图选不到正确的图，图片预览页向下滑动的时候会崩溃

**Comment by longitachi** [comment]
能描述下详细步骤吗，“选图选不到正确的图”是什么意思没看明白

**Comment by wutiaorong** [comment]
> 能描述下详细步骤吗，“选图选不到正确的图”是什么意思没看明白

选第一张图，结果选中的是最后一张图

**Comment by Lifei0229** [comment]
4.3.7只是适配阿语语言， 并没有解决手机阿语系统语言，图库索引错误 选择的还是不对

**Comment by Lifei0229** [comment]
作者Demo 是没有加阿语的系统语言 所以发现不了问题，你项目Localizations 加上Arabic 就可以复现了

我的临时解决如下
1
ZLPhotoPreviewController.swift 文件
51行加
if (Locale.preferredLanguages.first ?? "en").hasPrefix("ar") {
      view.semanticContentAttribute = .forceLeftToRight
}
2
搜索 class ZLPhotoPreviewSelectedView
840行
if (Locale.preferredLanguages.first ?? "en").hasPrefix("ar") {
       view.semanticContentAttribute = .forceLeftToRight
 }

**Comment by longitachi** [comment]
#721
