### ISSUE TITLE
拍完照片保留拍照的方向

### ISSUE THREAD

**Issue by plkgq** [longitachi/ZLPhotoBrowser#738]
当横屏拍照完毕时，预览照片和保存的照片会自动调整方向，但是我想保留原有拍照的方向，横屏拍摄照片的方向不变
请问我该如何处理

**Comment by plkgq** [comment]
目前拍照完成后获取的imageOrientation始终为up，我不知该如何调整方向，不知道是我配置出错了么？

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/17387abe5c37b22ae657fc88910c470d707d9eb6/Sources/Camera/ZLCustomCamera.swift#L411-L430
可以fork下，注释掉调用这个方法的部分

**Comment by plkgq** [comment]
> https://github.com/longitachi/ZLPhotoBrowser/blob/17387abe5c37b22ae657fc88910c470d707d9eb6/Sources/Camera/ZLCustomCamera.swift#L411-L430
> 
> 
> 可以fork下，注释掉调用这个方法的部分

非常感谢您的回复，我仔细看了下代码，connection?.videoOrientation = self.orientation这句和您提到的那个方法应该就是关键点吧？

**Comment by longitachi** [comment]
对，单注释掉这行代码也行，不需要监控设备方向，上面提到的方法可以一并注释

**Comment by plkgq** [comment]
> 对，单注释掉这行代码也行，不需要监控设备方向，上面提到的方法可以一并注释

明白了，非常感谢您的回复😊
