### ISSUE TITLE
直接在viewDidLoad() 中调用showPhotoLibrary 方法只会在APP第一运行的时候能进相册选择页面 返回在进去就不行了 

### ISSUE THREAD

**Issue by zaijianrumo** [longitachi/ZLPhotoBrowser#740]
override func viewDidLoad() {
        super.viewDidLoad()

        let ps = ZLPhotoPreviewSheet(selectedAssets:self.selectedAssets)
        
        ps.selectImageBlock = { [weak self] (images, assets, isOriginal) in
            self?.selectedAssets = assets
        }
        ps.showPhotoLibrary(sender: self)
        
    }

**Comment by zaijianrumo** [comment]
在viewDidLoad() 添加一个按钮,点击按钮调用ps.showPhotoLibrary 这样可以.

**Comment by longitachi** [comment]
1.`viewDidLoad`只会在控制器初始化时运行一次
2.本身这样调用就是错误的，你在`viewDidLoad `中调用，这是你的控制器还没有被push或者present出来，这时候就去调用相册会出现相册不出来的情况
