### ISSUE TITLE
如何将选择的图片转为固定的宽度/高度

### ISSUE THREAD

**Issue by baiyidjp** [longitachi/ZLPhotoBrowser#742]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.5
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```

   ```

 我传入一个固定的宽度，比如 1080，我选择了图片(非原图)后自动截图为 1080 的图片返回，如果不够 1080 就不处理这样的逻辑有吗

**Comment by longitachi** [comment]
不支持该功能，框架提供有的有对应方法，可以拿到图片后自行调用
https://github.com/longitachi/ZLPhotoBrowser/blob/e344bd94ea2fcb6a60ac7dce830675cfe3626760/Sources/Extensions/UIImage%2BZLPhotoBrowser.swift#L359
https://github.com/longitachi/ZLPhotoBrowser/blob/e344bd94ea2fcb6a60ac7dce830675cfe3626760/Sources/Extensions/UIImage%2BZLPhotoBrowser.swift#L371

**Comment by baiyidjp** [comment]
> 不支持该功能，框架提供有的有对应方法，可以拿到图片后自行调用
> 
> https://github.com/longitachi/ZLPhotoBrowser/blob/e344bd94ea2fcb6a60ac7dce830675cfe3626760/Sources/Extensions/UIImage%2BZLPhotoBrowser.swift#L359
> 
> 
> https://github.com/longitachi/ZLPhotoBrowser/blob/e344bd94ea2fcb6a60ac7dce830675cfe3626760/Sources/Extensions/UIImage%2BZLPhotoBrowser.swift#L371

我项目有这个方法，就是感觉麻烦点

**Comment by baiyidjp** [comment]
@longitachi 
非原图的压缩和裁切规则是啥？可以把代码贴一下吗

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/e344bd94ea2fcb6a60ac7dce830675cfe3626760/Sources/General/ZLFetchImageOperation.swift#L158-L176
