### ISSUE TITLE
有配置控制裁切后视频不保存在本地吗？

### ISSUE THREAD

**Issue by baiyidjp** [longitachi/ZLPhotoBrowser#743]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.5
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
没有

**Comment by baiyidjp** [comment]
> 没有

我只想要一个 URL 就行，产品这边不允许保存在本地，有实现的方法吗？

**Comment by baiyidjp** [comment]
我发现自己改还挺麻烦，因为你的回调是要传一个 PHAsset 的，但是视频只能转为 AVAsset，无法传到外面去
