### ISSUE TITLE
是否可以根据图片大小判断是否可以选择当前图片？

### ISSUE THREAD

**Issue by baiyidjp** [longitachi/ZLPhotoBrowser#745]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.5
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/e344bd94ea2fcb6a60ac7dce830675cfe3626760/Sources/General/ZLPhotoConfiguration.swift#L295-L298
属性都在`ZLPhotoConfiguration`里面，可以先仔细看下里面的配置

**Comment by baiyidjp** [comment]
> https://github.com/longitachi/ZLPhotoBrowser/blob/e344bd94ea2fcb6a60ac7dce830675cfe3626760/Sources/General/ZLPhotoConfiguration.swift#L295-L298
> 
> 
> 属性都在`ZLPhotoConfiguration`里面，可以先仔细看下里面的配置

嗯，最终是使用了这个，主要是一直在解决return 的问题，获取图片大小的api是一个回调的
