### ISSUE TITLE
网络的gif图片保存到相册问题

### ISSUE THREAD

**Issue by tianguanghui** [longitachi/ZLPhotoBrowser#748]
网络的gif图片保存到相册，只有第一帧，这个有解吗？

**Comment by longitachi** [comment]
是调用了`ZLImagePreviewController`预览图片，然后在里面长按保存？
是的话可以自己实现`longPressBlock`，然后搜下怎么保存gif图片到相册，我对这个也没研究过

**Comment by tianguanghui** [comment]
> 是调用了`ZLImagePreviewController`预览图片，然后在里面长按保存？ 是的话可以自己实现`longPressBlock`，然后搜下怎么保存gif图片到相册，我对这个也没研究过

@longitachi 对，预览的时候，拿到的是Image对象，直接用系统提供的存相册方法只能保存第一帧。
借助imageLoader和longPressBlock 我把网络图片加载和保存单独处理了，用SD加载，保存的时候直接用缓存的文件保存到相册了。
