### ISSUE TITLE
Demo里面样式更改不了

### ISSUE THREAD

**Issue by eatwhales** [longitachi/ZLPhotoBrowser#749]
#### Description and Steps

Demo 选择样式 -> 微信 or 传统样式。传统样式无效

#### Info
   ZLPhotoBrowser version:  e.g. 最新
   Device:  e.g. iPhone 11 or iPhone 13 Mini
   Device version:  e.g. iOS 15.5
   Xcode version:  e.g. Xcode 13.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Demo 选择样式 -> 微信 or 传统样式。传统样式无效
   ```

**Comment by longitachi** [comment]
我试了下iPhone12真机没问题，试了iPhone13 mini模拟器也没提。你可以调试下看看

**Comment by longitachi** [comment]
我试了下iPhone12真机没问题，试了iPhone13 mini模拟器也没提。你可以调试下看看

**Comment by eatwhales** [comment]
我又试了 还是不行

**Comment by eatwhales** [comment]
> 我试了下iPhone12真机没问题，试了iPhone13 mini模拟器也没提。你可以调试下看看

我又试了试，Xcode14 iPhone14Pro模拟器，一样不行

**Comment by longitachi** [comment]
<img width="289" alt="image" src="https://user-images.githubusercontent.com/11711768/202348790-e3d67228-5503-4f0d-911b-367dbbc9fa76.png">
<img width="289" alt="image" src="https://user-images.githubusercontent.com/11711768/202348841-cc102ff3-648d-4dc4-9cde-f2f024ee36ca.png">

**Comment by eatwhales** [comment]
> <img width="289" alt="image" src="https://user-images.githubusercontent.com/11711768/202348790-e3d67228-5503-4f0d-911b-367dbbc9fa76.png">
> 
> <img width="289" alt="image" src="https://user-images.githubusercontent.com/11711768/202348841-cc102ff3-648d-4dc4-9cde-f2f024ee36ca.png">
> 
> 

我才看明白 传统方式和微信方式的不同点不在于UI，而是导航栏

**Comment by longitachi** [comment]
@eatwhales 嗯，对的，导航栏形式的区别

**Comment by eatwhales** [comment]
> @eatwhales 嗯，对的，导航栏形式的区别

感谢大佬

**Comment by eatwhales** [comment]
> > @eatwhales 嗯，对的，导航栏形式的区别
> 
> 感谢大佬

建议大佬的文档 能增加下选择图片后直接进裁剪和拍照后直接进入裁剪，虽然问题里面有

**Comment by longitachi** [comment]
等后面有空了，可以wiki里多加点例子
