### ISSUE TITLE
选择视频然后根据获取的路径播放提示路径不存在

### ISSUE THREAD

**Issue by 979881765** [longitachi/ZLPhotoBrowser#750]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.5
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
PHAsset的视频，必须通过对应的方法，通过PHAsset这个路径应该是不能播放视频的，想要通过路径播放则需要将视频保存到沙盒，用这个路径
