### ISSUE TITLE
导出指定格式

### ISSUE THREAD

**Issue by 979881765** [longitachi/ZLPhotoBrowser#755]
@objc class func exportVideo(for asset: PHAsset, exportType: ZLVideoManager.ExportType = .mov, presetName: String = AVAssetExportPresetMediumQuality, complete: @escaping ((URL?, Error?) -> Void)) {}

默认导出的是mov，如果exportType设置为mp4，导出的还是mov

**Comment by longitachi** [comment]
调用时候传什么就是什么，这只是一个导出方法，看外面调用地方传的值

**Comment by 979881765** [comment]
传的是mp4  导出的是mov

**Comment by longitachi** [comment]
刚看了下代码，遗留的一个bug，之前创建存储路径方法默认按照 `ZLPhotoConfiguration` 中的配置走了，下个版本改下

**Comment by longitachi** [comment]
导出`PHAsset`对象可以用这个方法
https://github.com/longitachi/ZLPhotoBrowser/blob/657f85e552e1411cabfb859a00c7687577ab4793/Sources/General/ZLPhotoManager.swift#L400-L411
导出的质量是原图质量，导出效率也较高
