### ISSUE TITLE
更新到4.3.6之后报错：NSError找不到类型

### ISSUE THREAD

**Issue by IvesZhan** [longitachi/ZLPhotoBrowser#756]
### Issue Description
**更新到4.3.6之后报错
1、ZLPhotoManager中402行 

> NSError.assetSaveError (Type 'NSError' has no member 'assetSaveError')

2、ZLVideoManager中102行，155行，163行，171行
报错信息都是找不到NSError的扩展类型**

#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.6
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
        ZLPhotoConfiguration.default().shouldAnialysisAsset = false
        ZLPhotoConfiguration.default().allowSelectOriginal = false
        ZLPhotoConfiguration.default().allowEditImage = false
        ZLPhotoConfiguration.default().allowSelectGif = false
        ZLPhotoConfiguration.default().allowTakePhoto = false
        ZLPhotoConfiguration.default().allowSelectVideo = false
        ZLPhotoConfiguration.default().allowPreviewPhotos = false
        ZLPhotoConfiguration.default().maxSelectCount = 1
        ZLPhotoConfiguration.default().showSelectBtnWhenSingleSelect = true
        ZLPhotoUIConfiguration.default().indexLabelBgColor = UIColor(hexStr: "FC4077")
        ZLPhotoUIConfiguration.default().bottomToolViewBtnNormalBgColor = UIColor(hexStr: "FC4077")

   ```

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/master/Sources/Extensions/NSError%2BZLPhotoBrowser.swift 
pod集成的吗？拉下来有这个文件吗？

**Comment by longitachi** [comment]
我自己Pod集成试了下，没问题，不会报错啊

**Comment by hheng101** [comment]
同一个问题，我重启xcode，然后cmd+shift+k清一下缓存就好了
