### ISSUE TITLE
设置编辑图片不保存新图片至相册后，选择图片的block回调怎么区分哪张图是相册原图哪张是编辑后的图片

### ISSUE THREAD

**Issue by yinsenlee** [longitachi/ZLPhotoBrowser#757]
// 设置图片编辑后不自动保存新图片至相册
saveNewImageAfterEdit = NO;

self.photoPreviewSheet.selectImageBlock = ^(NSArray<UIImage *> * _Nonnull images, NSArray<PHAsset *> * _Nonnull assets, BOOL isOriginal) {

//举例：假如我从相册选了3张图片，编辑了第二张（进行了涂鸦或裁剪），点击完成按钮后，block回调，此时此处返回的images和assets怎么区分哪些是经过编辑的image，哪些是直接读取的相册asset

    };
[self.photoPreviewSheet showPhotoLibraryWithSender:viewController];

**Comment by longitachi** [comment]
现在没法直接判断。。。

**Comment by longitachi** [comment]
最新代码已支持，可以考虑先用 `pod 'ZLPhotoBrowser', :git => 'https://github.com/longitachi/ZLPhotoBrowser.git'` 这种方式集成
