### ISSUE TITLE
oc项目，Xcode更新到最新后，模拟器运行报错Validate Workspace

### ISSUE THREAD

**Issue by rockerkekex** [longitachi/ZLPhotoBrowser#759]
rt

**Comment by longitachi** [comment]
真机会报错吗，还有单独运行demo会报错吗。我电脑Xcode没更新，暂时测不了

**Comment by rockerkekex** [comment]
> 真机会报错吗，还有单独运行demo会报错吗。我电脑Xcode没更新，暂时测不了

真机没有问题，demo也不会报错。应该和我是OC项目有关。具体报错在这里  unsupported Swift architecture
<img width="429" alt="截屏2022-09-20 10 09 52" src="https://user-images.githubusercontent.com/1932007/191151759-b5a4eade-e9a5-46d3-b49a-85bd521fa969.png">
