### ISSUE TITLE
1.加载iColud照片时候显示进度圈圈 2.没选择LivePhoto，导致选择照片显示“请在系统相册中下载到本地后重新尝试”或“加载中，请稍后”3.使用新版本API导致报错

### ISSUE THREAD

**Issue by alkayoun** [longitachi/ZLPhotoBrowser#76]
谢谢谢谢谢谢大佬！！

**Comment by longitachi** [comment]
进度的暂时还没考虑。。。。不过LivePhoto那个，选择之后在 “@property (nonatomic, copy) void (^selectImageBlock)(NSArray<UIImage *> *images, NSArray<PHAsset *> *assets, BOOL isOriginal);” 回调的第一个数组images里面就是对应的封面照片，预览才用到assets对应的对象

**Comment by alkayoun** [comment]
关于 设置里 没选择 LivePhoto 导致LivePhoto类型照片选取不了，显示“正在加载”或“请下载到本地，再尝试”的问题，我发现 是ZLPhotoManager里面，判断图片是否在本地这个方法问题：
+ (BOOL)judgeAssetisInLocalAblum:(PHAsset *)asset;
方法内option.synchronous = YES;  会导致PhotoLive类型的图片获取不到资源，从而返回No。
（具体原因我搞不懂，只知道是这个参数问题）
注释掉这一个参数设置就能使用LivePhoto类型的封面照了。

**Comment by longitachi** [comment]
你说的这个意思应该不止出现在livephoto上面吧，  普通的图片 应该也会显示这个吧。这就是图片不在本地，无法获取到资源，必须从iCloud上面加载的缘故。

当然有可能会出现另外一种情况，在我的手机上有一个视频，他是在iCloud上，但是可以获取封面图，在播放的时候却无法播放。 我感觉你的这个livephoto和我这个视频的 asset 对象是一种情况。

**Comment by alkayoun** [comment]
不知道呢，我看普通图片 存在iCloud上的 在显示菊花转圈圈后就能从模糊图，下载到清晰的图片，然后没有出现这个问题。

对，手机上的视频没法播放现在。

然后关于选择了LivePhoto模式后选取照片，选择LivePhoto照片出现提示的问题，解决方法：
       同样在ZLPhotoManage内，获取live photo方法:requestLivePhotoForAsset方法中添加参数设置：

           PHLivePhotoRequestOptions *option = [[PHLivePhotoRequestOptions alloc] init];
           option.version = PHImageRequestOptionsVersionCurrent;
           option.deliveryMode = PHImageRequestOptionsDeliveryModeOpportunistic;
           option.networkAccessAllowed = YES;

将参数option添加到下面的获取方法中替换nil，则会下载iCould的LivePhoto图。（没有菊花等待图）

**Comment by alkayoun** [comment]
关于iCould上的视频无法播放问题也是一样的修复方法：
在ZLPhotoManage内，获取视频方法：requestVideoForAsset方法中添加参数设置：

PHVideoRequestOptions *option = [[PHVideoRequestOptions alloc] init];
    option.version = PHImageRequestOptionsVersionCurrent;
    option.deliveryMode = PHImageRequestOptionsDeliveryModeFastFormat;
    option.networkAccessAllowed = YES;

将参数option添加到下面的获取方法中替换nil，则会下载iCould的Video,
但是速度比较慢，在视频没有下载完成前选中，并确定后在主界面预览会崩溃。。（依旧没有菊花图）

**Comment by alkayoun** [comment]
重要：
 判断图片是否存储在本地/或者已经从iCloud上下载到本地方法：
+ (BOOL)judgeAssetisInLocalAblum:(PHAsset *)asset;
.m中设置：
        option.networkAccessAllowed = YES;  //是否加载iCloud图
         option.synchronous = NO;//同步加载

**Comment by alkayoun** [comment]
#if __IPHONE_OS_VERSION_MIN_REQUIRED >= 110000

#endif

**Comment by xiaoqiang051512** [comment]
点击确定一直提示“加载中，请稍后”这个问题，其实我的图片已经从iCloud上下载先来了的？这是bug吗？

**Comment by longitachi** [comment]
大图界面会显示吗？还有可以试一下其他软件能不能选择，比如 QQ微信

**Comment by xiaoqiang051512** [comment]
大图界面会显示，只是在选择的时候一直显示加载中
