### ISSUE TITLE
是否可以加一个image 和 video的选择互斥呢？

### ISSUE THREAD

**Issue by ZD-Yin** [longitachi/ZLPhotoBrowser#762]
有的发布场景中 image 和 video  只能选择其中一种，目前要满足如此只能曲线救国。

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/82b07ff21f615f3fe85d949899093b247f10c33f/Sources/General/ZLPhotoConfiguration.swift#L86-L88
当前已支持
