### ISSUE TITLE
ZLThumbnailViewController.collectionView(_:didSelectItemAt:) crash

### ISSUE THREAD

**Issue by iLiuChang** [longitachi/ZLPhotoBrowser#768]
偶现

ZLPhotoBrowser 版本: 4.3.6

firebase设备信息
<img width="962" alt="image" src="https://user-images.githubusercontent.com/13009406/194695444-6ca0f97b-df39-457c-aea8-602dfd0b63fd.png">

firebase闪退信息
<img width="854" alt="image" src="https://user-images.githubusercontent.com/13009406/194695542-cf2bf10a-583a-41a8-8deb-47a6b5113152.png">

Xcode Crashes 信息
Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000001053f93f4
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 5 Trace/BPT trap: 5
Terminating Process: exc handler [60083]
![image](https://user-images.githubusercontent.com/13009406/194702062-3af05135-436b-46ca-bae7-fb46bfeb2a70.png)

**Comment by liulishuo** [comment]
我这也有类似的日志上报，都是在数组通过下标索引取值时崩溃，很容易联想到是不是index越界了，但为什么不直接显示数组越界的崩溃信息呢？

**Comment by longitachi** [comment]
下个版本优化下，加一个下标判断
