### ISSUE TITLE
照片权限：选中的照片，当新增照片/视频的时候，数据源未刷新，展示异常，点击预览崩溃；

### ISSUE THREAD

**Issue by KALIANS** [longitachi/ZLPhotoBrowser#770]
如标题：
照片权限：选中的照片，当新增照片/视频的时候，数据源未刷新，展示异常，点击预览崩溃；

目前通过回调延迟解决 ：
<img width="1024" alt="企业微信截图_6979ae5b-3734-4fc4-b6b8-ee50289266ef" src="https://user-images.githubusercontent.com/12790636/194703883-22c92cc6-fdc9-4a66-8d0f-f2a7992addb3.png">

-------------------------
讨厌修改源码方式，建议修复～

**Comment by longitachi** [comment]
提供下Xcode和iOS系统版本吧，我这边试了下iOS15.5，在`limited`权限下增加照片会直接刷新数据源。

**Comment by KALIANS** [comment]
> 提供下Xcode和iOS系统版本吧，我这边试了下iOS15.5，在`limited`权限下增加照片会直接刷新数据源。

Xcode：13.3.1
iOS：14.1 

bug表像就是，会出现多个【添加图片的cell】或者黑块

**Comment by juxiaohui** [comment]
我也出现这个问题了，会出现多个+号按钮。

**Comment by longitachi** [comment]
@juxiaohui 有复现步骤吗？
