### ISSUE TITLE
Crash: 上传特定的一些 低分辨率图片时，会崩溃-> 非主线程操作

### ISSUE THREAD

**Issue by dennis-crypto** [longitachi/ZLPhotoBrowser#771]
#### Description and Steps

1.点击选择图片
2.选中一张特殊的图片（高度很小， 比如0.01，长度正常，且低分辨率 ），直接崩溃，而且居然报非主线操作UI crash 
没办法在pod 外部修复， 亲测 在对应的地方显示加上 ZLMainAsync 可修复
···
 ZLMainAsync {
    crash code
 }
···
如下图：

<img width="1224" alt="截屏2022-10-12 18 36 58" src="https://user-images.githubusercontent.com/70618688/195321271-b992edb0-9a0b-4fa2-bf00-dec094fdb48b.png">

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.5 +  4.3.6 +  4.3.7
   Device:  e.g. iPhone 13 +13 pro ( 所有机型)
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

```
  let config = ZLPhotoConfiguration.default()
  config.maxSelectCount = 1
  let picker = ZLPhotoPreviewSheet()
  picker.selectImageBlock = { [weak self] (images, assets, _) in
       // some logic
  }
picker.showPhotoLibrary(sender: self)
   ```

**Comment by longitachi** [comment]
你在这个方法里面第一行调试下看下崩溃的时候是不是主线程吧
 `private func requestSelectPhoto(viewController: UIViewController? = nil)`

如果不是的话试试加上这句代码看能解决不能，如果能的话我修复下
```swift
guard Thread.isMainThread else {
    requestSelectPhoto(viewController: viewController)
    return
}
```

**Comment by dennis-crypto** [comment]
感谢回复
```
你在这个方法里面第一行调试下看下崩溃的时候是不是主线程吧
private func requestSelectPhoto(viewController: UIViewController? = nil)
```
崩溃的场景下，在这一行还是处在主线程的.
<img width="1336" alt="截屏2022-10-13 13 53 06" src="https://user-images.githubusercontent.com/70618688/195513181-18c12db8-2997-4b4b-a78f-d9d78fcc4e89.png">

**Comment by dennis-crypto** [comment]
![矩形 (4)](https://user-images.githubusercontent.com/70618688/195519502-65c44899-e2b3-480f-aaa8-36cdf0a04009.png)
你可以用这张图片来测试

**Comment by longitachi** [comment]
我 `xcode14.0.1` `iPhone 12 iOS 16`试了下这张图片，没有出现崩溃

**Comment by dennis-crypto** [comment]
> one 12 iOS 16
那么奇怪
我测试的机型有：
`iPhone 11 Pro iOS 15 or 16` 
 模拟器 `13 pro iOS 15 `
