### ISSUE TITLE
导入icloud的视频，好像不下载的

### ISSUE THREAD

**Issue by 1078196603** [longitachi/ZLPhotoBrowser#773]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.7
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
是在相册里同步的其他设备的视频吗？ 然后选择相片时候没下载？ 是不是网络权限没开？
