### ISSUE TITLE
ios 16 崩溃

### ISSUE THREAD

**Issue by jiangxiaopeng** [longitachi/ZLPhotoBrowser#774]
### Issue Description

PrivacyAccounting
-[PACoalescingIntervalTracker coalesce:] (in PrivacyAccounting)

ios 系统库崩溃，请问你们碰到了吗？

#### Description and Steps

完整的堆栈：

Thread 19 name:  com.apple.privacyaccounting.PAAccessLogger
libdispatch.dylib    _dispatch_source_set_timer (in libdispatch.dylib)
PrivacyAccounting    -[PACoalescingIntervalTracker coalesce:] (in PrivacyAccounting)
PrivacyAccounting    ___22-[PAAccessLogger log:]_block_invoke (in PrivacyAccounting)
libdispatch.dylib    __dispatch_block_async_invoke2 (in libdispatch.dylib)
libdispatch.dylib    __dispatch_client_callout (in libdispatch.dylib)
libdispatch.dylib    __dispatch_lane_serial_drain (in libdispatch.dylib)
libdispatch.dylib    __dispatch_lane_invoke (in libdispatch.dylib)
libdispatch.dylib    __dispatch_workloop_worker_thread (in libdispatch.dylib)
libsystem_pthread.dylib    __pthread_wqthread (in libsystem_pthread.dylib)
libsystem_pthread.dylib    _start_wqthread (in libsystem_pthread.dylib)

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.6
   Device:  iPhone xs max
   Device version:   iOS 16.3
   Xcode version:  Xcode 14.0.1

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
进入相册就crash吗？必现吗？我`iPhone12`、`iOS 16.0` 正常

**Comment by jiangxiaopeng** [comment]
> 
不是必现的，是统计工具上收集到的。

**Comment by xxx0204** [comment]
我最近也遇到这个问题了，兄弟这个问题解决了么
