### ISSUE TITLE
OC项目，在模拟器环境下报错Could not build module 'ZLPhotoBrowser'

### ISSUE THREAD

**Issue by rockerkekex** [longitachi/ZLPhotoBrowser#775]
使用cocoapods集成，真机正常，只有模拟器环境会报错。
除了Could not build module 'ZLPhotoBrowser'，还会报错unsupported Swift architecture

<img width="429" alt="191151759-b5a4eade-e9a5-46d3-b49a-85bd521fa969" src="https://user-images.githubusercontent.com/1932007/196653705-e9980136-ec6b-4509-ac8f-5eb0ad750732.png">

**Comment by longitachi** [comment]
我试了下，用`@import ZLPhotoBrowser;`导入的话，模拟器刚开始编译报错，换成`#import <ZLPhotoBrowser/ZLPhotoBrowser-Swift.h>` 的方式导入可以编译成功。 然后切回去第一种导入方式也编译成功了。

**Comment by rockerkekex** [comment]
> 

试了这种方法，也不可以
我的项目没有自动生成target-Swfit.h，现在只导入了target-Bridging-Header.h，报错会和这个有关系吗？

**Comment by longitachi** [comment]
oc引用Swift应该直接导入就行了，我是新建的oc项目，直接`cocoapods`集成框架，然后也没交接文件，直接在oc的类里引用就能直接用

**Comment by rockerkekex** [comment]
> 

尝试过清除缓存。请问你的xcode版本号是多少，我的是14.0

**Comment by longitachi** [comment]
14.0.1，这个是我创建的demo
[PodZLPhotoBrowser.zip](https://github.com/longitachi/ZLPhotoBrowser/files/9858758/PodZLPhotoBrowser.zip)

**Comment by rockerkekex** [comment]
> 14.0.1，这个是我创建的demo
> [PodZLPhotoBrowser.zip](https://github.com/longitachi/ZLPhotoBrowser/files/9858758/PodZLPhotoBrowser.zip)

非常感谢！  我定位到问题了。
我之前在嵌入阿里云播放器SDK的时候，在Excluded Architectures选项里添加了arm64,这会导致ZLPhotoBrowser报错，如果去掉arm64，阿里云sdk又会报错，感觉有点无解了
<img width="500" alt="截屏2022-10-26 13 54 06" src="https://user-images.githubusercontent.com/1932007/197946451-54437553-3da1-4745-8c7d-b676319882b9.png">

**Comment by longitachi** [comment]
可以先以源码形式导入- -
