### ISSUE TITLE
关于 2 个 GIF 的崩溃，如图堆栈

### ISSUE THREAD

**Issue by baiyidjp** [longitachi/ZLPhotoBrowser#776]
### Issue Description

<img width="1478" alt="iShot2022-10-20 11 22 10" src="https://user-images.githubusercontent.com/12672573/196849069-2ec903de-11d6-4806-a6e1-43d772e5dec1.png">
<img width="1458" alt="iShot2022-10-20 11 21 34" src="https://user-images.githubusercontent.com/12672573/196849078-d96686e6-32b4-4073-88ce-b9500a1b246d.png">

#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.5
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 15.x, 16.x
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by baiyidjp** [comment]
第二张图好像看到作者修复了 [#752](https://github.com/longitachi/ZLPhotoBrowser/issues/752)

不知道是不是一样的问题

**Comment by longitachi** [comment]
应该是一个问题，升级下版本看看后续会不会出现吧
