### ISSUE TITLE
可否支持单选点击缩略图直接返回

### ISSUE THREAD

**Issue by haoqiangyu** [longitachi/ZLPhotoBrowser#777]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.7
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
最新代码已支持，跟随下个版本发布
```swift
// 满足下两个条件即可
ZLPhotoConfiguration.default()
    .allowPreviewPhotos(false)
    .maxSelectCount(1)
```
