### ISSUE TITLE
相册里面有视频的时候，打开会中断音乐播放

### ISSUE THREAD

**Issue by jaylanlu** [longitachi/ZLPhotoBrowser#786]
播放酷我音乐的时候，打开相册，如果相册里面有视频会音乐会被关闭

**Comment by jaylanlu** [comment]
我找到解决办法了  try? AVAudioSession.sharedInstance().setActive(false, options: .notifyOthersOnDeactivation) 设置一下就好了

**Comment by longitachi** [comment]
试了下QQ音乐没有出现，如果进相机界面会暂停，进相册小图界面不会。预览大图界面播放的话会暂停，等会提交代码优化下
