### ISSUE TITLE
编辑文字在iOS16上的问题

### ISSUE THREAD

**Issue by jaylanlu** [longitachi/ZLPhotoBrowser#789]
iOS 16上关闭手机竖屏锁定，弹出键盘的时候侧着手机，键盘和横屏出现，这个问题目前只在iOS 16上有，请问有什么解决方案吗

**Comment by longitachi** [comment]
这个问题我在B站、系统分享面板还有其他软件上也遇到过，感觉是系统的问题

**Comment by jaylanlu** [comment]
已经解决了，把键盘弹出放在viewdidload里面就好了，应该是布局没有完成导致的

**Comment by longitachi** [comment]
我在16.1系统上，在编辑界面横屏，然后点击添加文字，键盘会横屏出来，然后变成竖屏。 试了下放到`viewDidLoad`，情况一样
