### ISSUE TITLE
预览页面的collectionView不支持自动布局，设备旋转后显示错误

### ISSUE THREAD

**Issue by liupengios** [longitachi/ZLPhotoBrowser#79]
相册列表页面是支持自动布局（旋转后也是正常的），但是预览页面旋转后显示错误

**Comment by liupengios** [comment]
这里弹出ZLPhotoActionSheet时，使用的加到子视图上，而不是present（可以present出一个背景透明的控制器），所以把frame写死了，旋转时就有问题了


#import "ZLPhotoActionSheet.h"

- (void)show
{
    问题出在这儿
    self.frame = self.sender.view.bounds;
}

**Comment by liupengios** [comment]
解决办法

- (void)show
{
    self.frame = self.sender.view.bounds;
加上这一句话
    self.autoresizingMask = UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight;
}

**Comment by longitachi** [comment]
OK
