### ISSUE TITLE
相册选择弹窗能否支持半屏弹出？

### ISSUE THREAD

**Issue by big-watermelon** [longitachi/ZLPhotoBrowser#790]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.7
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/3135451893b2e97a9d4ba4272ee75815af4b2f0d/Sources/General/ZLImageNavController.swift#L52-L58
可以自己fork改下，这里现在写的 `fullScreen`，但不确定其他界面会不会有其它问题
