### ISSUE TITLE
截取的视频，最后不到1秒的画面缺失

### ISSUE THREAD

**Issue by ElvistLui** [longitachi/ZLPhotoBrowser#793]
### Issue Description
截取的视频，最后不到1秒的画面缺失

#### Description and Steps
1. 设置选择视频上限为60秒；
2. 在ZL相册内选择一个2分钟的视频；
3. 截取该视频的最后60秒；
4. 截取后的视频，相比于原视频，缺失了最后不到1秒的画面；

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.7
   Device:  e.g. iPhone 14Pro
   Device version:  e.g. iOS 16.1.2
   Xcode version:  e.g. Xcode 14.1

#### Configuration code of `ZLPhotoConfiguration`

   ```
+ (void)selectVideoFor:(UIViewController *)vc asset:(PHAsset *)asset selectedBlock:(void (^)(ZLResultModel * _Nonnull))selectedBlock cancelBlock:(void (^)(void))cancelBlock {
    
    int maxVideoTime = 60;
    // 配置
    [ZLPhotoConfiguration default].allowMixSelect = NO;
    [ZLPhotoConfiguration default].allowSelectImage = NO;
    [ZLPhotoConfiguration default].allowSelectVideo = YES;
    [ZLPhotoConfiguration default].maxSelectCount = 1;
    [ZLPhotoConfiguration default].maxVideoSelectCount = 1;
    [ZLPhotoConfiguration default].maxEditVideoTime = maxVideoTime;
    [ZLPhotoConfiguration default].maxSelectVideoDuration = 3600; // 暂时显示不能选择超过1小时的视频
    [ZLPhotoConfiguration default].allowEditVideo = YES;
    [ZLPhotoConfiguration default].saveNewImageAfterEdit = YES;
    [ZLPhotoConfiguration default].minRecordDuration = 3;
    [ZLPhotoConfiguration default].maxRecordDuration = 60;
    [ZLPhotoConfiguration default].editAfterSelectThumbnailImage = YES; // 点击视频时，直接点击进入编辑页
    
    [ZLPhotoUIConfiguration default].languageType = ZLLanguageTypeChineseSimplified;
    
    ZLPhotoPreviewSheet *ps = [[ZLPhotoPreviewSheet alloc] initWithSelectedAssets:asset ? @[asset] : @[]];
    ps.selectImageBlock = ^(NSArray<ZLResultModel *> * _Nonnull results, BOOL isOriginal) {
        
        if (selectedBlock) {
            selectedBlock(results.firstObject);
        }
    };
    ps.cancelBlock = ^{
        
        if (cancelBlock) {
            cancelBlock();
        }
    };
    [ps showPhotoLibraryWithSender:vc];
}
   ```

**Comment by jiaoyaxin** [comment]
从旧版本迁移到新版本也是 我10分钟到视频最后40多秒都丢了.
计算截取时间时的开始时间是用两个view的位置差算出来的. 但是这两个view宽不是1:1的, 也没进行数值转换, 直接就使用了.

**Comment by jiaoyaxin** [comment]
ZLEditVideoController

- (CMTime)getStartTime
{
    CGRect rect = [self.collectionView convertRect:self.editView.validRect fromView:self.editView];
    CGFloat s = MAX(0, _interval * rect.origin.x / (kItemWidth));
    return CMTimeMakeWithSeconds(s, self.playerLayer.player.currentTime.timescale);
}

collectionView 和  editView 宽度不一样, 
 _interval * rect.origin.x / (kItemWidth)这样算的前提是他两宽度一样才行.

**Comment by longitachi** [comment]
@jiaoyaxin 把`config`的配置发一下吧，我抽空试一下

**Comment by jiaoyaxin** [comment]
[ZLPhotoConfiguration default].maxSelectCount = 1;
    [ZLPhotoConfiguration default].maxPreviewCount = 20;
    [ZLPhotoConfiguration default].allowSelectImage = NO;
    [ZLPhotoConfiguration default].allowEditVideo = YES;
    [ZLPhotoConfiguration default].maxSelectVideoDuration = 600;
    [ZLPhotoConfiguration default].maxEditVideoTime = 600;
    [ZLPhotoConfiguration default].cameraConfiguration.maxRecordDuration = 180;
    [ZLPhotoUIConfiguration default].showSelectBtnWhenSingleSelect = YES;

**Comment by longitachi** [comment]
能说下具体操作步骤吗，我这边试了下一个336s的视频，设置`maxEditVideoTime = 300`，试了下裁剪出来的视频长度就是300s

**Comment by jiaoyaxin** [comment]
进去直接拉到最后,选择最后300s,   预期值应该是(36,300).

**Comment by ElvistLui** [comment]
@longitachi 我这截取的视频时长没问题，是截取的起始位置不对。
举个例子，我设置
[ZLPhotoConfiguration default].maxEditVideoTime = 60;
然后选择一个2分钟的视频，选择截取最后60秒。按理说截取的应该是原视频的(60,120)，但实际截取的却是(58:118)。
这样就导致了视频最后几秒丢失了

**Comment by longitachi** [comment]
> @longitachi 我这截取的视频时长没问题，是截取的起始位置不对。 举个例子，我设置 [ZLPhotoConfiguration default].maxEditVideoTime = 60; 然后选择一个2分钟的视频，选择截取最后60秒。按理说截取的应该是原视频的(60,120)，但实际截取的却是(58:118)。 这样就导致了视频最后几秒丢失了

好的，我之前理解错了，我以为是时长少了。
