### ISSUE TITLE
选择图片后，反复选择会导致数量出问题

### ISSUE THREAD

**Issue by eatwhales** [longitachi/ZLPhotoBrowser#795]
demo中：
1. 开启Record selected photos
2. Library selection选择随意几张图片
3. 在Main界面中，直接点击图片进入图片预览页，右上角取消选择，右下角确认
4. 打开Library selection会发现数量和外面对不上

**Comment by longitachi** [comment]
好的，外面没有同步更新已选择的results数组，不影响框架内功能，今天有空了更新下demo

**Comment by eatwhales** [comment]
> 好的，外面没有同步更新已选择的results数组，不影响框架内功能，今天有空了更新下demo

大佬有空的话，图片预览界面可以加个手势关闭吗
还有，就框架中所有的绿色 能有个统一的对象来控制吗

**Comment by longitachi** [comment]
绿色的下个版本可以加一个统一的。 手势关闭嘛~ 有点麻烦
