### ISSUE TITLE
ZLThumbnailPhotoCell是否可支持自定义覆盖层

### ISSUE THREAD

**Issue by guanru** [longitachi/ZLPhotoBrowser#797]
### Issue Description
需要实现，在不符合需求的图片缩略图上做出提示，例如下图，图片宽高小于指定值
作者是否可支持ZLThumbnailPhotoCell自定义覆盖层

![IMG_2503](https://user-images.githubusercontent.com/15244547/217462103-0384e28d-e24d-4381-846d-5b900ec2743a.PNG)

**Comment by longitachi** [comment]
这个太定制化，牵扯东西又太多， 自定义浮层之后是否允许点击，点击进入大图后右上角选择按钮、编辑按钮的显示及隐藏。
建议fork下进行更改

**Comment by guanru** [comment]
好的，感谢作者百忙解答
