### ISSUE TITLE
选择多张图片，滑动出屏幕范围后标记错误

### ISSUE THREAD

**Issue by codyDu** [longitachi/ZLPhotoBrowser#8]
是不是因为cell重用的原因？

**Comment by longitachi** [comment]
你好，请问是哪个界面？我邮箱495181165@qq.com，可以的话能把效果图(最好是gif)的发给我。

**Comment by longitachi** [comment]
前几天本地更新了，一忙就忘了同步了，刚才同步了，你更新下最新版本就好了。

**Comment by codyDu** [comment]
好的。我也正在做相册。复用问题一直没解决。我再看一下。thanks
