### ISSUE TITLE
请问可以指定选择区域大小吗

### ISSUE THREAD

**Issue by Cubernet** [longitachi/ZLPhotoBrowser#80]
您好，比如选取头像时，希望设定一个选择区域，只能选取一个正方形。。。

我现在只能通过手动编辑裁剪，看了下接口好像没找到对应的支持。

thanks

**Comment by longitachi** [comment]
暂时是不能的。

**Comment by Cubernet** [comment]
谢谢回复。

如果方便的话，希望后续在您有空的时候可以增加这个feature :)

再次感谢您分享出ZLPhotoBrowser这么棒的组件～

**Comment by longitachi** [comment]
请更新最新版本，增加了裁剪比例功能

**Comment by Cubernet** [comment]
真是神速，非常感谢～

**Comment by Cubernet** [comment]
抱歉再次打扰您，我刚才更新了版本之后，的确看到了编辑界面可以选定比例；
如果是单张图片的选择模式下，不知道现在能否选择图片之后，直接进入之前设定好比例的编辑页面——类似于微信修改头像的场景——选择图片后自动进入1:1的编辑界面。
谢谢您～

**Comment by longitachi** [comment]
你的意思是在小图界面点击之后直接进入编辑界面而不是查看大图界面吗？

**Comment by Cubernet** [comment]
嗯，是的。我的使用场景就是一个更换头像的地方。现在这种模式需要用户在小图界面选好后主动进入编辑界面按照1:1裁剪，如果用户忘记编辑了，上传的头像比例可能就是错误的。
所以如果可以增加一个变量，指定 在单选模式下点击小图直接进入编辑模式，编辑模式的比例也可以预先指定为1:1 或[1:1,3:4]。

因为不清楚增加这个feature是否会让您大量修改之前的代码逻辑，所以我提的有点冒昧；您根据实际情况考虑处理就好了。

Anyway，真的非常感谢您每一次的及时回复～

**Comment by longitachi** [comment]
如果你只在这一个场景使用框架，我可以给你说下，你可以在你的项目里单独修改一下代码

**Comment by Cubernet** [comment]
其他场景也有，不过您方便的话，说下在哪里修改也好，我去处理不同场景切换的逻辑，谢谢

**Comment by longitachi** [comment]
请更新最新版本2.2.9

新增两个属性
@property (nonatomic, assign) BOOL editAfterSelectThumbnailImage;
@property (nonatomic, strong) NSArray<NSDictionary *> *clipRatios;

 你分别置为yes和提供一个预置裁剪比例即可，具体使用方法参考demo

**Comment by Cubernet** [comment]
大佬真神速...
膜拜...

**Comment by Cubernet** [comment]
我先运行了下demo，发现editAfterSelectThumbnailImage貌似不起作用；不管yes还是no，单选模式下都无法直接进入编辑模式；
点击进入编辑模式后，clipRatios的设置是有用的；

**Comment by longitachi** [comment]
尴尬了😓。本地修改文件有点多，少提交了一块代码。稍等

**Comment by Cubernet** [comment]
辛苦了辛苦了～

**Comment by wscqs** [comment]
@Property (nonatomic, assign) BOOL editAfterSelectThumbnailImage;
@Property (nonatomic, strong) NSArray<NSDictionary *> *clipRatios;
设置完是编辑模式，  我希望能直接进入 剪切 模式（不然点Done,还是原图，不符合业务）

**Comment by GarveyCalvin** [comment]
前来考古，现在可以通过这样实现直接进入剪切模式：
```
let editImageConfiguration = ZLEditImageConfiguration()
editImageConfiguration.clipRatios = [.wh3x2]
editImageConfiguration.tools = [.clip]
config.editImageConfiguration = editImageConfiguration
config.editAfterSelectThumbnailImage = true
config.showClipDirectlyIfOnlyHasClipTool = true
```
