### ISSUE TITLE
选择GIF图崩溃

### ISSUE THREAD

**Issue by dianluyuanli** [longitachi/ZLPhotoBrowser#804]
### Issue Description
选择GIF崩溃
#### Description and Steps
选择大帧数gif图会卡主崩溃 我用的gif是1000帧的

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

选择大帧数GIF就会导致内存飙升，应该是超过50帧GIF加载就会这样，需要在加载的时候处理一下

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.9
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`
1
   Paste your code here.
   1

**Comment by dianluyuanli** [comment]
可以参考TZImage那里面50帧做一下处理

**Comment by longitachi** [comment]
这两天抽空看下

**Comment by dianluyuanli** [comment]
> 这两天抽空看下。能上传一张200帧或者更大的GIF图吗？

**Comment by dianluyuanli** [comment]
> 这两天抽空看下。能上传一张200帧或者更大的GIF图吗？
网盘下载一下这个GIF 
链接: https://pan.baidu.com/s/1pvdso0FYyKRssFNVhaCz6w?pwd=1234 提取码: 1234 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/commit/f39ecb0203f4382786861e8af69fc296d0f5152f
