### ISSUE TITLE
图片编辑问题

### ISSUE THREAD

**Issue by DeanFs** [longitachi/ZLPhotoBrowser#809]
### 图片编辑添加文字未确认时，收起键盘，选色条没有跟随键盘收起，如图：

![IMG_0795](https://user-images.githubusercontent.com/48240371/226790337-c9ca2619-20b6-49ea-8f82-16718c03154b.jpg)

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.9
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

**Comment by longitachi** [comment]
没明白“未确认时，收起键盘”是一个什么样的操作，能描述的详细点吗？或者传个视频

**Comment by DeanFs** [comment]
录了个微信的视频一直上传不了，麻烦您自己体验一下微信的图片编辑-添加文本的交互，他那个文字颜色设置条是会在收起键盘时跟随收起到屏幕底部的。

再看ZLPhotoBrowser的交互
https://user-images.githubusercontent.com/48240371/227476248-3e171e7d-890a-4afb-8b49-3f58745c44c3.MP4

键盘收起后就如我前面上传的截图，颜色设置条依然停留在屏幕中间，甚至可能跟添加的文本重叠。

一个小小的体验问题，忘您能抽空优化下。

**Comment by DeanFs** [comment]
> 好的，我大致明白了，下个版本优化下

周末看到您已经优化了这个问题，今天update一下，cocoapod拉不到最新代码，能加个新的tag吗？或者把原4.3.9的tag删除再添加到最新提交的位置吗？现在只能通过commit来拿最新代码，这样不方便之后跟随您的升级了

**Comment by DeanFs** [comment]
> 好的，我大致明白了，下个版本优化下

验了下，反而有个更严重的问题了，点击选择某个颜色时，键盘也会收起，且选择的颜色无效；另外能不能键盘收起的时候，像微信一样，选色bar还显示在屏幕内，只是悬停在底部，而不是整个跟随键盘不见了

辛苦了！

**Comment by longitachi** [comment]
看了下demo，没有发现你说的点击某个颜色时，键盘也会收起且选择颜色无效的问题

**Comment by longitachi** [comment]
关闭按钮的`Y`值有参考微信的。 `ZLCustomCamera`权限是`open`，你可以继承下，里面`UI`空间权限是`public`。
另外修改文案可以参考 https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(Swift)#Customize-language

**Comment by meetiosdev** [comment]
> DeanFs

hello I need help with how you have shown the gallery button icon in the camera
