### ISSUE TITLE
有没有想过再升一级

### ISSUE THREAD

**Issue by sprother** [longitachi/ZLPhotoBrowser#81]
ZLPhotoBrowser-->ZLMediaBrowser
支持图片视频音乐选取 哈哈 那样会更强大吧
官方的MPMediaPicker BUG多 操作也不人性化 可能是因为这方面需求没那么多吧

**Comment by longitachi** [comment]
选择视频音乐？  系统音乐软件存储的音乐？

**Comment by sprother** [comment]
嗯 itunes同步的音乐用MPMediaPickerController可以选取,但是BUG好多而且好难用 也没见官方维护 自定义可以用MPMediaQuery

**Comment by longitachi** [comment]
这个嘛。。感觉确实需求很小啊
