### ISSUE TITLE
怎么添加自定义多语言 

### ISSUE THREAD

**Issue by Runyalsj** [longitachi/ZLPhotoBrowser#810]
e.g. 4.3.9

项目有多语言切换功能， 要加一个马来西亚的语言。 在调用图片选择器里面的保存和Done 原图等文字显示如何适配马来语展示？

**Comment by Runyalsj** [comment]
或者说ZLPhotoBrowser 是否能提供一个类似ZLPhotoBrowser.Bundle 字段的取值能根据系统语言来取具体的key映射到对应语言的value, 给用户拓展此功能让我们来自定义多语言功能

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(Swift)#Customize-language

**Comment by Runyalsj** [comment]
> https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(Swift)#Customize-language

Thanks
