### ISSUE TITLE
UIView.appearance().semanticContentAttribute = .forceRightToLeft

### ISSUE THREAD

**Issue by KevinXinSuiLu** [longitachi/ZLPhotoBrowser#811]
### Issue Description
UIView.appearance().semanticContentAttribute = .forceRightToLeft 的情况下，选中的图片和预览的图片不一致

**Comment by longitachi** [comment]
没适配过阿拉伯语言的场景，这个后面看情况适配下吧

**Comment by longitachi** [comment]
#721
