### ISSUE TITLE
[PAAccessLogger] Failed to log access with error

### ISSUE THREAD

**Issue by qinwenzhou** [longitachi/ZLPhotoBrowser#813]
### Issue Description
每次调用 showPhotoLibrary 时我都会遇到下面这个错误，不知道怎么回事：
[PAAccessLogger] Failed to log access with error: access=<PATCCAccess 0x282b68960> accessor:<<PAApplication 0x282b733e0 identifierType:auditToken identifier:{pid:13264, version:38259}>> identifier:603CF9FF-1CB7-4932-B506-5BD2DD6BA98E kind:intervalEvent timestampAdjustment:0 visibilityState:0 assetIdentifierCount:0 tccService:kTCCServicePhotos, error=Error Domain=NSCocoaErrorDomain Code=4097 "connection to service with pid 12497 named com.apple.privacyaccountingd" UserInfo={NSDebugDescription=connection to service with pid 12497 named com.apple.privacyaccountingd}

#### Info
   ZLPhotoBrowser version:  Last version
   Device:  iPhone X
   Device version:  iOS 16.0
   Xcode version:  Xcode 14.1

#### Configuration code of `ZLPhotoConfiguration`

   ```
       let config = ZLPhotoConfiguration.default()
        config.maxSelectCount = 1
        config.allowSelectImage = true
        config.allowSelectVideo = false
        config.allowSelectGif = false
        config.allowSelectLivePhoto = false
        config.allowSelectOriginal = false
        config.allowEditVideo = false
        config.allowEditImage = true
        config.allowMixSelect = false
        
        let photoPicker = ZLPhotoPreviewSheet()
        photoPicker.showPhotoLibrary(sender: rootViewController)
        photoPicker.selectImageBlock = { (results, _) in
            let images = results.map { $0.image }
            if let image = images.first {
                  // do something...
            }
        }
        photoPicker.cancelBlock = {
            rootViewController.dismiss(animated: true)
        }
   ```

**Comment by longitachi** [comment]
试了下其他的相册框架，也有类似的输出。感觉像是Apple的错误
