### ISSUE TITLE
OC项目集成报错,求解决

### ISSUE THREAD

**Issue by lijianrun** [longitachi/ZLPhotoBrowser#814]
fatal error: could not build module 'ZLPhotoBrowser'
#import <ZLPhotoBrowser/ZLPhotoBrowser-Swift.h>

**Comment by longitachi** [comment]
我自己测试没遇到过这情况。可以使用 `@import ZLPhotoBrowser;` 试一下。
搜了下可以看看这个[链接](https://a1049145827.github.io/2019/01/11/iOS%E8%87%AA%E5%AE%9A%E4%B9%89Framework-%E4%BD%BF%E7%94%A8%E6%97%B6%E6%8A%A5%E9%94%99-Could-not-build-module-%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95/)，试试能不能解决

**Comment by lijianrun** [comment]
情况是这样的:
xcode verson 14.0.1  Mac M2芯片的

真机运行不会报错

在模拟器上运行会报错
1. error: unsupported Swift architecture
2. could not build module 'ZLPhotoBrowser
<img width="366" alt="image" src="https://user-images.githubusercontent.com/27796834/233533132-70efcb9a-7c21-4eed-a7ec-cafafa0a0d53.png">

**Comment by longitachi** [comment]
我这边是intel芯片，估计是芯片原因吧。我没M2芯片电脑，没法试- -

**Comment by ElvistLui** [comment]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/21191640/234167064-bd9e872c-60c0-4785-ae0a-7e620c5d28fd.png">

这里添加【arm64】了么？

**Comment by longitachi** [comment]
> <img alt="image" width="793" src="https://user-images.githubusercontent.com/21191640/234167064-bd9e872c-60c0-4785-ae0a-7e620c5d28fd.png">
> 
> 这里添加【arm64】了么？
@lijianrun 可以试下，搜到了个类似的回答 https://stackoverflow.com/a/71107765
