### ISSUE TITLE
navBarColor和bottomToolViewBgColor方法在真机上不生效

### ISSUE THREAD

**Issue by hahaha28** [longitachi/ZLPhotoBrowser#816]
具体属性设置为：
ZLPhotoConfiguration.default()
            .allowSelectVideo(false)
            .allowSelectGif(false)
            .allowEditImage(false)  // 编辑图片
            .allowSlideSelect(false)
            .allowDragSelect(false)
            .allowTakePhotoInLibrary(false)
            .showSelectedIndex(true)
            .allowSelectOriginal(false) // 没有原图选择按钮
            .alwaysRequestOriginal(true) // 默认选原图
            .maxSelectCount(9)
            
        
ZLPhotoUIConfiguration.default()
    .languageType(ZLLanguageType.chineseSimplified)
    .navBarColor(UIColor.red)
    .bottomToolViewBgColor(UIColor.red)

其中 navBarColor(UIColor.red) 和 bottomToolViewBgColor(UIColor.red) 属性在真机不生效，在模拟器生效
真机为 iphone14，系统是ios16.0.2
模拟器为 iphone14 pro 系统是ios16.4
希望大佬看一下，谢谢

![image](https://user-images.githubusercontent.com/46659807/236660866-f84d6dcc-8b33-4a09-a8b4-957f48b1528b.png)

![image](https://user-images.githubusercontent.com/46659807/236661223-dbe9e0d6-ed91-413c-9215-aa0929f78c35.png)

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/15c2102b096123bd551fe11093fb18f304d93ea6/Sources/General/ZLPhotoUIConfiguration.swift#L100-L109
上方有一层毛玻璃效果，可将对应属性置为`nil`

**Comment by hahaha28** [comment]
> https://github.com/longitachi/ZLPhotoBrowser/blob/15c2102b096123bd551fe11093fb18f304d93ea6/Sources/General/ZLPhotoUIConfiguration.swift#L99-L109
> 
> 
> 上方有一层毛玻璃效果，可将对应属性置为`nil`

感谢作者回复，ios小白昨天看了好久后发现了
