### ISSUE TITLE
异步线程更新UI设置导致崩溃

### ISSUE THREAD

**Issue by yinsenlee** [longitachi/ZLPhotoBrowser#821]
文件：ZLCustomCamera.swift

方法：private func setupCamera()
 
代码：// imageOutPut添加到session之后才能判断supportedFlashModes
            if !cameraConfig.showFlashSwitch || !imageOutput.supportedFlashModes.contains(.on) {
                self.showFlashBtn = false
            }
设置showFlashBtn属性的时候，set方法会同步设置按钮是否隐藏

这个操作在sessionQueue.async异步线程中执行，异步线程中执行UI操作会导致崩溃

可能还会有别的地方UI操作没有在主线程操作，这个没细看。

![截屏2023-06-07 15 04 45](https://github.com/longitachi/ZLPhotoBrowser/assets/3182034/29a1137f-31ee-4810-89b3-ec6bb52c9890)

另外：拍照页面能否支持横竖屏，或者通过配置来设置

**Comment by longitachi** [comment]
感谢提出bug，会尽快修复。 拍照界面无法支持横屏，在iPad上横屏就会有很多问题，我看了下微信的iPad上会用系统相机。

相机会监控横竖屏，不影响横屏拍照。
