### ISSUE TITLE
在iOS 14 版本 会报 Image not found 导致项目崩溃

### ISSUE THREAD

**Issue by SunsetLi** [longitachi/ZLPhotoBrowser#822]
在iOS 14 版本 会报 Image NO found 导致项目崩溃，从git上下载的demo也无法在iOS 14正常运行， Image NO found 项目崩溃

**Comment by longitachi** [comment]
新提issue时候，会有一些收集信息的选项，补充一下吧。

demo在iOS14模拟器上也会报错吗？

**Comment by SunsetLi** [comment]
对的对的

**Comment by longitachi** [comment]
我用demo跑了14.1的模拟器和14.6的真机，均为出现issue描述的问题。

**Comment by SunsetLi** [comment]
好吧，那有可能是部分模拟器出现的问提，我使用 14.0.1 版本崩溃了
![WeChatf9ed76216550253ef28ae4962160c0b9](https://github.com/longitachi/ZLPhotoBrowser/assets/20609780/dd3456f9-31c6-455c-b833-6f397c88e948)

**Comment by longitachi** [comment]
如果有iOS14的设备，可以试下真机。我后续再找点iOS14的机器试下

**Comment by wdnmd123-zzz** [comment]
> 
这个问题解决了吗

**Comment by longitachi** [comment]
> > 
> 
> 这个问题解决了吗

我这边没试出来crash

**Comment by fengxinzi1814** [comment]
我也出现这个问题了

**Comment by wdnmd123-zzz** [comment]
> 

14.0.1的模拟器有这个问题，可以换版本稍高一点的IOS14的模拟器
