### ISSUE TITLE
ZLBaseStickerView中 maxGesScale 初始化值问题

### ISSUE THREAD

**Issue by fred-gz** [longitachi/ZLPhotoBrowser#825]
### Issue Description
图片增加贴纸操作， 当在编辑页面把所编辑的图片拉伸到最大后， 再添加贴纸， 此时 maxGesScale应该同比例放大
否则拉伸编辑图片到最小后， 再操作贴纸拉伸时， 无法拉到最大

解决方法：
 ZLBaseStickerView init方法中， 矫正一下最大值
self.maxGesScale = self.maxGesScale / originScale

**Comment by longitachi** [comment]
后续优化下
