### ISSUE TITLE
把手机打横，拍照，之后得到的照片只占顶部一点点位置 感觉是处理方向的问题

### ISSUE THREAD

**Issue by longfeiwang91** [longitachi/ZLPhotoBrowser#828]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.2
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/issues/819
这个最新版已修复，横屏拍照后
