### ISSUE TITLE
老哥，支持多张图片同时编辑么，左右滑动切换图片。

### ISSUE THREAD

**Issue by dbbdsz** [longitachi/ZLPhotoBrowser#829]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.2
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
不支持~
