### ISSUE TITLE
ZLPhotoPreviewController  预览滚动时crash

### ISSUE THREAD

**Issue by Aliffter** [longitachi/ZLPhotoBrowser#834]
#### Description and Steps
1. 从相册中选择图片，点击图片后预览，
2. 侧滑滚动预览照片crash。 必现
同样的代码及配置。另外一个项目就是正常的。然而我这个项目就回crash，必现
原因：
进入页面时，查看 self.navigationController 有值，滑动后 self.navigationController 不知何时为空了，导致强转crash 
resetSubViewStatus方法 ---> let nav = self.navigationController as! ZLImageNavController

[crash如图：](https://upload-images.jianshu.io/upload_images/3409012-f9235b7621dde496.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

#### Info
   ZLPhotoBrowser version:  e.g. 4.1.9
   Device:  e.g. iPhone 13
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.2

#### Configuration code of `ZLPhotoConfiguration`

   ```
         let config = ZLPhotoConfiguration.default()
        config.allowSelectImage = true
        config.allowSelectVideo = false
        config.allowSelectGif = false
        config.allowSelectLivePhoto = false
        config.allowSelectOriginal = false
        config.allowEditVideo = false
        config.allowMixSelect = false
        config.maxSelectCount = 1
        
        let photoPicker = ZLPhotoPreviewSheet()
        
        photoPicker.selectImageBlock = { [weak self] (images, assets, _) in
           
        }
        
        photoPicker.showPhotoLibrary(sender: self)

   ```

**Comment by longitachi** [comment]
版本太老了，升级下就好了

**Comment by Aliffter** [comment]
恩嗯，找到原因了。谢谢😀
