### ISSUE TITLE
@rpath/libswiftAVFoundation.dylib

### ISSUE THREAD

**Issue by forkdog** [longitachi/ZLPhotoBrowser#839]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  4.4.3.2
   Device:   模拟器
   Device version:  iOS 14.0 模拟器
   Xcode version:  Xcode 14.3.1

新建一个空白工程，使用CocoaPods导入pod 'ZLPhotoBrowser'，不写任何代码，运行在iOS14模拟器上会崩溃，希望作者修复下。

`Warning: Error creating LLDB target at path '/Users/PP/Library/Developer/Xcode/DerivedData/Demo-exaggbsmpndngccldnxlkzennvgz/Build/Products/Debug-iphonesimulator/Demo.app'- using an empty LLDB target which can cause slow memory reads from remote devices.
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/PP/Library/Developer/CoreSimulator/Devices/786A8A38-C0CF-1F69-9EB3-C422F77B004A/data/Containers/Bundle/Application/3883B27C-3354-45F2-AE5B-A0B829843AFB/Demo.app/Demo
  Reason: image not found`

**Comment by longitachi** [comment]
#822 
可以试下14.0的真机。 当前已知在14.0还是14.0.1的模拟器上会crash，我这边没有对应版本的机器，没法测

**Comment by forkdog** [comment]
我也没，那还能修复在模拟器crash的问题吗

**Comment by KhayraHongtao** [comment]
User
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/apple/Library/Developer/CoreSimulator/Devices/8B09549D-9F9E-411E-8979-32A9AF1EC187/data/Containers/Bundle/Application/B12131CB-F491-48E2-AF9B-C4863E561670/HTProjectSwift.app/Frameworks/ZLPhotoBrowser.framework/ZLPhotoBrowser
  Reason: image not found
  
  模拟器14.0.1版本 真机 13.6.1版本都会cash

**Comment by longitachi** [comment]
![demo](https://github.com/longitachi/ZLPhotoBrowser/assets/11711768/2079f2ca-a7d4-4bde-bd5e-bdbcc0fd3737)
iPhone11 13.6.1系统 正常运行

**Comment by longitachi** [comment]
暂时没有能复现的设备，你们能复现的可以尝试解决下，提个PR

**Comment by longitachi** [comment]
@guanru  提了pr修复了， @forkdog @KhayraHongtao  可以用这个分支试下，看是否还会crash https://github.com/guanru/ZLPhotoBrowser/tree/upstream/fix

**Comment by KhayraHongtao** [comment]
> @guanru 提了pr修复了， @forkdog @KhayraHongtao 可以用这个分支试下，看是否还会crash https://github.com/guanru/ZLPhotoBrowser/tree/upstream/fix

我想知道做了哪些设置的处理吗？  我pod 到工程里面，还是有问题， 下载 demo运行没问题

**Comment by longitachi** [comment]
https://github.com/guanru/ZLPhotoBrowser/commit/b67f8047439e61c25d1149ce7c17c070bf1a0a72
可以在你的项目中因如下这个`libswiftAVFoundation.tbd` framework

**Comment by KhayraHongtao** [comment]
> 暂时没有能复现的设备，你们能复现的可以尝试解决下，提个PR

@longitachi 我想知道做了哪些设置的处理吗？ 我pod 到工程里面，还是有问题， 下载 demo运行没问题

**Comment by KhayraHongtao** [comment]
> @KhayraHongtao
> [guanru@b67f804](https://github.com/guanru/ZLPhotoBrowser/commit/b67f8047439e61c25d1149ce7c17c070bf1a0a72)
> 可以在你的项目中因如下这个`libswiftAVFoundation.tbd` framework

你好，我新建一个demo, 
pod 'ZLPhotoBrowser', '~> 4.4.5' 

选择 "General"（常规）选项卡。
滚动到 "Frameworks, Libraries, and Embedded Content"（框架、库和嵌入内容）部分。
在这个部分，你可以点击加号（+）按钮以添加框架。
在弹出窗口中，你可以搜索 libswiftAVFoundation.tbd 或手动选择它。

运行还不OK；

**Comment by KhayraHongtao** [comment]
> 等明天我用的demo，推到cocoapods尝试解决下。
好的，感谢

**Comment by KhayraHongtao** [comment]
> 等明天我用的demo，推到cocoapods尝试解决下。

可以了，回复一下我，非常感谢

**Comment by longitachi** [comment]
整不了，想着在`podspec`里面添加一下`s.frameworks    = 'libswiftAVFoundation'` 这个，发现不支持。你能提供个录屏吗，我看下怎么在13.6.1的机器上crash的，上面我也提供了视频，真机上没有遇到crash

**Comment by KhayraHongtao** [comment]
> 整不了，想着在`podspec`里面添加一下`s.frameworks = 'libswiftAVFoundation'` 这个，发现不支持。你能提供个录屏吗，我看下怎么在13.6.1的机器上crash的，上面我也提供了视频，真机上没有遇到crash

我有个录屏，我在怎么回答你上传录屏

**Comment by KhayraHongtao** [comment]
> 整不了，想着在`podspec`里面添加一下`s.frameworks = 'libswiftAVFoundation'` 这个，发现不支持。你能提供个录屏吗，我看下怎么在13.6.1的机器上crash的，上面我也提供了视频，真机上没有遇到crash

http://market.file.meididi88.com/Patrol/ios_video_1697103687.018455.mp4
我生成了一个链接，看下

**Comment by longitachi** [comment]
把demo传上来吧，我试下你的demo。手机系统是13.6.1的吗？

**Comment by KhayraHongtao** [comment]
> 把demo传上来吧，我试下你的demo。手机系统是13.6.1的吗？

github 出现的问题，我上传到 码云；；
https://gitee.com/Khayra_ht/update_photos_deme/tree/main/

在main  分支里面

**Comment by KhayraHongtao** [comment]
> 把demo传上来吧，我试下你的demo。手机系统是13.6.1的吗？

14.0.1

**Comment by KhayraHongtao** [comment]
> 把demo传上来吧，我试下你的demo。手机系统是13.6.1的吗？

下载你的demo,  模拟器14.0.1 运行是成功了，  但是集成  pod, 在运行 就 报错

**Comment by longitachi** [comment]
<img width="320" alt="image" src="https://github.com/longitachi/ZLPhotoBrowser/assets/11711768/cec786e9-ef3c-433e-8219-7c86d9a35def">
直接把zip包拖到评论窗口了，在这个issue里传吧

**Comment by KhayraHongtao** [comment]
> <img alt="image" width="320" src="https://user-images.githubusercontent.com/11711768/274835273-cec786e9-ef3c-433e-8219-7c86d9a35def.png"> 直接把zip包拖到评论窗口了，在这个issue里传吧
[demodemo----.zip](https://github.com/longitachi/ZLPhotoBrowser/files/12892359/demodemo----.zip)

**Comment by KhayraHongtao** [comment]
> <img alt="image" width="320" src="https://user-images.githubusercontent.com/11711768/274835273-cec786e9-ef3c-433e-8219-7c86d9a35def.png"> 直接把zip包拖到评论窗口了，在这个issue里传吧

好的，看下，谢谢，麻烦了

**Comment by KhayraHongtao** [comment]
> <img alt="image" width="320" src="https://user-images.githubusercontent.com/11711768/274835273-cec786e9-ef3c-433e-8219-7c86d9a35def.png"> 直接把zip包拖到评论窗口了，在这个issue里传吧
> [demodemo----.zip](https://github.com/longitachi/ZLPhotoBrowser/files/12892359/demodemo----.zip)

@longitachi 你好，有复现出来吗？

**Comment by longitachi** [comment]
没有14.0.1设备。。试了其他相近系统，暂没发现

**Comment by longitachi** [comment]
@KhayraHongtao 已修复

**Comment by KhayraHongtao** [comment]
> @KhayraHongtao 已修复

推上去了吗？ 我可以更新 sdk 版本就可以了？

**Comment by KhayraHongtao** [comment]
> @KhayraHongtao 已修复

看到了，，，谢谢

**Comment by KhayraHongtao** [comment]
> @KhayraHongtao 已修复

大概，什么时候推送个版本上去 ， 我先改pod里面文件

**Comment by longitachi** [comment]
明天吧
