### ISSUE TITLE
主界面的gif图，没找到设置的代码啊，就是可以动，是怎么回事

### ISSUE THREAD

**Issue by yanyi-tudou** [longitachi/ZLPhotoBrowser#84]
主界面的gif图，没找到设置的代码啊，就是可以动，是怎么回事

**Comment by longitachi** [comment]
因为框架返回给你的就是处理好的图片，就是_UIAnimatedImage类型的，所以不需要处理，直接赋值给UIImageView对象就能动

**Comment by yanyi-tudou** [comment]
哦，明白了，但是我要先把图片存到本地，然后在读取出来显示出来，这样的话，好像又转换成UIImage类型了，好像还得自己处理 @longitachi

**Comment by longitachi** [comment]
你导入ZLPhotoManager.h，使用如下方法转换就行了

+ (UIImage *)transformToGifImageWithData:(NSData *)data;

**Comment by yanyi-tudou** [comment]
我存到本地以后，然后读取出来，调用了那个方法，还是不行，然后加上这个方法 resumeGif，也不行，是不是因为我存储到本地的时候的方式不对，可不可以加你qq咨询一下

**Comment by longitachi** [comment]
可以 495181165
