### ISSUE TITLE
iCloud image support not well. 

### ISSUE THREAD

**Issue by FanYouXin** [longitachi/ZLPhotoBrowser#840]
### Issue Description
If there are too many images in the album in the iCloud, the application will get stuck when opening the album.
Picture over 8000.
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.3.2
   Device:  e.g. iPhone 13
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.2

#### Configuration code of `ZLPhotoConfiguration`

   ```
   According to user feedback, I haven't simulated this situation yet
   ```

**Comment by longitachi** [comment]
I have nearly 5,000 photos on my phone, and I haven't had a problem opening the photo album without getting stuck. Photos are loaded asynchronously and there will be a loading indicator.

Can you provide the configuration code for `ZLPhotoConfiguration`.
