### ISSUE TITLE
Xcode15适配问题

### ISSUE THREAD

**Issue by SPStore** [longitachi/ZLPhotoBrowser#841]
Xcode15上，Assets.xcassets 添加的资源文件，会自动生成 symbols 常量，系统内部定义了ImageResource结构体，如图：
<img width="991" alt="image" src="https://github.com/longitachi/ZLPhotoBrowser/assets/19994204/78fa2185-b8f4-4ca1-917d-156a55e17a7b">

你的Example中也定义了同名结构体，产生了冲突

**Comment by longitachi** [comment]
这个是`Kingfisher`里面的，今天我更新下`Kingfisher`源码，看他有没有解决
