### ISSUE TITLE
涂鸦建议

### ISSUE THREAD

**Issue by SPStore** [longitachi/ZLPhotoBrowser#843]
![image](https://github.com/longitachi/ZLPhotoBrowser/assets/19994204/871d0235-07e1-4830-9104-dd9aa6ee722a)

我有个小建议：我看微信中涂鸦的时候，曲线更加的圆滑，您的框架会有折线棱角，我看源码应该是如上图导致的，可以将addLine，改成addCurve，设置2个控制点，就能使得曲线更加圆滑。

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/commit/771b6a65da325c98329083e166354e25b24d27bc
