### ISSUE TITLE
alwaysRequestOriginal - video support (fetching videos from iCloud)

### ISSUE THREAD

**Issue by patryk-sredzinski** [longitachi/ZLPhotoBrowser#844]
### Issue Description
Is there any way to fetch videos from iCloud, when selecting them from gallery?
So I all videos are quickly accessible in selectImageBlock block?

#### Description and Steps
Right now, when I select multiple videos from my CameraRoll. I receive PHAssets, and I need to call:
ZLPhotoManager.fetchVideo(for: asset) for each of them.

Can we have it implemented in the picker itself? So I'll see the 'waiting...' spinner for the fetching time?

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.3
   Device:  iPhone 11
   Device version:  iOS 16.6
   Xcode version:  Xcode 14.3

**Comment by longitachi** [comment]
`alwaysRequestOriginal ` is only used for fetch the full image for the asset.

The demo now supports downloading videos on iCloud before selecting videos. Cocoapods has not been uploaded yet.
https://github.com/longitachi/ZLPhotoBrowser/blob/ea087338107abebf591d6125a1f491263aaf3c80/Sources/General/ZLPhotoConfiguration.swift#L100-L102
