### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib 闪退

### ISSUE THREAD

**Issue by KhayraHongtao** [longitachi/ZLPhotoBrowser#845]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.3.2
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 13.6.1
   Xcode version:  e.g. Xcode 14.0.1

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/apple/Library/Developer/CoreSimulator/Devices/8B09549D-9F9E-411E-8979-32A9AF1EC187/data/Containers/Bundle/Application/B12131CB-F491-48E2-AF9B-C4863E561670/HTProjectSwift.app/Frameworks/ZLPhotoBrowser.framework/ZLPhotoBrowser
  Reason: image not found
  
执行就报错

**Comment by longitachi** [comment]
#839
