### ISSUE TITLE
项目下载下来就报错了 'ImageResource' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by stevendinggang** [longitachi/ZLPhotoBrowser#848]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.3.2
   Device:  e.g. iPhone X
   Device version:  e.g. iOS 14.0
<img width="1277" alt="截屏2023-08-22 13 37 47" src="https://github.com/longitachi/ZLPhotoBrowser/assets/15857889/65b34a3e-ef3b-4424-86dd-6e8789fe7d6a">

   Xcode version:  e.g. Xcode 12.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
我搜了下仓库里就没有这个文件。。

**Comment by stevendinggang** [comment]
好的, 谢谢. 我关掉哈
