### ISSUE TITLE
iOS 8.0 点击相册会崩溃

### ISSUE THREAD

**Issue by TenYuan** [longitachi/ZLPhotoBrowser#85]
需要修改ZLThumbnailViewController.m  
源代码
ZLImageNavigationController *nav = (ZLImageNavigationController *)self.navigationController;
        if (nav.allowForceTouch && [self forceTouchAvailable]) {
            [self registerForPreviewingWithDelegate:self sourceView:self.collectionView];
        }
修改后的代码
if (iOS9_OR_LATER) {//判断当前系统是不是9.0以上
        ZLImageNavigationController *nav = (ZLImageNavigationController *)self.navigationController;
        if (nav.allowForceTouch && [self forceTouchAvailable]) {
            [self registerForPreviewingWithDelegate:self sourceView:self.collectionView];
        }
    }
崩溃原因：在forceTouchAvailable 方法，中UIForceTouchCapabilityAvailable 需要9.0以上系统支持

**Comment by TenYuan** [comment]
系统版本判断宏
#define iOS10_OR_LATER ([[[UIDevice currentDevice] systemVersion] floatValue] >= 10.0)
#define iOS9_OR_LATER ([[[UIDevice currentDevice] systemVersion] floatValue] >= 9.0)
#define iOS8_OR_LATER ([[[UIDevice currentDevice] systemVersion] floatValue] >= 8.0)
#define iOS7_OR_LATER ([[[UIDevice currentDevice] systemVersion] floatValue] >= 7.0)
#define iOS6_OR_LATER ([[[UIDevice currentDevice] systemVersion] floatValue] >= 6.0)

**Comment by longitachi** [comment]
谢谢，稍后会把该判断添加上去
