### ISSUE TITLE
Feature: Global Undo/Redo

### ISSUE THREAD

**Issue by patryk-sredzinski** [longitachi/ZLPhotoBrowser#856]
### Feature Description

I have been thinking of having an universal UNDO and REDO button on the top right corner of the Image Editing Controller.
That allows you to undo drawings, mosaic, stickers, filters etc.

What do you think about this?
I have got this working:

https://github.com/longitachi/ZLPhotoBrowser/assets/23390884/a4257ef0-4bd9-4ab2-b6c2-ed09df70d24a

Do you think we can get something like that?
What I currently have are changes that required me to completely remove 'REDO' functionality, and I don't like the code I did as it is more like a workaround and not really fitting your code style.

I could work on something like that, If you'll give me some advices how you'd like to (if at all) to have this supported. Being sure that my code will eventually end up on a master branch would be a good motivation. 

https://github.com/patryk-sredzinski/ZLPhotoBrowser/pull/10/files - Those are the changes I did to make what we see above.

**Comment by longitachi** [comment]
Thanks for your contribution. You can push your code in this branch (https://github.com/longitachi/ZLPhotoBrowser/tree/zl/universal-undo), I will also develop in this branch. But I'm not sure if this feature will eventually be adopted.

**Comment by longitachi** [comment]
I see that WeChat has recently added this feature as well. I wasn't sure about the UI style before, but now I can follow WeChat's UI.
