### ISSUE TITLE
有2个小细节

### ISSUE THREAD

**Issue by SPStore** [longitachi/ZLPhotoBrowser#857]
ZLPhotoPreviewPopInteractiveTransition这个转场动画还有些不足之处：
1、刚开始往下拖拽准备进行dismiss的那一瞬间，仔细体验会发现会稍微迟钝一下，不如微信原生流畅，仔细体验才能感觉到
2、浏览器中的每个cell中是有一个用于缩放的scrollView的，当scrollView放大之后，并且offset.y为边界值时，微信原生依然是可以拖拽dismiss的，这个浏览器遗漏了这个case，没有做手势兼容处理。
3、编辑图片的时候，选择贴纸 --> 保存(假如保存的时候贴纸的位置是A) --> 编辑(二次编辑) --> 移动贴纸(由A移动到B) --> 保存(第二次保存的时候，贴纸会有有一个从位置A到B的跳跃过程，这是个bug)

然后微信最近相册选择器有一些小改版，比如选择照片的时候，数字不在显示在右上角，而是左上角单独显示，编辑图片涂鸦的时候多了橡皮擦功能，橡皮擦与贝塞尔曲线相交时，曲线会变色并描边，还有震动效果。还有右侧新增了自定义滚动条

**Comment by longitachi** [comment]
新功能该得多，后面有时间会加~   有空了会先做下体验优化

**Comment by SPStore** [comment]
嗯嗯，新功能可以看情况而定，不加问题也不大。
有一些业界大多都有的还是希望能有，比如我说的第二条scrollView方大后也支持拖拽dismiss，很多浏览器都是支持的。我看了另外一个跟你这个类似的照片选择器，名叫HXPhotoPicker，他那个从功能全面以及bug上要优于你这个，但是它仅仅是功能做的多，代码几乎没有任何设计模式，最多是通过扩展的方式抽离代码，代码相当的混乱。

另外我新增了第3条bug，作者可以按我的步骤自测试试

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/issues/854
第三个已修复，暂未发版

**Comment by SPStore** [comment]
嗯嗯，后续有问题我会持续反馈，如果要时间我也可以申请提交代码，帮助你修复部分问题
