### ISSUE TITLE
代码有问题

### ISSUE THREAD

**Issue by SPStore** [longitachi/ZLPhotoBrowser#858]
<img width="1088" alt="image" src="https://github.com/longitachi/ZLPhotoBrowser/assets/19994204/cf891bce-ee94-49bf-9766-6bee42d34dc6">
红方框中的代码，全部是在主线程中执行的，HUD根本就弹不出来

**Comment by longitachi** [comment]
361ef899ce328fde4b944f160e328612cd6af546 fixed
