### ISSUE TITLE
没有导入 <Photos.framework>和<PhotosUI.framework>，导致编译报错

### ISSUE THREAD

**Issue by zhangle520** [longitachi/ZLPhotoBrowser#86]
"_OBJC_CLASS_$_PHLivePhotoRequestOptions", referenced from:
      objc-class-ref in ZLPhotoManager.o
  "_OBJC_CLASS_$_PHFetchOptions", referenced from:
      objc-class-ref in ZLPhotoManager.o
  "_PHImageManagerMaximumSize", referenced from:
      +[ZLPhotoManager requestOriginalImageForAsset:completion:] in ZLPhotoManager.o
      +[ZLPhotoManager requestLivePhotoForAsset:completion:] in ZLPhotoManager.o
  "_OBJC_CLASS_$_PHAssetCollectionChangeRequest", referenced from:
      objc-class-ref in ZLPhotoManager.o
  "_PHImageErrorKey", referenced from:
      ___62+[ZLPhotoManager requestOriginalImageDataForAsset:completion:]_block_invoke in ZLPhotoManager.o
      ___66+[ZLPhotoManager requestImageForAsset:size:resizeMode:completion:]_block_invoke in ZLPhotoManager.o
"_OBJC_CLASS_$_PHCollectionList", referenced from:
      objc-class-ref in ZLPhotoManager.o
  "_OBJC_CLASS_$_PHPhotoLibrary", referenced from:
      objc-class-ref in ZLPhotoActionSheet-5ADD1C56EE50D85D.o
      objc-class-ref in ZLPhotoManager.o
  "_OBJC_CLASS_$_PHLivePhotoView", referenced from:
      objc-class-ref in ZLForceTouchPreviewController.o
      objc-class-ref in ZLBigImageCell.o
      objc-class-ref in ZLShowLivePhotoViewController.o
 "_OBJC_CLASS_$_PHAssetCollection", referenced from:
      objc-class-ref in ImageViewController.o
      objc-class-ref in ZLPhotoManager.o
  "_OBJC_CLASS_$_PHAsset", referenced from:
      objc-class-ref in EaseMessageViewController.o
      objc-class-ref in ImageViewController.o
      objc-class-ref in ZLPhotoManager.o
"_OBJC_CLASS_$_PHImageRequestOptions", referenced from:
      objc-class-ref in ImageViewController.o
      objc-class-ref in ZLPhotoManager.o
"_OBJC_CLASS_$_PHImageManager", referenced from:
      objc-class-ref in EaseMessageViewController.o
      objc-class-ref in ImageViewController.o
      objc-class-ref in ZLPhotoManager.o ...
  "_OBJC_CLASS_$_PHAssetChangeRequest", referenced from:
      objc-class-ref in ZLPhotoManager.o
  "_OBJC_CLASS_$_PHCachingImageManager", referenced from:
      objc-class-ref in ZLCollectionCell.o
      objc-class-ref in ZLPhotoManager.o
      objc-class-ref in ZLBigImageCell.o
  "_PHImageCancelledKey", referenced from:
      ___62+[ZLPhotoManager requestOriginalImageDataForAsset:completion:]_block_invoke in ZLPhotoManager.o
      ___66+[ZLPhotoManager requestImageForAsset:size:resizeMode:completion:]_block_invoke in ZLPhotoManager.o
  "_PHImageResultIsDegradedKey", referenced from:
      ___29-[ZLCollectionCell setModel:]_block_invoke in ZLCollectionCell.o
      ___33-[ZLEditViewController loadImage]_block_invoke in ZLEditViewController.o
      ___39-[ZLPhotoActionSheet requestSelPhotos:]_block_invoke in ZLPhotoActionSheet-5ADD1C56EE50D85D.o
      ___84+[ZLPhotoManager requestSelectedImageForAsset:isOriginal:allowSelectGif:completion:]_block_invoke in ZLPhotoManager.o
      ___37-[ZLPreviewImageAndGif loadGifImage:]_block_invoke in ZLBigImageCell.o
      ___40-[ZLPreviewImageAndGif loadNormalImage:]_block_invoke in ZLBigImageCell.o
      ___38-[ZLPreviewLivePhoto loadNormalImage:]_block_invoke in ZLBigImageCell.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by longitachi** [comment]
你是文件夹直接拖进项目的吗？ 有没有导入 <Photos.framework>和<PhotosUI.framework>?

**Comment by zhangle520** [comment]
谢谢作者这么快速的回答了我的提问，现在这个问题已经解决了
