### ISSUE TITLE
荷兰文支持一下吧

### ISSUE THREAD

**Issue by FanYouXin** [longitachi/ZLPhotoBrowser#864]
"animated" = "Dynamisch diagram";//"动图"

"back" = "terug";//"返回"

"bursts" = "momentopname";//"连拍快照"

"apply" = "Toepassen";

"cameraRoll" = "Recente projecten";//"最近项目"

"cameraUnavailable" = "Camera niet beschikbaar";//相机不可用"

"cancel" = "annuleren";//取消

"customCameraRecordVideoTips" = "Pers en vasthouden camera";//按住摄像

"customCameraTakePhotoTips" = "Tik om foto's te nemen";//"轻触拍照"

"customCameraTips" = "Tik om een foto te nemen en druk en houd de camera vast";//轻触拍照，按住摄像

"depthEffect" = "afbeelding";//"人像"

"done" = "Volgende";//next

"Next" = "Volgende";

"edit" = "Bewerken";//"编辑"

"editFinish" = "Einde";//"完成"

"exceededMaxSelectCount" = "Op z'n hoogst %ld foto";//"最多只能选择%ld张图片"

"exceededMaxVideoSelectCount" = "Op z'n hoogst %ld video";//"最多只能选择%ld个视频"

"favorites" = "Persoonlijke verzameling";//"个人收藏"

"hudLoading" = "Verwerking";//"正在处理..."

"iCloudVideoLoadFaild" = "Iclaw kan niet synchroniseren";//"iCloud无法同步"

"imageLoadFailed" =  "Afbeelding kan niet worden geladen";//"图片加载失败"

"lessThanMinVideoSelectCount" = "Selecteer ten minste %ld video's";//"最少选择%ld个视频"

"livePhotos" =  "Live foto's";//"Live Photos"

"loading" =  "Laden even geduld aub";//"加载中，请稍后"

"longerThanMaxVideoDuration" =  "Kan geen video's selecteren die langer zijn dan %ld seconden";//"不能选择超过%ld秒的视频"

"minRecordTimeTips" =  "Neem minstens %ld seconden op";//"至少录制%ld秒"

"myPhotoStream" =  "Mijn foto stream";//"我的照片流"

"noCameraAuthority" =  "Geef %@ toegang tot uw camera via de telefoon\"Instellingen-Privacy-Camera\" optie";//"请在iPhone的\"设置-隐私-相机\"选项中，允许%@访问你的相机"

"noMicrophoneAuthority" = "Geef %@ toegang tot uw microfoon via de optie \"Instellingen-Privacy-microfoon\" van uw telefoon";//"请在iPhone的\"设置-隐私-麦克风\"选项中，允许%@访问你的麦克风"

"noPhotoLibratyAuthority" =  "Geef %@ toegang tot uw foto's in de optie \"Instellingen-Privacy-Foto's\" van uw telefoon";//"请在iPhone的\"设置-隐私-照片\"选项中，允许%@访问你的照片"

"noPhotoTips" =  "Geen foto";//"无照片"

"notAllowMixSelect" =  "Kan niet tegelijkertijd foto's en video's selecteren";//"不能同时选择照片和视频"

"noTitleAlbumListPlaceholder" =  "Alle foto's";//"所有照片"

"ok" =  "Zeker wel";//"确定"

"originalPhoto" =  "Originele afbeelding";//"原图"

"panoramas" = "Panorama";  //"全景照片"

"photo" =   "Foto";// "照片"

"preview" =  "Voorbeeld";//"Preview";

"previewAlbum" =   "Album";//"相册"

"previewCamera" = "Fotograaf"; //"拍照"

"previewCameraRecord" =  "Schieten";//"拍摄"

"recentlyAdded" = "Recent toegevoegd";//"最近添加"

"revert" = "vermindering";//"还原"

"save" = "opslaan";// "保存"

"saveImageError" = "Opslaan van foto mislukt";//"图片保存失败"

"saveVideoError" =  "Opslaan van video mislukt";//"视频保存失败"

"screenshots" = "Schermafbeelding";//"屏幕快照"

"selfPortraits" =   "selfie"; //"自拍"

"shorterThanMaxVideoDuration" = "Kan geen video's van minder dan %ld seconden selecteren";//"不能选择低于%ld秒的视频"

"slomoVideos" = "Slow-motion";//"慢动作"

"textStickerRemoveTips" = "Sleep hier om te verwijderen";//"拖到此处删除"

"timelapses" = "Time-lapse-fotografie";//"延时摄影"

"timeout" = "Verzoek time-out";//"请求超时"

"unableToAccessAllPhotos" = "Geen toegang tot alle foto's in het album,\nGeef toegang tot 'Alle foto's' in 'Foto's'"; //"无法访问相册中所有照片，\n请允许访问「照片」中的「所有照片」。"

"videos" = "video";//"视频"

/* No comment provided by engineer. */
"More_TabBarItem" = "";

**Comment by FanYouXin** [comment]
case nederland

**Comment by longitachi** [comment]
好的，下次更新会支持下

**Comment by longitachi** [comment]
已支持 https://github.com/longitachi/ZLPhotoBrowser/commit/b1f1dff6ceb2fc9a01592d04692708d3275aa42e
