### ISSUE TITLE
选择相册视频，报请求超时

### ISSUE THREAD

**Issue by zengweihuanfengzizhi** [longitachi/ZLPhotoBrowser#865]
#### Description and Steps
选择相册视频，报请求超时， https://foruda.gitee.com/images/1697616591530652336/33e7be01_8450133.jpeg

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.1
   Device:  e.g. 
   Device version:  e.g. 
   Xcode version:  e.g. Xcode 14.2

**Comment by longitachi** [comment]
可先确定网络环境是否正常WIFI是否设置了代理，这些都会影响iCloud视频的下载

**Comment by zengweihuanfengzizhi** [comment]
> 可先确定网络环境是否正常WIFI是否设置了代理，这些都会影响iCloud视频的下载

这个基本能确定是iCloud同步的视频是吗，因为是这样直接拍摄可以直接上传就是本地选取出现了，很难复现

**Comment by longitachi** [comment]
选择不上报超时，基本就确定是iCloud上的视频了。可以进大图界面看下有没有loading框
