### ISSUE TITLE
更新完新版本4.4.6之后，ios14相册列表选择圈圈点击不了

### ISSUE THREAD

**Issue by KhayraHongtao** [longitachi/ZLPhotoBrowser#866]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.6
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 14.0.1
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.

https://github.com/longitachi/ZLPhotoBrowser/assets/14037413/312f3709-edde-4ebb-bedc-a355147040f1


   ```

**Comment by KhayraHongtao** [comment]
https://github.com/longitachi/ZLPhotoBrowser/assets/14037413/9b6a18a8-a4ed-47ce-a91e-d6c4d9f6a31b
<img width="463" alt="WeChat9a78216bd04919de0e4cd2e02f1701a2" src="https://github.com/longitachi/ZLPhotoBrowser/assets/14037413/6b304b0d-61fd-473e-9d65-4df359860736">

**Comment by KhayraHongtao** [comment]
<img width="1012" alt="WeChatb8a711746dafa2cef0f8a8e7ac8f6a2b" src="https://github.com/longitachi/ZLPhotoBrowser/assets/14037413/ee159e13-8ad1-484e-b958-8fd9f5d0971f">

新版本的那个方法是支持 数字在选择上面的 ？

**Comment by KhayraHongtao** [comment]
> https://github.com/longitachi/ZLPhotoBrowser/assets/14037413/9b6a18a8-a4ed-47ce-a91e-d6c4d9f6a31b
> <img alt="WeChat9a78216bd04919de0e4cd2e02f1701a2" width="463" src="https://user-images.githubusercontent.com/14037413/276891465-6b304b0d-61fd-473e-9d65-4df359860736.png">

这个是圈圈按钮点击没效果，模拟器14.0.1，

**Comment by longitachi** [comment]
我试了下demo和单独pod集成均没问题。模拟器是14.0.1的SE2，你自己调试下吧。下个demo试试

**Comment by KhayraHongtao** [comment]
> 我试了下demo和单独pod集成均没问题。模拟器是14.0.1的SE2，你自己调试下吧。下个demo试试

不好意思，我发现问题，

**Comment by longitachi** [comment]
> 
> 不好意思，我发现问题，

？ 是什么问题？demo运行有问题吗？

**Comment by KhayraHongtao** [comment]
> > 不好意思，我发现问题，
> 
> ？ 是什么问题？demo运行有问题吗？

不是，是我程序里面OC代码对 swift 产生的影响，，  就是那个该死的 runtime 处理重复点击事件的问题；

**Comment by KhayraHongtao** [comment]
> <img alt="WeChatb8a711746dafa2cef0f8a8e7ac8f6a2b" width="1012" src="https://user-images.githubusercontent.com/14037413/276895033-ee159e13-8ad1-484e-b958-8fd9f5d0971f.png">
> 新版本的那个方法是支持 数字在选择上面的 ？

这个我也找到了。原生UI的配置也是单独的；；

**Comment by KhayraHongtao** [comment]
> <img alt="WeChatb8a711746dafa2cef0f8a8e7ac8f6a2b" width="1012" src="https://user-images.githubusercontent.com/14037413/276895033-ee159e13-8ad1-484e-b958-8fd9f5d0971f.png">
> 新版本的那个方法是支持 数字在选择上面的 ？

这个我也找到了。原生UI的配置也是单独的；；
