### ISSUE TITLE
选择更多照片中的取消按钮和确定按钮字体为白色，看不清

### ISSUE THREAD

**Issue by chennian** [longitachi/ZLPhotoBrowser#868]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.6
   Device:  e.g. iPhone 7
   Device version:  e.g. iOS 15.0
   Xcode version:  e.g. Xcode 15.0

#### Configuration code of `ZLPhotoConfiguration`

![2111698392965_ pic](https://github.com/longitachi/ZLPhotoBrowser/assets/12868392/303cb3dc-8a80-4d15-ad92-bf77d4522eb3)

**Comment by longitachi** [comment]
这两天看下，下个版本尝试修复下

**Comment by longitachi** [comment]
试了下demo不存在描述的问题，可能是你项目中全局设置了导航的颜色导致的
