### ISSUE TITLE
如何隐藏相机按钮？

### ISSUE THREAD

**Issue by little-dandan** [longitachi/ZLPhotoBrowser#870]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.6
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/31ce8be9be49d2af49bb4c1a098c2c6f547daf9b/Sources/General/ZLPhotoConfiguration.swift#L110-L112

配置都在这个类，UI配置在`ZLPhotoUIConfiguration`，可以自己查找下进行配置
