### ISSUE TITLE
关于UI的问题，是否支持隐藏列表最后的相机拍摄按钮和添加图片按钮？

### ISSUE THREAD

**Issue by little-dandan** [longitachi/ZLPhotoBrowser#872]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.6
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
#870 
添加图片按钮 `showAddPhotoButton = false`

**Comment by longitachi** [comment]
更多配置请查看`ZLPhotoConfiguration`和`ZLPhotoUIConfiguration`

**Comment by little-dandan** [comment]
谢谢你的回复，但是我没有找到如何隐藏关闭拍照按钮的！

**Comment by longitachi** [comment]
#870 里不是回复了吗？`allowTakePhotoInLibrary `
