### ISSUE TITLE
可以加个选择原图后，在原图下放显示选择图片的大小吗？

### ISSUE THREAD

**Issue by Ryan0520** [longitachi/ZLPhotoBrowser#873]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.6
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by Ryan0520** [comment]
有个需求是如果在选择原图的模式下，需要限制最大只能选择20MB以内的图片。我看了下只有限制视频的大小，没有限制图片的大小。

**Comment by longitachi** [comment]
显示原图大小这个后面有空了加下

**Comment by Ryan0520** [comment]
> https://github.com/longitachi/ZLPhotoBrowser/blob/fe59a4462d19498c47705ba2506ff724fbd57531/Sources/General/ZLPhotoConfiguration.swift#L212-L215
> 
> 
> 可以用这个去限制选择，不过框架外现在拿不到用户是否勾选了原图按钮的状态

我现在的做法是在这个block去做，但是在外界没法拿到用户是否勾选了原图按钮的状态就很难搞了。

**Comment by longitachi** [comment]
你这个需求也有点麻烦，勾选原图按钮时，限制20M以内。就算能拿到原图按钮状态，用户也可以先在未勾选原图按钮时选择一个大于20M的照片，然后再勾选原图按钮

**Comment by Ryan0520** [comment]
所以这个需求就是点击原图那一刻也要判断图片大小是否符合在一点范围

**Comment by longitachi** [comment]
定制化需求可以自己fork一下修改。或者可以用户选了原图，你拿到回调后判断大小压缩一下

**Comment by Ryan0520** [comment]
> 定制化需求可以自己fork一下修改。或者可以用户选了原图，你拿到回调后判断大小压缩一下

嗯，估计我得把fork加一些定制化的需求调整才行。每隔一段时间合并一些新特性

**Comment by Ryan0520** [comment]
在滑动选择图片的那个手势处理有点问题，如果当手势移动到屏幕外的话，有些状态没有重置，导致再次移动选择时会出现异常情况，我加了一下判断就没问题了，作者你看下。
![3141700102524_ pic](https://github.com/longitachi/ZLPhotoBrowser/assets/11271005/8fb9b4a4-1dba-4b7f-b1d0-63f361ad9cc9)

**Comment by longitachi** [comment]
好的，我这边复现了下，我改下这块逻辑
