### ISSUE TITLE
Demo本地视频无法播放?

### ISSUE THREAD

**Issue by milkatgit** [longitachi/ZLPhotoBrowser#875]
Demo里面的Create WeChat moment Demo 选择本地视频后,再次点击预览,不会播放,播放按钮灰色.

![image](https://github.com/longitachi/ZLPhotoBrowser/assets/25073103/63300127-50d0-40d5-8002-8f98db7536ef)

![image](https://github.com/longitachi/ZLPhotoBrowser/assets/25073103/810876cf-407f-49be-bd31-14129e5cfd94)

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.7
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by milkatgit** [comment]
![image](https://github.com/longitachi/ZLPhotoBrowser/assets/25073103/e52086a2-d57c-4022-a7d6-b9bce0ab4f69)

**Comment by longitachi** [comment]
感谢反馈，我加下，后续发个小版本
