### ISSUE TITLE
请问为什么不支持全选功能？

### ISSUE THREAD

**Issue by KeynoWu** [longitachi/ZLPhotoBrowser#876]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.7
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   如题，看到几个使用率较高的照片选择框架都没有支持全选功能，请问是有什么限制吗
   ```

**Comment by longitachi** [comment]
因为一般都没有全选照片的需求。而且也不适合做，现在大部分人手机里基本都是几千张照片，全选转图片内存直接炸了
