### ISSUE TITLE
iOS17 UIGraphicsBeginImageContextWithOptions Deprecated

### ISSUE THREAD

**Issue by DrunkardSworder** [longitachi/ZLPhotoBrowser#877]
![image](https://github.com/longitachi/ZLPhotoBrowser/assets/36027902/116bebc2-4868-4405-99e1-abe650d4221c)

UIGraphicsBeginImageContextWithOptions这个方法在iOS17中已经deprecated了，但是项目中有多处使用了这个方法，我在其他三方库中发现不少作者已经移除了这个方法。

![image](https://github.com/longitachi/ZLPhotoBrowser/assets/36027902/7753674f-4112-405a-8536-4c78b10b49bb)

不知道作者是否注意到这个问题。

**Comment by longitachi** [comment]
已替换，今天晚些会更新下版本
