### ISSUE TITLE
发现问题

### ISSUE THREAD

**Issue by sprother** [longitachi/ZLPhotoBrowser#88]
不知道是故意设计这样的还是~~~~
就是允许内部拍摄 进去有相机按钮 但点击返回相簿列表后随便点一行进入相册 就没有相机拍摄了

-.-另外建议适配下屏幕 ipad浏览相册每行显示4张实在太大虽然你没有适配iPad 但是暂时没有发现在iPad有啥不妥 建议顺便适配哈哈

然后一段摘自MWPhotoBrowser的collectionView自定义横数间隔数量代码
感觉很好用 可以参考下 我觉得很好用=.=
[collectionView.pdf](https://github.com/longitachi/ZLPhotoBrowser/files/1265664/collectionView.pdf)

**Comment by longitachi** [comment]
相机拍照只会在所有照片下显示， 另外感谢提的建议，已在2.3.1版本下优化了iPad的显示
