### ISSUE TITLE
手机型号iPhone14plus ，操作系统 iOS16.6, 编辑图片的过程中出现卡死现象，必现。 复现步骤：选择一张图片,点击编辑，选择底部第二种方式，点击x 或 对号，就会出现卡死，版本号4.4.8.2

### ISSUE THREAD

**Issue by PengYang1991** [longitachi/ZLPhotoBrowser#881]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.8.2
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
没有找到16.6的机器，模拟器只能下载16.4的系统，暂未发现crash。你可以自己用demo调试下尝试解决，可以提个pr
