### ISSUE TITLE
icloud的视频还未下载完成就可以点击确定

### ISSUE THREAD

**Issue by programmework** [longitachi/ZLPhotoBrowser#882]
#### Description and Steps

如题，能否提供限制一下呢？

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.8.2
   Device:  e.g. iPhone 12 Pro Max
   Device version:  e.g. iOS 17.1.1
   Xcode version:  e.g. Xcode 15.0.1

**Comment by longitachi** [comment]
你是想要 视频未下载完成可以点击确定呢   还是视频未下载完成不让点击确定呢？

**Comment by programmework** [comment]
> 你是想要 视频未下载完成可以点击确定呢 还是视频未下载完成不让点击确定呢？

现在好像是未下载完成就可以点击确定回调selectImageBlock了(感觉这样的话在回调里处理未下载完的icloud视频可能会有不可预知的错误)，所以我希望是没有下载完成就不能点击确定，提供这样一种限制的选项

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/bb6c054ef3cd60d32013096c8900449ad94be39a/Sources/General/ZLPhotoConfiguration.swift#L97-L99
