### ISSUE TITLE
能否开放选中起始下标

### ISSUE THREAD

**Issue by programmework** [longitachi/ZLPhotoBrowser#883]
#### Description and Steps

ZLPhotoConfiguration中的SelectedIndex 默认从1开始，期待的效果：像小红书中发布一篇笔记之后重新编辑，可以再添加相册图片，如果之前发布的笔记已经有两张图片了，此时再添加图片，希望下标可以是从3开始。

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.8.2
   Device:  e.g. iPhone 12 Pro Max
   Device version:  e.g. iOS 17.1.1
   Xcode version:  e.g. Xcode 15.0.1

**Comment by longitachi** [comment]
现在是不支持的，不过可以携带之前选择过的照片。 后面有空了看下

**Comment by longitachi** [comment]
88956343a642296c52de896d02054758e2442a99 已支持
