### ISSUE TITLE
只选择视频时，超出数量提示最多选择x张图片，而不是最多选择x个视频

### ISSUE THREAD

**Issue by qinqi777** [longitachi/ZLPhotoBrowser#884]
allowSelectImage = NO
allowSelectVideo = YES
maxSelectCount = 3

设置为上面的值。打开也确实只能选择视频没毛病。
就是选择了3个视频，再点第4个时，提示：最多只能选择3张图片
应该提示：最多只能选择3个视频

**Comment by qinqi777** [comment]
还有个问题，拍摄视频时，需要一直按着那个按钮不松手，如果maxDuration设置比较大时，这个不太友好。建议提供个枚举，可以使用长按的方式拍摄，也可以按一下开始拍摄再按一下结束拍摄。或者大佬能用一个按钮实现这两个功能也可以~

**Comment by longitachi** [comment]
可以自定义下文案 https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(Swift)#customize-language

**Comment by longitachi** [comment]
> 还有个问题，拍摄视频时，需要一直按着那个按钮不松手，如果maxDuration设置比较大时，这个不太友好。建议提供个枚举，可以使用长按的方式拍摄，也可以按一下开始拍摄再按一下结束拍摄。或者大佬能用一个按钮实现这两个功能也可以~

后面有空了看下
