### ISSUE TITLE
增加自定义配置

### ISSUE THREAD

**Issue by 0xtronzheng** [longitachi/ZLPhotoBrowser#887]
### Issue Description
能否在配置里面增加 自定义按钮文本的配置

#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.4.8.2
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by 0xtronzheng** [comment]
选择完photo 之后，需要可以自定义done 按钮的 文字

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(Swift)#customize-language

https://github.com/longitachi/ZLPhotoBrowser/blob/88956343a642296c52de896d02054758e2442a99/Sources/General/ZLLanguageDefine.swift#L161-L162

可以先修改`done`的文案，不过 `done` 这个相机拍照、文字贴纸输入界面也在用，后续会把这些key分开
