### ISSUE TITLE
功能拓展

### ISSUE THREAD

**Issue by yinsenlee** [longitachi/ZLPhotoBrowser#888]
作者你好：
当前这个拍照及相册开源库给我们带来了很多方便，下面有两个改动不知道有没有时间支持下：
1.相册里面原图按钮的图片颜色支持自定义
2.有没有办法在拍照完后直接进入预览页面，即现有的ZLPhotoPreviewController页面

感谢！

**Comment by longitachi** [comment]
第一个可以使用自定义图片 https://github.com/longitachi/ZLPhotoBrowser/wiki/How-to-use-(Swift)#Customize-image-resource
第二个感觉场景不通用，可以fork下
