### ISSUE TITLE
pod 导入点击报错

### ISSUE THREAD

**Issue by wulingf** [longitachi/ZLPhotoBrowser#89]
- (void) onClicked{
    ZLPhotoActionSheet *actionSheet = [self getPas];
    [actionSheet showPhotoLibrary];
}

- (ZLPhotoActionSheet *)getPas
{
    ZLPhotoActionSheet *actionSheet = [[ZLPhotoActionSheet alloc] init];
    
#pragma optional
    //以下参数为自定义参数，均可不设置，有默认值
//    actionSheet.sortAscending = self.sortSegment.selectedSegmentIndex==0;
//    actionSheet.allowSelectImage = self.selImageSwitch.isOn;
//    actionSheet.allowSelectGif = self.selGifSwitch.isOn;
//    actionSheet.allowSelectVideo = self.selVideoSwitch.isOn;
//    actionSheet.allowSelectLivePhoto = self.selLivePhotoSwitch.isOn;
//    actionSheet.allowForceTouch = self.allowForceTouchSwitch.isOn;
//    actionSheet.allowEditImage = self.allowEditSwitch.isOn;
//    actionSheet.allowMixSelect = self.mixSelectSwitch.isOn;
    //设置相册内部显示拍照按钮
    actionSheet.allowTakePhotoInLibrary = YES;
    //设置在内部拍照按钮上实时显示相机俘获画面
    actionSheet.showCaptureImageOnTakePhotoBtn = NO;
    //设置照片最大预览数
    actionSheet.maxPreviewCount = 9;
    //设置照片最大选择数
    actionSheet.maxSelectCount = 9;
    //设置允许选择的视频最大时长
//    actionSheet.maxVideoDuration = self.maxVideoDurationTextField.text.integerValue;
    //设置照片cell弧度
//    actionSheet.cellCornerRadio = self.cornerRadioTextField.text.floatValue;
    //单选模式是否显示选择按钮
    actionSheet.showSelectBtn = NO;
    //是否在选择图片后直接进入编辑界面
    actionSheet.editAfterSelectThumbnailImage = YES;
    //设置编辑比例
    //    actionSheet.clipRatios = @[GetClipRatio(4, 3)];
    //是否在已选择照片上显示遮罩层
//    actionSheet.showSelectedMask = self.maskSwitch.isOn;
    //遮罩层颜色
    //    actionSheet.selectedMaskColor = [UIColor orangeColor];
#pragma required
    //如果调用的方法没有传sender，则该属性必须提前赋值
    actionSheet.sender = self;
    
//    actionSheet.arrSelectedAssets = self.rememberLastSelSwitch.isOn&&self.maxSelCountTextField.text.integerValue>1 ? self.lastSelectAssets : nil;
    
    [actionSheet setSelectImageBlock:^(NSArray<UIImage *> * _Nonnull images, NSArray<PHAsset *> * _Nonnull assets, BOOL isOriginal) {
        NSLog(@"image:%@", images);
    }];
    
    return actionSheet;
}

**Comment by longitachi** [comment]
有报错信息吗
