### ISSUE TITLE
Preview/Edit UIImage

### ISSUE THREAD

**Issue by patryk-sredzinski** [longitachi/ZLPhotoBrowser#890]
Hey

Is there any way that I use UIImage and display photo editor with this image, resulting with edited UIImage?

I think I can show the photo editor by passing PHAssets, but I'd rather not add UIImage to iPhone Photos

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/e1e20297d9c1f2a9e67e4dfa97bd2eca7096b241/Sources/Edit/ZLEditImageViewController.swift#L406-L413

Do you want to call the image editor directly? If yes, you can use this method.

**Comment by patryk-sredzinski** [comment]
Awesome, are you aware if I can do the same with GIFs, so I can preview them?
