### ISSUE TITLE
Swift Package 显示 contains mixed language source files; feature not supported 错误

### ISSUE THREAD

**Issue by huihuisang** [longitachi/ZLPhotoBrowser#892]
#### Description and Steps
target at '/SourcePackages/checkouts/ZLPhotoBrowser/Sources' contains mixed language source files; feature not supported

#### Info
   ZLPhotoBrowser version:  4.4.9
   Xcode version:   Xcode 15.2.0

**Comment by Miles-Matheson** [comment]
+1

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/master/Sources/General/ZLWeakProxy.h
https://github.com/longitachi/ZLPhotoBrowser/blob/master/Sources/General/ZLWeakProxy.m
后来加了这两个文件，SPM貌似不支持了，建议先用pod吧

**Comment by wozyao** [comment]
Rule可以选择branch，然后填master，可暂时解决SPM fetch 失败的问题

**Comment by longitachi** [comment]
更新4.5.0版本即可
