### ISSUE TITLE
希望支持修改 btnSelect 颜色 / 样式

### ISSUE THREAD

**Issue by Arabaku** [longitachi/ZLPhotoBrowser#896]
4.4.6 版本开始支持设置选择按钮上是否显示序列号，同时 btnSelect 给了默认的选中样式。希望可以在 ZLPhotoUIConfiguration 中给出对其进行修改的方法。
<img width="761" alt="image" src="https://github.com/longitachi/ZLPhotoBrowser/assets/27410613/d0338a8e-ff18-4ea8-b0ec-7d9711fa3a03">

**Comment by longitachi** [comment]
修改序号字体颜色及背景色
https://github.com/longitachi/ZLPhotoBrowser/blob/500d3fcf9e5ff2e90e5b00fc97be131c0d832c9a/Sources/General/ZLPhotoUIConfiguration.swift#L424-L438

修改选择按钮图片参照这个
https://github.com/longitachi/ZLPhotoBrowser/blob/500d3fcf9e5ff2e90e5b00fc97be131c0d832c9a/Sources/General/ZLPhotoUIConfiguration.swift#L158-L174

**Comment by Arabaku** [comment]
非常感谢！
