### ISSUE TITLE
快速点击switchButton切换摄像头依然crash,必现;

### ISSUE THREAD

**Issue by mtc1146** [longitachi/ZLPhotoBrowser#897]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.5.0
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by mtc1146** [comment]
尝试将设置AVCaptureDeviceInput的时机由并发改为串行可以解决,供参考

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/issues/894

master已修复，这两天会发一个小版本
