### ISSUE TITLE
预览页面不支持navCancelButtonStyle

### ISSUE THREAD

**Issue by Doanyi** [longitachi/ZLPhotoBrowser#898]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.5.1
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
这个就是给相册小图界面用的属性，预览界面不支持。
