### ISSUE TITLE
运行demo的时候@available(iOS 9.0, *)报错

### ISSUE THREAD

**Issue by CHENDONGY** [longitachi/ZLPhotoBrowser#90]

**Comment by longitachi** [comment]
这个实在Xcode9.0以下版本报的错，不识别该条件判断，可以把他修改为 [UIDevice currentDevice].systemVersion.floatValue >= 9.0

**Comment by longitachi** [comment]
这个是在Xcode9.0以下版本报的错，不识别该条件判断，可以把他修改为 [UIDevice currentDevice].systemVersion.floatValue >= 9.0

**Comment by liupengios** [comment]
希望能尽快更新

**Comment by longitachi** [comment]
@liupengios 嗯好，暂时可以手动修改为  [UIDevice currentDevice].systemVersion.floatValue >= 9.0 ，后续版本会更新的

**Comment by GuangTingVR** [comment]
能不能把 编辑完后 就默认是编辑完后的照片   跟微信一样   这只能编辑一张图片.....  试着改了改不好.   还有编辑里的另外两个功能没有打开,打开后只有UI,没有实际操作!

**Comment by longitachi** [comment]
“编辑里的另外两个功能没有打开,打开后只有UI,没有实际操作!”这个是什么意思？  编辑完后这个功能可以考虑下，但是最近比较忙没时间整
