### ISSUE TITLE
授权选择部分照片的界面可配置导航主题吗？

### ISSUE THREAD

**Issue by springlo** [longitachi/ZLPhotoBrowser#904]
### Issue Description
 这导航栏的按钮都看不了了

#### Info
   ZLPhotoBrowser version:   4.3.5
   Device:  iPhone 14 Pro
   Device version:  e.g. iOS 16.1
   Xcode version:  e.g. Xcode 15.1

#### Configuration code of `ZLPhotoConfiguration`

![IMG_3676](https://github.com/longitachi/ZLPhotoBrowser/assets/373580/350e6b84-1b12-4b4f-967c-2b8d8bf8c107)

**Comment by longitachi** [comment]
这个是系统的界面，没法定制
