### ISSUE TITLE
ZLCustomCamera里isVideoMirrored = true，希望可以配置，不要写死true

### ISSUE THREAD

**Issue by Louis-Zeng** [longitachi/ZLPhotoBrowser#912]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.5.3
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/commit/902c35d6cbccea1a5e2c04e85e055200adef0653
