### ISSUE TITLE
反馈在非刘海屏手机UI适配问题

### ISSUE THREAD

**Issue by buliannashouge** [longitachi/ZLPhotoBrowser#914]
#### 
问题1：在非刘海屏手机使用ZLPhotoPreviewSheet，打开相册后勾选任意素材后 点击左下角「预览」按钮，进入预览页面后 点击左上角「返回」按钮 返回到选择图片页面时，导航栏内容向上偏移了状态栏的高度，导致与状态栏文字叠加。
问题2：在非刘海屏手机选择照片页面，选择任意图片后勾选「原图」，显示的原图片大小文字（共 300KB） 超出底部屏幕范围，内容一小部分被切掉。

#### Info
   ZLPhotoBrowser version:  e.g. 4.5.3
   Device:  e.g. iPhone 8 Plus
   Device version:  e.g. iOS 16.7.5
   Xcode version:  e.g. Xcode 15.2

**Comment by longitachi** [comment]
有空了看下，有问题的话跟下个版本解决
