### ISSUE TITLE
double-quoted include "ZLWeakProxy.h" in framework header, expected angle-bracketed instead

### ISSUE THREAD

**Issue by DaiYiWen** [longitachi/ZLPhotoBrowser#917]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.5.4
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
用的什么集成方式？

**Comment by DaiYiWen** [comment]
pod。删除重新安装又好了

**Comment by ljbshishabi** [comment]
我删除重新安装后还不行。。
我是之前用的SPM集成，随后发现不太给力，换回pod，现在出现这个问题了。
ps.之前SPM集成是能用的，换回pod之后才报错

**Comment by longitachi** [comment]
@ljbshishabi 集成的哪个版本？

**Comment by ljbshishabi** [comment]
4.5.6

**Comment by longitachi** [comment]
我这边试了下没报错，如果报错的话，把`ZLWeakProxy.swift`删了

**Comment by ljbshishabi** [comment]
我现在换回SPM了。。SPM+梯子还是好使点。。
