### ISSUE TITLE
请问关于图片和视频拍摄中加入捏合手势改变对焦远近的功能，要怎么调用

### ISSUE THREAD

**Issue by hezuoying** [longitachi/ZLPhotoBrowser#919]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.5.4
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
直接捏合就行，默认就支持
