### ISSUE TITLE
最大选择数设置为1时，图片右上角无选择按钮

### ISSUE THREAD

**Issue by hanson1024** [longitachi/ZLPhotoBrowser#92]
actionSheet.maxSelectCount = 1

**Comment by longitachi** [comment]
[https://github.com/longitachi/ZLPhotoBrowser/issues/82](url)

**Comment by longitachi** [comment]
[#82](https://github.com/longitachi/ZLPhotoBrowser/issues/82)

**Comment by jinyuyoulong** [comment]
defatult.showSelectBtnWhenSingleSelect = true
