### ISSUE TITLE
请问拍照时想使用广角模式，要怎么设置

### ISSUE THREAD

**Issue by hezuoying** [longitachi/ZLPhotoBrowser#920]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.5.4
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

#### Configuration code of `ZLPhotoConfiguration`

   ```
   Paste your code here.
   ```

**Comment by longitachi** [comment]
不支持广角模式，只支持手势捏合调整焦距
