### ISSUE TITLE
请问如何把相机放在第一位呢 

### ISSUE THREAD

**Issue by YuXunSTC** [longitachi/ZLPhotoBrowser#923]
如果相册中图片太多 是不是相机按钮就需要滑到底才能点击呢 

<img width="484" alt="ios" src="https://github.com/user-attachments/assets/d8ca2814-d21a-43af-a2cc-000a6de83bc5">

**Comment by longitachi** [comment]
相机在下面效果参考微信。 想要在上面就把`sortAscending`设置为`false`
