### ISSUE TITLE
图片保存到相册时，保存权限选择允许后，不应该再请求额外访问照片库权限

### ISSUE THREAD

**Issue by vinsent** [longitachi/ZLPhotoBrowser#924]
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Info
   ZLPhotoBrowser version:  e.g. 4.5.4
   Device:  e.g. iPhone 12 Pro
   Device version:  e.g. iOS 17.5.1
   Xcode version:  e.g. Xcode 15.4

#### Configuration code of `ZLPhotoConfiguration`

   ```
Default configuration

   ```

使用ZLImagePreviewController预览图片时，首次长按保存权限点击允许后，紧接着弹出了额外访问照片图库权限，但其实只需要保存权限就够了

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/2eaea61c854d07b23855711dd552c1d12b84b843/Sources/General/ZLPhotoManager.swift#L32-L34
保存图片后需要返回`PHAsset`对象，所以需要读取权限，如果不需要，你可以自己实现`ZLImagePreviewController`中的`longPressBlock`，自己写弹窗及保存逻辑

**Comment by vinsent** [comment]
好的，多谢
