### ISSUE TITLE
在相册里拍照后，没有直接返回该照片

### ISSUE THREAD

**Issue by OCer** [longitachi/ZLPhotoBrowser#929]
### Issue Description
主要有2个问题
1、设置了maxSelectCount = 1，allowEditImage = false，使用showPhotoLibrary方式打开相册，然后在相册内拍照，没有直接返回这张照片，还是需要自己选中然后点击确定，很明显这个是不合理的
2、设置了maxPreviewCount = 0，allowEditImage = false，allowSelectOriginal = true，alwaysRequestOriginal = true，也就是说，我不需要预览和编辑照片，我想要的是用户点击照片后就返回原图，但是目前还是返回缩略图
#### Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.
直接使用项目里最新的demo即可复现

#### Info
   ZLPhotoBrowser version:  e.g. 4.5.4
   Device:  iPhone 14
   Device version:  iOS 16.6.1
   Xcode version: Xcode 15.4

#### Configuration code of `ZLPhotoConfiguration`

   ```
       let actionSheet = ZLPhotoPreviewSheet(selectedAssets: [])
        let configuration = ZLPhotoConfiguration.default()
        configuration.allowSelectImage = true
        configuration.allowSelectVideo = false
        configuration.allowSelectGif = false
        configuration.cellCornerRadio = 2
        configuration.allowSlideSelect = false
        configuration.themeColorDeploy.bottomToolViewBtnNormalTitleColor = .white
        configuration.themeColorDeploy.navTitleColor = UIColor.white
        configuration.maxSelectCount = 1
        configuration.maxPreviewCount = 0
        configuration.allowSelectOriginal = true
        configuration.allowEditImage = false
        configuration.alwaysRequestOriginal = true

      // 相册方式打开
       self.getPas().showPhotoLibrary(sender: self)
   ```

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/blob/e11265ced854606a9a45c3c47c06c2a8a4f10d78/Sources/General/ZLPhotoConfiguration.swift#L132-L133
这个参数设置成`true`就行了

**Comment by OCer** [comment]
你好 我在你的demo里试过了 并不行哦 @longitachi

**Comment by longitachi** [comment]
第一个问题已修复。
至于第二个问题你如果设置`allowSelectOriginal = true`那么需要你自己勾选原图，`alwaysRequestOriginal`这个属性定义如下，只有`allowSelectOriginal = false`时候才生效
https://github.com/longitachi/ZLPhotoBrowser/blob/b65db1b49aa1e26608bf755a9e94b80b9317248d/Sources/General/ZLPhotoConfiguration.swift#L183-L185

**Comment by OCer** [comment]
你好  下载你的demo 确实可以了 什么时候可以打包到pod呢？
然后我看了下 我们项目用的4.2.5  直接升级到最新版本 会不会有问题呢？？  而且之前的人还在pod里替换了源码 不知道是干嘛用的
`  # 替换 ZLPhotoBrowser 中的源码，修复一些问题 Pods/ZLPhotoBrowser/Sources/General/ZLPhotoPreviewCell.swift
  pod_target = installer.pod_targets.find { |target| target.pod_name == 'ZLPhotoBrowser' }
  # 判断版本号，如果不是4.2.5就抛出错误
  puts "================= 更改 ZLPhotoBrowser 源码 version: #{pod_target.version}"
  if pod_target.version.to_s != '4.2.5'
    raise "ZLPhotoBrowser version is not 4.2.5"
  end

  # 读取文件内容
  pod_root = pod_target.sandbox.root
  file_to_modify = 'ZLPhotoBrowser/Sources/General/ZLPhotoPreviewCell.swift'
  file_path = File.join(pod_root, file_to_modify)
  file_content = File.read(file_path)

  # 替换文件中的一部分源码
  modified_content = file_content.gsub('seek(to: CMTimeMake(value: 0, timescale: 1))', 'seek(to: CMTimeMake(value: 0, timescale: 1), toleranceBefore: .zero, toleranceAfter: .zero)')
  modified_content = modified_content.gsub('seek(to: .zero)', 'seek(to: .zero, toleranceBefore: .zero, toleranceAfter: .zero)')

  add_code = "self.player = AVPlayer(playerItem: item)\n        self.player?.seek(to: .zero, toleranceBefore: .zero, toleranceAfter: .zero)"
  if modified_content.include?(add_code) == false
    modified_content = modified_content.gsub('self.player = AVPlayer(playerItem: item)', add_code)
  end

  # 将修改后的内容写入文件
  File.chmod(0755, file_path)
  File.open(file_path, 'w') { |file| file.puts modified_content }

  # 打印信息
  puts "================= Replacement in #{file_to_modify} completed: #{file_content != modified_content}"`

**Comment by longitachi** [comment]
等看下最近issue有没有新的问题，没的话这周抽空发一个

**Comment by OCer** [comment]
问一下 我们pod替换文件是替换了ZLPhotoPreviewCell的问题  请问那些问题现在修复了没呢

**Comment by longitachi** [comment]
具体是什么问题，能描述下吗？暂时没有接到过其他反馈，而且我也没遇到过相关的case？

**Comment by OCer** [comment]
大佬有空发版吗  等你这个了

**Comment by longitachi** [comment]
今天有空发一个

**Comment by OCer** [comment]
感谢大佬
