### ISSUE TITLE
ZLPhotoActionSheet 初始化失败

### ISSUE THREAD

**Issue by jun-hui** [longitachi/ZLPhotoBrowser#93]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle <...> (loaded)' with name 'ZLPhotoActionSheet''
请问这是怎么回事啊，我是用pods引入的，info.plist也配置了的，但就是初始化失败

**Comment by longitachi** [comment]
是最新版本吗？pod setup  在 pod update 试试

**Comment by jun-hui** [comment]
是的，是最新版2.4的

**Comment by longitachi** [comment]
还有这个问题？我之前集成也遇到过类似的，不知道跟你的一样不，我是清除下项目，完全退出xcode，再进来就没了，可能xcode犯抽了

**Comment by jun-hui** [comment]
我退出过，还是不行，模拟器，真机都不行，都是报这个错

**Comment by longitachi** [comment]
- -你在Podfile里把框架删了，然后在继承呢？😑

**Comment by jun-hui** [comment]
我发现问题了，pod update之前是2.3的，但是是有sheet.xib文件的，update之后却没有了，我现在重新update一次看看，不好意思

**Comment by jun-hui** [comment]
又重新update了一次，sheet.xib文件是有的，但还是不行，还是初始化失败

**Comment by longitachi** [comment]
你把框架从项目里删掉，然后在重新集成呢？你把完整的错误信息发出来

**Comment by jun-hui** [comment]
删掉过，一样的：
![25038092-8a76-4931-95a7-59cdf9534bb0](https://user-images.githubusercontent.com/23160552/30159925-e49b9340-93fc-11e7-88e2-c40b2f3f023b.png)

**Comment by longitachi** [comment]
你看下ZLPhotoActionSheet.xib有没有与该类文件关联
![b2eec56c-6f1d-435a-a399-ee91ef35bb84](https://user-images.githubusercontent.com/11711768/30191141-7c0e43de-9471-11e7-87ac-c642902f8a00.png)

**Comment by jun-hui** [comment]
有的，有关联上的

**Comment by longitachi** [comment]
你加下我QQ495181165

**Comment by longitachi** [comment]
你在项目 Build Phases -> Copy Pods Resources 下面找找xib和bundle文件是否存在
![b75d58ce-6064-4a3c-bd0e-821c79c28951](https://user-images.githubusercontent.com/11711768/30464955-276a5732-9a07-11e7-80fd-1af6377c12a7.png)

**Comment by FunnyFzl** [comment]
我也遇到这个问题

**Comment by DreamHuman** [comment]
解决方案是什么？

**Comment by longitachi** [comment]
现在还有这个问题吗？
