### ISSUE TITLE
怎么知道是点了编辑页的取消和确定，当以pod库的形式导入项目中

### ISSUE THREAD

**Issue by dgyiOS** [longitachi/ZLPhotoBrowser#930]
#### Description and Steps
1、裁剪页ZLClipImageViewController的"取消"和"确定"回调在ZLEditImageViewController有实现，但是并没有继续往上层传，
这样，就算我拿到了编辑页ZLEditImageViewController这个类，也没法拿到ZLClipImageViewController的取消和确定事件，
因为ZLEditImageViewController只是实现了ZLClipImageViewController这2个事件的block而已，
2、能否针对编辑页的这个"取消"和"确定"，做一个透传出去
3、尝试着hook这个裁剪页 ZLClipImageViewController 的 doneBtnClick 和 cancelBtnClick，貌似有问题，不知道是不是swift的hook的原因

#### Info
   ZLPhotoBrowser version:  e.g. 4.5.4
   Device:  e.g. iPhone 14 Pro
   Device version:  e.g. iOS 16.0
   Xcode version:  e.g. Xcode 14.0

**Comment by longitachi** [comment]
如果需要透传，可以自己fork下定制改下。
如果仅需要知道有没有进行过裁剪操作，可以通过`completion` 回调里的`ZLEditImageModel`里面的`clipStatus`的值来判断
https://github.com/longitachi/ZLPhotoBrowser/blob/b65db1b49aa1e26608bf755a9e94b80b9317248d/Sources/Edit/ZLEditImageViewController.swift#L429-L436

**Comment by dgyiOS** [comment]
好的，已经fork解决我的问题
