### ISSUE TITLE
ZLImagePreviewController 图片预览不支持手势关闭当前控制器吗？

### ISSUE THREAD

**Issue by MuRanJiangXia** [longitachi/ZLPhotoBrowser#932]
ZLImagePreviewController 图片预览不支持手势关闭当前控制器吗？

ZLPhotoPreviewController 这个支持 但是模块外不能使用

**Comment by longitachi** [comment]
升级最新版本即可

**Comment by MuRanJiangXia** [comment]
能兼容一下 push么 ，现在是 present 方式弹出可以~

**Comment by MuRanJiangXia** [comment]
/// 开始手势
    func beginInterative(_ pan: UIPanGestureRecognizer) {
        guard !interactive else { return }
        
        let vel = pan.velocity(in: viewController?.view)
        if abs(vel.x) >= abs(vel.y) || vel.y <= 0 {
            return
        }
        
        startPanPoint = pan.location(in: viewController?.view)
        interactive = true
        startTransition?()
        viewController?.dismiss(animated: true)
    }
