### ISSUE TITLE
ios 18 问题

### ISSUE THREAD

**Issue by riluoxiyanghuanghun** [longitachi/ZLPhotoBrowser#936]
iOS18 上初始化 
Unsupported fetch for asset collections with type 2 and subtype 2

**Comment by longitachi** [comment]
补充下版本号吧，可能不是最新版本。这个应该解决过了，或者更新下最新版本、使用demo试下

**Comment by riluoxiyanghuanghun** [comment]
更新之后这个问题是解决了，但是点击顶部最近项目，列表出来的类型少了很多

**Comment by longitachi** [comment]
能截图看下吗，我手机上对比了下，没有少项目

**Comment by riluoxiyanghuanghun** [comment]
点击最近项目，出来的列表，如果在iOS18以下列表会不少，如果在iOS18上，列表少很多

**Comment by longitachi** [comment]
我手里现在没iOS18的设备，最近有空了升级一个看看
