### ISSUE TITLE
运行报 pod错误  有时间麻烦解决下bug

### ISSUE THREAD

**Issue by JHCoderLion** [longitachi/ZLPhotoBrowser#94]

**Comment by longitachi** [comment]
报什么错误，有错误信息没？发一下

**Comment by JHCoderLion** [comment]
diff: /Users/dchip-mac001/Downloads/ZLPhotoBrowser-master/./Podfile.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by JHCoderLion** [comment]
麻烦弄好了更新下代码 谢谢

**Comment by longitachi** [comment]
你下载了demo，cd demo目录，执行 pod install就好了，确保你终端安装了cocoapods

**Comment by JHCoderLion** [comment]
OK
