### ISSUE TITLE
最新版Xcode打包后，选择相册无效

### ISSUE THREAD

**Issue by developerjet** [longitachi/ZLPhotoBrowser#941]
最新版Xcode打包后，发布AppStore。系统版本iOS 18.0.1选择相册无效，iOS 17选择相册能够正常弹出，请问有遇到过这个问题么。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by longitachi** [comment]
是最新版本吗？试下用Demo直接跑试下卡能不能调起

**Comment by Arlexovincy** [comment]
我也遇到这个问题了

**Comment by longitachi** [comment]
> 我也遇到这个问题了

如果不打包，直接Xcode跑你们项目，能打开相册吗？

**Comment by Arlexovincy** [comment]
试试用最新的版本，我试了下，最新的版本用xcode16，在iOS18下也能运行，能打开

**Comment by longitachi** [comment]
@Arlexovincy 也就是你遇到的问题是用的老版本的`ZLPhotoBrowser`，升级最新版本就可以了对吧？

**Comment by Jyhwenchai** [comment]
更新到最新版本的`ZLPhotoBrowser`就可以了

**Comment by developerjet** [comment]
> 更新到最新版本的`ZLPhotoBrowser`就可以了

好的
