### ISSUE TITLE
customAlertWhenNoAuthority not work as expected

### ISSUE THREAD

**Issue by RubyRook** [longitachi/ZLPhotoBrowser#942]
I prefer `customAlertWhenNoAuthority` trigger immediately when camera permission is denied, but default message appeared first and then `customAlertWhenNoAuthority` show my custom message later.

#### Description and Steps

https://github.com/user-attachments/assets/08d50386-573a-4851-9dda-8f470442d99e

#### Info
   ZLPhotoBrowser version:  e.g. 4.5.5
   Device:  e.g. iPhone 13 Pro
   Device version:  e.g. iOS 18.0.1
   Xcode version:  e.g. Xcode 15.4

#### Configuration code of `ZLPhotoConfiguration`

   ```
   let config = ZLPhotoConfiguration.default()

  config.customAlertWhenNoAuthority { type in
      if (type == .camera) {
          var message = "Go to “Settings” and enable camera access."
  
          if var appName = Bundle.main.object(forInfoDictionaryKey: "CFBundleDisplayName") {
              if #available(iOS 18.0, *) {
                  message = "Go to “Settings” → “Apps” → “\(appName)” and enable camera access."
              }
              else {
                  message = "Go to “Settings” → “\(appName)” and enable camera access."
              }
          }
  
          self.showAlertPermission(
              title: "Camera has been turned off",
              message: message
          )
      }
  }
   ```

**Comment by longitachi** [comment]
I modified the logic of the code. If `customAlertWhenNoAuthority` is implemented, it will be called back directly, but the custom camera will not be dismissed. Therefore, in the custom alert button click event, you need to get the top viewController on the window and dismiss the custom camera.
