### ISSUE TITLE
建议在选择照片(预览模式)下也可以实时查看和选择相机

### ISSUE THREAD

**Issue by ToForgive** [longitachi/ZLPhotoBrowser#95]
现在相册内部拍照可以显示实时的相机画面，但是在预览模式下不能，建议参考 iOS10+的短信里选择照片那样可以直接预览相机内容～😁

**Comment by longitachi** [comment]
嗯，多谢提的建议，会考虑增加这个功能的，不过感觉使用预览功能的有点少 - - ，一般都是直接进入相册了
