### ISSUE TITLE
Xcode16.1 使用弹不出相册选择视图

### ISSUE THREAD

**Issue by GuoMingJian** [longitachi/ZLPhotoBrowser#957]
#### Description and Steps
//
                let picker = ZLPhotoPreviewSheet()
                //
                picker.showPhotoLibrary(sender: currentVC)

#### Info
   ZLPhotoBrowser version:  e.g. 4.3.9
   Device:  e.g. iPhone 12 Pro Max
   Device version:  e.g. iOS 18.1.1
   Xcode version:  e.g. Xcode 16.1

#### Configuration code of `ZLPhotoConfiguration`

   ```
 let configuration = ZLPhotoConfiguration.default()
        // 最多选择x项
        configuration.maxSelectCount = 1
        // 是否允许选择照片
        configuration.allowSelectImage = true
        // 是否允许选择视频
        configuration.allowSelectVideo = false
        // 是否允许编辑图片
        configuration.allowEditImage = true
        // 是否允许编辑视频
        configuration.allowEditVideo = true
        // 是否允许勾选原图
        configuration.allowSelectOriginal = true
   ```

**Comment by longitachi** [comment]
更新下版本就行了

**Comment by GuoMingJian** [comment]
好的，问题解决了。感谢～

**Comment by esonwork** [comment]
> 更新下版本就行了

请问这个问题是在哪个版本解决的，我现在遇到的问题是：把你的库导入到了自己工程做了以下修改，没办法升级了

**Comment by longitachi** [comment]
> > 更新下版本就行了
> 
> 请问这个问题是在哪个版本解决的，我现在遇到的问题是：把你的库导入到了自己工程做了以下修改，没办法升级了

https://github.com/longitachi/ZLPhotoBrowser/releases/tag/4.5.6

**Comment by Yoo-000** [comment]
> > > 更新下版本就行了
> > 
> > 
> > 请问这个问题是在哪个版本解决的，我现在遇到的问题是：把你的库导入到了自己工程做了以下修改，没办法升级了
> 
> https://github.com/longitachi/ZLPhotoBrowser/releases/tag/4.5.6

你好，我项目内的版本特别的老，并且也做了大部分自己的内容，所以能否告知一下具体哪里做了修改

**Comment by longitachi** [comment]
@Yoo-000 https://github.com/longitachi/ZLPhotoBrowser/commit/646dbd62209a4de8d4320970e6dbdded98a2993e
参考这个，把`subType`改成 `any`
