### ISSUE TITLE
Xcode 9 Unable to load image data(已解决)

### ISSUE THREAD

**Issue by WithdrwnKing** [longitachi/ZLPhotoBrowser#96]
[ImageManager] Unable to load image data, /var/mobile/Media/DCIM/100APPLE/IMG_0405.JPG
新升级iOS11 后会提示这个错误，导致图片数组不正确。

**Comment by longitachi** [comment]
这个是什么时候会报这个错？我在xcode9 iOS11环江下没有见到过这个错。

**Comment by Lynnll** [comment]
您好，这个问题有复现吗？我也出现了。个别图片会报错。

**Comment by longitachi** [comment]
好的，我查一下

**Comment by Lynnll** [comment]
- (PHImageRequestID)requestImageForAsset:(PHAsset *)asset targetSize:(CGSize)targetSize contentMode:(PHImageContentMode)contentMode options:(nullable PHImageRequestOptions *)options resultHandler:(void (^)(UIImage *__nullable result, NSDictionary *__nullable info))resultHandler; 取图片的时候报的错。

**Comment by longitachi** [comment]
定位到该错误出现在相册列表界面，原因如下
在ZLPhotoBrowserCell.m的setModel:方法中做如下修改即可
![image](https://user-images.githubusercontent.com/11711768/30738149-abb6834e-9fbb-11e7-945c-2fd4dbde24b4.png)

**Comment by FizzChiang** [comment]
你好，请问造成这个崩溃的原因是什么

**Comment by xiaoliuTX** [comment]
讲请求image的代码放在@autoreleasepool{}中就好了

**Comment by longitachi** [comment]
@xiaoliuTX 好的，我等会试一下

**Comment by longitachi** [comment]
@xiaoliuTX 刚才试了下，不行，还是打印这个，应该就是属于iOS11 系统的一个bug
