### ISSUE TITLE
xcode 16.1 在iOS 18.1 打包后无法弹出相册

### ISSUE THREAD

**Issue by Yoo-000** [longitachi/ZLPhotoBrowser#962]
你好，我项目内的版本特别的老(4.3.7)，并且也做了大部分自己的内容，所以能否告知一下具体哪里做了修改

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/issues/957

**Comment by Yoo-000** [comment]
<img width="964" alt="配置" src="https://github.com/user-attachments/assets/9a47104f-f1af-49ae-8827-fddec4ff1bdf" />
项目内的配置是你所说的 .any，但是还是报错 “Unsupported fetch for asset collections with type 2 and subtype 2”

**Comment by Yoo-000** [comment]
> #957

我在 getCameraRollAlbum 方法内把  .albumRegular 修改为 .any 就可以了，感谢
