### ISSUE TITLE
pod 2.4.3 已适配 iPhone X 横竖屏

### ISSUE THREAD

**Issue by zhangnianqq** [longitachi/ZLPhotoBrowser#97]
![simulator screen shot - iphone x - 2017-09-22 at 10 30 47](https://user-images.githubusercontent.com/10876018/30726915-76ce60e6-9f13-11e7-8c3d-8ecfd91f37fa.png)

**Comment by longitachi** [comment]
pod 2.4.3 已适配iPhone X，更新最新版本即可
