### ISSUE TITLE
请问相关的block调用方法在Swift3.0中要如何实现呢？

### ISSUE THREAD

**Issue by jjzjx118** [longitachi/ZLPhotoBrowser#98]
比如下面这个方法，如果在swift中该如何写呢？ 

`   [_actionSheet setSelectImageBlock:^(NSArray<UIImage *> * _Nonnull images, NSArray<PHAsset *> * _Nonnull assets, BOOL isOriginal) {}];`

谢谢了

**Comment by longitachi** [comment]
[#65](https://github.com/longitachi/ZLPhotoBrowser/issues/65)
